# -*- coding: utf-8 -*-
"""Círculo 1 · Identidade. Versão fechada em 01/10/2026: cinco jornadas.
Regra de desenho: a Identidade padroniza, normatiza e sistematiza; os outros círculos executam."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 1, 'Identidade', 'ID', 'ID'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo1-identidade'
FECHADO = True
STATUS = 'Fechado em 01/10/2026 · mudanças aprovadas aplicadas em 02/10/2026 · proposta da revisão aplicada em 03/10/2026'
LEAD = ('A Identidade padroniza, normatiza e sistematiza. Quem executa são os outros círculos, e quem audita é a '
        'Governança. São cinco jornadas: declarar quem somos, transformar isso em regra, criar as marcas, definir o '
        'posicionamento e avaliar se os padrões funcionam. O Soul Brand é a declaração de identidade em vigor: '
        'é a saída da ID-01 e serve de insumo às outras quatro.')

# nomes de produtos usados em mais de uma jornada (evita erro de digitação)
DECL = 'Declaração de identidade vigente'
PADROES = 'Padrões de identidade vigentes'
PACOTE = 'Pacote de marca publicado'
POSIC = 'Posicionamento e casa de mensagens vigentes'
RELAT = 'Relatório de alinhamento'
REVISAO = 'Decisões de revisão dos padrões'
CONSULTAS = 'Registro de consultas e interpretações'
DIRECAO = 'Direção estratégica e públicos prioritários'
ESCUTA = 'Escuta dos públicos'
LICOES = 'Lições da crise'
LEITURA = 'Leitura de mercado, clientes e concorrentes'

JORNADAS = []

# ============================================================ FUNDAMENTO
JORNADAS.append(dict(
    code='ID-01',
    nome='Definir e revisar propósito, visão, missão, princípios e valores',
    dominio='Fundamento', classe='essencial', onda=1,
    objetivo='Manter uma declaração de identidade única, aprovada pelos sócios, que diga o que vale para todo o Ecossistema e o que é próprio de cada empresa.',
    frequencia='Rara: por evento (empresa nova) ou quando a avaliação da ID-05 decide rever a declaração',
    automacao=('baixa', 'Decisão humana e pouco frequente. O fluxo serve de roteiro, não de automação.'),
    base=['collins', 'iso37000', 'quinn', 'apqc'],
    lanes=['EST', 'SOC', 'GOV', 'EXE', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pedido de identidade para empresa nova recebido', 'EST', 'message'),
             I('Revisão da declaração decidida', 'IDR', 'message')],
    fins=[F('Declaração aprovada e publicada', 'IDR'), F('Revisão encerrada sem mudança', 'IDP')],
    etapas=[
        E('Reunir evidências', 'Identidade', 'Copiloto', 'médio',
          [(RELAT, 'ID-05'), (REVISAO, 'ID-05'), (DIRECAO, 'Estratégia'), (ESCUTA, 'Relações'),
           ('Pedido de identidade para empresa nova', 'Estratégia')],
          [T('Consolidar evidências e apontar lacunas', 'IDA'),
           T('Entrevistar sócios, líderes e executivos', 'IDP', 'manual'),
           T('Definir o que precisa mudar na declaração', 'IDP'),
           D('Há mudança a propor?', 'IDP', [S('Sim', 'prox'), S('Não', 'F2')])],
          [('Parecer de revisão', ['etapa 2'])]),
        E('Redigir a proposta de declaração', 'Identidade', 'Copiloto', 'médio',
          [('Parecer de revisão', 'etapa 1'), ('Decisão dos sócios registrada', 'etapa 4')],
          [T('Propor redações alternativas', 'IDA'),
           T('Escolher e ajustar a redação', 'IDP'),
           T('Separar o que é do Ecossistema e o que é de cada empresa', 'IDP')],
          [('Proposta de declaração', ['etapa 3'])]),
        E('Validar com líderes e executivos', 'Identidade, com os executivos', 'Assistido', 'médio',
          [('Proposta de declaração', 'etapa 2')],
          [T('Conduzir a validação com líderes e executivos', 'IDP', 'manual'),
           T('Apontar objeções e ajustes', 'EXE'),
           T('Consolidar objeções e ajustes', 'IDA'),
           D('Há objeção que muda a proposta?', 'IDP', [S('Não', 'prox'), S('Sim', 'E2')])],
          [('Proposta validada', ['etapa 4'])]),
        E('Aprovar com os sócios', 'Governança', 'Assistido', 'alto',
          [('Proposta validada', 'etapa 3')],
          [T('Levar a proposta à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a declaração', 'SOC', 'manual'),
           D('Declaração aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter a atual', 'F2', via=[T('Registrar a decisão dos sócios de manter a declaração atual', 'IDR')])])],
          [('Decisão dos sócios registrada', ['etapa 5', 'etapa 2', 'Governança'])]),
        E('Publicar a versão e avisar quem depende dela', 'Identidade', 'Autopiloto', 'baixo',
          [('Decisão dos sócios registrada', 'etapa 4')],
          [T('Registrar a versão e a data de vigência', 'IDR'),
           T('Listar padrões, marcas, mensagens e agentes afetados', 'IDA'),
           T('Avisar os donos afetados', 'IDR')],
          [(DECL, [TODOS, 'ID-02', 'ID-03', 'ID-04', 'ID-05', 'Estratégia']),
           ('Lista de padrões e materiais afetados', ['ID-02']),
           ('Mudança na declaração a comunicar', ['Gestão', 'Relações'])]),
    ]))

JORNADAS.append(dict(
    code='ID-02',
    nome='Transformar a identidade em regras práticas para pessoas e agentes',
    dominio='Fundamento', classe='essencial', onda=1,
    objetivo='Converter a declaração em padrões que qualquer pessoa ou agente aplica sem consultar o fundador, entregar a cada círculo que executa o conjunto de padrões de que ele precisa e responder às consultas sobre casos que o padrão não cobre.',
    frequencia='Por evento: nova versão da declaração, revisão decidida na ID-05, agente ou canal novo, consulta sobre caso não coberto',
    automacao=('alta nas consultas, média na redação', 'Responder consulta já coberta pelo padrão, publicar e carregar nos agentes rodam sem pessoa. Interpretar caso novo e redigir padrão são de copiloto.'),
    base=['mckinsey', 'schein', 'nng', 'google_persona', 'dmn', 'iso22361', 'impact', 'iia'],
    lanes=['SOL', 'ITG', 'SOC', 'GOV', 'GES', 'REL', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Consulta sobre caso não coberto recebida', 'SOL', 'message'),
             I('Padrão pedido para agente ou canal novo', 'ITG', 'message'),
             I('Revisão dos padrões decidida', 'IDR', 'message'),
             I('Nova versão da declaração publicada', 'IDR', 'message')],
    fins=[F('Padrões publicados e implantados', 'IDR'), F('Consulta respondida', 'IDR')],
    etapas=[
        E('Receber o pedido e decidir se ele pede padrão novo', 'Identidade', 'Copiloto', 'médio',
          [('Consulta sobre caso não coberto', 'Solicitante'),
           ('Pedido de padrão para agente ou canal novo', 'Integração'),
           ('Padrão ambíguo apontado pela auditoria', 'Governança'), (LICOES, 'Governança'),
           (DECL, 'ID-01'), ('Lista de padrões e materiais afetados', 'ID-01'), (REVISAO, 'ID-05')],
          [T('Comparar o pedido com os padrões vigentes e propor a resposta ou o escopo', 'IDA'),
           D('O padrão vigente já resolve o pedido?', 'IDA',
             [S('Não', 'seg'),
              S('Sim', 'F2', via=[T('Responder à consulta com o padrão vigente', 'IDA'),
                                  T('Registrar a consulta respondida pelo padrão', 'IDR')])]),
           T('Decidir se o caso pede interpretação ou padrão novo', 'IDP'),
           D('O caso pede padrão novo ou revisão?', 'IDP',
             [S('Sim', 'prox', via=[T('Dar a orientação provisória a quem pediu, quando há pedido', 'IDP')]),
              S('Não, só interpretação', 'F2', via=[T('Responder à consulta com a interpretação', 'IDP'),
                                                    T('Registrar a interpretação como precedente', 'IDR')])])],
          [('Escopo de padrões a escrever', ['etapa 2']),
           ('Resposta à consulta', ['Solicitante']),
           (CONSULTAS, ['ID-05'])]),
        E('Escrever os padrões em três frentes paralelas', 'Identidade, com Governança, Gestão, Integração e Relações', 'Copiloto', 'alto',
          [('Escopo de padrões a escrever', 'etapa 1'), ('Decisão dos sócios sobre critérios e limites', 'etapa 3'),
           ('Regras e alçadas vigentes', 'Governança')],
          [PAR(
              [T('Rascunhar os critérios de decisão e os critérios de auditoria', 'IDA'),
               T('Rascunhar o protocolo de crise e a definição do que conta como impacto', 'IDA'),
               T('Conferir os critérios com alçadas, regras e riscos', 'GOV'),
               T('Decidir os critérios e as exceções', 'IDP')],
              [T('Rascunhar comportamentos por valor, perfil de pessoa, padrão dos rituais e roteiro de integração', 'IDA'),
               T('Conferir o uso em seleção, integração, avaliação e reconhecimento', 'GES'),
               T('Validar os comportamentos com os líderes', 'IDP', 'manual')],
              [T('Rascunhar o guia de voz, a persona dos agentes e a regra de uso da marca por terceiros', 'IDA'),
               T('Conferir a viabilidade nos agentes', 'ITG'),
               T('Conferir o uso nos canais e com parceiros', 'REL'),
               T('Conferir os limites dos agentes com as alçadas', 'GOV'),
               T('Aprovar voz, persona e limites dos agentes', 'IDP')])],
          [('Padrões redigidos', ['etapa 3'])]),
        E('Testar os padrões em casos reais', 'Identidade, com Governança e os sócios', 'Copiloto', 'alto',
          [('Padrões redigidos', 'etapa 2'), ('Registros de entregas de pessoas e agentes', 'Integração')],
          [T('Aplicar os padrões a uma amostra de casos passados', 'IDA'),
           T('Julgar os casos de fronteira nos testes', 'IDP'),
           D('Os padrões separam o certo do errado?', 'IDP', [S('Sim', 'seg'), S('Não', 'E2')]),
           D('Mudou critério de decisão ou limite de agente?', 'IDP',
             [S('Não', 'prox'),
              S('Sim', 'seg', via=[T('Levar os critérios e os limites novos à decisão dos sócios', 'GOV', 'call'),
                                   T('Decidir sobre os critérios e os limites novos', 'SOC', 'manual')])]),
           D('Critérios e limites aprovados?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter os atuais', 'prox', via=[T('Retirar da versão os critérios e os limites não aprovados e registrar o motivo', 'IDR')])])],
          [('Padrões testados e casos de teste', ['etapa 4']),
           ('Decisão dos sócios sobre critérios e limites', ['etapa 2', 'Governança'])]),
        E('Publicar os padrões e entregar a cada círculo o que ele executa', 'Identidade, com Integração e Gestão', 'Autopiloto', 'baixo',
          [('Padrões testados e casos de teste', 'etapa 3')],
          [T('Versionar os padrões no catálogo', 'IDR'),
           T('Montar o conjunto de padrões de cada círculo que executa', 'IDA'),
           T('Carregar padrões e casos de teste nos agentes', 'ITG'),
           T('Incorporar comportamentos, perfil e rituais nos instrumentos de pessoas', 'GES'),
           T('Marcar como vencidos os materiais afetados e avisar quem os produz', 'IDR'),
           T('Avisar pessoas e donos de agentes', 'IDR')],
          [(PADROES, [TODOS, 'ID-03', 'ID-04', 'ID-05']),
           ('Kit de cultura e pessoas', ['Gestão']),
           ('Critérios de auditoria e casos de teste', ['Governança', 'Integração']),
           ('Protocolo de crise', ['Governança', 'Relações', 'Executivos']),
           ('Regra de uso da marca por terceiros', ['Relações', 'Governança']),
           ('Definição do que conta como impacto', ['Governança', 'Estratégia']),
           ('Aviso de materiais vencidos', ['Relações', 'Negócios', 'Gestão']),
           ('Mudança nos padrões a comunicar', ['Gestão'])]),
    ]))

# ================================================================= MARCA
JORNADAS.append(dict(
    code='ID-03',
    nome='Criar ou rever e registrar a marca de uma empresa, oferta ou projeto',
    dominio='Marca', classe='essencial', onda=2,
    objetivo='Decidir se o negócio novo usa uma marca existente ou ganha marca própria e, quando ganha, entregá-la criada, protegida e pronta para uso por pessoas e agentes. Vale também para rever uma marca existente, receber a marca de uma empresa adquirida e retirar uma marca de uso. Quem usa a marca produz os materiais com o pacote.',
    frequencia='Por evento: empresa, oferta ou projeto novo, empresa adquirida, vendida ou encerrada, ou revisão de marca decidida na ID-05',
    automacao=('média', 'Pesquisa, alternativas e pacote são de agente; arquitetura, nome e registro são decisão humana.'),
    base=['aaker', 'wheeler', 'inpi', 'apqc'],
    lanes=['SOL', 'EST', 'EXE', 'ASS', 'GOV', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pedido de marca recebido', 'SOL', 'message'),
             I('Retirada de marca pedida', 'SOL', 'message'),
             I('Revisão de marca decidida', 'IDR', 'message')],
    fins=[F('Marca pronta para uso', 'IDR'), F('Marca retirada de uso', 'IDR')],
    etapas=[
        E('Entender o pedido e pesquisar as marcas do portfólio e dos concorrentes', 'Identidade', 'Copiloto', 'baixo',
          [('Pedido de marca', 'Solicitante'), ('Pedido de retirada de marca', 'Solicitante'), (REVISAO, 'ID-05'),
           ('Posicionamento da oferta e público-alvo', 'Inteligência'), (LEITURA, 'Inteligência'),
           (PACOTE, 'ID-03'), (DECL, 'ID-01'), (POSIC, 'ID-04'), (PADROES, 'ID-02')],
          [T('Fechar o briefing com quem pediu', 'IDP'),
           T('Pesquisar as marcas do portfólio e dos concorrentes', 'IDA')],
          [('Briefing e pesquisa de marca', ['etapa 2'])]),
        E('Decidir que marca o negócio terá: existente, própria, recebida, revista ou retirada', 'Identidade, com Estratégia, o executivo e Governança', 'Copiloto', 'alto',
          [('Briefing e pesquisa de marca', 'etapa 1'), (DIRECAO, 'Estratégia')],
          [T('Aplicar os critérios de escolha entre marca existente e marca própria e recomendar', 'IDA'),
           T('Avaliar a recomendação à luz do portfólio', 'EST'),
           T('Opinar sobre o papel da marca do seu negócio', 'EXE'),
           T('Decidir o papel da marca, ouvido o executivo', 'IDP'),
           D('Que marca o negócio terá?', 'IDP',
             [S('Marca nova', 'prox'), S('Marca existente', 'E6'), S('Revisão da marca atual', 'E4'),
              S('Marca recebida de empresa adquirida', 'E5'),
              S('Retirada da marca', 'F2', via=[T('Agendar a retirada da marca para a data de efeito que veio no pedido', 'IDR'),
                                                T('Marcar a marca como retirada no repositório na data de efeito e avisar quem a usa', 'IDR'),
                                                T('Dar baixa ou transferir o registro da marca retirada', 'GOV')])])],
          [('Decisão sobre a marca do negócio', ['etapa 3', 'etapa 4', 'etapa 5', 'etapa 6', 'Estratégia', 'Solicitante']),
           ('Marca retirada de uso', ['Solicitante', 'Relações', 'Negócios', 'Integração', 'Gestão', 'Operações', 'Governança'])]),
        E('Definir a essência da marca e o nome', 'Identidade, com assessoria de propriedade intelectual', 'Copiloto', 'médio',
          [('Decisão sobre a marca do negócio', 'etapa 2')],
          [T('Gerar a essência da marca e nomes candidatos', 'IDA'),
           T('Verificar no INPI se já existe marca igual ou parecida e se os domínios estão livres', 'IDA'),
           T('Avaliar o risco de registro dos nomes', 'ASS'),
           T('Opinar sobre os nomes candidatos', 'EXE'),
           T('Escolher o nome, ouvido o executivo', 'IDP'),
           D('Nome livre e aprovado?', 'IDP',
             [S('Sim', 'prox', via=[T('Reservar os domínios do nome aprovado', 'IDR')]), S('Não', 'E3')])],
          [('Essência da marca e nome aprovado', ['etapa 4'])]),
        E('Desenhar a identidade visual e verbal', 'Identidade', 'Copiloto', 'médio',
          [('Essência da marca e nome aprovado', 'etapa 3'), ('Decisão sobre a marca do negócio', 'etapa 2')],
          [T('Gerar alternativas de identidade visual e verbal', 'IDA'),
           T('Refinar as alternativas', 'IDP'),
           T('Opinar sobre as alternativas de identidade visual e verbal', 'EXE'),
           T('Escolher a identidade, ouvido o executivo', 'IDP'),
           D('Identidade aprovada?', 'IDP', [S('Sim', 'prox'), S('Não', 'E4')])],
          [('Identidade visual e verbal aprovada', ['etapa 5'])]),
        E('Proteger a marca', 'Identidade e Governança', 'Copiloto', 'alto',
          [('Identidade visual e verbal aprovada', 'etapa 4'), ('Decisão sobre a marca do negócio', 'etapa 2')],
          [T('Decidir o que proteger: tipo de marca, classes e domínios', 'IDP'),
           T('Registrar os perfis da marca', 'IDR'),
           T('Depositar o pedido de registro no INPI ou transferir a titularidade da marca recebida', 'GOV'),
           T('Assumir os prazos de acompanhamento e renovação', 'GOV')],
          [('Pedido de registro depositado e prazos', ['etapa 6', 'Governança'])]),
        E('Montar o pacote de marca', 'Identidade', 'Copiloto', 'baixo',
          [('Decisão sobre a marca do negócio', 'etapa 2'),
           ('Pedido de registro depositado e prazos', 'etapa 5')],
          [T('Montar manual, modelos e arquivos para pessoas e agentes', 'IDA'),
           T('Conferir o pacote contra o padrão', 'IDR', 'rule'),
           T('Revisar o pacote', 'IDP')],
          [('Pacote de marca', ['etapa 7'])]),
        E('Publicar e entregar a quem usa a marca', 'Identidade', 'Autômato', 'baixo',
          [('Pacote de marca', 'etapa 6')],
          [T('Publicar no repositório de marca', 'IDR'),
           T('Avisar quem pediu e os círculos que usam a marca', 'IDR')],
          [(PACOTE, ['Solicitante', 'Relações', 'Negócios', 'Integração', 'Gestão', 'Operações', 'ID-03', 'ID-05'])]),
    ]))

# ========================================================= POSICIONAMENTO
JORNADAS.append(dict(
    code='ID-04',
    nome='Definir o posicionamento institucional e as mensagens para cada público',
    dominio='Posicionamento', classe='essencial', onda=2,
    objetivo='Definir uma promessa clara e as mensagens principais para cada público, no nível do Ecossistema e de cada empresa, para uso de pessoas e agentes. Quem comunica são Relações, para fora, e a Gestão, para dentro.',
    frequencia='A cada ciclo estratégico e por evento: nova declaração ou revisão decidida na ID-05',
    automacao=('média', 'Síntese e redação são de agente; escolha e aprovação são humanas.'),
    base=['apqc', 'hatch'],
    lanes=['EST', 'REL', 'GES', 'ITG', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Direção estratégica do ciclo aprovada', 'EST', 'message'),
             I('Revisão do posicionamento decidida', 'IDR', 'message'),
             I('Nova versão da declaração publicada', 'IDR', 'message')],
    fins=[F('Posicionamento e mensagens publicados', 'IDR')],
    etapas=[
        E('Levantar os insumos', 'Identidade', 'Copiloto', 'baixo',
          [(DECL, 'ID-01'), (DIRECAO, 'Estratégia'), (LEITURA, 'Inteligência'),
           (RELAT, 'ID-05'), (REVISAO, 'ID-05')],
          [T('Reunir e resumir os insumos', 'IDA'),
           T('Definir os públicos e as perguntas a responder', 'IDP')],
          [('Síntese de insumos', ['etapa 2'])]),
        E('Formular o posicionamento e a promessa por público', 'Identidade', 'Copiloto', 'médio',
          [('Síntese de insumos', 'etapa 1')],
          [T('Propor posicionamento e promessa para cada público', 'IDA'),
           T('Separar o que é do Ecossistema e o que é de cada empresa', 'IDP'),
           T('Escolher e ajustar a proposta', 'IDP')],
          [('Proposta de posicionamento', ['etapa 3'])]),
        E('Validar o posicionamento com Estratégia, Relações, Gestão e executivos', 'Identidade, com Estratégia, Relações e Gestão', 'Assistido', 'médio',
          [('Proposta de posicionamento', 'etapa 2')],
          [PAR([T('Conferir a coerência com a estratégia', 'EST')],
               [T('Conferir o uso em marketing e relacionamento', 'REL')],
               [T('Conferir a promessa para pessoas', 'GES')]),
           T('Fechar o posicionamento com os executivos', 'IDP', 'manual'),
           D('Posicionamento aprovado?', 'IDP', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Posicionamento aprovado', ['etapa 4'])]),
        E('Montar as mensagens principais e a narrativa por público', 'Identidade', 'Copiloto', 'médio',
          [('Posicionamento aprovado', 'etapa 3'), (PADROES, 'ID-02')],
          [T('Redigir mensagens-chave, provas e narrativa por público, no guia de voz', 'IDA'),
           T('Revisar e aprovar as mensagens', 'IDP')],
          [('Casa de mensagens e narrativa', ['etapa 5'])]),
        E('Publicar e entregar a quem comunica', 'Identidade, com Integração e Relações', 'Autopiloto', 'baixo',
          [('Casa de mensagens e narrativa', 'etapa 4')],
          [T('Publicar no repositório e avisar os círculos', 'IDR'),
           T('Carregar as mensagens nos agentes que falam com os públicos', 'ITG'),
           T('Preparar os porta-vozes com as mensagens', 'REL')],
          [(POSIC, ['Relações', 'Negócios', 'Gestão', 'Integração', 'Governança', 'Inteligência', 'ID-03', 'ID-05'])]),
    ]))

# ============================================================== AVALIAÇÃO
JORNADAS.append(dict(
    code='ID-05',
    nome='Avaliar se os padrões de identidade funcionam e decidir o que rever',
    dominio='Avaliação', classe='essencial', onda=2,
    objetivo='Saber, com os dados de quem executa e de quem audita, onde o que declaramos, o que vivemos e como somos vistos não batem; separar falha do padrão de falha de execução; e abrir a revisão do padrão certo.',
    frequencia='A cada ciclo de avaliação (cadência a definir) e por evento: depois de crise, de empresa que entra ou sai do portfólio, ou de troca de liderança',
    automacao=('média', 'Reunir, consolidar e calcular são de agente e automação; interpretar e decidir o que rever são de pessoas.'),
    base=['hatch', 'iso10010', 'iso20671', 'reptrak', 'iia'],
    lanes=['IDP', 'IDA', 'IDR'],
    inicios=[I('Avaliação extraordinária pedida', 'IDP', 'message'),
             I('Ciclo de avaliação dos padrões iniciado', 'IDR', 'timer')],
    fins=[F('Avaliação concluída e devolvida', 'IDR')],
    etapas=[
        E('Reunir os resultados dos círculos que medem', 'Identidade', 'Autopiloto', 'baixo',
          [('Resultado da auditoria das entregas', 'Governança'),
           ('Resultado da pesquisa de cultura e dados de pessoas', 'Gestão'),
           ('Percepção dos públicos e sinais de reputação', 'Relações'),
           (LICOES, 'Governança'),
           ('Indicadores de marca, cultura e reputação', 'Inteligência'),
           ('Portfólio de empresas atualizado', 'Estratégia'),
           (CONSULTAS, 'ID-02'), (DECL, 'ID-01'), (PADROES, 'ID-02'), (PACOTE, 'ID-03'), (POSIC, 'ID-04')],
          [T('Reunir os resultados recebidos e conferir o que falta', 'IDR'),
           T('Consolidar os resultados por padrão avaliado', 'IDA'),
           D('Falta dado de algum círculo?', 'IDA',
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Cobrar o dado do círculo dono ou registrar a ressalva', 'IDP')])])],
          [('Base da avaliação dos padrões', ['etapa 2'])]),
        E('Analisar as lacunas entre o declarado, o vivido e o percebido', 'Identidade', 'Copiloto', 'médio',
          [('Base da avaliação dos padrões', 'etapa 1')],
          [T('Calcular as lacunas entre visão, cultura e imagem', 'IDA'),
           T('Calcular os indicadores de clareza e atualidade dos padrões', 'IDA'),
           T('Interpretar e priorizar as lacunas', 'IDP')],
          [(RELAT, ['etapa 3', 'ID-01', 'ID-04', 'Estratégia', 'Sócios', 'Executivos', 'Líderes dos círculos']),
           ('Indicadores de clareza e atualidade dos padrões', ['Inteligência'])]),
        E('Decidir o que rever', 'Identidade, com executivos e líderes dos círculos', 'Copiloto', 'médio',
          [(RELAT, 'etapa 2')],
          [T('Separar falha do padrão e falha de execução em cada lacuna', 'IDA'),
           T('Decidir com executivos e líderes dos círculos o que rever', 'IDP', 'manual'),
           D('Há falha de padrão a corrigir?', 'IDP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Abrir a revisão na jornada dona do padrão', 'IDR')])]),
           D('Há falha de execução a apontar?', 'IDP',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Apontar a lacuna ao círculo que executa', 'IDR')])])],
          [(REVISAO, ['etapa 4', 'ID-01', 'ID-02', 'ID-03', 'ID-04']),
           ('Lacunas de execução apontadas', ['Gestão', 'Relações', 'Governança', 'Integração', 'Negócios', 'Operações'])]),
        E('Registrar a avaliação e devolver o resultado', 'Identidade', 'Autopiloto', 'baixo',
          [(REVISAO, 'etapa 3')],
          [T('Resumir o que funciona, o que será revisto e o que foi apontado', 'IDA'),
           T('Publicar o resumo e avisar quem forneceu dados', 'IDR')],
          [('Resumo da avaliação dos padrões', ['Sócios', 'Executivos', 'Líderes dos círculos', 'Governança', 'Gestão',
                                              'Relações', 'Inteligência'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Fundamento', 'Dizer quem somos e transformar isso em regra aplicável.'),
    ('Marca', 'Criar e proteger as marcas do Ecossistema e das empresas.'),
    ('Posicionamento', 'Definir a promessa e as mensagens para cada público.'),
    ('Avaliação', 'Conferir se os padrões funcionam e decidir o que rever.'),
]

ONDAS = {
    1: 'O que o modelo precisa para rodar com pessoas e agentes',
    2: 'O que sustenta marca, posicionamento e a revisão dos padrões',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4. Mostra que os processos de identidade estão espalhados por estratégia (1.1.4, 1.2.1), marketing (3.2.1.2, 3.2.1.4), pessoas (7.1.1.9, 7.3.1.1, 7.5.1, 7.8) e relações externas (categoria 12.0). Não existe categoria de identidade: por isso a Identidade padroniza e os círculos donos dessas funções executam.',
    'iia': 'Três linhas: a primeira está ligada à entrega de produtos e serviços; a segunda dá conhecimento especializado, apoio, monitoramento e contestação; a terceira, a auditoria interna, dá avaliação e assessoria independentes. Usado por analogia na ID-02 e na ID-05 para separar quem padroniza (Identidade), quem executa (os outros círculos) e quem audita (Governança).',
    'collins': 'A visão tem duas partes: ideologia central (valores e propósito) e futuro imaginado. Base da ID-01.',
    'iso37000': 'O propósito é o primeiro dos 11 princípios de governança; os valores informam o propósito e o modo de alcançá-lo. Base da aprovação pelos sócios na ID-01.',
    'quinn': 'Oito passos; usamos “descobrir o propósito”, “estimular o aprendizado individual” e “conectar as pessoas ao propósito”. Base da ID-01 e do rascunho de propósito pessoal transferido à Gestão.',
    'mckinsey': 'Quatro alavancas para mudar comportamento: exemplo dos líderes, entendimento e convicção, desenvolvimento de habilidades e mecanismos formais. Base do kit de cultura e pessoas, na ID-02.',
    'schein': 'Cultura em três níveis: artefatos e comportamentos, valores declarados e pressupostos básicos. Tratar rituais como artefatos é leitura nossa; o verbete não fala em rituais. Base do padrão dos rituais, na ID-02.',
    'nng': 'Quatro dimensões de tom: formal ou casual, sério ou divertido, respeitoso ou irreverente, sóbrio ou entusiasmado. Base do guia de voz na ID-02.',
    'google_persona': 'Passos para definir a persona de um agente de conversa. Base da persona dos agentes na ID-02.',
    'dmn': 'Padrão de modelagem de decisões, que inclui tabelas de decisão e foi desenhado para uso ao lado do BPMN. Usado na ID-02 para os critérios de decisão e para a regra de uso da marca por terceiros.',
    'iso22361': 'Diretrizes para a capacidade de gestão de crises. Base do protocolo de crise, que a ID-02 entrega à Governança e a Relações.',
    'impact': 'Cinco dimensões de impacto: o quê, quem, quanto, contribuição e risco. Base da definição do que conta como impacto, que a ID-02 entrega à Governança e à Estratégia.',
    'pas808': 'Guia para organizações orientadas a propósito, incluindo prestação de contas aos públicos. Base do rascunho do relato de impacto transferido à Governança.',
    'aaker': 'Arquitetura de marca em quatro estratégias: casa de marcas (house of brands), marcas endossadas (endorsed brands), submarcas (subbrands) e casa com marca (branded house, em que a marca-mãe domina); perguntas para escolher. Base da etapa 2 da ID-03.',
    'wheeler': 'Processo em cinco fases: pesquisa, estratégia, desenho da identidade, pontos de contato e gestão dos ativos. Base da ID-03.',
    'inpi': 'O registro de marca vale 10 anos, renováveis; a prorrogação é pedida no último ano de vigência ou em até seis meses depois. Base da etapa 5 da ID-03.',
    'hatch': 'Marca corporativa pede alinhamento entre visão, cultura e imagem; as três lacunas são visão–cultura, imagem–cultura e imagem–visão. Base da ID-05; a ID-04 usa o relatório dessas lacunas como insumo.',
    'iso10010': 'Orientação para entender, avaliar e melhorar a cultura de qualidade. Usamos a sequência entender, avaliar e melhorar na ID-05.',
    'iso20671': 'Avaliação de marca com elementos de entrada, dimensões de saída e indicadores. Base da ID-05.',
    'reptrak': 'Sete fatores de reputação: produtos e serviços, desempenho, inovação, liderança, conduta, cidadania e ambiente de trabalho. Usados como temas da percepção dos públicos que a ID-05 recebe de Relações.',
    'craig': 'Declaração de propósito pessoal seguida de um plano para transformar o propósito em impacto. Base do rascunho de propósito pessoal transferido à Gestão.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio e script, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# --------------------------------------------------- o que a Identidade não faz
FRONTEIRAS = [
    ('Escolher onde atuar e fixar os alvos', 'Estratégia',
     'A declaração e os critérios de decisão, que a Estratégia usa para conferir as próprias escolhas. Recebe dela a direção e os públicos prioritários.'),
    ('Posicionar cada oferta e gerar demanda', 'Inteligência e Relações',
     'O posicionamento institucional e a casa de mensagens (ID-04).'),
    ('Produzir materiais de marca', 'Quem usa a marca: Relações, Negócios, Gestão e Operações',
     'O pacote de marca com modelos prontos (ID-03) e a resposta a consultas (ID-02).'),
    ('Autorizar o uso da marca por terceiros', 'Relações, com Governança',
     'A regra de uso da marca por terceiros (ID-02).'),
    ('Comunicar para dentro', 'Gestão',
     'O guia de voz, as mensagens e o aviso do que mudou na declaração e nos padrões.'),
    ('Comunicar para fora e preparar porta-vozes', 'Relações',
     'O posicionamento, a casa de mensagens e o guia de voz.'),
    ('Integrar pessoas, realizar rituais, reconhecer e apoiar o propósito pessoal', 'Gestão',
     'O kit de cultura e pessoas: comportamentos por valor, perfil de pessoa, padrão dos rituais e roteiro de integração (ID-02).'),
    ('Ciclo da pessoa: vaga, contrato, avaliação e remuneração', 'Gestão',
     'O perfil de pessoa e os comportamentos esperados.'),
    ('Monitorar a reputação', 'Relações',
     'Os temas a monitorar e as mensagens. Recebe de volta a percepção dos públicos.'),
    ('Responder a crises', 'Governança, com o executivo da empresa',
     'O protocolo de crise (ID-02) e um assento no comitê de crise.'),
    ('Auditar as entregas de pessoas e agentes', 'Governança',
     'Os critérios de auditoria e os casos de teste (ID-02). Julga os casos de fronteira por consulta.'),
    ('Apurar e publicar o relato de impacto', 'Governança',
     'A definição do que conta como impacto (ID-02).'),
    ('Código de conduta, canal de relato e tratamento de violações', 'Governança',
     'Os comportamentos esperados.'),
    ('Construir, testar e liberar agentes', 'Integração',
     'Persona, voz, limites e casos de teste. A Integração roda os testes antes de liberar o agente.'),
    ('Registrar e renovar marcas', 'Governança',
     'A decisão do que proteger (ID-03).'),
]

# ------------------------------------------------------- decisões de fechamento
# (decisão, origem, efeito no desenho)
DECISOES = [
    ('A Identidade padroniza, normatiza e sistematiza; os outros círculos executam',
     'Regra sua (12:29), aplicada às treze jornadas por proposta minha, que você aprovou (12:59)',
     'O círculo fica com cinco jornadas; oito são transferidas a quem executa.'),
    ('O Soul Brand é insumo, não o centro das jornadas',
     'Orientação sua (10:01)',
     'Ele é a declaração de identidade em vigor: saída da ID-01 e entrada das demais.'),
    ('Comunicação interna fica na Gestão; a externa, em Relações',
     'Decisão sua (12:29) para a interna; a externa segue a decisão D3 da rodada 2',
     'A Identidade entrega voz, mensagens e o aviso do que mudou.'),
    ('Auditoria das entregas fica na Governança, com interoperabilidade com o que é cross',
     'Decisão sua (12:29)',
     'A Identidade entrega critérios de auditoria e casos de teste e julga os casos de fronteira.'),
    ('Integração cultural, rituais, reconhecimento e propósito pessoal ficam na parte de cultura e pessoas da Gestão',
     'Decisão sua (12:29), estendida por proposta minha aprovada (12:59)',
     'A Identidade entrega o kit de cultura e pessoas.'),
    ('Monitorar a reputação fica em Relações; responder a crises, na Governança com o executivo',
     'Proposta minha aprovada (12:59)',
     'A Identidade entrega o protocolo de crise e tem assento no comitê.'),
    ('O relato de impacto fica na Governança',
     'Proposta minha aprovada (12:59)',
     'A Identidade define o que conta como impacto.'),
    ('Material de marca é produzido por quem usa; uso por terceiros fica em Relações, com Governança',
     'Proposta minha aprovada (12:59)',
     'A Identidade entrega o pacote de marca com modelos e a regra de uso por terceiros.'),
    ('A Identidade mantém o ciclo de retorno e responde consultas em prazo combinado',
     'Condição proposta por mim e aprovada (12:59)',
     'ID-05 avalia os padrões com os dados de quem mede; a etapa 1 da ID-02 responde consultas. O prazo ainda não foi definido.'),
    ('Os padrões são obrigatórios',
     'Condição proposta por mim e aprovada (12:59)',
     'Cada jornada que executa terá um ponto de conferência contra o padrão. Vale como requisito para os próximos círculos.'),
    ('Quatro ajustes depois do fechamento: marca recebida e retirada de marca (ID-03); ramo “manter o atual” quando os sócios dizem não (ID-01 e ID-02); pesquisa de mercado vinda da Inteligência (ID-03); conferência da Governança nos limites dos agentes (ID-02)',
     'Propostas do revisor independente e do cruzamento com a Estratégia, aprovadas por você (15:48)',
     'Aplicados nesta versão.'),
    ('Reserva de domínios e registro de perfis da marca ficam na Identidade',
     'Decisão sua (15:48), contra a proposta do revisor',
     'A ID-03 fica como estava nesse ponto.'),
    ('O posicionamento institucional e a casa de mensagens passam a ir também à Inteligência',
     'Proposta do cruzamento com a Inteligência, aprovada por você (20:02)',
     'A ID-04, etapa 5, entrega o posicionamento à Inteligência, que o usa para enquadrar cada oferta (IN-07, etapa 3).'),
    ('Na marca, a Identidade decide, ouvido o executivo; a retirada vale na data de efeito do pedido',
     'Duas propostas, aprovadas por você (20:11 de 02/10/2026)',
     'Na ID-03, etapa 4, o executivo opina e a Identidade escolhe a identidade visual e verbal; na etapa 2, a retirada da marca é agendada para a data de efeito que vem no pedido da Estratégia.'),
    ('O nível “workflow” passa a se chamar etapa; cada círculo tem o seu código',
     'Você usou “etapas” (10:01); o código por círculo é proposta minha, sem objeção',
     'ID-01 a ID-05 aqui; ES-01 em diante na Estratégia.'),
]

# alertas que seguem para os próximos círculos
ALERTAS = [
    ('Carga da Gestão', 'A Gestão recebe quatro jornadas com muito trabalho humano: integração cultural, rituais e reconhecimento, propósito pessoal e comunicação interna. A carga só pode ser medida quando a Gestão for desenhada.'),
    ('Um indicador, um dono', 'Identidade responde por padrão claro e atual. Cultura vivida é da Gestão; percepção e reputação, de Relações; conformidade das entregas, da Governança.'),
    ('Prazo de resposta às consultas', 'Falta definir o prazo combinado da etapa 1 da ID-02. Sem medida de volume, não propus número.'),
    ('Uma auditoria só', 'A Governança amostra as entregas uma vez, com os critérios de cada círculo. A decidir no círculo 9.'),
]

# ------------------------------------------------ jornadas transferidas (rascunhos)
# (código antigo, destino, o que a Identidade entrega, o que volta para a Identidade)
TRANSFERIDAS_FONTE = '../c1/v13/circulo1-13-jornadas.json'
TRANSFERIDAS = [
    ('ID-04', 'Quem usa a marca produz o material. Uso por terceiros: Relações, com Governança',
     'Pacote de marca com modelos (ID-03); regra de uso da marca por terceiros (ID-02)',
     'Consulta, quando o caso não está coberto (ID-02)'),
    ('ID-05', 'Gestão',
     'Kit de cultura e pessoas: roteiro de integração e comportamentos por valor (ID-02)',
     'Resultado da pesquisa de cultura e dados de pessoas (ID-05)'),
    ('ID-06', 'Gestão',
     'Kit de cultura e pessoas: padrão dos rituais e critérios de reconhecimento (ID-02)',
     'Resultado da pesquisa de cultura e dados de pessoas (ID-05)'),
    ('ID-07', 'Gestão, dentro do ciclo de desenvolvimento',
     'Declaração e comportamentos por valor (ID-01 e ID-02). O roteiro de propósito pessoal entra no kit quando a Gestão ativar a jornada, que é recomendada',
     'Nada obrigatório: a participação é voluntária'),
    ('ID-09', 'Gestão, para dentro; Relações, para fora',
     'Guia de voz (ID-02), posicionamento e casa de mensagens (ID-04) e os avisos do que mudou (ID-01 e ID-02)',
     'Percepção dos públicos e sinais de reputação (ID-05)'),
    ('ID-10', 'Relações monitora; Governança, com o executivo, responde à crise',
     'Protocolo de crise (ID-02), mensagens (ID-04) e assento no comitê de crise',
     'Lições da crise (ID-02 e ID-05); percepção dos públicos e sinais de reputação (ID-05)'),
    ('ID-11', 'Governança',
     'Critérios de auditoria e casos de teste (ID-02); julgamento dos casos de fronteira por consulta',
     'Resultado da auditoria das entregas (ID-05); padrão ambíguo apontado pela auditoria (ID-02)'),
    ('ID-13', 'Governança',
     'Definição do que conta como impacto (ID-02)',
     'Nada obrigatório'),
]

# ----------------------------------------------- relação com a versão de 13 jornadas
# (tipo, antes, agora, nota)
MUDANCAS = [
    ('Ajustado', 'ID-01 · Definir e revisar propósito, visão, missão, princípios e valores', 'ID-01',
     'A revisão passa a ser aberta pela ID-05. O aviso do que mudou vai para Gestão e Relações, que comunicam.'),
    ('Ajustado', 'ID-02 · Transformar a identidade em regras práticas para pessoas e agentes', 'ID-02',
     'Ganha a resposta a consultas (etapa 1) e a entrega de um conjunto de padrões a cada círculo que executa (etapa 4). Passa a escrever também os critérios de auditoria, a regra de uso da marca por terceiros e a definição de impacto.'),
    ('Ajustado', 'ID-03 · Criar ou rever e registrar a marca de uma empresa, oferta ou projeto', 'ID-03',
     'Ganha o início por revisão decidida na ID-05. O pacote passa a servir quem produz os materiais.'),
    ('Ajustado', 'ID-08 · Definir o posicionamento institucional e as mensagens para cada público', 'ID-04',
     'Código novo. Preparar os porta-vozes passa a Relações.'),
    ('Ajustado', 'ID-12 · Medir o alinhamento entre identidade, cultura e imagem e planejar a correção das lacunas', 'ID-05',
     'Enxugada e renomeada. A Identidade deixa de coletar os dados e de planejar a correção: recebe os resultados de quem mede, decide o que rever nos padrões e aponta as falhas de execução a quem executa.'),
    ('Retirado', 'ID-04, ID-05, ID-06, ID-07, ID-09, ID-10, ID-11 e ID-13 da versão de treze jornadas', 'Transferidas',
     'Saem da Identidade e ficam guardadas como rascunho para Gestão, Governança e Relações. Ver a aba Transferidas.'),
    ('Acrescentado', 'Sem equivalente', 'Raia e parte “Líder do círculo”',
     'Papel novo no vocabulário do modelo, para as jornadas em que os líderes dos círculos decidem ou recebem.'),
    ('Ajustado', 'ID-03, etapa 2: três desfechos para a marca', 'Cinco desfechos',
     'Entram a marca recebida de empresa adquirida e a retirada da marca. Aprovado por você em 01/10/2026, às 15:48.'),
    ('Ajustado', 'ID-01, etapa 4, e ID-02, etapa 3: o “não” dos sócios só voltava à redação', 'Ramo “manter o atual”',
     'O motivo fica registrado. Na ID-02 a aprovação passa pela Governança. Aprovado às 15:48.'),
    ('Ajustado', 'ID-03, etapa 1: a Identidade pesquisava público, concorrentes e marcas', 'A Identidade pesquisa só marcas',
     'Público e concorrentes entram pela leitura da Inteligência. Aprovado às 15:48.'),
    ('Ajustado', 'ID-02, etapa 2: voz e agentes sem a Governança', 'Conferência da Governança',
     'Os limites dos agentes são conferidos com as alçadas. Aprovado às 15:48.'),
    ('Ajustado', 'Entrada “Leitura de mercado e concorrentes”, da Inteligência', 'Leitura de mercado, clientes e concorrentes',
     'Mesmo nome que a Estratégia usa, para a Inteligência ter um produto só.'),
    ('Ajustado', 'ID-04, etapa 5: o posicionamento não ia à Inteligência', 'A Inteligência entra nos destinos',
     'Quem posiciona cada oferta passa a receber o posicionamento institucional e a casa de mensagens. Aprovado às 20:02.'),
    ('Ajustado', 'ID-03, etapa 2: a marca era marcada como retirada assim que a Identidade decidia', 'A retirada vale na data de efeito que vem no pedido',
     'A retirada é agendada para a data de efeito e marcada no repositório nessa data, para a marca não sair de uso enquanto a empresa ou a oferta ainda atende clientes. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ID-03, etapa 4: o executivo escolhia e aprovava a identidade visual e verbal', 'A Identidade escolhe, ouvido o executivo',
     'O executivo opina numa tarefa própria; a escolha e a aprovação passam à pessoa da Identidade. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ID-03, etapas 2 e 3: papel da marca e nome decididos com o executivo', 'A Identidade decide, ouvido o executivo',
     'Proposta da revisão das mudanças das 20:11, aprovada por você às 09:30 de 03/10/2026.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'As trocas com a Estratégia e a Inteligência foram conferidas dos dois lados. Com os outros seis círculos, estão descritas pelo nome do círculo e serão conferidas quando cada um for desenhado.',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Na ID-02, as consultas entram pela etapa 1. Se o volume crescer, vale separar em jornada própria; hoje não há medida de volume.',
    'Na ID-03, a jornada termina no pedido de registro; oposição ou recusa do registro ainda não tem caminho desenhado.',
    'As oito jornadas transferidas são rascunho. Só passam a valer quando o círculo de destino for desenhado e fechado.',
    'Os números descrevem este desenho, não a operação atual.',
]

PONTOS = []

MUDOU_INTRO = ('Comparação com a versão de treze jornadas, publicada nesta mesma página antes do fechamento. '
               'Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')

# propostas de mudança em conteúdo já aprovado: só entram com a sua aprovação
# (o que mudaria, por quê, de onde veio)
PROPOSTAS = []

REVISAO_TXT = [
    'As jornadas ID-01, ID-03 e ID-04 vêm da versão de treze jornadas, que passou por revisão independente: 30 achados, 3 graves, corrigidos naquela versão.',
    'No fechamento, um revisor independente leu as cinco jornadas junto com as da Estratégia e propôs sete mudanças. Três foram aplicadas na hora, porque tratavam de partes novas (ID-02, etapa 1; ID-05, etapa 1; fronteira com a Estratégia). As demais viraram cinco propostas: você aprovou quatro, aplicadas nesta versão, e recusou uma.',
    'As fontes deste círculo foram conferidas por um segundo revisor na versão anterior (23 fontes: 18 confirmadas e 5 confirmadas em parte, corrigidas) e, neste fechamento, a do IIA.',
    'Depois do fechamento, o cruzamento com a Inteligência gerou uma proposta, que você aprovou às 20:02 e está aplicada. As duas propostas seguintes (data de efeito da retirada e escolha da identidade pela Identidade, ouvido o executivo) foram aprovadas às 20:11 de 02/10/2026 e estão aplicadas. A revisão independente dessas mudanças gerou uma proposta nova (papel da marca e nome na ID-03), na aba Decisões, não aplicada.',
]
