# -*- coding: utf-8 -*-
"""Círculo 2 · Estratégia. Proposta em debate (01/10/2026): seis jornadas.
Regra proposta: a Estratégia formula e propõe a direção, o portfólio, os alvos e a alocação, que os
sócios aprovam; decide com o executivo, dentro da alçada, a aposta que entra e a oferta que é lançada;
e acompanha se as hipóteses se confirmam. As empresas e os outros círculos executam."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 2, 'Estratégia', 'ES', 'ES'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo2-estrategia'
FECHADO = False
STATUS = 'Proposta em debate · 01/10/2026'
LEAD = ('A Estratégia formula e propõe a direção, o portfólio, os alvos e a alocação de recursos, que os sócios '
        'aprovam. Decide com o executivo, dentro da alçada, a aposta que entra e a oferta que é lançada, e acompanha '
        'se as hipóteses da estratégia se confirmam. Quem executa são as empresas e os outros círculos. '
        'São seis jornadas.')
PRINCIPIO = ('A regra da Identidade (padroniza; os outros executam) vale aqui em parte. A Estratégia escreve um padrão '
             'só, o método de estratégia. No resto, formula e propõe o que os sócios aprovam, decide dentro da alçada '
             'e acompanha as hipóteses.')
MUDOU_INTRO = ('Comparação com o catálogo da rodada 2 (49 jornadas e 216 workflows), que continua no documento do '
               'projeto até cada círculo ser fechado. Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')

# produtos usados em mais de uma jornada
ESTRAT = 'Estratégia vigente do Ecossistema e das empresas'
DIRECAO = 'Direção estratégica e públicos prioritários'
PORTALVO = 'Portfólio-alvo: papel de cada empresa, oferta e aposta'
HIPOT = 'Hipóteses da estratégia e sinais a vigiar'
METODO = 'Método de estratégia vigente: critérios dos portões, regras de realocação e calendário'
ALOC = 'Alocação de recursos por empresa, oferta e aposta'
ALVOS = 'Alvos e iniciativas do ciclo'
CARTEIRA = 'Situação da carteira de apostas'
SAIDA = 'Indicação de saída de empresa, oferta ou aposta'
PORTF = 'Portfólio de empresas atualizado'
CAUSAS = 'Desvios com causa concluída'
APROVADA = 'Aposta aprovada para o estágio seguinte, com recursos'
CASO = 'Caso de criação, aquisição, venda ou encerramento'
# produtos de outros círculos
DECL = 'Declaração de identidade vigente'
PADROES_ID = 'Padrões de identidade vigentes'
RELAT = 'Relatório de alinhamento'
RESULT = 'Resultado por empresa e consolidado'
EXEC_ORC = 'Execução do orçamento e da alocação por empresa, oferta e aposta'
CAIXA = 'Posição e projeção de caixa'
INDIC = 'Indicadores e análises por empresa, oferta e aposta'
RISCOS = 'Relatório de riscos e conformidade'
ALCADAS = 'Regras e alçadas vigentes'
LEITURA = 'Leitura de mercado, clientes e concorrentes'
EVID = 'Resposta com evidência sobre a aposta ou o caso'

JORNADAS = []

# ====================================================== DIREÇÃO E RECURSOS
JORNADAS.append(dict(
    code='ES-01',
    nome='Formular e revisar a estratégia do Ecossistema e de cada empresa',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Ter uma estratégia escrita e aprovada, do Ecossistema e de cada empresa, que diga onde atuar, o que não fazer e para quem, com as hipóteses de cada escolha, e que sirva de critério para alocar recursos e fixar alvos. Inclui as escolhas de cada círculo e o método de estratégia.',
    frequencia='A cada ciclo estratégico (cadência a definir) e por evento: mudança relevante de cenário, empresa nova no portfólio ou revisão decidida na ES-06',
    automacao=('baixa', 'Decisão humana, de risco alto e pouco frequente. O agente reúne evidências, monta opções e confere a coerência; a escolha é de pessoas e a aprovação é dos sócios.'),
    base=['apqc', 'rumelt', 'kaplan', 'parenting', 'horizons', 'iia'],
    lanes=['INT', 'SOC', 'GOV', 'EXE', 'LCI', 'IDE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Mudança relevante de cenário apontada', 'INT', 'message'),
             I('Ciclo estratégico iniciado', 'ESR', 'timer'),
             I('Revisão da estratégia decidida', 'ESR', 'message'),
             I('Empresa nova incluída no portfólio', 'ESR', 'message')],
    fins=[F('Estratégia aprovada e publicada', 'ESR'), F('Revisão encerrada sem mudança', 'ESR')],
    etapas=[
        E('Diagnosticar o cenário e a posição atual', 'Estratégia, com sócios, executivos e líderes dos círculos', 'Copiloto', 'médio',
          [(LEITURA, 'Inteligência'), ('Aviso de mudança relevante de cenário', 'Inteligência'),
           (RESULT, 'Gestão'), (RISCOS, 'Governança'), (DECL, 'Identidade'), (RELAT, 'Identidade'),
           (ALOC, 'ES-02'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'), ('Decisão de rever a estratégia', 'ES-06')],
          [T('Abrir o ciclo com o calendário e o método vigentes', 'ESR'),
           T('Definir os participantes e as perguntas do diagnóstico', 'ESP'),
           T('Reunir os dados e montar a leitura dos ambientes externo e interno', 'ESA'),
           T('Ouvir sócios, executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir o diagnóstico: o desafio central e as suas causas', 'ESP'),
           D('O diagnóstico pede mudar a estratégia?', 'ESP',
             [S('Sim', 'prox'),
              S('Só falta a estratégia de uma empresa nova', 'E3'),
              S('Não', 'F2', via=[T('Registrar o diagnóstico e a decisão de manter a estratégia', 'ESR')])])],
          [('Diagnóstico estratégico', ['etapa 2', 'etapa 3']),
           ('Perguntas do diagnóstico', ['Inteligência'])]),
        E('Formular as escolhas do Ecossistema: onde atuar e o que não fazer', 'Estratégia, com os executivos', 'Copiloto', 'alto',
          [('Diagnóstico estratégico', 'etapa 1'), ('Decisão dos sócios sobre a estratégia', 'etapa 4'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), ('Resposta à consulta', 'Identidade')],
          [T('Montar opções estratégicas e simular as consequências de cada uma', 'ESA'),
           T('Discutir as opções com os executivos', 'ESP', 'manual'),
           T('Escolher onde atuar, o que não fazer e a política que orienta as ações', 'ESP'),
           T('Definir o portfólio-alvo: o papel de cada empresa, oferta e aposta', 'ESP'),
           T('Escrever as hipóteses de cada escolha e os sinais que as confirmam ou refutam', 'ESP'),
           T('Definir os critérios dos portões e as regras de realocação', 'ESP'),
           T('Conferir as escolhas com a declaração e os critérios de decisão da identidade', 'ESA'),
           D('As escolhas são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E2'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira das escolhas estratégicas', 'IDE', 'call')])]),
           D('A Identidade considera as escolhas coerentes?', 'ESP', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Escolhas estratégicas e portfólio-alvo do Ecossistema', ['etapa 3']),
           ('Consulta sobre caso não coberto', ['Identidade'])]),
        E('Formular a estratégia de cada empresa e as escolhas de cada círculo', 'Executivos e líderes dos círculos, com Estratégia', 'Copiloto', 'médio',
          [('Escolhas estratégicas e portfólio-alvo do Ecossistema', 'etapa 2'), ('Diagnóstico estratégico', 'etapa 1')],
          [T('Montar o rascunho da estratégia de cada empresa a partir das escolhas do Ecossistema', 'ESA'),
           PAR([T('Decidir as escolhas da empresa: público, oferta e vantagem', 'EXE')],
               [T('Propor as escolhas do círculo: o que é serviço comum, o que construir e o que comprar', 'LCI')]),
           T('Conferir a coerência entre empresas, círculos e as escolhas do Ecossistema', 'ESP'),
           D('Há conflito entre empresas, círculos ou com o Ecossistema?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Resolver o conflito com os executivos e líderes envolvidos', 'ESP', 'manual')])]),
           T('Resumir a direção e os públicos prioritários para cada círculo', 'ESA'),
           T('Aprovar o resumo por círculo e o que pode ser dito para fora', 'ESP')],
          [('Proposta de estratégia do Ecossistema e das empresas', ['etapa 4'])]),
        E('Aprovar a estratégia com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estratégia do Ecossistema e das empresas', 'etapa 3')],
          [T('Levar a proposta de estratégia à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a estratégia', 'SOC', 'manual'),
           D('Estratégia aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter a atual', 'F2', via=[T('Registrar a decisão dos sócios de manter a estratégia atual', 'ESR')])])],
          [('Decisão dos sócios sobre a estratégia', ['etapa 5', 'etapa 2', 'Governança'])]),
        E('Publicar a estratégia e avisar quem depende dela', 'Estratégia', 'Autômato', 'baixo',
          [('Decisão dos sócios sobre a estratégia', 'etapa 4')],
          [T('Registrar a versão e a data de vigência da estratégia', 'ESR'),
           T('Publicar a estratégia, o portfólio-alvo, as hipóteses e o método', 'ESR'),
           T('Avisar círculos e executivos e abrir as jornadas que dependem da estratégia', 'ESR')],
          [(ESTRAT, ['ES-02', 'ES-03', 'ES-04', 'ES-05', 'ES-06', 'Sócios', 'Executivos', 'Líderes dos círculos']),
           (DIRECAO, [TODOS, 'Identidade']),
           (PORTALVO, ['ES-02', 'ES-04', 'Executivos', 'Negócios', 'Inteligência']),
           (HIPOT, ['ES-06', 'Inteligência']),
           (METODO, ['ES-02', 'ES-03', 'ES-04', 'Executivos']),
           ('Mudança na estratégia a comunicar', ['Gestão', 'Relações'])]),
    ]))

JORNADAS.append(dict(
    code='ES-02',
    nome='Rever o portfólio e realocar recursos entre empresas, ofertas e apostas',
    dominio='Direção e recursos', classe='essencial', onda=2,
    objetivo='Decidir, a cada período, para onde vão dinheiro, pessoas e atenção: o que recebe mais, o que mantém, o que perde recursos e o que deve ter a saída estudada, e o destino do resultado de cada empresa.',
    frequencia='A cada fechamento de período (cadência a definir) e por evento: estratégia nova ou revisão decidida na ES-06',
    automacao=('média', 'O agente compara o uso de recursos com o portfólio-alvo e simula realocações; a proposta é de pessoas e a decisão é dos sócios.'),
    base=['realloc', 'horizons', 'parenting', 'iia', 'apqc'],
    lanes=['GES', 'ASS', 'GOV', 'SOC', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Resultado do período fechado', 'GES', 'message'),
             I('Nova estratégia publicada', 'ESR', 'message'),
             I('Revisão do portfólio decidida', 'ESR', 'message')],
    fins=[F('Alocação decidida e comunicada', 'ESR'), F('Revisão encerrada sem realocação', 'ESR')],
    etapas=[
        E('Ler o resultado e o uso de recursos de cada unidade do portfólio', 'Estratégia, com os executivos', 'Copiloto', 'baixo',
          [(RESULT, 'Gestão'), (EXEC_ORC, 'Gestão'), (INDIC, 'Inteligência'),
           (ESTRAT, 'ES-01'), (PORTALVO, 'ES-01'), (ALVOS, 'ES-03'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'),
           ('Caso arquivado com o motivo', 'ES-05'), (CAUSAS, 'ES-06'), ('Decisão de rever o portfólio', 'ES-06')],
          [T('Comparar resultado e recursos usados com o papel de cada unidade no portfólio-alvo', 'ESA'),
           T('Interpretar a leitura com cada executivo', 'ESP', 'manual')],
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', ['etapa 2', 'Inteligência'])]),
        E('Propor a realocação e o destino do resultado', 'Estratégia, com assessoria', 'Copiloto', 'médio',
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', 'etapa 1'),
           ('Decisão de alocação e de destino do resultado', 'etapa 3'),
           (CAIXA, 'Gestão'), (METODO, 'ES-01'), (PADROES_ID, 'Identidade')],
          [T('Classificar cada unidade: semear, nutrir, podar ou colher', 'ESA'),
           T('Simular realocações de dinheiro, pessoas e capacidade dos círculos', 'ESA'),
           D('Há realocação ou destino de resultado a propor?', 'ESP',
             [S('Sim', 'seg'), S('Não', 'F2', via=[T('Registrar a revisão sem realocação', 'ESR')])]),
           T('Avaliar os efeitos societários, fiscais e contábeis das alternativas', 'ASS'),
           T('Montar a proposta de realocação e de destino do resultado', 'ESP'),
           T('Conferir a proposta com os critérios de decisão da identidade', 'ESA'),
           D('A proposta muda o papel de alguma empresa, oferta ou aposta?', 'ESP',
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Combinar a mudança de papel com o executivo afetado', 'ESP', 'manual')])])],
          [('Proposta de realocação e de destino do resultado', ['etapa 3'])]),
        E('Decidir a alocação com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de realocação e de destino do resultado', 'etapa 2')],
          [T('Levar a proposta de alocação à decisão dos sócios', 'GOV', 'call'),
           T('Decidir a alocação e o destino do resultado', 'SOC', 'manual'),
           D('Alocação aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter a atual', 'F2', via=[T('Registrar a decisão dos sócios de manter a alocação atual', 'ESR')])])],
          [('Decisão de alocação e de destino do resultado', ['etapa 4', 'etapa 2', 'Governança', 'Gestão'])]),
        E('Comunicar a decisão e encaminhar a execução', 'Estratégia', 'Autopiloto', 'baixo',
          [('Decisão de alocação e de destino do resultado', 'etapa 3')],
          [T('Registrar a decisão e o limite de recursos de cada unidade', 'ESR'),
           T('Atualizar o portfólio-alvo com os papéis decididos', 'ESR'),
           T('Avisar a Gestão e os executivos da alocação decidida', 'ESR'),
           D('A decisão manda estudar a saída de empresa, oferta ou aposta?', 'ESR',
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Comunicar a indicação de saída ao executivo afetado', 'ESP', 'manual'),
                                    T('Abrir o estudo de saída: empresa na ES-05, oferta ou aposta na ES-04', 'ESR')])])],
          [(ALOC, ['ES-01', 'ES-03', 'ES-04', 'Gestão', 'Executivos']),
           (PORTALVO, ['ES-04', 'Executivos']),
           (SAIDA, ['ES-04', 'ES-05'])]),
    ]))

JORNADAS.append(dict(
    code='ES-03',
    nome='Desdobrar a estratégia em alvos e iniciativas de cada empresa e de cada círculo',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Transformar a estratégia em poucos alvos mensuráveis do Ecossistema, de cada empresa e de cada círculo, com iniciativas, dono e indicador, combinados de cima para baixo e de baixo para cima, e conferir com a Gestão se cabem no orçamento.',
    frequencia='A cada ciclo de alvos (cadência a definir) e por evento: alocação que muda alvos ou orçamento, ou correção decidida na ES-06',
    automacao=('média', 'O agente desdobra, confere a soma e aponta conflitos; a negociação dos alvos é entre pessoas e a aprovação é dos sócios.'),
    base=['kaplan', 'okr', 'lei', 'rumelt', 'iia', 'apqc'],
    lanes=['SOC', 'GOV', 'EXE', 'LCI', 'INT', 'GES', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ciclo de alvos iniciado', 'ESR', 'timer'),
             I('Alocação que muda alvos ou orçamento decidida', 'ESR', 'message'),
             I('Novo desdobramento dos alvos decidido', 'ESR', 'message')],
    fins=[F('Alvos aprovados e publicados', 'ESR'), F('Alvos anteriores mantidos', 'ESR')],
    etapas=[
        E('Propor os alvos do Ecossistema', 'Estratégia', 'Copiloto', 'médio',
          [(ESTRAT, 'ES-01'), (METODO, 'ES-01'), (ALOC, 'ES-02'), (PORTF, 'ES-05'),
           ('Decisão de corrigir os alvos', 'ES-06'), (INDIC, 'Inteligência'),
           ('Definição do que conta como impacto', 'Identidade')],
          [T('Traduzir as escolhas em poucos objetivos com resultados mensuráveis', 'ESA'),
           T('Conferir os alvos com a definição do que conta como impacto', 'ESA'),
           T('Escolher os alvos do Ecossistema e o que fica de fora', 'ESP')],
          [('Alvos propostos do Ecossistema', ['etapa 2'])]),
        E('Combinar os alvos e as iniciativas com cada empresa e cada círculo', 'Estratégia, com executivos, líderes dos círculos e Inteligência', 'Copiloto', 'médio',
          [('Alvos propostos do Ecossistema', 'etapa 1'), ('Decisão dos sócios sobre alvos e orçamento', 'etapa 4')],
          [PAR([T('Propor os alvos e as iniciativas da empresa', 'EXE')],
               [T('Propor os alvos e as iniciativas do círculo', 'LCI')]),
           T('Conferir a soma, os conflitos e as dependências entre os alvos', 'ESA'),
           T('Conferir se cada alvo tem indicador, fonte e linha de base', 'INT'),
           T('Negociar os ajustes com executivos e líderes dos círculos', 'ESP', 'manual'),
           D('Os alvos somam e não conflitam?', 'ESP',
             [S('Sim', 'prox'), S('Não, renegociar', 'E2'),
              S('Não, sem acordo', 'prox', via=[T('Registrar a divergência para decisão dos sócios', 'ESP')])])],
          [('Alvos e iniciativas combinados', ['etapa 3'])]),
        E('Conferir com a Gestão e a Integração se os alvos cabem nos recursos', 'Estratégia, com Gestão e Integração', 'Copiloto', 'médio',
          [('Alvos e iniciativas combinados', 'etapa 2'), (CAIXA, 'Gestão')],
          [T('Montar o orçamento do ciclo a partir dos alvos e da alocação', 'GES', 'call'),
           T('Conferir a capacidade de executar as iniciativas na carteira de projetos', 'ITG'),
           T('Apontar o que não cabe no orçamento ou na capacidade', 'ESA'),
           D('Alvos e iniciativas cabem nos recursos?', 'ESP', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão', ['etapa 4'])]),
        E('Aprovar os alvos e o orçamento com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão', 'etapa 3')],
          [T('Levar a proposta de alvos e orçamento à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre os alvos e o orçamento', 'SOC', 'manual'),
           D('Alvos e orçamento aprovados?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter os atuais', 'F2', via=[T('Registrar a decisão dos sócios de manter os alvos atuais', 'ESR')])])],
          [('Decisão dos sócios sobre alvos e orçamento', ['etapa 5', 'etapa 2', 'Governança', 'Gestão'])]),
        E('Publicar os alvos e entregar ao ritual de acompanhamento', 'Estratégia, com Gestão', 'Autopiloto', 'baixo',
          [('Decisão dos sócios sobre alvos e orçamento', 'etapa 4')],
          [T('Registrar alvos, iniciativas, donos e indicadores no painel', 'ESR'),
           T('Avisar executivos, líderes dos círculos e donos das iniciativas', 'ESR'),
           T('Incluir os alvos no ritual de acompanhamento', 'GES')],
          [(ALVOS, [TODOS, 'ES-02', 'ES-06', 'Gestão', 'Integração', 'Inteligência'])]),
    ]))

# ====================================================== APOSTAS E EMPRESAS
JORNADAS.append(dict(
    code='ES-04',
    nome='Decidir em cada portão se uma aposta avança, espera, volta para ajuste ou é encerrada',
    dominio='Apostas e empresas', classe='essencial', onda=2,
    objetivo='Fazer cada ideia, oferta ou negócio novo passar por decisões explícitas antes de receber recursos: entrar na carteira e, depois de produtizada pela Inteligência, ser lançada. Em qualquer portão ou revisão, a aposta pode avançar, esperar, voltar para ajuste ou ser encerrada.',
    frequencia='Por evento: ideia nova, aposta definida no portfólio-alvo, oferta pronta para lançar, data de revisão da aposta ou saída indicada na ES-02',
    automacao=('alta na entrada e na preparação, baixa na decisão', 'Registrar, completar o dossiê, estimar e encaminhar rodam com agente e automação; a decisão do portão é de pessoas.'),
    base=['stagegate', 'horizons', 'dmn', 'apqc'],
    lanes=['SOL', 'INT', 'GOV', 'SOC', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ideia ou aposta nova recebida', 'SOL', 'message'),
             I('Oferta pronta para lançamento recebida', 'INT', 'message'),
             I('Aposta nova definida no portfólio-alvo', 'ESR', 'message'),
             I('Saída de oferta ou aposta indicada no portfólio', 'ESR', 'message'),
             I('Data de revisão da aposta atingida', 'ESR', 'timer')],
    fins=[F('Aposta aprovada para o estágio seguinte', 'ESR'),
          F('Aposta encerrada com lição registrada', 'ESR'),
          F('Aposta em espera', 'ESR'),
          F('Aposta devolvida para ajuste', 'ESR')],
    etapas=[
        E('Registrar a aposta e completar o dossiê', 'Estratégia', 'Autopiloto', 'baixo',
          [('Ideia ou aposta nova', 'Solicitante'), ('Pacote da oferta pronta para lançamento', 'Inteligência'),
           (PORTALVO, 'ES-01'), (PORTALVO, 'ES-02'), (SAIDA, 'ES-02')],
          [T('Registrar a aposta e o portão pedido', 'ESR'),
           T('Completar o dossiê: problema, público, hipótese, dono, estágio e recursos pedidos', 'ESA'),
           D('O dossiê tem o mínimo para avaliar?', 'ESA',
             [S('Sim', 'prox'),
              S('Não', 'F4', via=[T('Devolver a aposta a quem propôs com o que falta', 'ESR')])])],
          [('Dossiê da aposta', ['etapa 2']),
           ('Aposta devolvida com o que falta', ['Solicitante', 'Inteligência'])]),
        E('Avaliar a aposta contra os critérios do portão', 'Estratégia', 'Copiloto', 'médio',
          [('Dossiê da aposta', 'etapa 1'), (EVID, 'Inteligência'), (ESTRAT, 'ES-01'), (METODO, 'ES-01'),
           (ALOC, 'ES-02'), (PADROES_ID, 'Identidade')],
          [T('Estimar tamanho, esforço, risco e retorno com a evidência disponível', 'ESA'),
           T('Conferir o encaixe com a estratégia, o portfólio-alvo e os critérios da identidade', 'ESA'),
           T('Conferir os recursos pedidos contra o limite da alocação vigente', 'ESR', 'rule'),
           T('Conferir a evidência contra o critério do portão', 'ESP'),
           T('Recomendar a decisão do portão', 'ESP')],
          [('Avaliação da aposta com recomendação', ['etapa 3'])]),
        E('Decidir o destino da aposta no portão', 'Estratégia com o executivo, ou os sócios', 'Assistido', 'alto',
          [('Avaliação da aposta com recomendação', 'etapa 2'), (ALCADAS, 'Governança')],
          [T('Aplicar a tabela de alçadas aos recursos pedidos', 'ESR', 'rule'),
           T('Apresentar a avaliação e a recomendação a quem decide', 'ESP', 'manual'),
           D('A decisão passa da alçada da Estratégia?', 'ESR',
             [S('Não', 'seg', via=[T('Decidir o destino da aposta com o executivo, dentro da alçada', 'ESP', 'manual')]),
              S('Sim', 'seg', via=[T('Levar a aposta à decisão dos sócios', 'GOV', 'call'),
                                   T('Decidir o destino da aposta pelos sócios', 'SOC', 'manual')])]),
           D('Qual é a decisão do portão?', 'ESR',
             [S('Avança', 'prox'),
              S('Encerra', 'F2', via=[T('Registrar na carteira o motivo e a lição da aposta encerrada', 'ESA')]),
              S('Espera', 'F3', via=[T('Registrar na carteira a condição e a data de retomada', 'ESR')]),
              S('Volta para ajuste', 'F4', via=[T('Devolver a aposta com os ajustes pedidos', 'ESR')])])],
          [('Decisão do portão', ['etapa 4', 'Governança']),
           ('Lição da aposta encerrada', ['Inteligência', 'Solicitante']),
           ('Recursos da aposta encerrada a devolver', ['Gestão']),
           ('Aposta em espera ou devolvida', ['Solicitante', 'Inteligência']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
        E('Registrar a decisão e passar a aposta ao dono do estágio seguinte', 'Estratégia', 'Autômato', 'baixo',
          [('Decisão do portão', 'etapa 3')],
          [T('Registrar na carteira a decisão, os recursos aprovados e a data da próxima revisão', 'ESR'),
           D('Qual é o estágio seguinte?', 'ESR',
             [S('Desenho e validação da oferta', 'seg', via=[T('Passar a aposta à Inteligência para desenhar e validar a oferta', 'ESR')]),
              S('Lançamento', 'seg', via=[T('Passar a oferta aprovada ao executivo, a Relações e a Negócios', 'ESR')]),
              S('Empresa própria', 'seg', via=[T('Abrir a jornada de criação de empresa', 'ESR')])]),
           T('Avisar a Gestão dos recursos aprovados', 'ESR')],
          [(APROVADA, ['Inteligência', 'ES-05']),
           ('Oferta aprovada no portfólio', ['Executivos', 'Relações', 'Negócios', 'Inteligência']),
           ('Recursos aprovados para a aposta', ['Gestão']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
    ]))

JORNADAS.append(dict(
    code='ES-05',
    nome='Decidir e estruturar a criação, a aquisição, a venda ou o encerramento de uma empresa',
    dominio='Apostas e empresas', classe='essencial', onda=3,
    objetivo='Decidir com um caso escrito se o Ecossistema cria, adquire, vende ou encerra uma empresa, propor a estrutura, obter a decisão dos sócios, emitir o mandato para os círculos que executam e conferir o cumprimento. Fusão e cisão seguem o mesmo fluxo.',
    frequencia='Rara: por evento',
    automacao=('baixa', 'Decisão dos sócios, rara e de risco alto. O agente monta o caso, os cenários e o mandato e confere a execução.'),
    base=['apqc', 'parenting', 'realloc', 'iia'],
    lanes=['SOL', 'SOC', 'ASS', 'GOV', 'GES', 'IDE', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Oportunidade de aquisição ou de venda recebida', 'SOL', 'message'),
             I('Aposta que pede empresa própria aprovada', 'ESR', 'message'),
             I('Saída de empresa indicada no portfólio', 'ESR', 'message')],
    fins=[F('Mandato cumprido e portfólio atualizado', 'ESR'), F('Caso arquivado com o motivo', 'ESR')],
    etapas=[
        E('Montar o caso: por que criar, adquirir, vender ou encerrar', 'Estratégia, com quem propôs', 'Copiloto', 'médio',
          [(APROVADA, 'ES-04'), (SAIDA, 'ES-02'), ('Oportunidade de aquisição ou de venda', 'Solicitante'),
           (ESTRAT, 'ES-01'), (EVID, 'Inteligência'), (RESULT, 'Gestão'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade')],
          [T('Montar o caso e os cenários, incluindo a alternativa de não mudar', 'ESA'),
           T('Conferir se o caso cabe na estratégia e nos critérios de decisão da identidade', 'ESA'),
           T('Concluir o caso com quem propôs', 'ESP'),
           D('O caso se sustenta?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'F2', via=[T('Arquivar o caso com o motivo', 'ESR')])])],
          [(CASO, ['etapa 2', 'etapa 3']),
           ('Caso arquivado com o motivo', ['Solicitante', 'Inteligência', 'ES-02'])]),
        E('Apurar e negociar com a outra parte, quando houver', 'Estratégia, com Governança e Gestão', 'Assistido', 'alto',
          [(CASO, 'etapa 1')],
          [D('O caso envolve empresa de fora ou comprador?', 'ESP', [S('Não', 'prox'), S('Sim', 'seg')]),
           T('Firmar o acordo de confidencialidade com a outra parte', 'GOV', 'call'),
           PAR([T('Apurar contratos, obrigações e riscos da empresa ou do negócio', 'GOV', 'call')],
               [T('Apurar contas e pessoas da empresa ou do negócio', 'GES', 'call')]),
           T('Negociar preço e condições com a outra parte', 'ESP', 'manual'),
           D('A apuração e a negociação mantêm o caso?', 'ESP',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Arquivar o caso com o resultado da apuração', 'ESR')])])],
          [('Resultado da apuração e termos negociados', ['etapa 3']),
           ('Caso arquivado com o resultado da apuração', ['Solicitante', 'Inteligência'])]),
        E('Propor a estrutura societária e de governança', 'Estratégia, com Governança e assessoria', 'Copiloto', 'alto',
          [(CASO, 'etapa 1'), ('Resultado da apuração e termos negociados', 'etapa 2'),
           ('Decisão dos sócios sobre a empresa', 'etapa 4'), ('Pedido de mudança do mandato', 'etapa 6'),
           (ALCADAS, 'Governança')],
          [T('Comparar estruturas societárias e de governança', 'ESA'),
           T('Avaliar os efeitos jurídicos, fiscais e contábeis', 'ASS'),
           T('Conferir a estrutura com as regras e os riscos', 'GOV'),
           T('Decidir a estrutura e o executivo a propor', 'ESP')],
          [('Proposta de estrutura', ['etapa 4'])]),
        E('Aprovar o caso e a estrutura com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estrutura', 'etapa 3')],
          [T('Levar o caso e a estrutura à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a criação, a aquisição, a venda ou o encerramento', 'SOC', 'manual'),
           D('Proposta aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E3'),
              S('Não, arquivar', 'F2', via=[T('Registrar a decisão de não seguir e o motivo', 'ESR')])])],
          [('Decisão dos sócios sobre a empresa', ['etapa 5', 'etapa 3', 'Governança'])]),
        E('Emitir o mandato para os círculos que executam', 'Estratégia', 'Copiloto', 'médio',
          [('Decisão dos sócios sobre a empresa', 'etapa 4')],
          [T('Redigir o mandato: objetivo, estrutura, recursos, prazos e donos', 'ESA'),
           T('Definir com a Gestão o responsável e a equipe da execução', 'ESP', 'manual'),
           T('Aprovar o mandato', 'ESP'),
           D('Qual é o caso?', 'ESR',
             [S('Criação ou aquisição', 'seg', via=[T('Pedir a identidade e a marca da empresa', 'ESR')]),
              S('Venda ou encerramento', 'seg', via=[T('Pedir o plano de saída: clientes, contratos e pessoas', 'ESR')])]),
           T('Enviar o mandato a cada círculo que executa', 'ESR')],
          [('Mandato da empresa', ['etapa 6', 'Integração', 'Governança', 'Gestão', 'Relações', 'Executivos']),
           ('Pedido de identidade para empresa nova', ['Identidade']),
           ('Pedido de marca', ['Identidade']),
           ('Lista de pessoas da empresa adquirida', ['Gestão']),
           ('Pedido de plano de saída: clientes, contratos e pessoas', ['Relações', 'Governança', 'Gestão'])]),
        E('Acompanhar a execução do mandato até a empresa operar ou sair do portfólio', 'Integração, com Estratégia', 'Copiloto', 'alto',
          [('Mandato da empresa', 'etapa 5'), ('Situação da execução do mandato', 'Integração'),
           ('Decisão sobre a marca do negócio', 'Identidade'), ('Pacote de marca publicado', 'Identidade'),
           (DECL, 'Identidade')],
          [T('Coordenar a execução do mandato entre os círculos', 'ITG', 'call'),
           D('É criação ou aquisição?', 'ESR',
             [S('Sim', 'seg', via=[T('Entregar a identidade e a marca da empresa', 'IDE', 'call')]),
              S('Não', 'seg', via=[T('Registrar a pendência de retirada da marca', 'ESR')])]),
           T('Registrar a constituição, a alteração ou o encerramento da empresa', 'GOV', 'call'),
           PAR([T('Prover ou desmobilizar responsável, pessoas, contas e orçamento', 'GES', 'call')],
               [T('Ligar a empresa aos círculos ou desligá-la: acessos, acordos de serviço e rateio', 'ITG')]),
           T('Conferir a execução contra o mandato', 'ESA'),
           D('Mandato cumprido?', 'ESP',
             [S('Sim', 'seg'), S('Não, falta executar', 'E6'), S('Não, o mandato precisa mudar', 'E3')]),
           T('Atualizar o portfólio e o ciclo de alvos', 'ESR')],
          [(PORTF, ['ES-01', 'ES-02', 'ES-03', 'Identidade', 'Inteligência', 'Gestão', 'Governança']),
           ('Pedido de mudança do mandato', ['etapa 3']),
           ('Pendência de retirada da marca', ['Governança'])]),
    ]))

# ========================================================== ACOMPANHAMENTO
JORNADAS.append(dict(
    code='ES-06',
    nome='Acompanhar a execução da estratégia e corrigir o rumo',
    dominio='Acompanhamento', classe='essencial', onda=1,
    objetivo='Saber a cada revisão se a estratégia está sendo executada e se as hipóteses continuam de pé, separar falha de execução de hipótese errada, decidir as correções e prestar contas aos sócios.',
    frequencia='A cada revisão da estratégia (cadência a definir) e por evento, quando o ritual da Gestão aponta desvio grave',
    automacao=('média', 'O agente reúne os resultados, compara com os alvos e as hipóteses e propõe causas; a Inteligência contesta com os dados; a decisão de corrigir é de pessoas.'),
    base=['kaplan', 'apqc'],
    lanes=['GES', 'INT', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Desvio grave apontado pelo ritual', 'GES', 'message'),
             I('Ciclo de revisão da estratégia iniciado', 'ESR', 'timer')],
    fins=[F('Revisão concluída com correções encaminhadas', 'ESR'), F('Revisão concluída sem correção', 'ESR')],
    etapas=[
        E('Reunir os resultados contra os alvos e as hipóteses', 'Estratégia', 'Autopiloto', 'baixo',
          [(ALVOS, 'ES-03'), (ESTRAT, 'ES-01'), (HIPOT, 'ES-01'), (CARTEIRA, 'ES-04'),
           ('Desvios e decisões do ritual de acompanhamento', 'Gestão'), (INDIC, 'Inteligência'),
           (LEITURA, 'Inteligência'), ('Situação das iniciativas na carteira de projetos', 'Integração'),
           (RISCOS, 'Governança')],
          [T('Reunir resultados, desvios, sinais e situação das iniciativas', 'ESR'),
           T('Comparar o resultado com os alvos e os sinais com as hipóteses', 'ESA')],
          [('Painel da estratégia: alvos, resultados, hipóteses e sinais', ['etapa 2'])]),
        E('Separar falha de execução de hipótese errada', 'Estratégia, com Inteligência, executivos e líderes dos círculos', 'Copiloto', 'médio',
          [('Painel da estratégia: alvos, resultados, hipóteses e sinais', 'etapa 1')],
          [T('Propor a causa de cada desvio: execução, recurso, alvo ou hipótese', 'ESA'),
           T('Contestar as causas propostas com os dados medidos', 'INT'),
           T('Discutir as causas com executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir a causa de cada desvio', 'ESP'),
           D('Há correção a fazer?', 'ESP',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a revisão sem correção e avisar quem apontou o desvio', 'ESR')])])],
          [(CAUSAS, ['etapa 3', 'ES-02']),
           ('Revisão sem correção registrada', ['Gestão', 'Sócios'])]),
        E('Decidir as correções', 'Estratégia, com os executivos', 'Copiloto', 'médio',
          [(CAUSAS, 'etapa 2')],
          [T('Propor alternativas de correção e o efeito de cada uma', 'ESA'),
           T('Decidir as correções com os executivos', 'ESP', 'manual'),
           D('Há correção na execução?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Pedir o plano de correção ao dono da execução', 'ESR')])]),
           D('Há correção nos alvos?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Abrir novo desdobramento dos alvos', 'ESR')])]),
           D('Há correção nos recursos ou no portfólio?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Abrir a revisão do portfólio', 'ESR')])]),
           D('A hipótese da estratégia falhou?', 'ESP',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Abrir a revisão da estratégia', 'ESR')])])],
          [('Correções decididas, com dono e prazo', ['etapa 4']),
           ('Pedido de plano de correção', ['Executivos', 'Líderes dos círculos', 'Gestão']),
           ('Decisão de corrigir os alvos', ['ES-03']),
           ('Decisão de rever o portfólio', ['ES-02']),
           ('Decisão de rever a estratégia', ['ES-01'])]),
        E('Registrar as correções e prestar contas da revisão', 'Estratégia', 'Autopiloto', 'baixo',
          [('Correções decididas, com dono e prazo', 'etapa 3')],
          [T('Registrar correções, donos e prazos no painel', 'ESR'),
           T('Resumir o resultado e as lições da revisão', 'ESA'),
           T('Avisar círculos e executivos afetados e enviar o resultado aos sócios', 'ESR')],
          [('Correções da estratégia publicadas, com dono e prazo', [TODOS, 'Gestão']),
           ('Resultado da revisão da estratégia', ['Sócios', 'Governança']),
           ('Lições da revisão da estratégia', ['Inteligência'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Direção e recursos', 'Escolher onde atuar, alocar os recursos e fixar os alvos.'),
    ('Apostas e empresas', 'Decidir o que entra, o que avança e o que sai do portfólio.'),
    ('Acompanhamento', 'Conferir se a estratégia é executada e se continua certa.'),
]

ONDAS = {
    1: 'O que o modelo precisa para rodar: direção, alvos e correção de rumo',
    2: 'O que cuida do portfólio e das apostas',
    3: 'O que roda por evento raro',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4, categoria 1.0, Develop Vision and Strategy, com quatro grupos: 1.1, conceito de negócio e visão de longo prazo; 1.2, estratégia de negócio; 1.3, iniciativas estratégicas; 1.4, modelos de negócio. A tabela de cobertura, na aba Método, mostra onde cada processo foi parar: nas seis jornadas ou em outro círculo.',
    'kaplan': 'Sistema de gestão em cinco estágios: desenvolver a estratégia, traduzir a estratégia, planejar as operações, monitorar e aprender, testar e adaptar a estratégia. Os autores descrevem três tipos de reunião (revisão operacional, revisão da estratégia e teste e adaptação da estratégia) e pedem pautas distintas para a revisão operacional e a da estratégia, para o curto prazo não expulsar a discussão da estratégia. Base da sequência ES-01, ES-03 e ES-06. Pôr o ritual operacional na Gestão e a revisão da estratégia neste círculo é escolha nossa: os autores dizem que as mesmas pessoas costumam participar das duas reuniões.',
    'rumelt': 'O núcleo de uma boa estratégia tem três partes: diagnóstico, política orientadora e ações coerentes. Um dos sinais de estratégia ruim é confundir alvos com estratégia. Base das etapas 1 e 2 da ES-01 e da separação entre formular (ES-01) e fixar alvos (ES-03).',
    'okr': 'Objetivos ambiciosos e resultados-chave mensuráveis. Base das etapas 1 e 2 da ES-03.',
    'lei': 'Desdobramento da estratégia (hoshin kanri): alinha as funções e atividades da organização, na vertical e na horizontal, com os objetivos estratégicos, num processo de cima para baixo e de baixo para cima. O verbete chama esse diálogo de catchball. Base da etapa 2 da ES-03.',
    'horizons': 'Três horizontes de crescimento, geridos ao mesmo tempo: o negócio principal de hoje (horizonte 1), as oportunidades emergentes (horizonte 2) e as ideias de crescimento futuro (horizonte 3). Usado para dar papel a cada unidade no portfólio-alvo (ES-01 e ES-02) e para situar as apostas (ES-04).',
    'parenting': 'Duas perguntas que, segundo os autores, a maioria dos executivos-chefes deixa de responder na estratégia corporativa: que negócios esta empresa, e não as rivais, deve ter, e por quê; e que estrutura organizacional, processos de gestão e filosofia favorecem o desempenho superior dos seus negócios. Base do portfólio-alvo na ES-01, da leitura do portfólio na ES-02 e do caso na ES-05.',
    'realloc': 'Quatro atividades de alocação: semear (entrar em área de negócio nova, por aquisição ou investimento próprio), nutrir (reforçar um negócio existente), podar (tirar recursos de um negócio existente) e colher (vender negócios inteiros que não cabem mais no portfólio ou separá-los). Quatro recomendações: ter um portfólio-alvo, usar todos os instrumentos de realocação, adotar regras simples para romper o status quo e implantar processos que reduzam a inércia. Numa amostra de mais de 1.600 empresas dos Estados Unidos, de 1990 a 2005, os autores relatam que o terço que mais realocou capital entre unidades de negócio teve, em média, retorno total ao acionista 30% maior por ano que o terço que menos realocou: 10,2% contra 7,8% ao ano, diferença relativa, não de 30 pontos percentuais. Em períodos de menos de três anos, quem mais realocou teve retorno menor. Base da ES-02 e, na venda de empresa, da ES-05.',
    'stagegate': 'O trabalho de inovação é dividido em estágios, cada um precedido de um portão. Em cada portão, gestores seniores (os gatekeepers) decidem entre Go, Kill, Hold e Recycle. A página lista os quatro resultados sem defini-los; lê-los como avançar, encerrar, esperar e voltar para ajuste é interpretação nossa. A fonte tem cinco estágios e cinco portões, de desenvolvimento de produto; a ES-04 usa a lógica, com dois portões.',
    'iia': 'No modelo, o órgão de governança presta contas pela supervisão da organização e delega responsabilidade e recursos à gestão; as três linhas ficam abaixo dele. Usado por analogia para separar o que os sócios aprovam (ES-01, ES-02, ES-03 e ES-05) do que a Estratégia propõe e decide dentro da alçada.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio e script, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'dmn': 'Padrão de modelagem de decisões, que inclui tabelas de decisão. Usado na ES-04 para a tabela de alçadas e para o limite de recursos da alocação.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# ----------------------------------- cobertura do referencial (APQC PCF 7.4, categoria 1.0)
COBERTURA = [
    ('1.1.1', 'Assess the external environment', 'ES-01, etapa 1, com a leitura da Inteligência'),
    ('1.1.2', 'Survey market and determine customer needs and wants', 'Fora: Inteligência'),
    ('1.1.3', 'Assess the internal environment', 'ES-01, etapa 1'),
    ('1.1.4', 'Establish strategic vision', 'Fora: Identidade (ID-01)'),
    ('1.1.5', 'Conduct organization restructuring opportunities', 'ES-05'),
    ('1.2.1', 'Develop overall mission statement', 'Fora: Identidade (ID-01)'),
    ('1.2.2', 'Define and evaluate strategic options to achieve the mission', 'ES-01, etapa 2'),
    ('1.2.3', 'Set/Develop long-term enterprise strategy', 'ES-01 e ES-02. Serviços compartilhados (1.2.3.6) na ES-01, etapa 3; fusão, cisão, aquisição e saída (1.2.3.3) na ES-05'),
    ('1.2.4', 'Coordinate and align cross-functional and process strategies', 'ES-01, etapa 3, e ES-03, etapa 2'),
    ('1.2.5', 'Create organizational design', 'Fora: Integração (jornadas e catálogo) e Governança (alçadas)'),
    ('1.2.6', 'Develop and set organizational objectives', 'ES-03'),
    ('1.2.7', 'Formulate business unit strategies', 'ES-01, etapa 3'),
    ('1.2.8', 'Develop customer experience strategy', 'Fora e sem dono definido: é o ponto 5 para decidir'),
    ('1.2.9', 'Communicate strategies internally and externally', 'Fora: Gestão, para dentro, e Relações, para fora. A ES-01 entrega o que comunicar'),
    ('1.3.1 a 1.3.3', 'Develop strategic initiatives; Evaluate strategic initiatives; Select strategic initiatives', 'ES-03, para as iniciativas dos alvos; ES-04, para as apostas'),
    ('1.3.4', 'Establish high-level measures', 'ES-03, etapa 2, com a Inteligência'),
    ('1.3.5', 'Execute strategic initiatives', 'Fora: executivos e círculos; os projetos ficam na Integração'),
    ('1.3.6 e 1.3.7', 'Review execution of strategic initiatives; Refine strategic initiatives and project plans as needed', 'ES-06'),
    ('1.4', 'Develop and maintain business models', 'Fora: Inteligência, pela decisão D4 da rodada 2'),
]

# --------------------------------------------------- o que a Estratégia não faz
FRONTEIRAS = [
    ('Definir propósito, valores, marca e posicionamento', 'Identidade',
     'A direção e os públicos prioritários. Confere as próprias escolhas com a declaração e os critérios de decisão da Identidade.'),
    ('Ler mercado, clientes e concorrentes e medir indicadores', 'Inteligência',
     'As perguntas do diagnóstico, as hipóteses e os sinais a vigiar (ES-01) e os alvos que precisam de indicador (ES-03).'),
    ('Produtizar a oferta e desenhar o modelo de negócio', 'Inteligência',
     'A decisão em cada portão: a aposta que entra e a oferta que é lançada (ES-04).'),
    ('Executar a estratégia da empresa', 'Executivo da empresa',
     'O método de estratégia, o papel da empresa no portfólio-alvo e a conferência de coerência entre as empresas (ES-01).'),
    ('Montar e controlar o orçamento', 'Gestão',
     'A alocação por empresa, oferta e aposta (ES-02) e os alvos e iniciativas (ES-03).'),
    ('Rodar o ritual de acompanhamento dos alvos', 'Gestão',
     'Os alvos, as iniciativas e os donos (ES-03). Recebe de volta os desvios e as decisões do ritual.'),
    ('Executar aportes, distribuição de resultado e ajustes de orçamento', 'Gestão',
     'A decisão de alocação e de destino do resultado (ES-02).'),
    ('Definir e aplicar o critério de rateio do custo dos círculos', 'Governança define, com a Estratégia; Gestão aplica',
     'O que é serviço comum a todas as empresas e o que é de cada uma (ES-01, etapa 3).'),
    ('Gerir os projetos das iniciativas e coordenar a implantação de empresa', 'Integração',
     'As iniciativas aprovadas (ES-03) e o mandato da empresa (ES-05).'),
    ('Constituir, alterar e encerrar empresas; registrar as decisões dos sócios; definir as alçadas', 'Governança',
     'O caso, a proposta de estrutura e cada proposta que sobe aos sócios.'),
    ('Captar dinheiro de fora ou admitir sócio numa empresa', 'Sócios, com Governança e Gestão',
     'O caso e a proposta de estrutura, quando a operação muda o portfólio (ES-05).'),
    ('Priorizar parceiros e gerar demanda', 'Relações',
     'A direção, os públicos prioritários e a oferta aprovada no portfólio.'),
    ('Definir preço e política comercial', 'Negócios',
     'O papel de cada oferta no portfólio-alvo e a oferta aprovada.'),
    ('Comunicar a estratégia para dentro e para fora', 'Gestão, para dentro; Relações, para fora',
     'O resumo da direção, já com o que pode ser dito para fora, e o aviso do que mudou.'),
    ('Levar as lições entre empresas ao catálogo', 'Inteligência, com Integração',
     'A leitura do portfólio (ES-02) e as lições da revisão (ES-06).'),
]

# ------------------------------------------------------------ pontos a decidir
PONTOS = [
    ('A regra da Identidade vale para a Estratégia?',
     'Vale em parte. A Estratégia escreve um padrão só, o método de estratégia: critérios dos portões, regras de realocação e calendário. No resto, formula e propõe a direção, o portfólio, os alvos e a alocação, que os sócios aprovam; decide com o executivo, dentro da alçada, a aposta que entra e a oferta que é lançada; e acompanha se as hipóteses se confirmam. Quem executa são as empresas e os outros círculos; a Gestão monta o orçamento e roda o ritual.',
     'Com o ritual na Gestão, a Estratégia vê os desvios de segunda mão. Kaplan e Norton pedem pautas separadas para a revisão operacional e a da estratégia, mas dizem que as mesmas pessoas costumam participar das duas. A alternativa é a Estratégia conduzir as duas reuniões, com pautas separadas.'),
    ('Quem lidera a empresa nova de ponta a ponta?',
     'A Estratégia lidera até o mandato e confere o cumprimento (ES-05). A execução é de quem sabe fazer: a Governança registra, a Gestão provê pessoas e contas, a Identidade entrega identidade e marca, e a Integração coordena como projeto.',
     'A troca de dono no meio da jornada é um ponto de risco: ninguém responde pelo todo. A alternativa é um dono só até a empresa operar, com responsável nomeado no mandato; nesse caso a etapa 6 passa a ser da Estratégia.'),
    ('Quais decisões sobem para os sócios?',
     'Três recorrentes e uma por evento: a estratégia (ES-01), a alocação e o destino do resultado (ES-02), os alvos e o orçamento (ES-03) e criar, adquirir, vender ou encerrar empresa (ES-05). Os portões das apostas (ES-04) só sobem quando passam da alçada da Estratégia.',
     'Três aprovações recorrentes podem travar o ciclo. A alternativa é os sócios aprovarem a estratégia e a alocação, e os alvos ficarem com os executivos dentro do limite aprovado. Falta também dizer quem são os sócios em cada caso: os do Ecossistema ou os de cada empresa. As alçadas e essa distinção ficam para o círculo 9, Governança.'),
    ('Quantos portões uma aposta atravessa?',
     'Dois, pela sua decisão D4: a entrada na carteira e o lançamento. A validação com clientes é marco da jornada da Inteligência; a escala é do executivo, dentro do orçamento; encerrar é resultado possível de qualquer portão ou revisão.',
     'Um terceiro portão, antes da validação com clientes, protegeria os recursos gastos em pilotos. A referência de estágios e portões usa cinco, do conceito ao lançamento de um produto. Sem volume de apostas medido, não há base para pôr mais de dois.'),
    ('Quem responde pela estratégia de experiência do cliente?',
     'Relações, por ser dona das relações com clientes antes e depois do contrato; Operações entra com os níveis de serviço. O referencial trata o tema como processo de estratégia (1.2.8); aqui ele não está em nenhuma jornada da Estratégia.',
     'A experiência é feita na entrega: a alternativa é Operações liderar. Pode ser decidido quando os círculos 4 e 7 forem desenhados.'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'C1 · Da estratégia ao resultado', 'ES-01, ES-03 e ES-06',
     'Dividida em formular, desdobrar e acompanhar. O ritual de acompanhamento (W-C1.4) continua na Gestão.'),
    ('Ajustado', 'E4 · Do resultado da empresa à decisão do Ecossistema', 'ES-02',
     'Vira revisão do portfólio e realocação de recursos. Executar a decisão (W-E4.3) fica na Gestão; levar as lições ao catálogo (W-E4.4), na Inteligência.'),
    ('Ajustado', 'I-ES1 · Da ideia à aposta priorizada', 'ES-04',
     'Vira decisão por portões. A revisão da carteira (W-ES1.4) passa à ES-02, que só indica a saída; quem decide é o portão.'),
    ('Ajustado', 'W-V1.6 · Decidir o lançamento, dentro da V1', 'ES-04',
     'O lançamento vira o segundo portão. A V1 continua liderada pela Inteligência.'),
    ('Ajustado', 'E5 · Da aposta à empresa nova', 'ES-05',
     'Passa a cobrir também aquisição, venda e encerramento. Constituir e registrar (W-E5.3) fica na Governança; ligar aos círculos (W-E5.5), na Integração.'),
    ('Ajustado', 'Decisão D4: a Estratégia decide a aposta que entra e a oferta que é lançada', 'ES-04',
     'Mantida, com um limite: a Estratégia decide com o executivo dentro da alçada; acima dela, decidem os sócios.'),
    ('Acrescentado', 'Sem equivalente', 'Portfólio-alvo, hipóteses e método de estratégia',
     'Três produtos novos da ES-01. O portfólio-alvo é a referência da ES-02; as hipóteses e os sinais são o que a ES-06 acompanha; o método traz os critérios dos portões e as regras de realocação.'),
    ('Acrescentado', 'Sem equivalente', 'Escolhas de cada círculo',
     'Na ES-01, etapa 3, cada líder de círculo propõe o que é serviço comum, o que construir e o que comprar.'),
    ('Acrescentado', 'Sem equivalente', 'Ponto de conferência com a identidade',
     'Na ES-01, ES-02, ES-03, ES-04 e ES-05 o agente confere as propostas com os padrões da Identidade. Na ES-01, o caso de fronteira vira consulta à ID-02.'),
    ('Acrescentado', 'Sem equivalente', 'Raia e parte “Líder do círculo”',
     'Papel novo no vocabulário do modelo: na ES-01 e na ES-03, cada líder de círculo propõe as escolhas e os alvos do seu círculo.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'Nenhuma cadência foi fixada: ciclo estratégico, período de resultado, ciclo de alvos e revisão da estratégia estão como “a definir”.',
    'O método de estratégia tem lugar no desenho (ES-01), mas o conteúdo ainda não foi escrito: critérios dos portões, regras de realocação e calendário.',
    'As alçadas que separam a decisão da Estratégia da decisão dos sócios ainda não existem; serão definidas no círculo 9, Governança.',
    'A raia “Sócios” não distingue os sócios do Ecossistema dos sócios de cada empresa. Quem delibera o quê fica para o círculo 9.',
    'As trocas com a Identidade foram conferidas dos dois lados. Com os outros sete círculos, estão descritas pelo nome do círculo e serão conferidas quando cada um for desenhado.',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Na ES-05, vender ou encerrar uma empresa pede retirar a marca de uso, e a ID-03 não tem esse caminho. A pendência fica registrada com a Governança; mudar a ID-03 depende da sua aprovação, porque o círculo 1 está fechado.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = [
    'Um revisor independente leu a primeira versão das seis jornadas e apontou 33 achados, 6 graves. Todos foram tratados nesta versão; os que dependem de escolha sua viraram pontos para decidir. O grave principal: o texto dizia que a Estratégia decide, e nos fluxos quem decide são os sócios.',
    'Um segundo revisor reabriu as dez fontes deste círculo: sete confirmadas e três confirmadas em parte. As correções de redação foram aplicadas na aba Fontes.',
    'A versão corrigida passou de novo por todos os testes automáticos, mas não por uma segunda revisão independente.',
]
