# -*- coding: utf-8 -*-
"""Círculo 3 · Inteligência. Proposta em debate (01/10/2026): oito jornadas.
Regra proposta: a Inteligência responde pela evidência, pela medida, pelo método e pelo desenho da
oferta. Não decide o portfólio (Estratégia), não monta nem opera agentes (Integração) e não responde
pelo resultado que mede: cada dado e cada indicador têm um dono fora dela."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 3, 'Inteligência', 'IN', 'IN'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo3-inteligencia'
FECHADO = False
STATUS = 'Proposta em debate · 01/10/2026'
LEAD = ('A Inteligência sabe antes e melhor e transforma o que sabe em oferta. Lê o mercado, responde a quem decide, '
        'torna o dado confiável, mede os indicadores, cura as bases de conhecimento, escreve os métodos e desenha as '
        'ofertas. Não decide o portfólio (Estratégia), não monta nem opera agentes (Integração) e não responde pelo '
        'resultado que mede: cada dado e cada indicador têm um dono. São oito jornadas.')
PRINCIPIO = ('Regra proposta para o círculo: a Inteligência responde pela evidência, pela medida, pelo método e pelo '
             'desenho da oferta. Quem decide e quem executa são os outros círculos, e cada dado e cada indicador têm um '
             'dono fora dela.')
MUDOU_INTRO = ('Comparação com o catálogo da rodada 2 (49 jornadas e 216 workflows), que continua no documento do '
               'projeto até cada círculo ser fechado. Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')
COBERTURA_TXT = ('Processos do APQC PCF 7.4 ligados às funções da Inteligência, grupo a grupo: onde cada um está neste '
                 'modelo. Os nomes estão como no referencial.')

# P, A e R do próprio círculo
P, A, R = 'INP', 'INA', 'INR'

# produtos da Inteligência usados em mais de uma jornada
LEITURA = 'Leitura de mercado, clientes e concorrentes'
PLANO = 'Plano de leitura: perguntas, sinais, fontes e critério de aviso'
REGISTRO = 'Registro de perguntas, respostas e uso'
EVID = 'Resposta com evidência sobre a aposta ou o caso'
FICHA_DADO = 'Ficha do dado: definição, dono, fonte, regras de qualidade e classificação'
DADO = 'Dado confiável publicado no catálogo'
FICHAS_IND = 'Fichas dos indicadores aprovadas pelos donos'
INDIC = 'Indicadores e análises por empresa, oferta e aposta'
BASE = 'Base de conhecimento publicada'
METODO_PUB = 'Método publicado, com versão e data de revisão'
RECOM = 'Recomendação de melhoria, com evidência, ganho esperado e dono sugerido'
PACOTE = 'Pacote da oferta: escopo, entregáveis, preço-base, material e termos'
PACOTE_PORTAO = 'Pacote da oferta pronta para lançamento'
OFERTA_CAT = 'Oferta no catálogo: escopo, método, material, preço-base e indicadores'
SOLUCAO = 'Solução, método de entrega e entregáveis'
MODELO = 'Modelo de negócio, preço-base e hipóteses a validar'
# produtos de outros círculos
DECL = 'Declaração de identidade vigente'
PADROES_ID = 'Padrões de identidade vigentes'
DIRECAO = 'Direção estratégica e públicos prioritários'
PORTALVO = 'Portfólio-alvo: papel de cada empresa, oferta e aposta'
HIPOT = 'Hipóteses da estratégia e sinais a vigiar'
ALVOS = 'Alvos e iniciativas do ciclo'
PORTF = 'Portfólio de empresas atualizado'
APROVADA = 'Aposta aprovada para o estágio seguinte, com recursos'
SIGILO = 'Regras de sigilo e de dados pessoais'
AUDIT = 'Resultado da auditoria das entregas'

JORNADAS = []

# ======================================================== MERCADO E DECISÃO
JORNADAS.append(dict(
    code='IN-01',
    nome='Ler o mercado, os clientes e os concorrentes e avisar das mudanças relevantes',
    dominio='Mercado e decisão', classe='essencial', onda=1,
    objetivo='Manter uma leitura atual de mercado, clientes e concorrentes, guiada pelas perguntas de quem decide, e avisar a tempo quando um sinal muda uma hipótese da estratégia ou abre uma oportunidade.',
    frequencia='A cada ciclo de leitura (cadência a definir) e por evento: perguntas ou hipóteses novas da Estratégia, ou sinal relevante detectado',
    automacao=('média', 'Coletar, registrar, agrupar e redigir são de agente e automação; combinar as perguntas com quem decide, julgar a relevância e emitir o aviso são de pessoas.'),
    base=['cia_ciclo', 'herring', 'horizon', 'yardstick', 'apqc'],
    lanes=['EST', 'REL', 'NEG', P, A, R],
    inicios=[I('Perguntas ou hipóteses novas recebidas', 'EST', 'message'),
             I('Sinal relevante detectado', R, 'signal'),
             I('Ciclo de leitura iniciado', R, 'timer')],
    fins=[F('Leitura publicada', R), F('Leitura encerrada sem novidade', R)],
    etapas=[
        E('Combinar com quem decide as perguntas e os sinais a vigiar', 'Inteligência, com Estratégia e executivos', 'Copiloto', 'baixo',
          [('Perguntas do diagnóstico', 'Estratégia'), (HIPOT, 'Estratégia'), (PORTALVO, 'Estratégia'), (PORTF, 'Estratégia'),
           (DIRECAO, 'Estratégia'), (REGISTRO, 'IN-02'), ('Perguntas sem resposta e lacunas de fonte', 'etapa 5')],
          [T('Comparar o que abriu a leitura com o plano de leitura vigente', A),
           D('O plano de leitura precisa mudar?', P, [S('Sim', 'seg'), S('Não', 'prox')]),
           T('Listar as decisões previstas, as hipóteses e os atores do mercado a acompanhar', A),
           T('Combinar as perguntas e os sinais a vigiar com quem decide', P, 'manual'),
           T('Definir as fontes, a frequência e o critério de aviso de cada sinal', P)],
          [(PLANO, ['etapa 2', 'etapa 3'])]),
        E('Coletar sinais e dados de mercado, clientes e concorrentes', 'Inteligência, com Relações, Negócios e Operações', 'Autopiloto', 'baixo',
          [(PLANO, 'etapa 1'),
           ('Sinais de clientes, parceiros e concorrentes vistos no relacionamento', 'Relações'),
           ('Motivos de ganho e de perda de propostas', 'Negócios'),
           ('Pedidos, reclamações e incidentes de clientes', 'Operações')],
          [T('Coletar nas fontes externas o que o plano de leitura pede', A),
           T('Reunir os sinais registrados por Relações, Negócios e Operações', R),
           T('Registrar cada item com fonte, data e confiabilidade', R)],
          [('Registros de mercado com fonte, data e confiabilidade', ['etapa 3'])]),
        E('Analisar o que os sinais dizem sobre cada pergunta e cada hipótese', 'Inteligência', 'Copiloto', 'médio',
          [('Registros de mercado com fonte, data e confiabilidade', 'etapa 2'), (PLANO, 'etapa 1'), (INDIC, 'IN-04')],
          [T('Agrupar os registros por pergunta, segmento, concorrente e tendência', A),
           T('Comparar os sinais com as hipóteses da estratégia e apontar o que mudou', A),
           T('Julgar a relevância e o grau de confiança de cada conclusão', P),
           D('Algum sinal muda uma hipótese ou pede decisão antes do próximo ciclo?', P,
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Emitir o aviso de mudança relevante a quem decide', P)])]),
           D('A análise traz algo novo para quem decide?', P,
             [S('Sim', 'prox'), S('Não', 'F2', via=[T('Registrar a análise sem novidade e arquivar os registros', R)])])],
          [('Análise de mercado por pergunta e hipótese', ['etapa 4']),
           ('Aviso de mudança relevante de cenário', ['Estratégia', 'Executivos'])]),
        E('Redigir a leitura e conferi-la com quem está perto do cliente', 'Inteligência, com Relações e Negócios', 'Copiloto', 'médio',
          [('Análise de mercado por pergunta e hipótese', 'etapa 3')],
          [T('Redigir a leitura: resposta a cada pergunta, com evidência e grau de confiança', A),
           PAR([T('Conferir a leitura com o que se vê no relacionamento com os públicos', 'REL')],
               [T('Conferir a leitura com o que se vê nas vendas', 'NEG')]),
           T('Aprovar a leitura e declarar o que continua incerto', P),
           D('A leitura aponta oportunidade que vale virar aposta?', P,
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Enviar a oportunidade à Estratégia como ideia de aposta', R)])])],
          [('Leitura aprovada', ['etapa 5']),
           ('Ideia ou aposta nova', ['Estratégia'])]),
        E('Publicar a leitura e registrar o que ficou sem resposta', 'Inteligência', 'Autômato', 'baixo',
          [('Leitura aprovada', 'etapa 4')],
          [T('Publicar a leitura e avisar quem depende dela', R),
           T('Registrar as perguntas sem resposta e as lacunas de fonte para o próximo plano', R)],
          [(LEITURA, ['Identidade', 'Estratégia', 'Relações', 'Negócios', 'Executivos', 'IN-02', 'IN-07']),
           ('Perguntas sem resposta e lacunas de fonte', ['etapa 1'])]),
    ]))

JORNADAS.append(dict(
    code='IN-02',
    nome='Responder a perguntas de decisão com evidência',
    dominio='Mercado e decisão', classe='essencial', onda=1,
    objetivo='Dar a quem vai decidir uma resposta com fonte e grau de confiança, dentro do prazo combinado, e guardar a pergunta, a resposta e o uso para que a próxima seja mais rápida.',
    frequencia='Por evento: cada pergunta de quem vai decidir, de qualquer círculo, empresa ou portão. O volume não foi medido',
    automacao=('alta', 'Registrar, buscar, avaliar, montar e entregar a resposta rodam com agente e automação. A pessoa entra quando falta evidência ou quando a decisão apoiada é de risco alto.'),
    base=['cebma', 'yardstick'],
    lanes=['SOL', P, A, R],
    inicios=[I('Pergunta de decisão recebida', 'SOL', 'message')],
    fins=[F('Pergunta respondida e registrada', R)],
    etapas=[
        E('Receber a pergunta e torná-la respondível', 'Inteligência', 'Autopiloto', 'baixo',
          [('Pergunta de decisão, com a decisão apoiada, o risco e o prazo', 'Solicitante'), (BASE, 'IN-05')],
          [T('Registrar a pergunta, quem decide, a decisão apoiada, o risco e o prazo', R),
           T('Reescrever a pergunta de forma respondível e procurar resposta já registrada', A),
           D('Já existe resposta válida para a pergunta?', A,
             [S('Não', 'prox'),
              S('Sim', 'E4', via=[T('Conferir se a resposta registrada continua válida e atualizar a data', A)])])],
          [('Pergunta respondível registrada', ['etapa 2']),
           ('Resposta já registrada e ainda válida', ['etapa 4'])]),
        E('Buscar a evidência e avaliar se é confiável', 'Inteligência', 'Autopiloto', 'baixo',
          [('Pergunta respondível registrada', 'etapa 1'), (DADO, 'IN-03'), (INDIC, 'IN-04'), (BASE, 'IN-05'), (LEITURA, 'IN-01')],
          [T('Buscar a evidência nos dados, nos indicadores, na base de conhecimento e na leitura de mercado', A),
           T('Avaliar a confiabilidade e a relevância de cada evidência', A),
           D('A evidência basta para responder no prazo?', A, [S('Sim', 'prox'), S('Não', 'seg')]),
           D('Vale coletar evidência nova antes de responder?', P,
             [S('Não, responder com a lacuna declarada', 'prox'),
              S('Sim', 'E2', via=[T('Pedir o dado que falta ao círculo dono ou coletar na fonte', P)])])],
          [('Evidência avaliada, com as lacunas', ['etapa 3'])]),
        E('Montar a resposta com fonte e grau de confiança', 'Inteligência', 'Autopiloto', 'médio',
          [('Evidência avaliada, com as lacunas', 'etapa 2')],
          [T('Pesar e reunir a evidência numa resposta com fonte, data e grau de confiança', A),
           D('A decisão apoiada é de risco alto?', R,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Revisar a resposta e o grau de confiança antes de entregar', P)])])],
          [('Resposta montada, com fonte e grau de confiança', ['etapa 4'])]),
        E('Entregar a resposta e registrar para reuso', 'Inteligência', 'Autômato', 'baixo',
          [('Resposta montada, com fonte e grau de confiança', 'etapa 3'), ('Resposta já registrada e ainda válida', 'etapa 1')],
          [T('Entregar a resposta a quem perguntou, dentro do prazo', R),
           T('Registrar a pergunta, a resposta e as fontes para reuso', R),
           T('Perguntar a quem decidiu se a resposta foi usada e registrar o retorno', R)],
          [('Resposta com evidência, fonte e grau de confiança', ['Solicitante']),
           (EVID, ['Estratégia']),
           (REGISTRO, ['IN-01', 'IN-05', 'IN-08'])]),
    ]))

# ======================================== DADOS, INDICADORES E CONHECIMENTO
JORNADAS.append(dict(
    code='IN-03',
    nome='Tornar cada dado confiável: definir, validar, catalogar e classificar',
    dominio='Dados, indicadores e conhecimento', classe='essencial', onda=1,
    objetivo='Fazer com que cada dado usado em decisão, indicador ou agente tenha definição, dono, fonte, regra de qualidade e classificação de sigilo, e esteja no catálogo para pessoas e agentes. A Integração conecta a fonte, guarda o dado e controla o acesso; a Governança define o sigilo e as regras de dados pessoais.',
    frequencia='Por evento: dado ou fonte nova pedida, queda de qualidade detectada ou prazo de guarda vencido',
    automacao=('alta', 'Validar pela regra, catalogar, publicar e monitorar a qualidade rodam sem pessoa. Definir o dado com o dono e decidir a classificação são de copiloto: o agente propõe, a pessoa decide.'),
    base=['dqf', 'fair', 'lgpd', 'dmn', 'apqc'],
    lanes=['SOL', 'LCI', 'GOV', 'ITG', P, A, R],
    inicios=[I('Pedido de dado ou fonte nova recebido', 'SOL', 'message'),
             I('Queda de qualidade do dado detectada', R, 'signal'),
             I('Prazo de guarda do dado atingido', R, 'timer')],
    fins=[F('Dado publicado no catálogo', R), F('Dado retirado do catálogo', R), F('Pedido de dado recusado', R)],
    etapas=[
        E('Definir o dado com o dono: para que serve, de onde vem e que regra de qualidade vale', 'Inteligência, com o círculo dono do dado e Governança', 'Copiloto', 'alto',
          [('Pedido de dado ou de fonte nova', 'Solicitante'), ('Pedido de dado para indicador', 'IN-04'),
           (SIGILO, 'Governança'), ('Queda de qualidade apontada pelo monitoramento', 'etapa 4')],
          [T('Localizar o dado no catálogo e registrar o que abriu o trabalho', R),
           D('O que o trabalho exige?', R,
             [S('Dado ou fonte nova', 'seg'),
              S('Correção de dado já catalogado', 'E3'),
              S('Retirada de dado com prazo de guarda vencido', 'F2',
                via=[T('Arquivar ou eliminar o dado e retirar os acessos', 'ITG'),
                     T('Registrar a retirada no catálogo e avisar quem usava o dado', R)])]),
           T('Propor a definição do dado, a fonte, as regras de qualidade e a classificação de sigilo', A),
           T('Confirmar a definição e assumir a responsabilidade pelo dado', 'LCI'),
           T('Decidir a classificação de sigilo e de dado pessoal pela regra da Governança', P),
           D('O dado é pessoal ou sigiloso?', P,
             [S('Não', 'prox'),
              S('Sim', 'seg', via=[T('Conferir a finalidade, a necessidade e a regra de sigilo do tratamento', 'GOV')])]),
           D('O tratamento do dado é permitido pelas regras?', 'GOV',
             [S('Sim', 'prox'),
              S('Não', 'F3', via=[T('Registrar a recusa com o motivo e avisar quem pediu', R)])])],
          [(FICHA_DADO, ['etapa 2', 'etapa 3', 'etapa 4']),
           ('Dado retirado do catálogo', ['Integração', 'Governança', TODOS]),
           ('Pedido de dado recusado com o motivo', ['Solicitante'])]),
        E('Conectar a fonte e receber o dado bruto', 'Integração, com Inteligência', 'Autopiloto', 'baixo',
          [(FICHA_DADO, 'etapa 1')],
          [T('Conectar a fonte e guardar o dado bruto com o acesso da classificação', 'ITG'),
           T('Conferir se o dado recebido corresponde à ficha', A)],
          [('Dado bruto conferido com a ficha', ['etapa 3'])]),
        E('Validar e corrigir o dado pelas regras de qualidade', 'Inteligência', 'Autômato', 'baixo',
          [('Dado bruto conferido com a ficha', 'etapa 2'), (FICHA_DADO, 'etapa 1')],
          [T('Aplicar as regras de qualidade: completo, único, consistente, atual, válido e exato', R, 'rule'),
           T('Corrigir pela regra o que a regra resolve e marcar o que sobra', R),
           D('Sobrou erro que a regra não resolve?', R,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Tratar o erro com o dono do dado ou marcar o dado como não confiável', P)])])],
          [('Dado validado, com a medida de qualidade', ['etapa 4'])]),
        E('Catalogar e publicar o dado para pessoas e agentes', 'Inteligência, com Integração', 'Autômato', 'baixo',
          [('Dado validado, com a medida de qualidade', 'etapa 3'), (FICHA_DADO, 'etapa 1')],
          [T('Registrar o dado no catálogo com identificador, definição, dono, fonte e classificação', R),
           T('Liberar o acesso de pessoas e agentes conforme a classificação', 'ITG'),
           T('Ligar o monitoramento das regras de qualidade a cada carga', R),
           T('Avisar quem pediu e quem usa o dado', R)],
          [(DADO, [TODOS, 'IN-02', 'IN-04']),
           ('Queda de qualidade apontada pelo monitoramento', ['etapa 1'])]),
    ]))

JORNADAS.append(dict(
    code='IN-04',
    nome='Definir e medir os indicadores e publicar as análises',
    dominio='Dados, indicadores e conhecimento', classe='essencial', onda=1,
    objetivo='Fazer com que cada alvo e cada decisão recorrente tenham um indicador com definição, dono, fonte, linha de base e cadência, calculado do mesmo jeito para todos e publicado com a análise. A Inteligência responde pela medida; o dono do indicador responde pelo resultado.',
    frequencia='A cada período de medição (cadência a definir) e por evento: alvos novos, pedido de indicador, oferta ou empresa nova, ou revisão dos indicadores',
    automacao=('alta', 'Calcular, comparar, redigir e publicar rodam com agente e automação. Aprovar a ficha, validar conclusão nova e decidir o que rever são de pessoas.'),
    base=['fabric', 'dqf', 'apqc'],
    lanes=['EST', 'SOL', 'EXE', 'LCI', P, A, R],
    inicios=[I('Alvos do ciclo publicados', 'EST', 'message'),
             I('Pedido de indicador recebido', 'SOL', 'message'),
             I('Período de medição fechado', R, 'timer'),
             I('Revisão dos indicadores iniciada', R, 'timer')],
    fins=[F('Indicadores do período publicados', R), F('Revisão dos indicadores concluída', R)],
    etapas=[
        E('Definir cada indicador com o dono: o que mede, fórmula, fonte, linha de base e cadência', 'Inteligência, com o dono do resultado', 'Copiloto', 'médio',
          [(ALVOS, 'Estratégia'), (PORTF, 'Estratégia'), ('Pedido de indicador', 'Solicitante'), (OFERTA_CAT, 'IN-07'),
           (DADO, 'IN-03'), ('Indicadores a mudar ou retirar', 'etapa 4')],
          [T('Registrar o que abriu o trabalho e localizar os indicadores afetados', R),
           D('O que o trabalho exige?', R,
             [S('Indicador novo ou alterado', 'seg'), S('Medição do período', 'E2'), S('Revisão dos indicadores', 'E4')]),
           T('Propor a ficha de cada indicador: o que mede, fórmula, fonte, linha de base, cadência e dono', A),
           T('Conferir a ficha com os critérios de boa medida e apontar incentivo perverso', A),
           PAR([T('Aprovar as fichas dos indicadores da empresa e assumir o resultado', 'EXE')],
               [T('Aprovar as fichas dos indicadores do círculo e assumir o resultado', 'LCI')]),
           D('Existe dado confiável para calcular cada indicador?', A,
             [S('Sim', 'prox'), S('Não', 'prox', via=[T('Pedir o dado que falta na jornada de dados', R)])])],
          [(FICHAS_IND, ['etapa 2', 'etapa 4']),
           ('Pedido de dado para indicador', ['IN-03'])]),
        E('Calcular os indicadores do período', 'Inteligência', 'Autômato', 'baixo',
          [(FICHAS_IND, 'etapa 1'), (DADO, 'IN-03'), ('Resultado por empresa e consolidado', 'Gestão'),
           ('Resultado da pesquisa de cultura e dados de pessoas', 'Gestão'),
           ('Percepção dos públicos e sinais de reputação', 'Relações'),
           ('Indicadores de clareza e atualidade dos padrões', 'Identidade')],
          [T('Calcular cada indicador pela ficha, com o dado do catálogo', R),
           T('Marcar o indicador calculado com dado incompleto ou fora da regra de qualidade', R, 'rule')],
          [('Indicadores calculados, com a marca de qualidade', ['etapa 3'])]),
        E('Analisar o resultado e publicar os indicadores com a conclusão', 'Inteligência', 'Autopiloto', 'baixo',
          [('Indicadores calculados, com a marca de qualidade', 'etapa 2'), (ALVOS, 'Estratégia')],
          [T('Comparar cada indicador com o alvo, a linha de base e o período anterior', A),
           T('Redigir a análise com a conclusão e o que mudou', A),
           D('Há desvio relevante ou conclusão nova?', A,
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Validar a conclusão antes de publicar', P)])]),
           T('Publicar os indicadores e a análise no painel e avisar os donos', R),
           D('Algum indicador foi contestado ou ficou sem dado confiável?', R, [S('Não', 'F1'), S('Sim', 'prox')])],
          [(INDIC, ['Estratégia', 'Executivos', 'Gestão', 'IN-01', 'IN-02', 'IN-06', 'IN-08']),
           ('Indicadores de marca, cultura e reputação', ['Identidade']),
           ('Painel de indicadores de cada círculo, com dono e análise', [TODOS, 'Líderes dos círculos']),
           ('Indicadores contestados ou sem dado confiável', ['etapa 4'])]),
        E('Rever os indicadores: o que manter, mudar ou retirar', 'Inteligência, com os donos dos indicadores', 'Copiloto', 'baixo',
          [('Indicadores contestados ou sem dado confiável', 'etapa 3'), (FICHAS_IND, 'etapa 1')],
          [T('Apontar indicadores sem uso, sem dono, sem dado confiável ou que deixaram de medir o alvo', A),
           T('Decidir com os donos o que manter, mudar ou retirar', P, 'manual'),
           D('Há indicador a mudar ou retirar?', P,
             [S('Não', 'prox'),
              S('Sim', 'E1', via=[T('Registrar o que muda e o que sai em cada indicador', R)])])],
          [('Indicadores a mudar ou retirar', ['etapa 1']),
           ('Resultado da revisão dos indicadores', ['Líderes dos círculos', 'Executivos', 'Gestão'])]),
    ]))

JORNADAS.append(dict(
    code='IN-05',
    nome='Curar as bases de conhecimento que pessoas e agentes consultam',
    dominio='Dados, indicadores e conhecimento', classe='essencial', onda=1,
    objetivo='Manter, para cada tema, uma base única, curada e com dono, em que pessoas e agentes encontram a resposta certa e atual, e fazer cada pergunta sem resposta virar pedido de curadoria.',
    frequencia='Por evento: conteúdo novo, decisão, padrão ou método publicado, lacuna ou conteúdo vencido detectado; e a cada revisão da base (cadência a definir)',
    automacao=('alta na estrutura, na publicação e na medição; média na curadoria', 'Reunir, estruturar, testar, publicar e medir o uso rodam com agente e automação. Validar o que vale hoje é do dono do tema.'),
    base=['kcs', 'apqc_km', 'iso30401', 'anthropic_evals'],
    lanes=['SOL', 'LCI', 'ITG', P, A, R],
    inicios=[I('Conteúdo novo apontado', 'SOL', 'message'),
             I('Lacuna ou conteúdo vencido detectado', R, 'signal'),
             I('Revisão da base iniciada', R, 'timer')],
    fins=[F('Base publicada e medida', R), F('Conteúdo descartado', R)],
    etapas=[
        E('Reunir o conteúdo e classificar por tema, dono e uso', 'Inteligência', 'Autopiloto', 'baixo',
          [('Conteúdo novo apontado', 'Solicitante'), (REGISTRO, 'IN-02'), (METODO_PUB, 'IN-06'), (OFERTA_CAT, 'IN-07'),
           ('Lições e resultado das melhorias', 'IN-08'), (DECL, 'Identidade'), (PADROES_ID, 'Identidade'),
           (DIRECAO, 'Estratégia'), ('Lacunas e conteúdo vencido', 'etapa 5')],
          [T('Reunir documentos, decisões, respostas e casos por tema, com origem e data', A),
           T('Apontar duplicidade, contradição e conteúdo vencido', A),
           T('Classificar o conteúdo por tema, dono e uso em jornadas e agentes', A)],
          [('Conteúdo reunido por tema, com origem e data', ['etapa 2'])]),
        E('Curar o conteúdo com o dono do tema', 'Inteligência, com o círculo dono do tema', 'Copiloto', 'médio',
          [('Conteúdo reunido por tema, com origem e data', 'etapa 1'), (PADROES_ID, 'Identidade'), (SIGILO, 'Governança'),
           ('Respostas de teste que falharam', 'etapa 3')],
          [T('Conferir fontes, datas e contradições e propor a versão curada', A),
           T('Conferir o conteúdo com os padrões de identidade e com a regra de sigilo', A),
           T('Validar o que vale hoje no tema', 'LCI'),
           D('O dono do tema confirma o conteúdo?', 'LCI',
             [S('Sim', 'prox'), S('Não, ajustar', 'E2'),
              S('Não, descartar', 'F2', via=[T('Registrar o descarte do conteúdo e o motivo', R)])])],
          [('Conteúdo curado: validado, datado, com fonte e sem o que venceu', ['etapa 3'])]),
        E('Estruturar a base e testar com perguntas de teste', 'Inteligência', 'Autopiloto', 'baixo',
          [('Conteúdo curado: validado, datado, com fonte e sem o que venceu', 'etapa 2')],
          [T('Estruturar o conteúdo por tema, no formato que pessoas e agentes consultam', A),
           T('Escrever as perguntas de teste da base, com a resposta esperada', A),
           T('Rodar as perguntas de teste e comparar com a resposta esperada', R),
           D('A base responde certo às perguntas de teste?', R,
             [S('Sim', 'prox'),
              S('Não', 'E2', via=[T('Revisar as respostas de teste que falharam e apontar a causa', P)])])],
          [('Base estruturada e testada', ['etapa 4']),
           ('Respostas de teste que falharam', ['etapa 2'])]),
        E('Publicar a versão e servir a base aos agentes', 'Inteligência, com Integração', 'Autômato', 'baixo',
          [('Base estruturada e testada', 'etapa 3')],
          [T('Publicar a versão única da base, com dono e data de revisão', R),
           T('Servir a base aos agentes que a consultam', 'ITG'),
           T('Avisar pessoas e donos de agentes do que mudou', R)],
          [(BASE, [TODOS, 'Integração', 'IN-02', 'IN-06', 'etapa 5']),
           ('Perguntas de teste da base, com a resposta esperada', ['Integração'])]),
        E('Medir o uso e apontar lacunas e conteúdo vencido', 'Inteligência', 'Autômato', 'baixo',
          [(BASE, 'etapa 4'), ('Consultas dos agentes sem resposta ou com resposta sem fonte', 'Integração')],
          [T('Medir as consultas, as perguntas sem resposta e as respostas sem fonte', R),
           T('Marcar o conteúdo que passou da data de revisão', R),
           T('Abrir pedido de curadoria para cada lacuna e conteúdo vencido', R)],
          [('Lacunas e conteúdo vencido', ['etapa 1']),
           ('Medição de uso das bases', ['IN-08'])]),
    ]))

# ========================================================== MÉTODO E OFERTA
JORNADAS.append(dict(
    code='IN-06',
    nome='Transformar uma prática em método testado e publicado',
    dominio='Método e oferta', classe='essencial', onda=2,
    objetivo='Fazer com que o que funciona na prática vire método escrito, testado em caso real por quem não o descreveu, publicado com dono e versão, e entregue a pessoas e agentes com critério de sucesso e casos de teste. O método é revisto pelo resultado que produz.',
    frequencia='Por evento: prática apontada, recomendação da IN-08, método pedido para oferta, capacidade ou agente; e na data de revisão de cada método',
    automacao=('média', 'Entrevistar, estruturar, redigir, medir e montar o kit são de agente; escolher a prática, aplicar em caso real e decidir manter, rever ou retirar são de pessoas.'),
    base=['jaakkola', 'apqc_km', 'anthropic_evals', 'nist_airmf', 'pdca'],
    lanes=['SOL', 'ITG', 'PES', P, A, R],
    inicios=[I('Prática com bom resultado apontada', 'SOL', 'message'),
             I('Método pedido para capacidade ou agente', 'ITG', 'message'),
             I('Método novo ou revisão recomendada', R, 'message'),
             I('Data de revisão do método atingida', R, 'timer')],
    fins=[F('Método mantido em uso', R), F('Prática não virou método', R), F('Método retirado de uso', R)],
    etapas=[
        E('Escolher a prática que vale virar método', 'Inteligência, com o círculo que pratica', 'Copiloto', 'baixo',
          [('Prática apontada', 'Solicitante'), ('Pedido de método para capacidade ou agente', 'Integração'),
           ('Pedido de método para a oferta', 'IN-07'), (RECOM, 'IN-08'), (INDIC, 'IN-04')],
          [T('Registrar o que abriu o trabalho e localizar o método, se já existe', R),
           D('É revisão de método já publicado?', R, [S('Não', 'seg'), S('Sim', 'E5')]),
           T('Comparar o resultado da prática apontada com os indicadores', A),
           T('Escolher a prática com o círculo que a executa', P, 'manual'),
           D('A prática tem resultado comprovado e vale virar método?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar o motivo e avisar quem apontou a prática', R)])])],
          [('Prática escolhida para virar método', ['etapa 2']),
           ('Prática recusada com o motivo', ['Solicitante'])]),
        E('Descrever o método: princípios, passos, critérios e exemplos', 'Inteligência, com quem pratica', 'Copiloto', 'médio',
          [('Prática escolhida para virar método', 'etapa 1'), ('Resultado do teste em caso real', 'etapa 3'),
           ('Decisão de rever o método', 'etapa 5'), (PADROES_ID, 'Identidade')],
          [T('Entrevistar quem pratica e estruturar princípios, passos, critérios e exemplos', A),
           T('Explicar a prática e validar a descrição', 'PES'),
           T('Escrever o critério de sucesso e os casos de teste do método', A),
           T('Conferir o método com os padrões de identidade', A),
           T('Aprovar a descrição, o critério de sucesso e os casos de teste', P)],
          [('Método descrito, com critério de sucesso e casos de teste', ['etapa 3'])]),
        E('Testar o método em caso real, com quem não o descreveu', 'Inteligência, com o círculo que pratica', 'Assistido', 'médio',
          [('Método descrito, com critério de sucesso e casos de teste', 'etapa 2')],
          [T('Aplicar o método em caso real, sem ajuda de quem o descreveu', 'PES'),
           T('Medir o resultado e comparar com o da prática original', A),
           D('O resultado é igual ou melhor que o da prática original?', P,
             [S('Sim', 'prox'), S('Não, ajustar', 'E2'),
              S('Não, desistir', 'F2', via=[T('Registrar o teste e o motivo de não publicar o método', R)])])],
          [('Método testado, com o resultado medido', ['etapa 4']),
           ('Resultado do teste em caso real', ['etapa 2'])]),
        E('Publicar o método e entregar o kit a quem vai usar', 'Inteligência, com Integração', 'Autopiloto', 'baixo',
          [('Método testado, com o resultado medido', 'etapa 3'), (BASE, 'IN-05')],
          [T('Publicar o método com dono, versão e data de revisão', R),
           T('Montar o kit para agentes: passos, conhecimento, casos de teste e critério de sucesso', A),
           T('Incluir o método na ficha da capacidade e rodar os casos de teste nos agentes', 'ITG'),
           T('Avisar quem usa o método', R)],
          [(METODO_PUB, [TODOS, 'Integração', 'IN-05', 'IN-07', 'etapa 5']),
           ('Kit do método para agentes: passos, conhecimento, casos de teste e critério de sucesso', ['Integração'])]),
        E('Rever o método pelo resultado que ele produz', 'Inteligência, com o dono do método', 'Copiloto', 'baixo',
          [(METODO_PUB, 'etapa 4'), (INDIC, 'IN-04'),
           ('Resultado dos testes e do monitoramento dos agentes', 'Integração'), (AUDIT, 'Governança')],
          [T('Medir o resultado do método em uso por pessoas e agentes contra o critério de sucesso', A),
           T('Decidir com o dono do método: manter, rever ou retirar', P, 'manual'),
           D('O que fazer com o método?', P,
             [S('Manter', 'prox'), S('Rever', 'E2'),
              S('Retirar', 'F3', via=[T('Retirar o método de uso e avisar quem o usa', R)])])],
          [('Decisão de rever o método', ['etapa 2']),
           ('Resultado da revisão do método', ['Integração', 'Líderes dos círculos']),
           ('Método retirado de uso', [TODOS, 'Integração'])]),
    ]))

JORNADAS.append(dict(
    code='IN-07',
    nome='Desenhar e validar uma oferta com o seu modelo de negócio e prepará-la para o lançamento',
    dominio='Método e oferta', classe='essencial', onda=2,
    objetivo='Levar uma aposta aprovada no portão de entrada até uma oferta pronta para vender e entregar: problema e público definidos, solução e método de entrega desenhados, modelo de negócio e preço-base validados com clientes reais e pacote completo. Os dois portões são da Estratégia: a aposta que entra e a oferta que é lançada.',
    frequencia='Por evento: aposta aprovada no portão de entrada, ajuste pedido pelo portão de lançamento, revisão de oferta em uso ou oferta encerrada',
    automacao=('média na preparação, baixa nas decisões', 'O agente reúne evidência, monta alternativas, simula o modelo, mede o piloto e redige o pacote. Escolher o problema, decidir o desenho e o modelo, conduzir o piloto e aprovar o pacote são de pessoas; lançar é decisão da Estratégia.'),
    base=['stagegate', 'doublediamond', 'vpc', 'bmc', 'leanstartup', 'nng_blueprint', 'jaakkola', 'apqc'],
    lanes=['EST', 'SOL', 'REL', 'NEG', 'GES', 'ASS', 'OPE', 'ITG', 'IDE', 'GOV', P, A, R],
    inicios=[I('Aposta aprovada no portão de entrada recebida', 'EST', 'message'),
             I('Oferta em uso encerrada no portão', 'EST', 'message'),
             I('Revisão de oferta em uso pedida', 'SOL', 'message')],
    fins=[F('Oferta aprovada e entregue a quem vende e entrega', R),
          F('Oferta encerrada e retirada do catálogo', R),
          F('Aposta devolvida à Estratégia com a evidência', R)],
    etapas=[
        E('Enquadrar o problema, o público e a proposta de valor', 'Inteligência, com Relações', 'Copiloto', 'médio',
          [(APROVADA, 'Estratégia'), (PORTALVO, 'Estratégia'), (DIRECAO, 'Estratégia'), ('Lição da aposta encerrada', 'Estratégia'),
           ('Pedido de revisão de oferta em uso', 'Solicitante'), (LEITURA, 'IN-01'), (DECL, 'Identidade'),
           ('Ajustes pedidos pelo portão de lançamento', 'etapa 6')],
          [T('Registrar a aposta ou a oferta recebida e o que o portão decidiu', R),
           D('Por onde a oferta entra?', P,
             [S('Aposta nova', 'seg'),
              S('Ajuste na solução ou no modelo', 'E2'),
              S('Ajuste só no pacote', 'E5'),
              S('Oferta em uso encerrada', 'F2', via=[T('Retirar a oferta do catálogo e avisar quem vende e entrega', R)])]),
           T('Incluir o desenvolvimento da oferta na carteira de projetos', 'ITG'),
           T('Reunir a evidência sobre o problema: tarefas, dores e ganhos do público', A),
           T('Indicar clientes do público-alvo para a conversa', 'REL'),
           T('Conversar com clientes do público-alvo', P, 'manual'),
           T('Definir o problema, o público-alvo, a proposta de valor e o posicionamento da oferta', P)],
          [('Problema, público-alvo e proposta de valor', ['etapa 2']),
           ('Posicionamento da oferta e público-alvo', ['Identidade', 'Relações']),
           ('Plano de desenvolvimento da oferta', ['Integração']),
           ('Oferta retirada do catálogo', ['Negócios', 'Relações', 'Operações', 'Integração'])]),
        E('Desenhar a solução, o método de entrega e o que será entregue', 'Inteligência, com Operações e Integração', 'Copiloto', 'médio',
          [('Problema, público-alvo e proposta de valor', 'etapa 1'), ('Resultado do piloto com clientes', 'etapa 4'),
           ('Revisão do modelo pedida', 'etapa 3'), (METODO_PUB, 'IN-06')],
          [T('Montar alternativas de solução e comparar com as ofertas existentes', A),
           T('Desenhar a entrega: o que o cliente faz, o que ele vê e o que acontece por trás', A),
           T('Decidir o desenho da solução e os entregáveis', P),
           PAR([T('Confirmar que a operação consegue entregar a solução', 'OPE')],
               [T('Apontar as capacidades, os agentes e os sistemas que faltam', 'ITG')]),
           D('A solução usa método que ainda não existe?', P,
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Pedir o método na jornada de métodos', R)])])],
          [(SOLUCAO, ['etapa 3', 'etapa 5']),
           ('Capacidades necessárias para a oferta', ['Integração']),
           ('Pedido de método para a oferta', ['IN-06'])]),
        E('Desenhar o modelo de negócio e o preço-base', 'Inteligência, com Negócios e Gestão', 'Copiloto', 'médio',
          [(SOLUCAO, 'etapa 2'), ('Tabela de preços e política comercial vigentes', 'Negócios'),
           ('Custos e margens por empresa e oferta', 'Gestão')],
          [T('Preencher o modelo de negócio nos nove blocos e simular receita, custo e margem', A),
           PAR([T('Confirmar que a oferta é vendável e opinar sobre o preço-base', 'NEG')],
               [T('Conferir custos, margem e efeito no caixa', 'GES')],
               [T('Avaliar o enquadramento fiscal e contábil da oferta', 'ASS')]),
           T('Decidir o modelo de negócio e o preço-base', P),
           T('Escrever as hipóteses a validar e o critério de validação, antes do piloto', P),
           D('A margem-alvo é atendida nas premissas?', P, [S('Sim', 'prox'), S('Não', 'E2')])],
          [(MODELO, ['etapa 4', 'etapa 5']),
           ('Revisão do modelo pedida', ['etapa 2'])]),
        E('Validar a oferta com clientes reais', 'Inteligência, com Relações e Operações', 'Assistido', 'médio',
          [(MODELO, 'etapa 3')],
          [T('Indicar os clientes do piloto e abrir a conversa com eles', 'REL'),
           T('Conduzir o piloto com o cliente, na versão mínima da oferta', P, 'manual'),
           T('Entregar o piloto ao cliente', 'OPE'),
           T('Registrar e medir o resultado contra o critério de validação', A),
           D('O piloto atingiu o critério de validação?', P,
             [S('Sim', 'prox'),
              S('Não, ajustar', 'E2'),
              S('Não, parar ou mudar a aposta', 'F3',
                via=[T('Enviar à Estratégia a evidência do piloto e a recomendação', P)])])],
          [('Evidência de validação com clientes', ['etapa 5']),
           ('Resultado do piloto com clientes', ['etapa 2']),
           (EVID, ['Estratégia']),
           ('Lição do piloto', ['IN-08'])]),
        E('Produtizar a oferta: escopo, material, termos e entrega prontos', 'Inteligência, com Identidade, Governança e Operações', 'Copiloto', 'alto',
          [('Evidência de validação com clientes', 'etapa 4'), (SOLUCAO, 'etapa 2'), (MODELO, 'etapa 3'),
           (PADROES_ID, 'Identidade'), ('Decisão sobre a marca do negócio', 'Identidade'),
           ('Pacote de marca publicado', 'Identidade'), ('Resposta à consulta', 'Identidade'), (METODO_PUB, 'IN-06')],
          [T('Pedir a marca da oferta à Identidade', R),
           PAR([T('Redigir o escopo, os entregáveis e o que fica de fora', A),
                T('Fechar o roteiro de entrega com quem vai entregar', 'OPE')],
               [T('Entregar a decisão e o pacote de marca da oferta', 'IDE', 'call'),
                T('Redigir o material de venda e de entrega no padrão da marca', A)],
               [T('Redigir os termos da oferta no modelo de contrato', A),
                T('Revisar os termos e a proteção do que é próprio', 'GOV')]),
           T('Conferir o pacote pela lista de verificação e pelos padrões de identidade', A),
           D('Há ponto que os padrões de identidade não cobrem?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Responder à consulta sobre o caso não coberto', 'IDE', 'call')])]),
           T('Aprovar o pacote da oferta', P)],
          [(PACOTE, ['etapa 6']),
           ('Pedido de marca', ['Identidade']),
           ('Consulta sobre caso não coberto', ['Identidade'])]),
        E('Passar pelo portão de lançamento e entregar a oferta a quem vende e entrega', 'Inteligência, com Estratégia', 'Autopiloto', 'baixo',
          [(PACOTE, 'etapa 5'), ('Oferta aprovada no portfólio', 'Estratégia'),
           ('Aposta em espera ou devolvida', 'Estratégia'), ('Aposta devolvida com o que falta', 'Estratégia')],
          [T('Enviar o pacote da oferta ao portão de lançamento', R),
           T('Decidir o lançamento no portão', 'EST', 'call'),
           D('Qual foi o resultado do portão?', R,
             [S('Aprovada', 'seg'),
              S('Devolvida para ajuste', 'E1'),
              S('Em espera', 'E6', via=[T('Registrar a condição de retomada e reapresentar o pacote na data marcada', R)]),
              S('Encerrada', 'F2', via=[T('Retirar a oferta do catálogo e registrar a lição do portão', R)])]),
           T('Registrar a oferta no catálogo, com escopo, método, material, preço-base e indicadores', R),
           T('Entregar o pacote a Negócios, Relações, Operações e Integração', R)],
          [(PACOTE_PORTAO, ['Estratégia']),
           ('Ajustes pedidos pelo portão de lançamento', ['etapa 1']),
           (OFERTA_CAT, ['Negócios', 'Relações', 'Operações', 'Integração', 'Executivos', 'IN-04', 'IN-05'])]),
    ]))

# ============================================================== APRENDIZADO
JORNADAS.append(dict(
    code='IN-08',
    nome='Aprender com as lições e os resultados e recomendar melhorias',
    dominio='Aprendizado', classe='essencial', onda=3,
    objetivo='Fazer com que cada lição de aposta, caso, piloto, projeto, cliente ou revisão seja registrada, cruzada com os indicadores e transformada em recomendação com evidência, entregue a quem pode agir; e conferir se a melhoria aceita deu resultado.',
    frequencia='Por evento: cada lição recebida; e a cada ciclo de aprendizado (cadência a definir), para cruzar as lições e recomendar',
    automacao=('média', 'Registrar, classificar, cruzar, redigir e conferir são de agente e automação; escolher o que recomendar e responder à recomendação são de pessoas.'),
    base=['pdca', 'kcs', 'cebma'],
    lanes=['SOL', 'LCI', P, A, R],
    inicios=[I('Lição recebida', 'SOL', 'message'),
             I('Ciclo de aprendizado iniciado', R, 'timer')],
    fins=[F('Melhorias recomendadas e conferidas', R), F('Ciclo encerrado sem recomendação', R)],
    etapas=[
        E('Registrar cada lição com contexto, causa e evidência', 'Inteligência', 'Autopiloto', 'baixo',
          [('Lição apontada', 'Solicitante'), ('Lição da aposta encerrada', 'Estratégia'),
           ('Lições da revisão da estratégia', 'Estratégia'), ('Caso arquivado com o motivo', 'Estratégia'),
           ('Caso arquivado com o resultado da apuração', 'Estratégia'),
           ('Leitura do portfólio: resultado, recursos e papel de cada unidade', 'Estratégia'),
           ('Resumo da avaliação dos padrões', 'Identidade'), ('Lição do piloto', 'IN-07'),
           ('Lições de projetos e implantações encerrados', 'Integração'),
           ('Lições de clientes perdidos, renovados e ampliados', 'Relações')],
          [T('Registrar a lição com contexto, causa, evidência e quem apontou', A),
           T('Classificar a lição por jornada, método, oferta e empresa', A),
           D('A lição tem o mínimo para ser usada?', A,
             [S('Sim', 'prox'), S('Não', 'prox', via=[T('Pedir o que falta a quem apontou a lição', R)])])],
          [('Lições registradas e classificadas', ['etapa 2'])]),
        E('Cruzar lições, indicadores e uso das bases e escolher o que recomendar', 'Inteligência', 'Copiloto', 'baixo',
          [('Lições registradas e classificadas', 'etapa 1'), (INDIC, 'IN-04'), ('Medição de uso das bases', 'IN-05'),
           (REGISTRO, 'IN-02')],
          [T('Cruzar as lições com os indicadores e o uso das bases e apontar o que se repete', A),
           T('Escolher o que recomendar, com o ganho esperado e o dono sugerido', P),
           D('Há melhoria que vale recomendar?', P,
             [S('Sim', 'prox'), S('Não', 'F2', via=[T('Registrar o ciclo sem recomendação', R)])])],
          [('Melhorias escolhidas, com evidência e dono sugerido', ['etapa 3'])]),
        E('Entregar cada recomendação ao dono e registrar a resposta', 'Inteligência, com o dono da melhoria', 'Autopiloto', 'baixo',
          [('Melhorias escolhidas, com evidência e dono sugerido', 'etapa 2')],
          [T('Redigir a recomendação com evidência, ganho esperado e dono sugerido', A),
           D('A quem cabe a melhoria?', P,
             [S('A um círculo ou executivo', 'seg'),
              S('À Estratégia, como aposta nova', 'prox', via=[T('Enviar a ideia à Estratégia como aposta nova', R)])]),
           T('Enviar a recomendação ao dono', R),
           T('Responder à recomendação: aceitar, adiar ou recusar, com o motivo', 'LCI'),
           T('Registrar a resposta do dono e o prazo combinado', R)],
          [(RECOM, ['IN-06', 'Integração', 'Líderes dos círculos', 'Executivos']),
           ('Ideia ou aposta nova', ['Estratégia']),
           ('Recomendações respondidas pelos donos', ['etapa 4'])]),
        E('Conferir se a melhoria aceita foi feita e deu resultado', 'Inteligência', 'Autopiloto', 'baixo',
          [('Recomendações respondidas pelos donos', 'etapa 3'), (INDIC, 'IN-04')],
          [T('Conferir no prazo combinado se a melhoria aceita foi feita', R),
           T('Medir o resultado da melhoria contra o ganho esperado', A),
           T('Publicar as lições e o resultado das melhorias', R)],
          [('Lições e resultado das melhorias', ['IN-05', 'Líderes dos círculos', 'Executivos', 'Sócios'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Mercado e decisão', 'Saber antes: ler o mercado e responder a quem decide.'),
    ('Dados, indicadores e conhecimento', 'Saber melhor: dado confiável, medida única e base curada.'),
    ('Método e oferta', 'Transformar o que se sabe em método e em oferta.'),
    ('Aprendizado', 'Fechar o ciclo: da lição à melhoria conferida.'),
]

ONDAS = {
    1: 'O que os círculos 1 e 2 já esperam da Inteligência e o que os agentes precisam para rodar',
    2: 'O que transforma o que se sabe em método e em oferta',
    3: 'O que fecha o ciclo de aprendizado',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4. Os processos das funções da Inteligência estão em quatro categorias: modelos de negócio (1.4), desenvolvimento de produtos e serviços (2.1 a 2.3), mercados e clientes (3.1, e 3.2 em parte) e gestão da informação (8.4). A tabela de cobertura, na aba Método, mostra onde cada grupo foi parar. A leitura do PDF parou na categoria 9: a categoria 13 não foi lida e não é citada.',
    'cia_ciclo': 'Ciclo de inteligência em cinco passos: planejamento e direção, coleta, processamento, análise e produção, e disseminação, que devolve a análise a quem abriu o ciclo. Base da sequência de etapas da IN-01.',
    'herring': 'Processo de tópicos-chave de inteligência (KIT): as necessidades de inteligência são identificadas e priorizadas em diálogo com quem decide. O resumo dá três tipos de tópico: decisões e ações estratégicas, temas de alerta antecipado e descrição dos atores do mercado. Base da etapa 1 da IN-01.',
    'horizon': 'Horizon scanning: coleta sistemática de percepções sobre tendências emergentes e sinais fracos de mudança, para identificar ameaças, riscos e oportunidades. Cinco passos: formar o grupo, identificar as fontes, reunir e guardar os dados de forma organizada, analisar e redigir os resultados. Base das etapas 2 e 3 da IN-01.',
    'cebma': 'Prática baseada em evidência: decidir com o uso consciencioso, explícito e criterioso da melhor evidência disponível, de várias fontes. Seis passos: perguntar, buscar, avaliar, agregar, aplicar e avaliar o resultado da decisão. Base das quatro etapas da IN-02 e da conferência do resultado na IN-08.',
    'yardstick': 'Régua de probabilidade da inteligência de defesa britânica: a escala de probabilidade é dividida em sete faixas numéricas, cada uma com um termo. Usamos a ideia de termos padronizados para declarar o grau de confiança na IN-01 e na IN-02. A régua trata de probabilidade; os termos e as faixas não foram lidos.',
    'dqf': 'Seis dimensões de qualidade do dado: completude, unicidade, consistência, atualidade, validade e exatidão. Ciclo de vida em seis estágios: planejar; coletar, adquirir e ingerir; preparar, guardar e manter; usar e processar; compartilhar e publicar; arquivar ou destruir. Base das etapas da IN-03 e da marca de qualidade dos indicadores na IN-04.',
    'fair': 'Princípios de localização (F1 a F4): identificador único e persistente, metadados ricos, metadados que citam o identificador do dado e registro em recurso pesquisável. Base da ficha e do catálogo de dados na IN-03.',
    'lgpd': 'Definições de dado pessoal, dado pessoal sensível, dado anonimizado e tratamento (art. 5º); princípios da finalidade, da adequação e da necessidade (art. 6º); dever de manter registro das operações de tratamento (art. 37). Base da classificação e da recusa de dado na etapa 1 da IN-03. Quem define a regra é a Governança.',
    'fabric': 'Seis propriedades de um sistema de informação de desempenho: focado, apropriado, equilibrado, robusto, integrado e com custo compatível. Oito critérios de uma boa medida: relevante, sem incentivo perverso, atribuível, bem definida, tempestiva, confiável, comparável e verificável. Base da ficha e da revisão dos indicadores na IN-04.',
    'kcs': 'Oito práticas em dois ciclos. No ciclo de solução: capturar, estruturar, reusar e melhorar. No ciclo de evolução: saúde do conteúdo, integração ao processo, avaliação de desempenho, e liderança e comunicação. O ciclo de evolução aprende com os padrões de reuso. Base das etapas da IN-05 e do cruzamento de lições na IN-08. O guia foi escrito para atendimento; usá-lo em bases para agentes é leitura nossa.',
    'apqc_km': 'Fluxo do conhecimento em sete passos: criar, identificar, coletar, revisar, compartilhar, acessar e usar. Base da sequência da IN-05 e da IN-06.',
    'iso30401': 'Requisitos e diretrizes para estabelecer, implementar, manter, revisar e melhorar um sistema de gestão do conhecimento. Usamos essa sequência na IN-05; o conteúdo da norma não foi lido.',
    'anthropic_evals': 'Critério de sucesso específico, mensurável, alcançável e relevante; avaliações que espelham a tarefa real e são automatizadas quando possível; três formas de correção: por código, por pessoa e por modelo. Base das perguntas de teste da IN-05 e do critério de sucesso e dos casos de teste da IN-06.',
    'nist_airmf': 'O núcleo tem quatro funções: governar, mapear, medir e gerir. Medir usa ferramentas e métodos quantitativos, qualitativos ou mistos para analisar, avaliar, comparar e monitorar. Base da medição do método em uso por agentes, na etapa 5 da IN-06. O framework trata de risco de IA; usá-lo para a qualidade do resultado é leitura nossa.',
    'pdca': 'Ciclo de quatro passos para conduzir uma mudança: planejar, testar em pequena escala, verificar o que se aprendeu e agir, incorporando o que funcionou. Base do teste em caso real da IN-06 e da sequência da IN-08.',
    'nng_blueprint': 'Mapa de serviço com quatro elementos: ações do cliente, ações à vista do cliente, ações de bastidor e processos de apoio. Base do desenho da entrega na etapa 2 da IN-07.',
    'bmc': 'Quadro de modelo de negócio em nove blocos: segmentos de clientes, propostas de valor, canais, relacionamento com clientes, fontes de receita, recursos-chave, atividades-chave, parcerias-chave e estrutura de custos. Base da etapa 3 da IN-07.',
    'vpc': 'Perfil do cliente (tarefas, dores e ganhos) e mapa de valor (o que se oferece, as dores que alivia e os ganhos que cria). O encaixe é uma afirmação até os clientes confirmarem. Base das etapas 1 e 4 da IN-07.',
    'leanstartup': 'Construir, medir e aprender: transformar ideias em produto, medir a resposta dos clientes e aprender se é o caso de mudar o rumo ou perseverar. O produto mínimo viável serve para começar a aprender o mais cedo possível. Base do piloto na etapa 4 da IN-07.',
    'doublediamond': 'Quatro fases em dois diamantes: descobrir e definir o problema, desenvolver e entregar a solução. Base da ordem das etapas 1 e 2 da IN-07: primeiro o problema, depois a solução.',
    'jaakkola': 'Três práticas de produtização em empresas de serviços profissionais: especificar e padronizar a oferta; tornar tangíveis a oferta e a competência profissional; sistematizar e padronizar processos e métodos. Base da etapa 5 da IN-07 e da IN-06.',
    'stagegate': 'Depois da descoberta e ideação, a página lista cinco estágios, cada um precedido de um portão: conceito, construir o caso de negócio, desenvolvimento, teste e validação, e lançamento. A IN-07 cobre o trabalho entre os dois portões que a Estratégia decide: a entrada na carteira e o lançamento.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio e script, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'dmn': 'Padrão de modelagem de decisões, que inclui tabelas de decisão. Usado na IN-03 para as regras de qualidade do dado.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# ----------------------------------- cobertura do referencial (APQC PCF 7.4)
COBERTURA = [
    ('1.4.1', 'Develop business models', 'IN-07, etapa 3'),
    ('1.4.2', 'Maintain business models', 'IN-07, pela revisão de oferta em uso, com os indicadores da IN-04'),
    ('1.4.3', 'Establish business model governance', 'Fora: Estratégia, nos dois portões'),
    ('2.1.1', 'Manage product and service portfolio', 'Fora: Estratégia, na revisão do portfólio e nos portões'),
    ('2.1.2', 'Manage product and service life cycle', 'IN-07: entrada, revisão e retirada da oferta do catálogo. A decisão de encerrar é da Estratégia'),
    ('2.1.3', 'Manage patents, copyrights, and regulatory requirements', 'Fora: Governança. A IN-07, etapa 5, pede a revisão dos termos e da proteção do que é próprio'),
    ('2.1.4', 'Manage product and service master data', 'IN-07, etapa 6 (oferta no catálogo), e IN-03'),
    ('2.2.1', 'Perform discovery research', 'IN-01, quando a tecnologia é um dos sinais a vigiar. Avaliar a viabilidade de integrar é da Integração'),
    ('2.2.2', 'Generate new product/service concepts', 'IN-01 e IN-08 enviam a ideia à Estratégia; o conceito é desenhado na IN-07, etapa 1'),
    ('2.2.3', 'Define product/service development requirements', 'IN-07, etapas 1 e 2'),
    ('2.3.1', 'Design and prototype products and services', 'IN-07, etapas 2 e 3'),
    ('2.3.2', 'Test market for new or revised products and services', 'IN-07, etapa 4'),
    ('2.3.3', 'Prepare for production/service delivery', 'IN-07, etapas 5 e 6, com Operações e Integração'),
    ('3.1.1', 'Perform customer and market intelligence analysis', 'IN-01'),
    ('3.1.2', 'Evaluate and prioritize market opportunities', 'IN-01 aponta a oportunidade; priorizar é da Estratégia. Validar com clientes (3.1.2.4) está na IN-07, etapa 4'),
    ('3.2.1', 'Define offering and customer value proposition', 'IN-07, etapas 1 e 4. A marca nova (3.2.1.4) é da Identidade'),
    ('3.2.2', 'Define pricing strategy', 'Em parte: o preço-base está na IN-07, etapa 3. Diretrizes de preço e desconto são de Negócios'),
    ('8.4.1', 'Define business information and analytics strategy', 'IN-03 e IN-04: que dado e que indicador cada decisão pede'),
    ('8.4.2', 'Define and maintain business information architecture', 'IN-03, etapa 1: definição, fonte e dono do dado. Modelos e arquitetura de dados são da Integração'),
    ('8.4.3', 'Define and execute business information lifecycle planning and control', 'IN-03: regras de qualidade e ciclo de vida. A política de sigilo e de dados pessoais é da Governança'),
    ('8.4.4', 'Manage business information', 'IN-03, etapas 3 e 4. Guarda e acesso são da Integração'),
]

# ------------------------------------------------ o que a Inteligência não faz
FRONTEIRAS = [
    ('Decidir a aposta que entra, a oferta que é lançada e o que sai do portfólio', 'Estratégia',
     'A leitura de mercado (IN-01), a resposta com evidência (IN-02), os indicadores por empresa, oferta e aposta (IN-04) e o pacote da oferta pronta (IN-07).'),
    ('Definir marca, voz e posicionamento institucional', 'Identidade',
     'O posicionamento da oferta e o público-alvo (IN-07) e a leitura de mercado (IN-01). Confere conteúdo, método e pacote da oferta com os padrões.'),
    ('Responder pelo resultado medido', 'O dono de cada indicador: executivo ou líder do círculo',
     'A medida: definição, cálculo, publicação e análise (IN-04).'),
    ('Responder pelo conteúdo de cada dado', 'O círculo que gera o dado',
     'A definição, a regra de qualidade, a validação e o catálogo (IN-03).'),
    ('Conectar as fontes, guardar os dados e controlar o acesso', 'Integração',
     'A ficha de cada dado, com a classificação que define o acesso (IN-03).'),
    ('Montar, testar, liberar e operar agentes e automações', 'Integração',
     'O método, a base de conhecimento, o critério de sucesso e os casos de teste (IN-05 e IN-06). Recebe de volta o resultado dos testes e do monitoramento.'),
    ('Definir o sigilo, as regras de dados pessoais e as alçadas', 'Governança',
     'A classificação proposta de cada dado e de cada base. Aplica as regras da Governança na IN-03 e na IN-05.'),
    ('Auditar as entregas de pessoas e agentes', 'Governança',
     'O critério de sucesso e os casos de teste de cada método (IN-06). Usa o resultado da auditoria para rever o método; não faz amostragem própria.'),
    ('Rodar o ritual de acompanhamento dos alvos', 'Gestão',
     'Os indicadores e as análises de cada período (IN-04).'),
    ('Apurar o resultado financeiro e de pessoas', 'Gestão',
     'A ficha dos indicadores e a regra de qualidade dos dados. Recebe o resultado por empresa e consolidado.'),
    ('Definir a tabela de preços e a política comercial; vender', 'Negócios',
     'O modelo de negócio e o preço-base validado com clientes (IN-07).'),
    ('Gerar demanda, lançar a oferta e cuidar do relacionamento com clientes', 'Relações',
     'O posicionamento e o pacote da oferta (IN-07) e a leitura de mercado (IN-01). Relações indica os clientes para pesquisa e piloto.'),
    ('Entregar a oferta ao cliente', 'Operações',
     'O método e o roteiro de entrega (IN-07). Operações confirma a capacidade e entrega o piloto.'),
    ('Coordenar o projeto de desenvolvimento e de lançamento da oferta', 'Integração, como PMO corporativo',
     'O plano de desenvolvimento e as capacidades necessárias (IN-07).'),
    ('Redesenhar jornadas e capacidades', 'Integração',
     'A recomendação de melhoria com evidência (IN-08).'),
    ('Revisar termos, contratos e propriedade intelectual das ofertas', 'Governança',
     'Os termos redigidos no modelo de contrato (IN-07, etapa 5).'),
]

# -------------------------------------------------------- pontos para decidir
PONTOS = [
    ('Qual é a regra do círculo?',
     'A Inteligência responde pela evidência, pela medida, pelo método e pelo desenho da oferta. Quem decide e quem executa são os outros círculos. Cada dado e cada indicador têm um dono fora dela: o círculo ou o executivo que responde pelo conteúdo e pelo resultado.',
     'Um círculo que só analisa pode virar torre de marfim: produz leitura e recomendação que ninguém usa, e ninguém cobra. Por isso a IN-02 registra se a resposta foi usada e a IN-08 confere se a melhoria aceita foi feita. A alternativa é dar à Inteligência alvos de resultado, como a receita das ofertas novas; ela passaria a responder por um resultado que não controla.'),
    ('Até onde a Inteligência vai no preço e no posicionamento da oferta?',
     'Fica com a proposta de valor, o posicionamento da oferta, o modelo de negócio e o preço-base validado com clientes (IN-07), pela sua decisão D4. Depois do portão de lançamento, a tabela de preços e a política comercial são de Negócios, e a geração de demanda é de Relações.',
     'O referencial da APQC põe proposta de valor, posicionamento e estratégia de preço em marketing e vendas (3.2.1 e 3.2.2), não em desenvolvimento de produto. Com dois círculos mexendo no preço, a margem depois do lançamento pode ficar sem dono. A alternativa é Negócios decidir o preço-base já na etapa 3, e a Inteligência só simular.'),
    ('Quem coordena o desenvolvimento e o lançamento da oferta?',
     'A Inteligência lidera o conteúdo da oferta até o portão. A Integração, como PMO corporativo, acompanha o desenvolvimento na carteira de projetos e coordena o lançamento depois do portão, com o executivo da empresa. Isso pede incluir a Integração entre os destinos da oferta aprovada na jornada de portões da Estratégia, que é mudança no círculo 2.',
     'A oferta troca de mãos no portão: cinco círculos recebem o pacote, e o lançamento pode ficar sem dono. A alternativa é a Inteligência coordenar até a primeira venda; ela conhece a oferta, mas passaria a executar, o que contraria a regra do ponto 1.'),
    ('Como medir se o resultado é bom sem criar uma terceira auditoria?',
     'A Inteligência não amostra entregas. Escreve o critério de sucesso e os casos de teste de cada método (IN-06) e as perguntas de teste de cada base (IN-05); a Integração roda os testes e monitora os agentes; a Governança audita as entregas uma vez. A Inteligência lê esses resultados e os indicadores para rever o método.',
     'A revisão do método fica dependente da medição de outros dois círculos: se os testes ou a auditoria forem fracos, a Inteligência revê às cegas. A alternativa é a Inteligência avaliar por conta própria uma amostra dos resultados dos agentes, ao custo de três círculos olhando a mesma entrega.'),
    ('Vale manter oito jornadas?',
     'Sim. Responder perguntas (IN-02) e aprender com as lições (IN-08) poderiam ser etapas de outras jornadas, mas têm gatilho e resultado próprios, e a IN-02 é a candidata mais clara a fluxo executável.',
     'Oito jornadas para quatro funções é mais do que a Identidade (cinco) e a Estratégia (seis). A alternativa é fundir a IN-02 na IN-04 e a IN-08 na IN-05 e ficar com seis; perdem-se, como resultados próprios, o registro de uso das respostas e a conferência das melhorias.'),
]

DECISOES = []
ALERTAS = []

# ------------------- propostas de mudança em círculos já fechados (nenhuma aplicada)
PROPOSTAS = [
    ('Círculo 1, ID-04, etapa 5: incluir a Inteligência entre os destinos do “Posicionamento e casa de mensagens vigentes”',
     'A tabela de fronteiras do círculo 1 já diz que a Identidade entrega o posicionamento institucional a quem posiciona cada oferta, mas o fluxo não o envia à Inteligência. Hoje a IN-07 usa só a declaração e os padrões.',
     'Cruzamento com a Inteligência'),
    ('Círculo 2, ES-01, etapa 5: incluir a Inteligência entre os destinos do “Método de estratégia vigente”',
     'A Inteligência prepara o pacote que vai ao portão de lançamento e precisa dos critérios do portão. Hoje só os conhece pela aposta aprovada.',
     'Cruzamento com a Inteligência'),
    ('Círculo 2, ES-04: acrescentar o início “Revisão da aposta pedida pela Inteligência”',
     'Quando o piloto com clientes refuta a hipótese, a IN-07 devolve a aposta com a evidência. Hoje a jornada de portões só reabre a aposta na data de revisão.',
     'Cruzamento com a Inteligência'),
    ('Círculo 2, ES-04, etapa 4: incluir a Integração entre os destinos da “Oferta aprovada no portfólio”',
     'Decorre do ponto 3, se você aprovar: a Integração, como PMO corporativo, coordena o lançamento.',
     'Ponto 3 deste círculo'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'V1 · Do problema à oferta', 'IN-07',
     'Continua liderada pela Inteligência. Decidir o lançamento (W-V1.6) já está na jornada de portões da Estratégia. Ganha a entrada por ajuste pedido pelo portão, por revisão de oferta em uso e por oferta encerrada.'),
    ('Ajustado', 'C3 · Do dado ao aprendizado', 'IN-01, IN-02, IN-04 e IN-08',
     'Dividida por função: captar sinais de mercado (W-C3.1) vira a IN-01; produzir indicadores e análises (W-C3.2), a IN-04; responder perguntas de decisão (W-C3.3), a IN-02; transformar aprendizado em melhoria (W-C3.4), a IN-08.'),
    ('Ajustado', 'I-IN1 · Da fonte ao dado confiável', 'IN-03',
     'Mesmo escopo. Ganha a recusa do dado que a regra não permite tratar, a correção de dado já catalogado e a retirada no fim do prazo de guarda.'),
    ('Ajustado', 'I-IN2 · Da prática ao método', 'IN-06',
     'Mesmo escopo. Ganha o critério de sucesso e os casos de teste, o kit para agentes e a retirada do método.'),
    ('Ajustado', 'I-IN3 · Do conteúdo bruto à base de conhecimento', 'IN-05',
     'Mesmo escopo. As perguntas de teste passam a ser entregues à Integração, e a lacuna medida reabre a curadoria.'),
    ('Acrescentado', 'Sem equivalente', 'Plano de leitura e aviso de mudança',
     'Na IN-01, a leitura passa a ser guiada pelas perguntas de quem decide e pelas hipóteses da estratégia, com critério de aviso para cada sinal.'),
    ('Acrescentado', 'Sem equivalente', 'Dono do dado e dono do indicador',
     'Na IN-03 e na IN-04, o líder do círculo ou o executivo confirma a definição e assume o dado ou o resultado.'),
    ('Acrescentado', 'Sem equivalente', 'Registro de uso das respostas e conferência das melhorias',
     'A IN-02 pergunta se a resposta foi usada; a IN-08 confere se a melhoria aceita foi feita e deu resultado.'),
    ('Acrescentado', 'Sem equivalente', 'Ponto de conferência com a identidade',
     'Na IN-05, na IN-06 e na IN-07, conteúdo, método e pacote da oferta são conferidos com os padrões da Identidade. Na IN-07, o caso não coberto vira consulta à Identidade.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'Nenhuma cadência foi fixada: ciclo de leitura, período de medição, revisão dos indicadores, revisão das bases e ciclo de aprendizado estão como “a definir”. O prazo de resposta da IN-02 também.',
    'As trocas com a Identidade e a Estratégia foram conferidas dos dois lados. Com os outros seis círculos, estão descritas pelo nome do círculo e serão conferidas quando cada um for desenhado.',
    'Na IN-07, os critérios do portão de lançamento chegam à Inteligência só pela aposta aprovada; entregar o método de estratégia à Inteligência é proposta de mudança no círculo 2.',
    'As participações da Inteligência em jornadas de outros círculos no catálogo da rodada 2 (C5, C8, C11 e V7) serão conferidas quando esses círculos forem desenhados.',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = []
