
# ============================================================ PROJETOS
JORNADAS.append(dict(
    code='IT-01',
    nome='Gerir a carteira de projetos do Ecossistema e das empresas',
    dominio='Projetos e implantação', classe='essencial', onda=1,
    objetivo='Fazer cada projeto, interno ou de cliente, entrar numa carteira única com objetivo, dono, prazo, custo e empresa; ser priorizado contra a capacidade; ser acompanhado com o desvio apontado a tempo; e ser encerrado com a entrega conferida e as lições registradas. O executivo decide a prioridade dos projetos da sua empresa; a Integração decide a dos projetos corporativos e o método; o conflito de capacidade entre empresas sobe à Estratégia. A Integração informa a situação da carteira à Estratégia e à Gestão.',
    frequencia='Por evento: iniciativa aprovada, decisão de portão, oferta para lançamento, implantação de cliente, capacidade nova, plano de saída, aposta devolvida ou encerrada; e a cada ciclo de acompanhamento (cadência a definir)',
    automacao=('média', 'Registrar, estimar, simular a carga, coletar a situação e apontar desvios são de agente e automação; definir objetivo e dono, priorizar os projetos corporativos e decidir a correção são de pessoa da Integração; a prioridade dos projetos de cada empresa é do executivo.'),
    base=['iso21502', 'apqc'],
    lanes=['EST', 'INT', 'EXE', P, A, R],
    inicios=[I('Iniciativa, decisão de portão ou de encerramento recebida', 'EST', 'message'),
             I('Projeto aberto por outra jornada da Integração', R, 'message'),
             I('Aposta devolvida ou encerrada avisada', 'INT', 'message'),
             I('Ciclo de acompanhamento da carteira iniciado', R, 'timer')],
    fins=[F('Projeto encerrado, com a entrega conferida e as lições registradas', R),
          F('Projeto suspenso ou encerrado antes da entrega, com recursos liberados', R),
          F('Situação da carteira informada', R),
          F('Projeto não priorizado, em espera', R),
          F('Projeto atualizado com a decisão do portão', R)],
    etapas=[
        E('Registrar o projeto e o que ele pede', 'Integração', 'Copiloto', 'baixo',
          [(ALVOS, 'Estratégia'), (METODO_EST, 'Estratégia'), (DEC_PORTAO, 'Estratégia'), (DEC_ENCERRAR, 'Estratégia'),
           (AP_DEVOLVIDA, 'Inteligência'), (PREVISAO, 'Negócios'), (PROJETO, 'IT-02'), (PROJETO, 'IT-03'), (PROJETO, 'IT-04'),
           (PROJETO, 'IT-05'), (PROJETO, 'IT-08'),
           ('Projeto suspenso ou encerrado por outra jornada', 'IT-02'), ('Projeto suspenso ou encerrado por outra jornada', 'IT-03'),
           ('Projeto suspenso ou encerrado por outra jornada', 'IT-04'),
           ('Projeto suspenso ou encerrado por outra jornada', 'IT-08'), ('Projeto reativado', 'IT-03')],
          [T('Registrar o que abriu o trabalho, a empresa e o projeto afetado', R),
           D('O que abriu o trabalho?', R,
             [S('Projeto novo ou reativado: iniciativa, implantação, lançamento, capacidade, redesenho ou saída', 'seg'),
              S('Aposta devolvida ou encerrada, oferta encerrada, ou projeto suspenso por outra jornada', 'F2',
                via=[T('Suspender ou encerrar o projeto e avisar a Gestão dos recursos liberados', R)]),
              S('Decisão do portão sobre aposta que já está na carteira, ou ciclo de acompanhamento', 'E3')]),
           T('Estimar prazo, custo, pessoas, agentes e dependências do projeto', A),
           T('Definir o objetivo, o dono e o alvo ou o contrato a que o projeto se liga', P)],
          [('Projeto registrado, com estimativa', ['etapa 2']),
           ('Recursos liberados de projeto suspenso ou encerrado', ['Gestão'])]),
        E('Priorizar o projeto na carteira', 'Integração; o executivo, nos projetos da sua empresa; o conflito entre empresas, a Estratégia', 'Copiloto', 'médio',
          [('Projeto registrado, com estimativa', 'etapa 1')],
          [T('Simular a carga da carteira com o projeto novo e apontar os conflitos de capacidade', A),
           T('Propor a ordem dos projetos pela regra de prioridade e pelos alvos', P),
           D('De quem é a prioridade?', R,
             [S('Projeto de uma empresa', 'seg', via=[T('Decidir a prioridade dos projetos da sua empresa', 'EXE')]),
              S('Projeto corporativo ou de círculo', 'seg',
                via=[T('Decidir a prioridade dos projetos corporativos, pelos alvos e pelo método de estratégia', P)])]),
           D('Há conflito de capacidade entre empresas?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Decidir o conflito de capacidade entre empresas, pelos alvos e pela alocação', 'EST', 'call')])]),
           D('O projeto entra agora?', P,
             [S('Sim', 'prox', via=[T('Fechar a carteira priorizada e avisar os donos dos projetos', P)]),
              S('Não: espera capacidade ou prioridade', 'F4',
                via=[T('Registrar o projeto em espera, com a condição para entrar, e avisar o dono', R)])])],
          [('Projeto priorizado, com início e marcos', ['etapa 3'])]),
        E('Acompanhar o projeto e corrigir o desvio', 'Integração, com o dono do projeto', 'Autopiloto', 'médio',
          [('Projeto priorizado, com início e marcos', 'etapa 2'), ('Situação, marco ou desvio informado pelo dono do projeto', 'Líderes dos círculos')],
          [D('O que chegou à etapa?', R,
             [S('Ciclo de acompanhamento da carteira', 'F3',
                via=[T('Rever os projetos em espera e devolver à priorização os que já cabem', A),
                     T('Informar a situação da carteira à Estratégia, à Gestão e aos executivos', R)]),
              S('Decisão do portão sobre aposta da carteira', 'F5', via=[T('Atualizar o projeto com a decisão do portão', R)]),
              S('Projeto priorizado', 'seg')]),
           T('Receber a situação, o marco, o desvio ou a conclusão de cada projeto', R, 'receive'),
           T('Comparar prazo, custo e entrega com o plano e apontar o desvio', A),
           D('Como está o projeto?', P,
             [S('Em andamento, sem desvio', 'E3', via=[T('Atualizar a situação da carteira', R)]),
              S('Em andamento, com desvio', 'E3',
                via=[T('Decidir a correção com o dono do projeto e avisar o executivo quando o desvio é dele', P)]),
              S('Concluído', 'prox')])],
          [(SITUACAO, ['Estratégia', 'Gestão', 'Executivos'])]),
        E('Encerrar o projeto e registrar as lições', 'Integração, com o dono do projeto', 'Copiloto', 'baixo',
          [('Entrega do projeto', 'Líderes dos círculos'), ('Entrega do projeto', 'IT-02'), ('Entrega do projeto', 'IT-03'),
           ('Entrega do projeto', 'IT-04')],
          [T('Conferir a entrega com o objetivo, o prazo e o custo do projeto', P),
           T('Confirmar o aceite do dono do projeto: cliente, executivo ou líder do círculo', P),
           T('Registrar o encerramento, o resultado e as lições do projeto', R)],
          [(LICOES, ['Inteligência']),
           (REGISTROS, ['Inteligência']),
           ('Projeto encerrado, com o resultado', ['Gestão', 'Executivos']),
           ('Entrega do projeto a quem o pediu', ['IT-08'])]),
    ]))

JORNADAS.append(dict(
    code='IT-02',
    nome='Implantar o cliente, do contrato assinado à operação',
    dominio='Projetos e implantação', classe='essencial', onda=1,
    objetivo='Fazer cada contrato assinado virar um cliente implantado e aceito, com um plano combinado com o cliente e com Operações, ambiente, acessos, pessoas e materiais prontos, e passado a Operações para a entrega recorrente. A Integração coordena; Operações confirma a capacidade e assume a entrega; a Gestão compra o que falta; o cliente aceita.',
    frequencia='Por evento: contrato de cliente assinado ou com escopo novo',
    automacao=('média', 'Montar o cronograma e os riscos, configurar acessos, conferir requisitos, os padrões e acompanhar são de agente e automação; combinar o plano com o cliente, implantar e conferir o aceite são de pessoas.'),
    base=['iso21502', 'apqc'],
    lanes=['NEG', 'CLI', 'OPE', 'GES', 'IDE', P, A, R],
    inicios=[I('Contrato de cliente assinado recebido', 'NEG', 'message')],
    fins=[F('Cliente implantado, aceito e passado a Operações', R),
          F('Impasse da implantação levado ao executivo', R)],
    etapas=[
        E('Planejar a implantação com o cliente e com Operações', 'Integração, com o cliente e Operações', 'Copiloto', 'médio',
          [(CONTRATO, 'Negócios'), (CX, 'Relações')],
          [T('Montar o cronograma, os riscos e a lista de requisitos a partir do escopo vendido', A),
           T('Combinar o plano de implantação com o cliente', P, 'manual'),
           PAR([T('Confirmar o plano de implantação e os responsáveis do cliente', 'CLI')],
               [T('Confirmar a capacidade de entrega e quem assume o cliente', 'OPE')]),
           D('Operações confirmou a capacidade?', P,
             [S('Sim', 'seg'),
              S('Não: rever prazo ou recursos', 'E1', via=[T('Rever o cronograma e os recursos com Operações', A)])]),
           T('Decidir o plano de implantação e abri-lo na carteira de projetos', P)],
          [(PLANO_IMPL, ['Relações', 'Operações', 'Gestão', 'etapa 2']),
           (PROJETO, ['IT-01'])]),
        E('Preparar o ambiente, os acessos, as pessoas e os materiais', 'Integração, com Operações e Gestão', 'Autopiloto', 'médio',
          [(PLANO_IMPL, 'etapa 1'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade'),
           ('Agente liberado para quem pediu', 'IT-06'), ('Item de tecnologia resolvido para quem pediu', 'IT-07'),
           ('Agente ou acesso não entregue, com o motivo', 'IT-06'), ('Agente ou acesso não entregue, com o motivo', 'IT-07')],
          [T('Pedir a configuração dos agentes e os acessos do cliente', R),
           T('Preparar os materiais e as comunicações da implantação', A),
           D('Os materiais estão conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir os materiais no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre os materiais de implantação não cobertos pelos padrões', 'IDE', 'call')])]),
           D('Falta pessoa, compra ou assessoria para a implantação?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Contratar ou comprar o que falta para a implantação', 'GES')])]),
           T('Receber os agentes liberados e os acessos configurados, ou o motivo de não estarem', R, 'receive'),
           D('Os agentes e os acessos ficaram prontos?', A,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Levar ao executivo o que impede a implantação e suspender o projeto na carteira', R)])]),
           T('Conferir a lista de requisitos atendida', A)],
          [('Ambiente, acessos, pessoas e materiais prontos', ['etapa 3']),
           ('Projeto suspenso ou encerrado por outra jornada', ['IT-01']),
           (PED_AGENTE, ['IT-06']),
           (PED_ACESSO, ['IT-07']),
           (CONSULTA, ['Identidade'])]),
        E('Implantar e conferir o aceite do cliente', 'Integração, com Operações e o cliente', 'Copiloto', 'médio',
          [('Ambiente, acessos, pessoas e materiais prontos', 'etapa 2')],
          [T('Implantar com Operações: configurar, migrar, treinar e testar com o cliente', P, 'manual'),
           T('Conferir a implantação com o cliente', 'CLI'),
           T('Registrar o andamento e as pendências da implantação', R),
           D('O cliente aceitou a implantação?', P,
             [S('Sim', 'prox'),
              S('Não: há pendência a corrigir', 'E3', via=[T('Corrigir a pendência apontada pelo cliente', P)]),
              S('Impasse: a pendência não se resolve na implantação', 'F2',
                via=[T('Levar o impasse ao executivo, com o que falta e as opções, e suspender o projeto na carteira', R)])])],
          [('Implantação aceita pelo cliente', ['etapa 4']),
           ('Impasse da implantação, com as opções', ['Executivos']),
           ('Projeto suspenso ou encerrado por outra jornada', ['IT-01'])]),
        E('Passar o cliente a Operações e encerrar a implantação', 'Integração', 'Autômato', 'baixo',
          [('Implantação aceita pelo cliente', 'etapa 3')],
          [T('Passar o cliente a Operações com o registro do que foi implantado', R),
           T('Avisar a Gestão do início da entrega e mandar à carteira a entrega, com as lições', R)],
          [('Cliente implantado e aceito, passado à entrega', ['Operações', 'Gestão']),
           ('Entrega do projeto', ['IT-01'])]),
    ]))

JORNADAS.append(dict(
    code='IT-03',
    nome='Coordenar o lançamento da oferta aprovada',
    dominio='Projetos e implantação', classe='essencial', onda=1,
    objetivo='Fazer cada oferta aprovada no portão de lançamento chegar ao mercado com um plano único: quem faz o quê em Relações, Negócios, Operações, Gestão e Governança, com marcos e riscos, a prontidão conferida antes de lançar e os primeiros resultados acompanhados. A Integração coordena com o executivo da empresa; cada círculo executa a sua parte.',
    frequencia='Por evento: oferta aprovada para lançamento',
    automacao=('média', 'Montar o plano, coletar a prontidão e acompanhar os primeiros indicadores são de agente e automação; fechar o plano e decidir lançar são de pessoa da Integração, ouvido o executivo.'),
    base=['iso21502', 'apqc'],
    lanes=['EST', 'REL', 'NEG', 'OPE', 'GES', 'GOV', 'EXE', P, A, R],
    inicios=[I('Oferta aprovada para lançamento recebida', 'EST', 'message'),
             I('Lançamento retomado pelo executivo', 'EXE', 'message')],
    fins=[F('Oferta lançada e primeiros resultados acompanhados', R),
          F('Lançamento suspenso, com o impedimento levado ao executivo', R)],
    etapas=[
        E('Montar o plano de lançamento com o executivo e os círculos', 'Integração, ouvido o executivo', 'Copiloto', 'médio',
          [(OFERTA_LANC, 'Estratégia'), (OFERTA_CAT, 'Inteligência'), (CAPAC_OFERTA, 'Inteligência'), (PLANO_DEM, 'Relações')],
          [D('O que abriu o trabalho?', R,
             [S('Oferta aprovada para lançamento', 'seg'),
              S('Lançamento retomado depois de impedimento', 'E2',
                via=[T('Reativar o projeto na carteira e propor a nova data, com o que impedia resolvido', A)])]),
           T('Propor o plano: marcos, a parte de cada círculo, capacidades, riscos e data', A),
           PAR([T('Confirmar a parte de demanda e comunicação do lançamento', 'REL')],
               [T('Confirmar a tabela, o material de venda e quem vende', 'NEG')],
               [T('Confirmar a capacidade de entrega e o atendimento', 'OPE')],
               [T('Confirmar o orçamento e a cobrança', 'GES')],
               [T('Confirmar os termos e as regras da oferta', 'GOV')]),
           T('Opinar sobre o plano e a data de lançamento da sua empresa', 'EXE'),
           T('Decidir o plano de lançamento, ouvido o executivo', P)],
          [(PLANO_LANC, ['Relações', 'Negócios', 'Operações', 'Gestão', 'Governança', 'Executivos', 'etapa 2']),
           (PROJETO, ['IT-01'])]),
        E('Conferir a prontidão e decidir lançar', 'Integração, ouvido o executivo', 'Copiloto', 'médio',
          [(PLANO_LANC, 'etapa 1'), ('Prontidão de cada círculo para o lançamento', 'Líderes dos círculos')],
          [T('Receber a prontidão de cada círculo no marco combinado', R, 'receive'),
           T('Conferir a prontidão contra o plano e apontar o que falta', A),
           T('Conferir a prontidão com o executivo da empresa', P, 'manual'),
           D('A oferta está pronta para lançar?', P,
             [S('Sim', 'prox'),
              S('Falta item com prazo de solução', 'E2', via=[T('Cobrar o item que falta do círculo dono, com o novo prazo', R)]),
              S('Falta o que impede o lançamento', 'F2',
                via=[T('Levar o impedimento ao executivo e à Gestão e suspender o projeto na carteira', R)])])],
          [('Lançamento autorizado', ['etapa 3']),
           ('Projeto reativado', ['IT-01']),
           ('Impedimento do lançamento, com as opções', ['Executivos', 'Gestão']),
           ('Projeto suspenso ou encerrado por outra jornada', ['IT-01'])]),
        E('Lançar e acompanhar os primeiros resultados', 'Integração', 'Autopiloto', 'baixo',
          [('Lançamento autorizado', 'etapa 2'), (PAINEL, 'Inteligência')],
          [T('Avisar os círculos e o executivo do lançamento na data', R),
           T('Acompanhar os primeiros indicadores e apontar os problemas de entrega, venda ou demanda', A),
           T('Mandar à carteira a entrega do lançamento, com as lições', R)],
          [('Oferta lançada', ['Operações', 'Gestão', 'Executivos']),
           ('Entrega do projeto', ['IT-01'])]),
    ]))

JORNADAS.append(dict(
    code='IT-04',
    nome='Montar e coordenar o plano de saída de oferta ou de empresa',
    dominio='Projetos e implantação', classe='essencial', onda=1,
    objetivo='Fazer cada oferta encerrada ou empresa que sai do portfólio ter um plano de saída de clientes, contratos, pessoas, sistemas e dados, montado com os círculos que executam e entregue à Estratégia, que decide a data; e, com a data confirmada, coordenar a execução até a conclusão, apontando as pendências. No mandato de criação ou de aquisição, a Integração abre na carteira o projeto de ligar a empresa aos círculos. Cada círculo executa a sua parte; a Integração coordena.',
    frequencia='Por evento: pedido de plano de saída, mandato de empresa, data de saída confirmada ou pendência apontada',
    automacao=('baixa', 'Levantar o que é afetado e acompanhar são de agente e automação; montar o plano com os círculos, fechar o plano e coordenar a execução são de pessoa da Integração.'),
    base=['iso21502', 'apqc'],
    lanes=['EST', 'REL', 'NEG', 'OPE', 'GES', 'GOV', 'EXE', P, A, R],
    inicios=[I('Pedido de plano de saída recebido', 'EST', 'message'),
             I('Mandato da empresa recebido', 'EST', 'message'),
             I('Pendência da saída apontada pela Estratégia', 'EST', 'message'),
             I('Data de saída confirmada recebida', 'EST', 'message')],
    fins=[F('Saída concluída e informada à Estratégia', R),
          F('Projeto de ligação da empresa aberto na carteira', R),
          F('Pendência da saída apontada à Estratégia e ao executivo', R),
          F('Mandato registrado sob sigilo', R),
          F('Plano de saída entregue à Estratégia, à espera da data', R),
          F('Pendência apontada pela Estratégia tratada com o círculo dono', R)],
    etapas=[
        E('Montar o plano de saída com os círculos', 'Integração, com Relações, Negócios, Operações, Gestão e Governança', 'Copiloto', 'alto',
          [(PED_SAIDA_OF, 'Estratégia'), (PED_SAIDA_EMP, 'Estratégia'), (MANDATO, 'Estratégia'), (DEC_ENCERRAR, 'Estratégia'),
           (OFERTA_FORA, 'Inteligência'), (EM_CURSO_SAI, 'Inteligência'), (CONTR_AFET, 'Negócios')],
          [T('Registrar o pedido ou o mandato e o que ele alcança', R),
           D('O que abriu o trabalho?', R,
             [S('Pedido de plano de saída de oferta ou de empresa', 'seg'),
              S('Data de saída confirmada da oferta', 'E2',
                via=[T('Retomar o plano de saída já entregue, com a data confirmada', R)]),
              S('Mandato de venda ou de encerramento de empresa, com o plano conferido', 'E2',
                via=[T('Retomar o plano de saída conferido e incluído no mandato', R)]),
              S('Pendência da saída apontada pela Estratégia depois da conclusão', 'F6',
                via=[T('Coordenar com o círculo dono a pendência apontada', P, 'manual'),
                     T('Apontar ao executivo o resultado da pendência', R)]),
              S('Mandato de criação ou de aquisição de empresa', 'F2',
                via=[T('Abrir na carteira o projeto de ligar a empresa aos círculos e aos acordos de serviço', R),
                     T('Pedir os acessos e os acordos de serviço da empresa a ligar', R)]),
              S('Mandato de busca de comprador ou de mudança de mandato', 'F4',
                via=[T('Registrar o mandato sob sigilo e abrir na carteira o que ele pede', R)])]),
           T('Levantar clientes, contratos, pessoas, sistemas, dados e projetos afetados', A),
           PAR([T('Propor a transição dos clientes', 'REL')],
               [T('Propor o encerramento ou a transferência dos contratos de clientes', 'NEG')],
               [T('Propor o fim das entregas em curso', 'OPE')],
               [T('Propor o destino das pessoas, dos custos e dos contratos de fornecedores', 'GES')],
               [T('Conferir as obrigações legais e contratuais da saída', 'GOV')]),
           T('Opinar sobre o plano de saída da sua empresa', 'EXE'),
           T('Fechar o plano de saída com prazos, responsáveis e riscos', P),
           D('O plano está fechado?', P,
             [S('Sim', 'F5', via=[T('Entregar o plano à Estratégia e registrar que a saída espera a data ou o mandato', R)]),
              S('Não, falta a parte de um círculo', 'F5',
                via=[T('Completar o plano com o círculo que falta', P, 'manual'),
                     T('Entregar o plano completo à Estratégia e registrar a espera', R)])])],
          [(SAIDA_OFERTA, ['Estratégia']),
           (SAIDA_EMPRESA, ['Estratégia']),
           (PED_ACESSO, ['IT-07']),
           ('Pedido de serviço da empresa a ligar', ['IT-05']),
           (SAIDA_CLI, ['Relações', 'Negócios', 'Operações', 'Gestão', 'Governança']),
           (PROJETO, ['IT-01']),
           ('Plano de saída fechado', ['etapa 2'])]),
        E('Coordenar a execução da saída na data confirmada', 'Integração, com os círculos que executam', 'Copiloto', 'alto',
          [('Plano de saída fechado', 'etapa 1'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'), (PEND_SAIDA_OF, 'Estratégia'),
           (CLI_SAIDA, 'Relações'), (CONTR_ENC_SAIDA, 'Negócios'), (PEND_CONTR, 'Negócios')],
          [T('Registrar a data de saída ou a data do mandato e o plano que vale', R),
           T('Avisar cada círculo da data e dos marcos da sua parte', R),
           T('Coordenar a execução entre os círculos e tratar os bloqueios', P, 'manual'),
           T('Pedir a retirada dos acessos e o destino dos dados e dos sistemas da saída', R),
           T('Receber de cada círculo a conclusão da sua parte', R, 'receive'),
           D('A saída foi concluída como planejado?', P,
             [S('Sim', 'prox'),
              S('Há pendência que o círculo dono resolve no prazo', 'E2',
                via=[T('Cobrar a pendência do círculo dono, com o novo prazo', R)]),
              S('Há pendência que não se resolve no plano', 'F3',
                via=[T('Informar à Estratégia a conclusão com a pendência, suspender o projeto e apontá-la ao executivo', R)])])],
          [(PED_ACESSO, ['IT-07']),
           (SAIDA_CONCL, ['Estratégia']),
           ('Projeto suspenso ou encerrado por outra jornada', ['IT-01']),
           ('Pendência da saída, com o efeito', ['Executivos']),
           ('Saída executada', ['etapa 3'])]),
        E('Concluir a saída e informar a Estratégia', 'Integração', 'Autômato', 'baixo',
          [('Saída executada', 'etapa 2')],
          [T('Registrar a conclusão da saída e informar a Estratégia', R),
           T('Mandar à carteira a entrega da saída, com as lições', R)],
          [(SAIDA_CONCL, ['Estratégia']),
           ('Entrega do projeto', ['IT-01'])]),
    ]))
