
# ================================================= CAPACIDADES E AGENTES
JORNADAS.append(dict(
    code='IT-05',
    nome='Atender pedidos de capacidade e de serviço e manter o catálogo de capacidades',
    dominio='Capacidades e agentes', classe='essencial', onda=1,
    objetivo='Fazer cada pedido de serviço de uma empresa a um círculo chegar ao círculo dono da capacidade com um acordo de serviço, e cada necessidade de capacidade nova ou mudada virar uma ficha com método, conhecimento, executor (pessoa, agente, automação ou assessoria), ferramentas, acordo de serviço, indicador e alçada, aceita pelo líder do círculo dono e publicada no catálogo, ligada às jornadas e às tarefas. A Inteligência dá o método e o conhecimento; a Governança define a alçada; o líder do círculo dono aceita a capacidade.',
    frequencia='Por evento: pedido de serviço, necessidade de capacidade, capacidades pedidas por oferta, método publicado, retirado ou recusado; e na revisão do catálogo (cadência a definir)',
    automacao=('média', 'Registrar, identificar a capacidade, encaminhar, propor a ficha e versionar o catálogo são de agente e automação; decidir a ficha e o executor é de pessoa da Integração; aceitar a capacidade é do líder do círculo dono; a alçada é da Governança.'),
    base=['apqc'],
    lanes=['SOL', 'EXE', 'INT', 'GOV', 'LCI', P, A, R],
    inicios=[I('Pedido de serviço de empresa recebido', 'EXE', 'message'),
             I('Necessidade de capacidade nova ou mudada recebida', 'SOL', 'message'),
             I('Capacidades pedidas por oferta recebidas', 'INT', 'message'),
             I('Método publicado, retirado ou recusado avisado', 'INT', 'message'),
             I('Revisão do catálogo de capacidades iniciada', R, 'timer')],
    fins=[F('Capacidade publicada no catálogo', R),
          F('Pedido de serviço encaminhado ao círculo dono, com acordo de serviço', R),
          F('Capacidade retirada do catálogo', R),
          F('Capacidade sem método, à espera da Inteligência', R),
          F('Necessidade sem método publicado, devolvida a quem pediu', R),
          F('Capacidade não aceita pelo líder do círculo dono, com o motivo', R)],
    etapas=[
        E('Receber o pedido e achar a capacidade', 'Integração', 'Autopiloto', 'baixo',
          [('Pedido de serviço de empresa', 'Executivos'), ('Pedido de serviço da empresa a ligar', 'IT-04'),
           ('Necessidade de capacidade nova ou mudada', 'Solicitante'),
           (CAPAC_OFERTA, 'Inteligência'), (METODO_PUB, 'Inteligência'), (METODO_RET, 'Inteligência'), (METODO_REC, 'Inteligência'),
           (AVAL_METODO, 'Inteligência'), ('Redesenho que pede capacidade nova ou mudada', 'IT-08')],
          [T('Registrar o pedido, quem pede e a capacidade procurada no catálogo', R),
           D('O que abriu o trabalho?', A,
             [S('Pedido de serviço de capacidade que já existe', 'F2',
                via=[T('Combinar o acordo de serviço com quem pediu', 'LCI'),
                     T('Encaminhar o pedido ao círculo dono e registrar o acordo de serviço', R)]),
              S('Capacidade nova, ou que falha, ou que pode mudar de modo', 'seg'),
              S('Método publicado que muda a capacidade, ou avaliação do método', 'seg'),
              S('Método recusado ou não publicado pela Inteligência', 'F5',
                via=[T('Avisar quem pediu a capacidade que o método não foi publicado, com o motivo', R)]),
              S('Método retirado, ou capacidade sem uso na revisão', 'E3',
                via=[T('Marcar a capacidade a retirar e as jornadas e os agentes que a usam', R)])]),
           T('Estimar o ganho esperado e a prioridade da necessidade', A)],
          [('Necessidade de capacidade priorizada', ['etapa 2']),
           ('Pedido de serviço encaminhado, com acordo de serviço', ['Executivos', 'Líderes dos círculos']),
           ('Capacidade não criada, com o motivo', ['IT-08'])]),
        E('Desenhar a ficha da capacidade com o dono e a Inteligência', 'Integração, com o círculo dono, a Inteligência e a Governança', 'Copiloto', 'médio',
          [('Necessidade de capacidade priorizada', 'etapa 1'), (KIT, 'Inteligência'), (BASE_PUB, 'Inteligência'),
           (PADROES_ID, 'Identidade'), (ALCADAS, 'Governança')],
          [D('Há método publicado para a capacidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'F4', via=[T('Pedir à Inteligência o método para a capacidade, com a necessidade e o ganho', R)])]),
           T('Propor a ficha: método, conhecimento, executor, ferramentas, acordo de serviço e indicador', A),
           T('Decidir o executor da capacidade: pessoa, agente, automação ou assessoria', P),
           T('Definir a alçada do executor da capacidade', 'GOV'),
           T('Aceitar a ficha e assumir a capacidade no seu círculo', 'LCI'),
           D('O líder do círculo dono aceitou a ficha?', P,
             [S('Sim', 'prox'),
              S('Não, ajustar a ficha', 'E2'),
              S('Não: o dono não assume a capacidade', 'F6',
                via=[T('Registrar o motivo e avisar quem pediu a capacidade', R)])])],
          [(FICHA, ['etapa 3', 'IT-06']),
           (PED_METODO, ['Inteligência']),
           ('Capacidade não criada, com o motivo', ['IT-08'])]),
        E('Publicar ou retirar a capacidade no catálogo e pedir a construção', 'Integração', 'Autopiloto', 'baixo',
          [(FICHA, 'etapa 2')],
          [D('O que a capacidade pede?', R,
             [S('Agente ou automação', 'seg',
                via=[T('Pedir a montagem ou a mudança do agente ou da automação', R)]),
              S('Pessoa ou assessoria', 'seg', via=[T('Abrir na carteira o projeto de preparar pessoas ou contratar a assessoria', R)]),
              S('Retirada da capacidade', 'F3',
                via=[T('Retirar a capacidade do catálogo, pedir a retirada dos agentes e avisar os donos afetados', R)])]),
           T('Versionar a ficha e ligar a capacidade às jornadas, às tarefas e aos donos', R),
           T('Publicar a capacidade no catálogo, em construção até o agente ou a pessoa estarem prontos', R)],
          [(PED_AGENTE, ['IT-06']),
           (PROJETO, ['IT-01']),
           (CATALOGO, [TODOS]),
           (REGISTROS, ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='IT-06',
    nome='Cuidar dos agentes e automações: montar, testar, liberar, monitorar e corrigir',
    dominio='Capacidades e agentes', classe='essencial', onda=1,
    objetivo='Fazer cada agente ou automação ser montado pela ficha da capacidade, com o método, o conhecimento, os padrões de identidade e a alçada; passar nos casos de teste da Inteligência e da Identidade antes de entrar em uso; ser aceito pelo líder do círculo dono; e ser monitorado em uso, com o desvio corrigido, suspenso quando sai da alçada e retirado quando o método, a base ou a marca saem de uso. A Inteligência diz o que o agente precisa saber e mede se ele acertou; a Integração monta, testa, libera e mantém; a Governança define a alçada e audita.',
    frequencia='Por evento: pedido de montagem ou de mudança, método, base, padrão ou marca alterados, falha ou desvio detectado; e a cada ciclo de monitoramento (cadência a definir)',
    automacao=('média', 'Montar, rodar os casos de teste, medir o acerto e monitorar são de agente e automação; decidir a arquitetura, julgar os casos de fronteira, liberar e decidir a correção são de pessoa da Integração; aceitar o agente é do líder do círculo dono; a alçada é da Governança.'),
    base=['anthropic_evals', 'nist_airmf', 'apqc'],
    lanes=['INT', 'IDE', 'GOV', 'LCI', P, A, R],
    inicios=[I('Pedido de montagem, de mudança ou de retirada de agente recebido', R, 'message'),
             I('Base de conhecimento ou perguntas de teste alteradas', 'INT', 'message'),
             I('Padrão, posicionamento ou marca alterados', 'IDE', 'message'),
             I('Falha ou desvio de agente detectado', R, 'signal'),
             I('Ciclo de monitoramento dos agentes iniciado', R, 'timer')],
    fins=[F('Agente em uso, monitorado', R),
          F('Agente retirado de uso', R),
          F('Agente suspenso, com a Governança e o dono avisados', R),
          F('Falha devolvida à Inteligência: método ou base', R)],
    etapas=[
        E('Montar ou mudar o agente pela ficha', 'Integração', 'Copiloto', 'médio',
          [(PED_AGENTE, 'IT-05'), (PED_AGENTE, 'IT-02'), (FICHA, 'IT-05'), (KIT, 'Inteligência'), (BASE_PUB, 'Inteligência'),
           (PERG_TESTE, 'Inteligência'), (CRIT_AUDIT, 'Identidade'), (PADROES_ID, 'Identidade'), (POSIC, 'Identidade'),
           (PACOTE_MARCA, 'Identidade'), (MARCA_RET, 'Identidade'), (ALCADAS, 'Governança'), ('Desvio a corrigir no agente', 'etapa 4')],
          [T('Registrar o que abriu o trabalho e os agentes afetados', R),
           D('O que abriu o trabalho?', R,
             [S('Agente novo, mudança pedida, conteúdo alterado ou desvio a corrigir', 'seg'),
              S('Retirada pedida pelo catálogo, ou marca retirada de uso', 'F2',
                via=[T('Retirar o agente ou o conteúdo de uso e avisar o dono da capacidade', R)]),
              S('Ciclo de monitoramento', 'E4')]),
           D('Há padrão de identidade para o canal ou o tipo de agente?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Pedir à Identidade o padrão para o agente ou o canal novo', R),
                                   T('Receber os padrões e os casos de teste da Identidade', R, 'receive')])]),
           T('Decidir a arquitetura do agente: modelo, ferramentas, conhecimento e integrações', P),
           T('Montar as instruções, o conhecimento, as ferramentas, a voz e a alçada do agente', A)],
          [('Agente montado', ['etapa 2']),
           (PED_PADRAO, ['Identidade'])]),
        E('Testar o agente com os casos de teste', 'Integração, com a Inteligência', 'Copiloto', 'médio',
          [('Agente montado', 'etapa 1')],
          [T('Rodar os casos de teste do método, da base e da Identidade', R),
           T('Medir o acerto do conteúdo e julgar os casos de fronteira de conteúdo', 'INT'),
           T('Medir erro, tempo e custo e julgar os casos de fronteira de operação', P),
           D('O agente atinge o critério de sucesso?', P,
             [S('Sim', 'prox'),
              S('Não: falha do agente', 'E1', via=[T('Apontar a falha do agente e o que corrigir', A)]),
              S('Não: o método ou a base é que falha', 'F4',
                via=[T('Devolver à Inteligência o resultado dos testes, com os casos que falham', R)])])],
          [('Agente aprovado nos testes', ['etapa 3']),
           ('Agente ou acesso não entregue, com o motivo', ['IT-02']),
           (RES_TESTES, ['Inteligência'])]),
        E('Liberar o agente em uso', 'Integração; aceita o líder do círculo dono; a Governança confere a alçada', 'Copiloto', 'alto',
          [('Agente aprovado nos testes', 'etapa 2')],
          [T('Conferir a alçada e os acessos do agente', 'GOV'),
           T('Aceitar o agente na capacidade do seu círculo', 'LCI'),
           D('A Governança e o líder do círculo dono aceitaram o agente?', P,
             [S('Sim', 'seg'),
              S('Não, ajustar', 'E1')]),
           T('Liberar o agente em uso', P),
           T('Registrar a versão liberada, a alçada e o dono e marcar a capacidade como em uso', R)],
          [('Agente em uso', ['etapa 4']),
           ('Agente liberado para quem pediu', ['IT-02']),
           (REGISTROS, ['Inteligência'])]),
        E('Monitorar o agente em uso e tratar o desvio', 'Integração', 'Autopiloto', 'médio',
          [('Agente em uso', 'etapa 3')],
          [T('Monitorar erro, disponibilidade, custo e consultas e mandar a amostra à Inteligência', R),
           T('Registrar as entregas dos agentes para a auditoria e para a Identidade', R),
           D('Há desvio no agente?', A,
             [S('Não', 'prox'),
              S('Sim, corrigível na montagem', 'E1', via=[T('Abrir a correção do agente', R)]),
              S('Sim: risco ou decisão fora da alçada', 'F3',
                via=[T('Suspender o agente, avisar a Governança e o dono e registrar a correção pendente', R)])])],
          [(RES_TESTES, ['Inteligência']),
           (CONSULTAS_AG, ['Inteligência']),
           (REG_ENTREGAS, ['Identidade', 'Governança']),
           ('Desvio a corrigir no agente', ['etapa 1']),
           ('Agente suspenso, com o motivo', ['Governança', 'Líderes dos círculos']),
           ('Agente ou acesso não entregue, com o motivo', ['IT-02'])]),
    ]))
