# -*- coding: utf-8 -*-
"""Referências conferidas. ref: a referência; conf: o que foi lido de fato; links.
O uso de cada fonte é declarado por círculo (USO)."""

FONTES_BASE = {'apqc': {'ref': 'APQC, Process Classification Framework (PCF), cross-industry',
          'conf': 'PDF da versão 7.4 (agosto de 2024) aberto em dois endereços; os elementos das categorias 1, 3 e 7 foram conferidos um a um, por mim e por '
                  'um revisor independente. A leitura do PDF parou na categoria 9: os grupos de relações externas (12.4, questões legais e éticas; 12.5, '
                  'relações públicas) só foram vistos em cópia de versão anterior e por isso não são citados pelo número. A versão 8.0 (27/02/2026) foi '
                  'conferida só nas 13 categorias, na página da coleção de definições da APQC.',
          'links': [('PCF 7.4 (PDF, cópia 1)',
                     'https://www.business-analysis.com.au/wp-content/uploads/2025/04/K014750_APQC-Process-Classification-Framework-PCF-Cross-Industry-PDF-Version-7.4_January-2025.pdf'),
                    ('PCF 7.4 (PDF, cópia 2)',
                     'https://solutions.ifrc.org/sites/default/files/2024-10/K014750_APQC%20Process%20Classification%20Framework%20(PCF)%20-%20Cross%20Industry%20-%20PDF%20Version%207.4.pdf'),
                    ('PCF 8.0 (página oficial)',
                     'https://www.apqc.org/resource-library/resource-listing/apqc-process-classification-framework-pcf-cross-industry-excel-12'),
                    ('PCF 8.0, 13 categorias',
                     'https://www.apqc.org/resource-library/resource-collection/pcf-version-80-process-definitions-and-key-measures-collection'),
                    ('cópia de versão anterior', 'https://waleriabueno.wordpress.com/wp-content/uploads/2021/02/apqc-pcf-7.pdf')]},
 'collins': {'ref': 'Jim Collins e Jerry Porras, Building Your Company’s Vision, Harvard Business Review, set.–out. 1996',
             'conf': 'Página oficial do artigo aberta; o texto completo é pago, a definição citada está visível.',
             'links': [('hbr.org', 'https://hbr.org/1996/09/building-your-companys-vision')]},
 'iso37000': {'ref': 'ISO 37000:2021, Governance of organizations — Guidance',
              'conf': 'Página do comitê ISO/TC 309 aberta; a norma completa é paga e não foi lida.',
              'links': [('committee.iso.org', 'https://committee.iso.org/ISO_37000_Governance')]},
 'pas808': {'ref': 'BSI, PAS 808:2022, Purpose-driven organizations. Worldviews, principles and behaviours for delivering sustainability. Guide',
            'conf': 'Página oficial da BSI aberta (publicada em 30/07/2022); o texto completo é pago e não foi lido.',
            'links': [('knowledge.bsigroup.com',
                       'https://knowledge.bsigroup.com/products/purpose-driven-organizations-worldviews-principles-and-behaviours-for-delivering-sustainability-guide')]},
 'quinn': {'ref': 'Robert Quinn e Anjan Thakor, Creating a Purpose-Driven Organization, Harvard Business Review, jul.–ago. 2018',
           'conf': 'Página oficial aberta (título, autores e data); os oito passos foram conferidos em cópia do artigo hospedada pela FAO.',
           'links': [('hbr.org', 'https://hbr.org/2018/07/creating-a-purpose-driven-organization'),
                     ('cópia (FAO)', 'https://www.fao.org/fileadmin/templates/library/pdf/Harvard_Business_Review.pdf')]},
 'hatch': {'ref': 'Mary Jo Hatch e Majken Schultz, Are the Strategic Stars Aligned for Your Corporate Brand?, Harvard Business Review, fev. 2001, v. 79, n. 2, '
                  'p. 129–134',
           'conf': 'Página oficial aberta (texto pago); o resumo com as três lacunas foi conferido no registro da Copenhagen Business School.',
           'links': [('hbr.org', 'https://hbr.org/2001/02/are-the-strategic-stars-aligned-for-your-corporate-brand'),
                     ('registro CBS', 'https://research.cbs.dk/en/publications/are-the-strategic-stars-aligned-for-your-corporate-brand/')]},
 'aaker': {'ref': 'David Aaker e Erich Joachimsthaler, The Brand Relationship Spectrum, California Management Review, v. 42, n. 4, 2000',
           'conf': 'Registro do artigo aberto na Case Centre; estratégias e perguntas conferidas em cópia do artigo hospedada por terceiro. As páginas não são '
                   'citadas: a cópia mostra 8–22 e há citação como 8–23.',
           'links': [('The Case Centre', 'https://www.thecasecentre.org/products/view?id=5390'),
                     ('cópia do artigo', 'https://ngovietliem.com/wp-content/uploads/2022/12/Reading-4.2-Brand-relationship-spectrum.pdf')]},
 'wheeler': {'ref': 'Alina Wheeler, Designing Brand Identity',
             'conf': 'As cinco fases foram conferidas em entrevista da autora; o livro não foi lido.',
             'links': [('entrevista (Logo Geek)', 'https://logogeek.uk/podcast/design-a-brand-identity-with-alina-wheeler/')]},
 'inpi': {'ref': 'INPI, serviço de prorrogação de registro de marca (gov.br)',
          'conf': 'Página oficial do serviço aberta. O artigo da Lei 9.279/1996 não foi conferido no texto da lei.',
          'links': [('gov.br', 'https://www.gov.br/pt-br/servicos/solicitar-a-prorrogacao-de-registro-de-marca-e-expedicao-de-certificado-de-registro')]},
 'iso20671': {'ref': 'ISO 20671-1:2021, Brand evaluation — Part 1: Principles and fundamentals',
              'conf': 'Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida.',
              'links': [('iso.org', 'https://www.iso.org/standard/81739.html')]},
 'iso10010': {'ref': 'ISO 10010:2022, Quality management — Guidance to understand, evaluate and improve organizational quality culture',
              'conf': 'Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida. O foco da norma é cultura de qualidade; usamos a '
                      'sequência entender, avaliar e melhorar, que está no título, não o conteúdo.',
              'links': [('iso.org', 'https://www.iso.org/standard/38457.html')]},
 'mckinsey': {'ref': 'Tessa Basford e Bill Schaninger, The four building blocks of change, McKinsey, 11/04/2016',
              'conf': 'Artigo aberto no site da McKinsey.',
              'links': [('mckinsey.com',
                         'https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/the-four-building-blocks--of-change')]},
 'schein': {'ref': 'Edgar Schein, modelo de cultura organizacional em três níveis',
            'conf': 'Fonte secundária: verbete da Wikipédia. O livro não foi lido.',
            'links': [('Wikipédia', 'https://en.wikipedia.org/wiki/Edgar_Schein')]},
 'craig': {'ref': 'Nick Craig e Scott Snook, From Purpose to Impact, Harvard Business Review, v. 92, n. 5, maio de 2014',
           'conf': 'Registro do artigo aberto no site da Harvard Business School e página do artigo na HBR (resumo); o texto completo não foi lido. As páginas '
                   'não são citadas: os registros divergem entre 104–111 e 105–111.',
           'links': [('hbs.edu', 'https://www.hbs.edu/faculty/Pages/item.aspx?num=47372'), ('hbr.org', 'https://hbr.org/2014/05/from-purpose-to-impact')]},
 'reptrak': {'ref': 'RepTrak, Global RepTrak 100 (2026)',
             'conf': 'Página oficial aberta.',
             'links': [('reptrak.com', 'https://www.reptrak.com/globalreptrak/')]},
 'iso22361': {'ref': 'ISO 22361:2022, Security and resilience — Crisis management — Guidelines',
              'conf': 'Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida.',
              'links': [('iso.org', 'https://www.iso.org/standard/50267.html')]},
 'nng': {'ref': 'Kate Moran, The Four Dimensions of Tone of Voice, Nielsen Norman Group, 17/07/2016',
         'conf': 'Artigo aberto no site da NN/g.',
         'links': [('nngroup.com', 'https://www.nngroup.com/articles/tone-of-voice-dimensions/')]},
 'google_persona': {'ref': 'Google, Conversation Design: Create a persona',
                    'conf': 'Página oficial aberta. A plataforma a que o guia se refere foi descontinuada em 13/06/2023; o método de persona continua '
                            'aplicável.',
                    'links': [('developers.google.com', 'https://developers.google.com/assistant/conversation-design/create-a-persona')]},
 'impact': {'ref': 'Impact Frontiers, Five Dimensions of Impact (Impact Management Norms)',
            'conf': 'Página oficial aberta.',
            'links': [('impactfrontiers.org', 'https://impactfrontiers.org/norms/five-dimensions-of-impact/')]},
 'bpmn': {'ref': 'OMG, Business Process Model and Notation (BPMN) 2.0.2; ISO/IEC 19510:2013',
          'conf': 'Páginas oficiais da OMG e da ISO abertas; a lista de tipos de tarefa foi conferida no BPMN Quick Guide; a atividade de chamada foi aceita '
                  'pelo metamodelo usado nos testes. A especificação completa não foi lida.',
          'links': [('omg.org', 'https://www.omg.org/spec/BPMN/2.0.2/About-BPMN'),
                    ('iso.org', 'https://www.iso.org/standard/62652.html'),
                    ('BPMN Quick Guide', 'https://www.bpmnquickguide.com/quickguide/bpmn-quick-guide/tasks')]},
 'camunda': {'ref': 'Camunda, Best Practices: Naming BPMN elements',
             'conf': 'Documentação oficial aberta.',
             'links': [('docs.camunda.io', 'https://docs.camunda.io/docs/components/best-practices/modeling/naming-bpmn-elements/')]},
 'dmn': {'ref': 'OMG, Decision Model and Notation (DMN)', 'conf': 'Página oficial da OMG aberta.', 'links': [('omg.org', 'https://www.omg.org/spec/DMN')]},
 'sipoc': {'ref': 'ASQ, SIPOC+CM Diagram', 'conf': 'Página oficial da ASQ aberta.', 'links': [('asq.org', 'https://asq.org/quality-resources/sipoc')]},
 'iia': {'ref': 'The Institute of Internal Auditors, The IIA’s Three Lines Model: An Update of the Three Lines of Defense (2020; versão lida atualizada em '
                'setembro de 2024)',
         'conf': 'Documento oficial aberto no site do IIA. O modelo trata de governança e gestão de riscos; aplicá-lo à separação de papéis entre os '
                 'círculos é analogia nossa.',
         'links': [('theiia.org',
                    'https://www.theiia.org/globalassets/documents/resources/the-iias-three-lines-model-an-update-of-the-three-lines-of-defense-july-2020/three-lines-model-updated-english.pdf')]},
 'kaplan': {'ref': 'Robert Kaplan e David Norton, Mastering the Management System, Harvard Business Review, janeiro de 2008',
            'conf': 'Página oficial aberta (resumo; o texto completo é pago). Os nomes dos cinco estágios e a diferença entre reunião operacional e reunião de '
                    'estratégia foram conferidos em cópia do artigo hospedada por terceiro.',
            'links': [('hbr.org', 'https://hbr.org/2008/01/mastering-the-management-system'),
                      ('cópia do artigo', 'https://www.strimgroup.com/wp-content/uploads/pdf/KaplanNorton_HBR_MasteringTheManagementSystem.pdf')]},
 'rumelt': {'ref': 'Richard Rumelt, The perils of bad strategy, McKinsey Quarterly, 01/06/2011',
            'conf': 'Artigo aberto no site da McKinsey.',
            'links': [('mckinsey.com', 'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/the-perils-of-bad-strategy')]},
 'okr': {'ref': 'Google re:Work, Guide: Set goals with OKRs',
         'conf': 'Guia oficial aberto.',
         'links': [('rework.withgoogle.com', 'https://rework.withgoogle.com/intl/en/guides/set-goals-with-okrs')]},
 'lei': {'ref': 'Lean Enterprise Institute, Lean Lexicon: Strategy Deployment (hoshin kanri)',
         'conf': 'Verbete oficial aberto.',
         'links': [('lean.org', 'https://www.lean.org/lexicon-terms/strategy-deployment/')]},
 'horizons': {'ref': 'McKinsey, Enduring Ideas: The three horizons of growth, McKinsey Quarterly, 01/12/2009',
              'conf': 'Artigo aberto no site da McKinsey.',
              'links': [('mckinsey.com',
                         'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/enduring-ideas-the-three-horizons-of-growth')]},
 'parenting': {'ref': 'Andrew Campbell, Michael Goold e Marcus Alexander, Corporate Strategy: The Quest for Parenting Advantage, Harvard Business Review, '
                      'mar.–abr. 1995',
               'conf': 'Página oficial aberta; o texto completo é pago. Só as duas perguntas do trecho de abertura, visível na página, foram conferidas.',
               'links': [('hbr.org', 'https://hbr.org/1995/03/corporate-strategy-the-quest-for-parenting-advantage')]},
 'realloc': {'ref': 'Stephen Hall, Dan Lovallo e Reinier Musters, How to put your money where your strategy is, McKinsey Quarterly, março de 2012',
             'conf': 'Artigo aberto no site da McKinsey (página e PDF). O número citado é dos autores, sobre a amostra deles; não foi reproduzido por nós.',
             'links': [('mckinsey.com',
                        'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/how-to-put-your-money-where-your-strategy-is'),
                       ('PDF',
                        'https://www.mckinsey.com/~/media/McKinsey/Business%20Functions/Strategy%20and%20Corporate%20Finance/Our%20Insights/How%20to%20put%20your%20money%20where%20your%20strategy%20is/How%20to%20put%20your%20money%20where%20your%20strategy%20is.pdf')]},
 'stagegate': {'ref': 'Stage-Gate International, The Stage-Gate Model: An Overview (página do blog, com o nome de Robert G. Cooper)',
               'conf': 'Página oficial aberta. Os metadados da página indicam publicação em 15/12/2025 e outra autora; por isso a data e a autoria não '
                       'entram na referência.',
               'links': [('stage-gate.com', 'https://www.stage-gate.com/blog/the-stage-gate-model-an-overview/')]}}
