# -*- coding: utf-8 -*-
"""Círculo 8 · Gestão. Fechado em 03/10/2026, aprovado às 11:50: treze jornadas; GE-14 e GE-15 acrescentadas em 03/10/2026, às 21:05.
Regra do círculo: a Gestão decide o que é do seu ofício (o desdobramento e o controle do orçamento aprovado, o ritual de
acompanhamento, a cobrança, a compra, o fechamento das contas, a aplicação do rateio e os processos de pessoas), dentro
da alçada. Os sócios aprovam alvos e orçamento; o executivo decide o que passa da alçada da Gestão e o líder decide a
contratação na sua equipe; a Governança define as alçadas, o critério de rateio e as regras e guarda os contratos. O desligamento é decidido pelo executivo, com o líder."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 8, 'Gestão', 'GE', 'GE'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo8-gestao'
FECHADO = True
STATUS = 'Fechado em 03/10/2026, aprovado às 11:50 · auditoria de execução aplicada em 03/10/2026 · GE-14, GE-15 e as etapas novas aprovadas às 21:05'
LEAD = ('A Gestão garante os recursos e a rotina. Desdobra e controla o orçamento aprovado, roda o ritual de acompanhamento '
        'dos alvos, fatura e recebe, compra e paga, fecha as contas e os impostos, aplica o rateio entre as empresas e '
        'cuida das pessoas: provê, integra à cultura, avalia, desenvolve, paga, reconhece e comunica para dentro. Cuida '
        'também dos ativos, das dívidas tributárias e dos parcelamentos, do plano de contas, dos centros de custo e do plano tributário do grupo. '
        'Não define as regras nem escolhe o rumo. São quinze jornadas.')
PRINCIPIO = ('Regra do círculo, aprovada por você às 11:50 de 03/10/2026: a Gestão decide o que é do seu ofício '
             '(o desdobramento e o controle do orçamento aprovado, o ritual de acompanhamento, a cobrança, a compra, o '
             'fechamento das contas, a aplicação do rateio e os processos de pessoas), dentro da alçada. Os sócios aprovam '
             'alvos e orçamento; o executivo decide o que passa da alçada da Gestão; o líder decide a contratação na sua '
             'equipe; o desligamento é decidido pelo executivo, com o líder; a Governança define as alçadas, o critério de '
             'rateio e as regras e guarda os contratos.')
MUDOU_INTRO = ('Comparação com o catálogo da rodada 2 (49 jornadas e 216 workflows), que continua no documento do '
               'projeto até cada círculo ser fechado. Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')
COBERTURA_TXT = ('Processos do APQC PCF 7.4 ligados às funções da Gestão (categorias 7.0, 9.0 e 10.0 e o grupo 4.2), '
                 'grupo a grupo: onde cada um está neste modelo. Os nomes estão como no referencial.')

P, A, R = 'GEP', 'GEA', 'GER'

# produtos da Gestão esperados pelos círculos fechados (nomes exatos)
PESQUISA = 'Resultado da pesquisa de cultura e dados de pessoas'
DESVIOS = 'Desvios e decisões do ritual de acompanhamento'
EXEC_ORC = 'Execução do orçamento e da alocação por empresa, oferta e aposta'
CAIXA = 'Posição e projeção de caixa'
RESULTADO = 'Resultado por empresa e consolidado'
MARGENS = 'Custos e margens por empresa e oferta'
ORC_DEM = 'Orçamento de demanda do ciclo'
RESP_REC = 'Resposta ao pedido de recurso adicional'
SIT_FAT = 'Situação de faturas e pagamentos do cliente'
COMPRADOS = 'Materiais e serviços comprados, com a data de entrega'
RECURSOS_OK = 'Pessoas, compras e ativos do plano confirmados'
# pedidos aceitos pelos círculos fechados de qualquer origem
PED_TEC = 'Pedido, incidente ou risco de tecnologia'
CONSULTA = 'Consulta sobre caso não coberto'
# produtos internos usados em mais de uma jornada
ORC_VIG = 'Orçamento vigente por empresa, círculo, oferta e aposta'
RATEIO = 'Rateio do custo dos círculos por empresa'
CONTRATADA = 'Pessoa contratada, com papel e líder'
MUD_PESSOAS = 'Mudança de pessoas registrada'
INTEGRADA = 'Integração cultural concluída, com o resultado da verificação'
RECONHEC = 'Reconhecimentos concedidos'
PARTICIP = 'Registro de participação em rituais'
HISTORIAS = 'Histórias e reconhecimentos a comunicar'
RECEITAS = 'Receitas faturadas e recebidas'
PAGOS = 'Pagamentos a fornecedores e parceiros realizados'
FOLHA = 'Folha e encargos pagos'
ATIVOS = 'Registro de ativos atualizado, com depreciação e baixas'
PED_COMPRA = 'Pedido de compra'
MUD_REMUN = 'Mudanças de remuneração aprovadas'
# produtos de outros círculos
KIT = 'Kit de cultura e pessoas'
VENCIDOS = 'Aviso de materiais vencidos'
LACUNAS_EXEC = 'Lacunas de execução apontadas'
MARCA_RET = 'Marca retirada de uso'
PACOTE_MARCA = 'Pacote de marca publicado'
MUD_DECL = 'Mudança na declaração a comunicar'
MUD_PADROES = 'Mudança nos padrões a comunicar'
POSIC = 'Posicionamento e casa de mensagens vigentes'
RESUMO_PAD = 'Resumo da avaliação dos padrões'
PADROES_ID = 'Padrões de identidade vigentes'
RESPOSTA_ID = 'Resposta à consulta'
ALOCACAO = 'Alocação de recursos por empresa, oferta e aposta'
ALVOS = 'Alvos e iniciativas do ciclo'
AP_ESPERA = 'Aposta em espera ou devolvida'
AP_MANTIDA = 'Aposta mantida depois da revisão'
CORRECOES = 'Correções de execução publicadas, com dono e prazo'
DATA_SAIDA = 'Data de saída confirmada da aposta ou da oferta encerrada'
DEC_ALOC = 'Decisão de alocação e de destino do resultado'
DEC_SOCIOS = 'Decisão dos sócios sobre alvos e orçamento'
LISTA_ADQ = 'Lista de pessoas da empresa adquirida'
MANDATO = 'Mandato da empresa'
MUD_EST = 'Mudança na estratégia a comunicar'
METODO_EST = 'Método de estratégia vigente: critérios dos portões, regras de realocação e calendário'
PED_CORRECAO = 'Pedido de plano de correção'
PORTFOLIO = 'Portfólio de empresas atualizado'
REC_APOSTA = 'Recursos aprovados para a aposta'
REC_DEVOLVER = 'Recursos da aposta encerrada a devolver'
REV_SEM = 'Revisão sem correção registrada'
OFERTA_FORA = 'Aposta ou oferta encerrada e fora do catálogo de ofertas'
AP_DEVOLVIDA = 'Aviso de aposta devolvida, com recursos e projeto suspensos até a decisão da Estratégia'
INDICADORES = 'Indicadores e análises por empresa, oferta e aposta'
REV_IND = 'Resultado da revisão dos indicadores, com as contestações de indicador de alvo vigente'
PAINEL = 'Painel de indicadores de cada círculo, com dono e análise'
CONT_EXT = 'Conteúdo externo publicado'
PED_REC = 'Pedido de recurso adicional para demanda'
PLANO_DEM = 'Plano de demanda do ciclo: públicos, ofertas, canais, ações, alvos e orçamento'
ACORDO_CONJ = 'Acordo de oferta conjunta entre as empresas'
ATA = 'Ata de registro de preços vigente, com saldo e órgãos participantes'
CONTRATO = 'Contrato de cliente assinado, com o escopo vendido'
CONTR_FIM = 'Contrato encerrado, com a data de fim'
CONTR_SAIDA = 'Contratos encerrados ou transferidos na saída'
DESVIO_PREV = 'Desvio da previsão contra os alvos, com as ações'
PLANO_VENDAS = 'Plano de vendas do ciclo: alvos por empresa, oferta e canal'
PREVISAO = 'Previsão de receita e de vendas'
TABELA = 'Tabela de preços e política comercial vigentes'
VENCIMENTO = 'Vencimento do contrato e resultado da renovação'
CLI_IMPL = 'Cliente implantado e aceito, passado à entrega'
CUSTO_TEC = 'Custo de tecnologia por empresa e por círculo'
IMPEDIMENTO = 'Impedimento do lançamento, com as opções'
OFERTA_LANCADA = 'Oferta lançada'
PLANO_IMPL = 'Plano de implantação do cliente'
PLANO_LANC = 'Plano de lançamento da oferta'
SAIDA_CLI = 'Plano de saída de clientes e contratos'
PROJ_ENC = 'Projeto encerrado, com o resultado'
REC_LIB_IT = 'Recursos liberados de projeto suspenso ou encerrado'
SITUACAO = 'Situação das iniciativas na carteira de projetos'
CREDITO = 'Crédito ou reembolso aprovado para o cliente'
DESEMP_FORN = 'Desempenho dos fornecedores na entrega e na qualidade'
FATURAR = 'Entregas confirmadas para faturar, com a medição dos níveis de serviço'
COBRANCA_FORN = 'Pedido de cobrança do fornecedor pela falha'
PED_COMPRA_OP = 'Pedido de compra de materiais e serviços'
PLANO_CAP = 'Plano de capacidade de entrega: pessoas, parceiros, materiais e ativos'
REC_LIB_OP = 'Recursos da operação liberados, com a data'
ALCADAS = 'Regras e alçadas vigentes'
SIGILO = 'Regras de sigilo e de dados pessoais'
CRITERIO_RATEIO = 'Critério de rateio do custo dos círculos'

JORNADAS = []
