
# ========================================================== PLANEJAMENTO E CONTROLE
JORNADAS.append(dict(
    code='GE-01',
    nome='Desdobrar o orçamento aprovado e controlar as mudanças de recurso',
    dominio='Planejamento e controle', classe='essencial', onda=1,
    objetivo='Fazer o orçamento aprovado pelos sócios ser desdobrado por empresa, círculo, oferta, aposta e conta, com um dono por linha; os planos de demanda, de vendas, de capacidade e de lançamento caberem nele ou terem a diferença apontada; cada pedido de recurso, liberação, congelamento ou devolução ser decidido na alçada, pela Gestão ou, acima dela, pelo executivo (recurso da empresa), pelo Administrador do IMTS.OS (recurso dos círculos compartilhados) ou pelos sócios (aumento do total aprovado); e o orçamento vigente ser publicado a quem executa. Os sócios aprovam; a Gestão desdobra e controla; a realocação entre empresas fica na revisão do portfólio da Estratégia.',
    frequencia='A cada ciclo de orçamento, depois da aprovação dos sócios, e por evento: pedido de recurso, aposta aprovada, devolvida ou encerrada, projeto suspenso, recurso liberado',
    automacao=('média', 'Desdobrar, conferir os planos com o orçamento, calcular o efeito e publicar são de agente e automação; fechar o desdobramento e decidir dentro da alçada são de pessoa da Gestão; acima da alçada, do executivo, do Administrador do IMTS.OS ou dos sócios.'),
    base=['apqc'],
    lanes=['EST', 'SOC', 'ADM', 'EXE', P, A, R],
    inicios=[I('Alvos e orçamento aprovados pelos sócios', 'EST', 'message'),
             I('Pedido de recurso, liberação ou devolução recebido', R, 'message')],
    fins=[F('Orçamento vigente publicado', R)],
    etapas=[
        E('Desdobrar o orçamento aprovado e conferir os planos', 'Gestão', 'Copiloto', 'médio',
          [(DEC_SOCIOS, 'Estratégia'), (ALVOS, 'Estratégia'), (ALOCACAO, 'Estratégia'), (METODO_EST, 'Estratégia'),
           (PLANO_VENDAS, 'Negócios'), (PREVISAO, 'Negócios'), (PLANO_DEM, 'Relações'), (PLANO_CAP, 'Operações'),
           (SITUACAO, 'Integração'), (CUSTO_TEC, 'Integração'), (PLANO_LANC, 'Integração'), (RATEIO, 'GE-06')],
          [D('O que iniciou o trabalho?', R,
             [S('Orçamento do ciclo aprovado', 'seg'),
              S('Pedido de recurso, liberação ou devolução', 'E2')]),
           T('Desdobrar o orçamento por empresa, círculo, oferta, aposta e conta, com um dono por linha', A),
           T('Conferir os planos de demanda, vendas, capacidade e lançamento com o orçamento', A),
           T('Fechar o orçamento desdobrado e apontar a cada dono o que não coube', P),
           D('Há pedido de recurso em aberto para decidir agora?', R,
             [S('Não', 'E3'),
              S('Sim', 'prox')])],
          [('Orçamento desdobrado, com dono por linha', ['etapa 3']),
           (ORC_DEM, ['Relações']),
           (RECURSOS_OK, ['Operações'])]),
        E('Decidir pedidos de recurso, liberações e devoluções', 'Gestão; acima da alçada, o executivo, o Administrador do IMTS.OS ou os sócios', 'Copiloto', 'médio',
          [(PED_REC, 'Relações'), (REC_APOSTA, 'Estratégia'), (REC_DEVOLVER, 'Estratégia'), (AP_ESPERA, 'Estratégia'),
           (AP_MANTIDA, 'Estratégia'), (DATA_SAIDA, 'Estratégia'), (AP_DEVOLVIDA, 'Inteligência'),
           (OFERTA_FORA, 'Inteligência'), (IMPEDIMENTO, 'Integração'), (REC_LIB_IT, 'Integração'),
           (REC_LIB_OP, 'Operações'), (ALCADAS, 'Governança'), (PED_REC, 'GE-02')],
          [T('Registrar o pedido, a liberação ou a decisão e a linha do orçamento afetada', R),
           T('Calcular o efeito no orçamento e no caixa', A),
           T('Conferir o efeito e a alçada do pedido', P),
           D('Quem decide o pedido?', P,
             [S('A Gestão: cabe na alçada, ou é liberação, congelamento ou devolução já decidida', 'seg',
                via=[T('Decidir o pedido dentro da alçada da Gestão', P)]),
              S('O executivo: recurso da empresa acima da alçada da Gestão', 'seg',
                via=[T('Decidir o pedido acima da alçada da Gestão', 'EXE')]),
              S('O Administrador do IMTS.OS: recurso de círculo compartilhado, ou entre círculos, acima da alçada da Gestão', 'seg',
                via=[T('Decidir o pedido de recurso dos círculos acima da alçada da Gestão', 'ADM')]),
              S('Os sócios: aumenta o total do orçamento aprovado', 'seg',
                via=[T('Decidir o aumento do total do orçamento aprovado', 'SOC')]),
              S('A Estratégia: mexe na alocação entre empresas', 'seg',
                via=[T('Registrar o pedido para a revisão do portfólio e avisar quem pediu', R)])]),
           D('O pedido foi atendido?', P,
             [S('Sim, no todo ou em parte', 'seg', via=[T('Ajustar o orçamento', R)]),
              S('Não', 'seg')]),
           T('Responder a quem pediu, com o motivo', R)],
          [(RESP_REC, ['Relações']),
           ('Decisão sobre o recurso pedido, com o motivo', ['Executivos', 'Líderes dos círculos', 'Administrador do IMTS.OS']),
           ('Orçamento ajustado', ['etapa 3'])]),
        E('Publicar o orçamento vigente', 'Gestão', 'Autômato', 'baixo',
          [('Orçamento desdobrado, com dono por linha', 'etapa 1'), ('Orçamento ajustado', 'etapa 2')],
          [T('Publicar o orçamento vigente a cada dono e aos registros de compra e de pagamento', R)],
          [(ORC_VIG, ['Executivos', 'Líderes dos círculos', 'GE-02', 'GE-04', 'GE-05', 'GE-07', 'GE-12'])]),
    ]))

JORNADAS.append(dict(
    code='GE-02',
    nome='Rodar o ritual de acompanhamento dos alvos e cobrar as ações',
    dominio='Planejamento e controle', classe='essencial', onda=1,
    objetivo='Fazer cada período ter os resultados reunidos contra os alvos, com a execução do orçamento, os desvios e as causas prováveis; cada contrato ter o planejado no racional financeiro comparado com o realizado, e o que estiver fora do racional entrar na pauta com o dono; cada desvio ser discutido com o dono no ritual e ter uma ação com dono e prazo, decidida na alçada; cada pedido de plano de correção e cada correção publicada pela Estratégia entrar na pauta; e cada ação ser cobrada até concluir, com o atraso levado ao executivo. A Gestão roda o ritual; os donos decidem as ações; a Estratégia decide a correção de rumo.',
    frequencia='No calendário do método de estratégia (cadência: mensal) e por evento: pedido de plano de correção',
    automacao=('alta', 'Reunir, apontar desvios, registrar e cobrar são de agente e automação; conduzir o ritual é de pessoa da Gestão; propor e decidir as ações é dos líderes e do executivo.'),
    base=['apqc'],
    lanes=['EST', 'LCI', 'EXE', P, A, R],
    inicios=[I('Período do ritual de acompanhamento iniciado', R, 'timer'),
             I('Pedido de plano de correção recebido', 'EST', 'message')],
    fins=[F('Ritual realizado e ações acompanhadas', R),
          F('Ritual realizado, com ação em atraso levada ao executivo', R)],
    etapas=[
        E('Reunir os resultados do período contra os alvos', 'Gestão, com a Inteligência', 'Autopiloto', 'baixo',
          [(ALVOS, 'Estratégia'), (METODO_EST, 'Estratégia'), (INDICADORES, 'Inteligência'), (REV_IND, 'Inteligência'),
           (PAINEL, 'Inteligência'), (DESVIO_PREV, 'Negócios'), (SITUACAO, 'Integração'), (PROJ_ENC, 'Integração'),
           (ORC_VIG, 'GE-01'), (EXEC_ORC, 'GE-05'), ('Ações em atraso do ritual', 'etapa 4')],
          [T('Reunir indicadores, execução do orçamento, iniciativas e desvios do período', R),
           T('Apontar os desvios, as causas prováveis e os donos', A)],
          [('Pauta do ritual com os desvios e os donos', ['etapa 3'])]),
        E('Comparar o planejado e o realizado de cada contrato', 'Gestão', 'Autopiloto', 'baixo',
          [('Racional financeiro do contrato aprovado', 'Negócios'), (RECEITAS, 'GE-03')],
          [T('Reunir o racional financeiro de cada contrato e o realizado: receita, custo, margem e caixa', R),
           T('Apontar os contratos fora do racional e a causa provável', A),
           D('Há contrato fora do racional?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Incluir o contrato fora do racional na pauta do ritual, com o dono', R)])])],
          [('Contratos fora do racional, com a causa provável e o dono', ['etapa 3'])]),
        E('Conduzir o ritual e registrar as decisões', 'Gestão conduz; o líder decide na alçada; acima dela, o executivo; mudança de alvo, a Estratégia; recurso novo, a GE-01', 'Copiloto', 'médio',
          [('Pauta do ritual com os desvios e os donos', 'etapa 1'), ('Contratos fora do racional, com a causa provável e o dono', 'etapa 2'), (PED_CORRECAO, 'Estratégia'), (CORRECOES, 'Estratégia'),
           (REV_SEM, 'Estratégia')],
          [T('Incluir na pauta os pedidos de plano de correção e as correções publicadas', R),
           T('Conduzir o ritual com os donos dos alvos', P),
           T('Apresentar os desvios e propor as ações', 'LCI'),
           D('A ação cabe na alçada do líder do círculo?', P,
             [S('Sim', 'seg', via=[T('Decidir a ação na sua alçada', 'LCI')]),
              S('Não: passa do orçamento ou da alçada do círculo', 'seg', via=[T('Decidir a ação acima da alçada do líder', 'EXE')]),
              S('Não: a ação muda alvo', 'seg', via=[T('Levar a mudança de alvo à revisão da execução pela Estratégia', R)]),
              S('Não: a ação pede recurso novo', 'seg', via=[T('Abrir o pedido de recurso no orçamento', R)])]),
           T('Registrar desvios, decisões, donos e prazos', R),
           D('Há desvio grave pelo critério do método de estratégia?', R,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Apontar o desvio grave à Estratégia, que abre a revisão da execução', R)])])],
          [(DESVIOS, ['Estratégia']),
           ('Desvio grave ou mudança de alvo apontados pelo ritual', ['Estratégia']),
           (PED_REC, ['GE-01']),
           ('Ações do ritual, com dono e prazo', ['etapa 4'])]),
        E('Cobrar as ações até concluir', 'Gestão', 'Autômato', 'baixo',
          [('Ações do ritual, com dono e prazo', 'etapa 3')],
          [T('Lembrar cada dono e acompanhar o prazo das ações', R),
           D('A ação foi concluída no prazo?', A,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Levar o atraso ao próximo ritual e ao executivo', R)])])],
          [('Situação das ações do ritual', ['Executivos', 'Líderes dos círculos']),
           ('Ações em atraso do ritual', ['etapa 1'])]),
    ]))
