
# ========================================================== FINANÇAS
JORNADAS.append(dict(
    code='GE-03',
    nome='Faturar os clientes e receber e cobrar o que é devido',
    dominio='Finanças', classe='essencial', onda=1,
    objetivo='Fazer cada cliente ter o cadastro de cobrança conforme o contrato, a tabela, a ata e a divisão da oferta conjunta; cada entrega confirmada por Operações virar fatura, com a medição dos níveis de serviço e os créditos aprovados; cada recebimento ser conciliado e cada atraso cobrado, com a negociação acima do limite decidida pela Gestão, ouvido o executivo, e a suspensão das novas entregas do cliente privado na segunda fatura vencida decidida pelo executivo; o reembolso pago só depois de aprovado pelo líder do círculo; e a situação de faturas e pagamentos de cada cliente ir a Relações e a Negócios. Operações confirma a entrega; a Gestão fatura e recebe.',
    frequencia='Por evento: contrato, oferta ou cliente novo, mudado ou encerrado; entregas confirmadas; vencimento de fatura',
    automacao=('média', 'Cadastrar, calcular, emitir, conciliar, cobrar e informar são de agente e automação; aprovar a fatura fora do padrão, decidir a negociação do atraso e propor a suspensão são de pessoa da Gestão; aprovar o reembolso é do líder do círculo; decidir a suspensão é do executivo.'),
    base=['apqc'],
    lanes=['NEG', 'OPE', 'EXE', 'LCI', P, A, R],
    inicios=[I('Contrato, oferta ou cliente novo, mudado ou encerrado recebido', 'NEG', 'message'),
             I('Entregas confirmadas para faturar recebidas', 'OPE', 'message'),
             I('Vencimento de fatura', R, 'timer')],
    fins=[F('Fatura recebida ou cobrada e situação informada', R),
          F('Cadastro de cobrança atualizado, sem fatura a emitir agora', R),
          F('Fatura emitida, à espera do vencimento', R)],
    etapas=[
        E('Cadastrar o cliente e as condições de cobrança', 'Gestão', 'Autopiloto', 'baixo',
          [(CONTRATO, 'Negócios'), (ATA, 'Negócios'), (TABELA, 'Negócios'), (ACORDO_CONJ, 'Negócios'), (CONTR_FIM, 'Negócios'),
           (CONTR_SAIDA, 'Negócios'), (VENCIMENTO, 'Negócios'), (CLI_IMPL, 'Integração'), (PLANO_IMPL, 'Integração'),
           (OFERTA_LANCADA, 'Integração'), (PLANO_LANC, 'Integração'), (SAIDA_CLI, 'Integração')],
          [D('O que iniciou o trabalho?', R,
             [S('Contrato, oferta ou cliente novo, mudado ou encerrado', 'seg'),
              S('Entregas confirmadas para faturar', 'E2'),
              S('Vencimento de fatura', 'E3')]),
           T('Cadastrar ou atualizar cliente, contrato, preços, calendário de cobrança e divisão da receita', R),
           T('Conferir o cadastro contra o contrato, a tabela e a ata', A),
           D('Há entregas confirmadas a faturar agora?', R,
             [S('Não', 'F2'),
              S('Sim', 'prox')])],
          [('Cadastro de cobrança do cliente', ['etapa 2'])]),
        E('Calcular e emitir a fatura', 'Gestão', 'Autopiloto', 'médio',
          [('Cadastro de cobrança do cliente', 'etapa 1'), (FATURAR, 'Operações'), (CREDITO, 'Operações')],
          [D('Há crédito ou reembolso aprovado para o cliente?', R,
             [S('Não', 'seg'),
              S('Crédito na próxima fatura', 'seg', via=[T('Lançar o crédito na próxima fatura', R)]),
              S('Reembolso, ou cliente sem fatura futura', 'seg',
                via=[T('Aprovar o pagamento do reembolso na alçada', 'LCI'),
                     T('Pagar o reembolso ao cliente e registrar', R)])]),
           T('Calcular a fatura pelas entregas confirmadas, os níveis de serviço e os créditos', A),
           D('A fatura foge do padrão ou tem glosa ou ajuste?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir e aprovar a fatura fora do padrão', P)])]),
           T('Emitir a fatura e os documentos fiscais e enviá-los ao cliente', R),
           D('O pagamento já foi recebido na emissão?', R,
             [S('Não', 'F3'),
              S('Sim', 'prox')])],
          [('Fatura emitida', ['etapa 3', 'Clientes']),
           ('Reembolso pago ao cliente', ['Clientes'])]),
        E('Receber e cobrar', 'Gestão', 'Autopiloto', 'médio',
          [('Fatura emitida', 'etapa 2')],
          [T('Conciliar os recebimentos com as faturas', R),
           D('A fatura foi paga no vencimento?', R,
             [S('Sim', 'prox'),
              S('Não', 'seg', via=[T('Cobrar o cliente pelos canais combinados', A)])]),
           D('O atraso passa do limite da política de cobrança?', R,
             [S('Não', 'prox'),
              S('Sim', 'seg', via=[T('Decidir a negociação ou a cobrança do atraso, ouvido o executivo', P)])]),
           D('O cliente é privado e já tem a segunda fatura vencida?', R,
             [S('Não, ou é contrato público', 'prox'),
              S('Sim', 'prox', via=[T('Propor ao executivo a suspensão das novas entregas', P),
                                    T('Decidir a suspensão das novas entregas do cliente', 'EXE')])])],
          [('Recebimentos conciliados e atrasos tratados', ['etapa 4']),
           ('Suspensão de novas entregas por atraso, decidida pelo executivo', ['Operações'])]),
        E('Informar a situação de cada cliente', 'Gestão', 'Autopiloto', 'baixo',
          [('Recebimentos conciliados e atrasos tratados', 'etapa 3')],
          [T('Atualizar a situação de faturas e pagamentos de cada cliente', R),
           T('Apontar clientes com atraso recorrente', A)],
          [(SIT_FAT, ['Relações', 'Negócios']),
           (RECEITAS, ['GE-05', 'GE-13'])]),
    ]))

JORNADAS.append(dict(
    code='GE-04',
    nome='Comprar e pagar: do pedido de compra ao fornecedor e ao parceiro pagos',
    dominio='Finanças', classe='essencial', onda=1,
    objetivo='Fazer cada pedido de compra ser conferido contra o orçamento e a alçada; cada fornecedor ser escolhido por preço, prazo, qualidade e risco, com o contrato revisado e guardado pela Governança; cada compra ser recebida e conferida por quem pediu; cada fatura de fornecedor ser conferida com o pedido e o recebimento e paga com a aprovação do líder do círculo, que não é quem escolhe o fornecedor; cada fornecedor ser avaliado e cobrado pelas falhas; a remuneração de cada parceiro ser apurada pelo contrato e paga; e os contratos de fornecedor serem encerrados ou transferidos na saída. Quem precisa pede, inclusive a Integração nas compras da implantação e de tecnologia; a Gestão compra e paga; a Governança revisa e guarda o contrato.',
    frequencia='Por evento: pedido de compra, fatura de fornecedor, falha ou desempenho de fornecedor apontado',
    automacao=('média', 'Conferir orçamento e alçada, cotar, emitir o pedido, registrar o recebimento, conferir a fatura e pagar são de agente e automação; escolher o fornecedor, resolver divergências e cobrar a falha são de pessoa da Gestão; aprovar o pagamento é do líder do círculo.'),
    base=['apqc'],
    lanes=['SOL', 'EST', 'GOV', 'SOC', 'EXE', 'LCI', P, A, R],
    inicios=[I('Pedido de compra recebido', 'SOL', 'message'),
             I('Fatura de fornecedor recebida', R, 'message'),
             I('Falha ou desempenho de fornecedor apontado', R, 'message'),
             I('Período de remuneração de parceiros iniciado', R, 'timer'),
             I('Saída com contratos de fornecedor recebida', 'EST', 'message')],
    fins=[F('Compra paga e fornecedor avaliado', R),
          F('Fornecedor avaliado, sem pagamento a fazer', R)],
    etapas=[
        E('Receber e conferir o pedido de compra', 'Gestão; acima da alçada, o executivo; acima da reserva de contingência, os sócios', 'Autopiloto', 'baixo',
          [(PED_COMPRA_OP, 'Operações'), (PED_COMPRA, 'Solicitante'), (PED_COMPRA, 'GE-12'), (PLANO_CAP, 'Operações'),
           (ORC_VIG, 'GE-01'), (ALCADAS, 'Governança'), (COBRANCA_FORN, 'Operações'), (DESEMP_FORN, 'Operações'),
           (CONTRATO, 'Negócios'), (ACORDO_CONJ, 'Negócios'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia')],
          [D('O que iniciou o trabalho?', R,
             [S('Pedido de compra', 'seg'),
              S('Fatura de fornecedor', 'E5'),
              S('Falha ou desempenho de fornecedor', 'E4'),
              S('Remuneração de parceiros do período', 'E5',
                via=[T('Apurar a remuneração de cada parceiro pelo contrato e pela divisão acordada', A)]),
              S('Saída de oferta ou de empresa', 'E4',
                via=[T('Encerrar ou transferir os contratos de fornecedor da saída', P)])]),
           T('Registrar o pedido e conferir o orçamento e a alçada', R),
           D('O pedido tem orçamento e cabe na alçada de quem pediu?', A,
             [S('Sim', 'prox'),
              S('Não, fora do orçamento ou acima da alçada', 'prox', via=[T('Aprovar o pedido fora do orçamento ou acima da alçada', 'EXE')]),
              S('Não, acima da reserva de contingência', 'prox', via=[T('Aprovar o pedido acima da reserva de contingência', 'SOC')])])],
          [('Pedido de compra aprovado', ['etapa 2']),
           ('Falha ou desempenho de fornecedor registrado', ['etapa 4'])]),
        E('Escolher o fornecedor e emitir o pedido', 'Gestão; o contrato, com a Governança', 'Copiloto', 'médio',
          [('Pedido de compra aprovado', 'etapa 1'), ('Fornecedores avaliados', 'etapa 4')],
          [T('Cotar com fornecedores cadastrados e comparar preço, prazo, qualidade e risco', A),
           T('Escolher o fornecedor', P),
           D('A compra pede contrato?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Revisar o contrato com o fornecedor e guardá-lo', 'GOV')])]),
           T('Emitir o pedido ao fornecedor e informar a data de entrega a quem pediu', R)],
          [('Pedido emitido ao fornecedor', ['etapa 3', 'etapa 5']),
           (COMPRADOS, ['Operações']),
           ('Contrato de fornecedor para revisar e guardar', ['Governança'])]),
        E('Receber o que foi comprado', 'Gestão, com quem pediu', 'Copiloto', 'baixo',
          [('Pedido emitido ao fornecedor', 'etapa 2')],
          [T('Receber e conferir o que foi entregue', 'SOL'),
           T('Registrar o recebimento e a pontualidade do fornecedor', R)],
          [('Compra recebida', ['etapa 4', 'etapa 5'])]),
        E('Avaliar o fornecedor e cobrar as falhas', 'Gestão', 'Copiloto', 'médio',
          [('Compra recebida', 'etapa 3'), ('Falha ou desempenho de fornecedor registrado', 'etapa 1')],
          [T('Consolidar o desempenho do fornecedor em prazo, qualidade e custo', A),
           D('Há falha a cobrar do fornecedor?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Cobrar do fornecedor a falha, conforme o contrato', P)])]),
           T('Decidir manter, desenvolver ou trocar o fornecedor', P)],
          [('Fornecedores avaliados', ['etapa 2', 'etapa 5'])]),
        E('Conferir a fatura e pagar', 'Gestão', 'Copiloto', 'médio',
          [('Fornecedores avaliados', 'etapa 4'), ('Pedido emitido ao fornecedor', 'etapa 2'), ('Compra recebida', 'etapa 3')],
          [D('Há fatura ou remuneração a pagar?', R,
             [S('Sim', 'seg'),
              S('Não', 'F2')]),
           T('Conferir a fatura com o pedido e o recebimento, ou a remuneração com o contrato', A),
           D('Os valores batem?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Resolver a divergência com o fornecedor ou o parceiro', P)])]),
           T('Aprovar o pagamento na alçada', 'LCI'),
           T('Programar e fazer o pagamento e registrá-lo', R)],
          [(PAGOS, ['GE-05'])]),
    ]))

JORNADAS.append(dict(
    code='GE-05',
    nome='Gerir o caixa, fechar as contas e os impostos e prestar contas',
    dominio='Finanças', classe='essencial', onda=1,
    objetivo='Fazer cada recebimento e pagamento ser registrado e conciliado; o caixa ser projetado com a previsão de receita, os compromissos e o orçamento e informado à Estratégia; cada período ser fechado por empresa e consolidado, com os impostos apurados e as obrigações entregues, o resultado, os custos e margens e a execução do orçamento publicados; e cada aporte, distribuição ou mudança de contas decidido pelos sócios ou pelo mandato ser executado com dupla aprovação: a Gestão prepara e confere; o líder do círculo, o executivo ou o Administrador do IMTS.OS aprovam; as contas e os poderes bancários são conferidos pela Governança. Os sócios decidem; a Governança recebe as demonstrações para prestar contas.',
    frequencia='A cada período de fechamento (cadência: fechamento mensal; balanço anual) e por evento: decisão de alocação ou de destino do resultado, mandato ou mudança no portfólio',
    automacao=('média', 'Registrar, conciliar, projetar, fechar e apurar são de agente e automação; conferir o fechamento e os impostos e conferir a execução de aportes e distribuições são de pessoa da Gestão; aprovar o fechamento, os impostos e a execução é do líder do círculo ou, acima da alçada, do executivo; as contas do IMTS.OS, do Administrador; a conferência das contas, da Governança.'),
    base=['apqc', 'cc2002'],
    lanes=['EST', 'GOV', 'ADM', 'EXE', 'LCI', P, A, R],
    inicios=[I('Fechamento do período iniciado', R, 'timer'),
             I('Decisão de alocação, de destino do resultado ou mandato recebido', 'EST', 'message')],
    fins=[F('Aportes, distribuição ou mudanças de contas executados e registrados', R),
          F('Período fechado e informado, sem execução pendente', R)],
    etapas=[
        E('Registrar e conciliar o movimento e projetar o caixa', 'Gestão', 'Autopiloto', 'baixo',
          [(RECEITAS, 'GE-03'), (PAGOS, 'GE-04'), (FOLHA, 'GE-13'), (PREVISAO, 'Negócios'), (ORC_VIG, 'GE-01')],
          [D('O que iniciou o trabalho?', R,
             [S('Fechamento do período', 'seg'),
              S('Decisão de alocação, de destino do resultado ou mandato', 'E3')]),
           T('Registrar e conciliar contas, recebimentos e pagamentos', R),
           T('Projetar o caixa com a previsão de receita, os compromissos e o orçamento', A)],
          [(CAIXA, ['Estratégia']),
           ('Movimento do período conciliado', ['etapa 2'])]),
        E('Fechar as contas, apurar o resultado e os impostos', 'Gestão', 'Copiloto', 'médio',
          [('Movimento do período conciliado', 'etapa 1'), (RATEIO, 'GE-06'), (ATIVOS, 'GE-12')],
          [T('Fechar a contabilidade do período por empresa e consolidar', A),
           T('Apurar os impostos do período e preparar as obrigações fiscais', A),
           T('Conferir o fechamento e os impostos', P),
           T('Aprovar o fechamento e o recolhimento dos impostos', 'LCI'),
           T('Recolher os impostos e entregar as obrigações', R),
           T('Apurar o resultado, os custos e margens e a execução do orçamento', A),
           D('Há aporte, distribuição ou mudança de contas a executar?', R,
             [S('Não', 'F2'),
              S('Sim', 'prox')])],
          [(RESULTADO, ['Estratégia', 'Inteligência']),
           (MARGENS, ['Inteligência']),
           (EXEC_ORC, ['Estratégia', 'GE-02']),
           ('Demonstrações e obrigações fiscais do período', ['Governança']),
           ('Período fechado', ['etapa 3'])]),
        E('Executar aportes, distribuição e mudanças de contas', 'Gestão prepara; o líder do círculo, o executivo ou o Administrador do IMTS.OS aprovam; a Governança confere as contas', 'Copiloto', 'alto',
          [('Período fechado', 'etapa 2'), (DEC_ALOC, 'Estratégia'), (ALOCACAO, 'Estratégia'), (MANDATO, 'Estratégia'),
           (PORTFOLIO, 'Estratégia'), (ALCADAS, 'Governança')],
          [T('Preparar a execução do aporte, da distribuição ou da mudança de contas da empresa', A),
           T('Conferir a execução com a decisão e a alçada', P),
           D('O que será executado?', P,
             [S('Aporte ou distribuição dentro da alçada da Gestão', 'seg',
                via=[T('Aprovar a execução do aporte ou da distribuição', 'LCI')]),
              S('Aporte ou distribuição acima da alçada da Gestão', 'seg',
                via=[T('Autorizar a execução acima da alçada da Gestão', 'EXE')]),
              S('Abertura, encerramento ou mudança de poderes de contas da empresa', 'seg',
                via=[T('Autorizar a mudança de contas da empresa', 'EXE'),
                     T('Conferir os poderes e a mudança de contas', 'GOV')]),
              S('Contas do IMTS.OS ou dos círculos compartilhados', 'seg',
                via=[T('Autorizar a mudança de contas do IMTS.OS', 'ADM'),
                     T('Conferir os poderes e a mudança de contas do IMTS.OS', 'GOV')])]),
           T('Executar e registrar a movimentação', R)],
          [('Aportes, distribuição ou mudanças de contas executados', ['Executivos', 'Governança'])]),
    ]))

JORNADAS.append(dict(
    code='GE-06',
    nome='Aplicar o rateio do custo dos círculos entre as empresas',
    dominio='Finanças', classe='essencial', onda=1,
    objetivo='Fazer o custo dos círculos do Ecossistema central ser repartido entre as empresas pelo critério definido pela Governança com a Estratégia: custo e uso apurados, critério aplicado, rateio conferido, aberto à opinião de cada executivo, publicado e lançado nas contas; e cada contestação do critério ir à Governança. A Governança define o critério; a Gestão aplica.',
    frequencia='A cada período de fechamento (cadência: mensal, com o fechamento)',
    automacao=('média', 'Reunir o custo e o uso, aplicar o critério, publicar e lançar são de agente e automação; conferir e tratar a contestação são de pessoa da Gestão; o executivo opina.'),
    base=['apqc'],
    lanes=['EXE', P, A, R],
    inicios=[I('Período de rateio iniciado', R, 'timer')],
    fins=[F('Rateio publicado e lançado', R)],
    etapas=[
        E('Apurar o custo dos círculos e o uso de cada empresa', 'Gestão', 'Autopiloto', 'baixo',
          [(CRITERIO_RATEIO, 'Governança'), (CUSTO_TEC, 'Integração'), (PORTFOLIO, 'Estratégia')],
          [T('Reunir o custo de cada círculo e o uso dos serviços por empresa', R),
           T('Aplicar o critério de rateio e calcular a parte de cada empresa', A)],
          [('Rateio calculado', ['etapa 2'])]),
        E('Conferir e publicar o rateio', 'Gestão; o executivo opina', 'Assistido', 'médio',
          [('Rateio calculado', 'etapa 1')],
          [T('Conferir o rateio com o critério', P),
           T('Opinar sobre o rateio da sua empresa', 'EXE'),
           D('Há contestação do rateio?', P,
             [S('Não', 'seg'),
              S('Do cálculo', 'seg', via=[T('Rever o cálculo e responder ao executivo', P)]),
              S('Do critério', 'seg', via=[T('Levar a contestação do critério à Governança', R)])]),
           T('Publicar e lançar o rateio nas contas de cada empresa', R)],
          [(RATEIO, ['GE-01', 'GE-05', 'Executivos']),
           ('Contestação do critério de rateio', ['Governança'])]),
    ]))
