
# ========================================================== PESSOAS E CULTURA
JORNADAS.append(dict(
    code='GE-07',
    nome='Prover pessoas: vaga, seleção, contratação, movimentação e desligamento',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Fazer cada vaga, movimentação ou desligamento pedido pelo líder, pelo plano de capacidade ou pelo mandato ser conferido contra o orçamento, o perfil do kit de cultura e a alçada; cada vaga ser preenchida por seleção pelos comportamentos esperados, com a contratação decidida pelo líder; cada pessoa ser contratada, movimentada ou desligada com o registro, a folha e os acessos atualizados; e cada pessoa nova ir à integração. O líder decide quem entra na sua equipe; a Gestão conduz e confere; o executivo decide o que passa da alçada na empresa, e o Administrador do IMTS.OS, nos círculos; os sócios decidem o desligamento de executivo ou de líder de círculo.',
    frequencia='Por evento: pedido do líder, plano de capacidade, mandato, saída, recurso liberado',
    automacao=('média', 'Registrar, conferir orçamento e perfil, divulgar, triar e atualizar registros e acessos são de agente e automação; aprovar a abertura, conferir a decisão e fazer a proposta são de pessoa da Gestão; a escolha é do líder; o desligamento, com o executivo.'),
    base=['apqc', 'lgpd', 'clt'],
    lanes=['LID', 'PES', 'SOC', 'ADM', 'EXE', P, A, R],
    inicios=[I('Vaga, movimentação ou desligamento pedido pelo líder', 'LID', 'message'),
             I('Plano de capacidade, mandato ou recurso liberado recebido', R, 'message')],
    fins=[F('Pessoa contratada, movimentada ou desligada e registrada', R)],
    etapas=[
        E('Abrir a vaga ou decidir a movimentação', 'Gestão, com o líder; acima da alçada, o executivo', 'Copiloto', 'alto',
          [('Pedido de vaga, de movimentação ou de desligamento', 'Líderes'), (PLANO_CAP, 'Operações'),
           (REC_LIB_OP, 'Operações'), (REC_LIB_IT, 'Integração'), (LISTA_ADQ, 'Estratégia'), (MANDATO, 'Estratégia'),
           (DATA_SAIDA, 'Estratégia'), (KIT, 'Identidade'), (ORC_VIG, 'GE-01'), (ALCADAS, 'Governança')],
          [T('Registrar o pedido e conferir o orçamento, o perfil e a alçada', A),
           T('Aprovar o pedido conforme o orçamento e a alçada', P),
           D('O pedido passa da alçada da Gestão?', P,
             [S('Não', 'seg'),
              S('Sim, pessoa de uma empresa', 'seg', via=[T('Decidir o pedido acima da alçada da Gestão', 'EXE')]),
              S('Sim, pessoa dos círculos do IMTS.OS', 'seg',
                via=[T('Decidir o pedido de pessoa dos círculos acima da alçada da Gestão', 'ADM')])]),
           D('O que é pedido?', P,
             [S('Vaga nova ou reposição', 'prox'),
              S('Incorporação de pessoas da empresa adquirida', 'E4',
                via=[T('Cadastrar as pessoas da empresa adquirida conforme o mandato', R)]),
              S('Promoção, mudança de papel ou realocação', 'E4',
                via=[T('Decidir a movimentação com o líder', P)]),
              S('Desligamento', 'E4',
                via=[T('Decidir o desligamento com o líder', 'EXE'),
                     T('Fazer o desligamento, o acerto rescisório e a devolução do que é da empresa', P)]),
              S('Desligamento de executivo ou de líder de círculo', 'E4',
                via=[T('Decidir o desligamento do executivo ou do líder de círculo', 'SOC'),
                     T('Fazer o desligamento decidido pelos sócios, com o acerto rescisório', P)])])],
          [('Vaga aberta, com perfil e orçamento', ['etapa 2']),
           ('Movimentação ou desligamento feito', ['etapa 4'])]),
        E('Atrair e selecionar', 'Gestão conduz; o líder escolhe', 'Assistido', 'médio',
          [('Vaga aberta, com perfil e orçamento', 'etapa 1'), (SIGILO, 'Governança')],
          [T('Divulgar a vaga e buscar candidatos', A),
           T('Triar os candidatos pelo perfil e pelos comportamentos do kit de cultura', A),
           T('Revisar a triagem do agente antes de recusar candidatos', P),
           T('Entrevistar e avaliar os finalistas', 'LID'),
           T('Decidir a contratação', 'LID'),
           D('A escolha confere com o perfil, a política e a alçada?', P,
             [S('Sim', 'prox'),
              S('Não', 'E2', via=[T('Devolver a escolha ao líder com o motivo', P)])])],
          [('Pessoa escolhida', ['etapa 3'])]),
        E('Contratar a pessoa', 'Gestão', 'Copiloto', 'médio',
          [('Pessoa escolhida', 'etapa 2')],
          [T('Fazer a proposta e combinar as condições', P),
           D('A pessoa aceitou a proposta?', 'PES',
             [S('Sim', 'seg'),
              S('Não', 'E2', via=[T('Registrar a recusa e voltar aos finalistas', R)])]),
           T('Formalizar o contrato e cadastrar a pessoa na folha', R)],
          [(CONTRATADA, ['GE-08', 'GE-13', 'Líderes']),
           ('Contratação formalizada', ['etapa 4'])]),
        E('Registrar a mudança e avisar quem precisa', 'Gestão', 'Autômato', 'baixo',
          [('Contratação formalizada', 'etapa 3'), ('Movimentação ou desligamento feito', 'etapa 1')],
          [T('Atualizar o cadastro, a folha e a estrutura', R),
           T('Pedir à Integração os acessos novos ou a retirada de acessos', R)],
          [(PED_TEC, ['Integração']),
           (MUD_PESSOAS, ['GE-08', 'GE-13', 'Líderes'])]),
    ]))

JORNADAS.append(dict(
    code='GE-08',
    nome='Integrar pessoas novas à cultura',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Fazer cada pessoa nova, ou que mudou de papel, e cada pessoa de empresa adquirida entender o propósito, os valores e os comportamentos esperados, e sentir-se parte, antes de responder sozinha pelo seu papel: trilha montada pelo papel, conduzida com o líder, vínculos iniciais e verificação de entendimento e de pertencimento, com reforço combinado quando falta. A Identidade define o kit; a Gestão integra; o líder acompanha.',
    frequencia='Por pessoa: contratação, mudança de papel ou incorporação de empresa adquirida',
    automacao=('média', 'Abrir, montar a trilha, conduzir as dúvidas, verificar e registrar são de agente e automação; combinar o reforço é de pessoa da Gestão; conversar e confirmar os comportamentos é do líder.'),
    base=['apqc'],
    lanes=['LID', 'PES', P, A, R],
    inicios=[I('Pessoa contratada ou com papel novo', R, 'message'),
             I('Pessoas de empresa adquirida recebidas', R, 'message')],
    fins=[F('Integração cultural concluída e registrada', R)],
    etapas=[
        E('Preparar a trilha de integração', 'Gestão', 'Autopiloto', 'baixo',
          [(CONTRATADA, 'GE-07'), (MUD_PESSOAS, 'GE-07'), (LISTA_ADQ, 'Estratégia'), (KIT, 'Identidade'),
           (PADROES_ID, 'Identidade')],
          [T('Abrir a integração e agendar os marcos', R),
           T('Montar a trilha conforme o papel', A)],
          [('Trilha de integração', ['etapa 2', 'Pessoas', 'Líderes'])]),
        E('Apresentar propósito, valores e comportamentos', 'Gestão, com o líder', 'Assistido', 'baixo',
          [('Trilha de integração', 'etapa 1')],
          [T('Conduzir a trilha e tirar dúvidas', A),
           T('Conversar sobre como os valores aparecem no dia a dia da função', 'LID'),
           T('Concluir a trilha', 'PES')],
          [('Trilha concluída', ['etapa 3'])]),
        E('Conectar a pessoa à comunidade', 'Líder', 'Assistido', 'baixo',
          [('Trilha concluída', 'etapa 2')],
          [T('Indicar um padrinho ou uma madrinha', 'LID'),
           T('Participar do primeiro ritual', 'PES')],
          [('Vínculos iniciais registrados', ['etapa 4'])]),
        E('Verificar a integração e registrar', 'Gestão, com o líder', 'Copiloto', 'médio',
          [('Vínculos iniciais registrados', 'etapa 3')],
          [T('Aplicar a verificação de entendimento e de pertencimento', A),
           T('Confirmar os comportamentos observados', 'LID'),
           D('A pessoa se integrou?', 'LID',
             [S('Sim', 'seg'),
              S('Não, com reforço possível', 'E2', via=[T('Combinar o reforço com o líder', P)]),
              S('Não, sem condição de seguir no papel', 'seg',
                via=[T('Levar ao líder e ao executivo a decisão sobre a permanência', R)])]),
           T('Registrar a conclusão, avisar o líder e enviar os dados agregados à pesquisa', R)],
          [(INTEGRADA, ['Líderes', 'GE-09'])]),
    ]))

JORNADAS.append(dict(
    code='GE-09',
    nome='Avaliar e desenvolver as pessoas e medir a cultura',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Fazer cada pessoa ser avaliada pelos alvos e pelos comportamentos do kit de cultura, com as avaliações calibradas, as mudanças de remuneração propostas na política pela Gestão e aprovadas pelo executivo ou, nos círculos do IMTS.OS, pelo Administrador, e um plano de desenvolvimento combinado com o líder; quem quiser, ligar o seu propósito ao seu papel, com participação voluntária, a declaração guardada pela pessoa e o ajuste de papel só com o acordo dela; e a cultura e o engajamento serem medidos sem identificar quem respondeu e entregues à Identidade e à Inteligência. O líder avalia; a Gestão calibra, desenvolve e mede.',
    frequencia='A cada ciclo de avaliação e desenvolvimento e a cada pesquisa de cultura (cadências: avaliação semestral; pesquisa de cultura anual)',
    automacao=('média', 'Preparar a avaliação, guiar a reflexão, acompanhar o treino e aplicar e analisar a pesquisa são de agente e automação; calibrar, propor a remuneração, aprovar treinos e apresentar o resultado são de pessoa da Gestão; avaliar é do líder; aprovar a remuneração é do executivo ou do Administrador do IMTS.OS.'),
    base=['apqc', 'lgpd'],
    lanes=['LID', 'PES', 'EXE', 'ADM', P, A, R],
    inicios=[I('Ciclo de avaliação e desenvolvimento iniciado', R, 'timer'),
             I('Pesquisa de cultura e engajamento iniciada', R, 'timer')],
    fins=[F('Pesquisa de cultura aplicada e resultado entregue', R),
          F('Ciclo de avaliação e desenvolvimento concluído', R)],
    etapas=[
        E('Avaliar o desempenho e decidir a remuneração na política', 'Gestão calibra; o líder avalia', 'Assistido', 'médio',
          [(KIT, 'Identidade'), (LACUNAS_EXEC, 'Identidade'), (RESUMO_PAD, 'Identidade'), (ALVOS, 'Estratégia'),
           (INTEGRADA, 'GE-08')],
          [D('Qual ciclo iniciou?', R,
             [S('Avaliação e desenvolvimento', 'seg'),
              S('Pesquisa de cultura e engajamento', 'E3')]),
           T('Preparar a avaliação pelos alvos e pelos comportamentos do kit', A),
           T('Avaliar a pessoa e combinar o plano de desenvolvimento', 'LID'),
           T('Fazer a autoavaliação e combinar o plano', 'PES'),
           T('Calibrar as avaliações e propor as mudanças de remuneração na política', P),
           D('De quem é a mudança de remuneração?', R,
             [S('Pessoas de uma empresa', 'seg', via=[T('Aprovar as mudanças de remuneração da empresa', 'EXE')]),
              S('Pessoas dos círculos do IMTS.OS, inclusive da Gestão', 'seg',
                via=[T('Aprovar as mudanças de remuneração dos círculos', 'ADM')])]),
           T('Lançar as mudanças de remuneração aprovadas na próxima folha', R)],
          [('Avaliações e planos de desenvolvimento', ['etapa 2']),
           (MUD_REMUN, ['GE-13'])]),
        E('Ligar o propósito ao papel e desenvolver as pessoas', 'Gestão, com a pessoa e o líder', 'Copiloto', 'baixo',
          [('Avaliações e planos de desenvolvimento', 'etapa 1')],
          [T('Convidar a pessoa a ligar o seu propósito ao papel, com participação voluntária', R),
           D('A pessoa aceitou o convite?', 'PES',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Guiar a reflexão sobre histórias, valores e forças', A),
                                   T('Escrever a declaração de propósito e escolher o que compartilha', 'PES'),
                                   T('Conversar com o líder sobre propósito e papel e fechar o plano', 'PES'),
                                   T('Avaliar o ajuste de papel, com o acordo da pessoa', P)])]),
           T('Oferecer e acompanhar o treino e o desenvolvimento do plano', A),
           T('Aprovar os treinos que pedem orçamento', P),
           D('O desenvolvimento do ciclo foi registrado?', R,
             [S('Sim', 'F2'),
              S('Não', 'F2', via=[T('Registrar o plano e os treinos do ciclo', R)])])],
          [('Plano de desenvolvimento ligado ao propósito', ['Líderes'])]),
        E('Medir a cultura e o engajamento', 'Gestão', 'Copiloto', 'baixo',
          [(PARTICIP, 'GE-10'), (INTEGRADA, 'GE-08'), (SIGILO, 'Governança')],
          [T('Aplicar a pesquisa de cultura e de engajamento', R),
           T('Analisar os resultados com os dados de pessoas, sem identificar quem respondeu', A),
           T('Conferir e apresentar o resultado aos líderes', P)],
          [(PESQUISA, ['Identidade', 'Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='GE-13',
    nome='Calcular e pagar a folha e os encargos',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Fazer cada folha ter o ponto, as variáveis, as comissões de quem vende sobre a receita recebida, os reconhecimentos e as mudanças de remuneração do período apurados a partir dos registros de pessoas, conferida pela Gestão, aprovada pelo executivo ou, nos círculos do IMTS.OS, pelo Administrador, paga no prazo e com os encargos recolhidos. A Gestão apura, confere e paga; quem aprova é outra pessoa.',
    frequencia='A cada período de folha (cadência: mensal; salário até o quinto dia útil do mês seguinte; FGTS até o dia 20)',
    automacao=('média', 'Apurar, pagar e recolher são de agente e automação; conferir a folha é de pessoa da Gestão; aprovar é do executivo ou do Administrador do IMTS.OS.'),
    base=['apqc', 'clt', 'fgts'],
    lanes=['EXE', 'ADM', P, A, R],
    inicios=[I('Período da folha iniciado', R, 'timer')],
    fins=[F('Folha paga e encargos recolhidos', R)],
    etapas=[
        E('Apurar a folha do período', 'Gestão', 'Autopiloto', 'baixo',
          [(CONTRATADA, 'GE-07'), (MUD_PESSOAS, 'GE-07'), (MUD_REMUN, 'GE-09'), (RECONHEC, 'GE-10'),
           (CONTRATO, 'Negócios'), (RECEITAS, 'GE-03'), (SIGILO, 'Governança')],
          [T('Reunir o ponto, as mudanças de pessoas, as receitas recebidas e os reconhecimentos', R),
           T('Apurar salários, variáveis, comissões sobre a receita recebida e reconhecimentos', A)],
          [('Folha apurada', ['etapa 2'])]),
        E('Aprovar e pagar a folha', 'Gestão', 'Copiloto', 'médio',
          [('Folha apurada', 'etapa 1')],
          [T('Conferir a folha', P),
           D('De quem é a folha?', R,
             [S('De uma empresa', 'seg', via=[T('Aprovar a folha da empresa', 'EXE')]),
              S('Dos círculos do IMTS.OS', 'seg', via=[T('Aprovar a folha dos círculos', 'ADM')])]),
           T('Pagar a folha e recolher os encargos', R)],
          [(FOLHA, ['GE-05'])]),
    ]))

JORNADAS.append(dict(
    code='GE-10',
    nome='Realizar os rituais de cultura e o reconhecimento de pessoas e equipes',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Reforçar, com cadência fixa, os comportamentos que os valores pedem: cada ritual preparado pelo padrão do kit de cultura, cada indicação de reconhecimento conferida com os critérios e decidida com os líderes, o ritual conduzido pelo líder, as histórias registradas e comunicadas e os reconhecimentos levados à folha. A Identidade define o padrão; a Gestão prepara, decide com os líderes e registra; o líder conduz.',
    frequencia='No calendário de rituais (cadência: trimestral)',
    automacao=('média', 'Colher indicações, montar o roteiro, conferir com os critérios, selecionar histórias e registrar são de agente e automação; decidir os reconhecimentos é de pessoa da Gestão, com os líderes; conduzir o ritual é do líder.'),
    base=['apqc'],
    lanes=['LID', P, A, R],
    inicios=[I('Ritual do calendário iniciado', R, 'timer')],
    fins=[F('Ritual realizado e registrado', R)],
    etapas=[
        E('Preparar o ritual', 'Gestão', 'Autopiloto', 'baixo',
          [(PADROES_ID, 'Identidade'), (KIT, 'Identidade'), ('Indicações de reconhecimento', 'Líderes'), (ALVOS, 'Estratégia')],
          [T('Abrir a preparação e colher as indicações', R),
           T('Montar o roteiro e o material do ritual', A)],
          [('Roteiro do ritual e lista de indicações', ['etapa 2'])]),
        E('Avaliar as indicações de reconhecimento', 'Gestão, com os líderes', 'Assistido', 'médio',
          [('Roteiro do ritual e lista de indicações', 'etapa 1')],
          [T('Conferir cada indicação com os critérios do kit', A),
           T('Decidir os reconhecimentos com os líderes', P),
           T('Aprovar a recompensa dentro do orçamento', P)],
          [('Reconhecimentos aprovados', ['etapa 3']),
           ('Retorno sobre as indicações', ['Líderes'])]),
        E('Realizar o ritual', 'Líder', 'Assistido', 'baixo',
          [('Reconhecimentos aprovados', 'etapa 2')],
          [T('Conduzir o ritual', 'LID'),
           T('Apoiar a condução e registrar as histórias', P)],
          [('Histórias registradas', ['etapa 4'])]),
        E('Comunicar e registrar', 'Gestão', 'Autopiloto', 'baixo',
          [('Histórias registradas', 'etapa 3')],
          [T('Selecionar as histórias e os reconhecimentos a comunicar', A),
           T('Registrar a participação e os reconhecimentos', R)],
          [(HISTORIAS, ['GE-11']),
           (PARTICIP, ['GE-09']),
           (RECONHEC, ['GE-13'])]),
    ]))

JORNADAS.append(dict(
    code='GE-11',
    nome='Planejar e publicar a comunicação interna',
    dominio='Pessoas e cultura', classe='essencial', onda=1,
    objetivo='Manter as pessoas informadas e alinhadas, com uma só voz: cada mudança na identidade, nos padrões e na estratégia, cada alvo, correção, mudança no portfólio e conteúdo externo relevante entrar na pauta; cada conteúdo ser redigido na voz e na marca vigentes, conferido, validado pela Governança quando sensível e aprovado; os materiais vencidos saírem dos canais; e o alcance e o entendimento serem medidos. A Identidade define a voz e as mensagens; a Gestão comunica para dentro; Relações, para fora.',
    frequencia='No calendário da comunicação interna (cadência: mensal) e por evento: fato ou mudança a comunicar',
    automacao=('alta', 'Propor a pauta, redigir, conferir, publicar, retirar materiais vencidos e medir são de agente e automação; decidir a pauta e aprovar o conteúdo são de pessoa da Gestão.'),
    base=['apqc'],
    lanes=['GOV', 'PES', P, A, R],
    inicios=[I('Ciclo da comunicação interna iniciado', R, 'timer'),
             I('Fato ou mudança a comunicar recebido', R, 'message')],
    fins=[F('Comunicação interna publicada e medida', R)],
    etapas=[
        E('Planejar a pauta', 'Gestão', 'Copiloto', 'baixo',
          [(MUD_DECL, 'Identidade'), (MUD_PADROES, 'Identidade'), (POSIC, 'Identidade'), (PADROES_ID, 'Identidade'),
           (MUD_EST, 'Estratégia'), (ALVOS, 'Estratégia'), (CORRECOES, 'Estratégia'), (PORTFOLIO, 'Estratégia'),
           (CONT_EXT, 'Relações'), (HISTORIAS, 'GE-10'), ('Medição da comunicação interna', 'etapa 4')],
          [T('Propor a pauta e o calendário a partir dos fatos', A),
           T('Decidir pauta, público, canal e o que é sensível', P)],
          [('Pauta e calendário aprovados', ['etapa 2'])]),
        E('Produzir o conteúdo', 'Gestão; o conteúdo sensível, com a Governança', 'Copiloto', 'baixo',
          [('Pauta e calendário aprovados', 'etapa 1'), (PACOTE_MARCA, 'Identidade'), (MARCA_RET, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Redigir o conteúdo na voz do Ecossistema', A),
           T('Conferir o conteúdo com o guia de voz, as mensagens e a marca vigente', A),
           D('O conteúdo está conforme os padrões?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o conteúdo reprovado', P)])]),
           D('Há caso não coberto pelos padrões?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Consultar a Identidade sobre o caso não coberto', R),
                                   T('Receber a resposta da Identidade e ajustar o conteúdo', R, 'receive')])]),
           D('O conteúdo é sensível?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Validar o conteúdo sensível', 'GOV')])]),
           T('Aprovar o conteúdo', P)],
          [('Conteúdo aprovado', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Publicar nos canais internos', 'Gestão', 'Autômato', 'baixo',
          [('Conteúdo aprovado', 'etapa 2'), (VENCIDOS, 'Identidade')],
          [T('Publicar nos canais internos', R),
           T('Retirar dos canais internos os materiais vencidos ou de marca retirada', R)],
          [('Comunicação interna publicada', ['Pessoas', 'etapa 4'])]),
        E('Medir e registrar', 'Gestão', 'Autopiloto', 'baixo',
          [('Comunicação interna publicada', 'etapa 3')],
          [T('Medir alcance e entendimento', A),
           T('Registrar a medição para o próximo ciclo', R)],
          [('Medição da comunicação interna', ['etapa 1'])]),
    ]))
