
# ========================================================== ATIVOS E ADMINISTRAÇÃO
JORNADAS.append(dict(
    code='GE-12',
    nome='Gerir os ativos, os espaços e os serviços administrativos',
    dominio='Ativos e administração', classe='essencial', onda=1,
    objetivo='Fazer cada pedido de ativo, de espaço ou de serviço administrativo ser atendido pela melhor opção (comprar, alugar, remanejar ativo ocioso ou recusar), decidida pela Gestão dentro do orçamento; cada ativo ser registrado com o responsável e a depreciação, mantido e inventariado; e cada ativo ocioso, perdido ou no fim da vida ser baixado (vendido, doado, reciclado ou descartado), com os dados guardados nele eliminados. A Gestão decide e controla; a compra segue a jornada de compras.',
    frequencia='Por evento: pedido de ativo, espaço ou serviço; e a cada ciclo de manutenção e inventário (cadência: inventário anual; manutenção pelo plano de cada ativo)',
    automacao=('alta', 'Avaliar o pedido, pedir a compra, registrar, programar a manutenção, inventariar e executar a baixa são de agente e automação; decidir o atendimento e o destino do ativo são de pessoa da Gestão.'),
    base=['apqc'],
    lanes=['SOL', P, A, R],
    inicios=[I('Pedido de ativo, de espaço ou de serviço administrativo recebido', 'SOL', 'message'),
             I('Ciclo de manutenção e inventário iniciado', R, 'timer')],
    fins=[F('Ativo atendido, registrado, mantido ou baixado', R),
          F('Pedido atendido ou recusado, sem ativo a registrar', R)],
    etapas=[
        E('Avaliar e atender o pedido', 'Gestão', 'Copiloto', 'médio',
          [('Pedido de ativo, de espaço ou de serviço administrativo', 'Solicitante'), (PLANO_CAP, 'Operações'),
           (REC_LIB_OP, 'Operações'), (ORC_VIG, 'GE-01'), (ALCADAS, 'Governança')],
          [D('O que iniciou o trabalho?', R,
             [S('Pedido de ativo, de espaço ou de serviço', 'seg'),
              S('Ciclo de manutenção e inventário', 'E2')]),
           T('Avaliar o pedido: comprar, alugar, remanejar ativo ocioso ou recusar', A),
           T('Decidir o atendimento do pedido', P),
           D('O atendimento pede compra ou contrato?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir a compra ou o contrato pela jornada de compras', R)])]),
           D('O atendimento cria ou muda um ativo?', R,
             [S('Não: serviço atendido ou pedido recusado', 'F2', via=[T('Responder a quem pediu', R)]),
              S('Sim', 'prox')])],
          [(PED_COMPRA, ['GE-04']),
           ('Ativo ou serviço a registrar', ['etapa 2'])]),
        E('Registrar e manter os ativos e fazer o inventário', 'Gestão', 'Autopiloto', 'baixo',
          [('Ativo ou serviço a registrar', 'etapa 1')],
          [T('Registrar o ativo, o responsável e a depreciação', R),
           T('Programar e acompanhar a manutenção', A),
           T('Conferir o inventário e apontar ativo ocioso, perdido ou a baixar', A)],
          [('Ativos apontados para baixa', ['etapa 3']),
           (ATIVOS, ['GE-05'])]),
        E('Baixar o ativo', 'Gestão', 'Copiloto', 'médio',
          [('Ativos apontados para baixa', 'etapa 2')],
          [D('Há ativo a baixar?', A,
             [S('Não', 'prox'),
              S('Sim', 'seg')]),
           T('Decidir vender, doar, reciclar ou descartar o ativo', P),
           T('Eliminar os dados guardados no ativo e executar a baixa', R)],
          [(ATIVOS, ['GE-05'])]),
    ]))
