
# ================================================================ DEMANDA
JORNADAS.append(dict(
    code='RE-01',
    nome='Planejar a geração de demanda do ciclo por público, oferta e canal',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Ter, a cada ciclo, um plano de demanda de cada empresa que diga a que públicos falar, com que ofertas, por quais canais e ações, com que alvo e com que orçamento, a partir da direção, dos alvos, das ofertas no catálogo e do resultado do ciclo anterior, e com o critério de oportunidade qualificada combinado com Negócios. Relações decide o plano, ouvidos Negócios e o executivo; a Gestão confere o orçamento.',
    frequencia='A cada ciclo de demanda (cadência: trimestral) e por evento: oferta aprovada para lançamento, revisão pedida pelo resultado das ações ou resposta da Gestão a pedido de recurso',
    automacao=('média', 'Reunir as entradas, comparar com os alvos, propor o plano e somar o custo são de agente e automação; decidir públicos, canais, ações e alvos e combinar o critério com Negócios são de pessoa de Relações.'),
    base=['barcelona', 'apqc'],
    lanes=['EST', 'GES', 'NEG', 'EXE', P, A, R],
    inicios=[I('Ciclo de demanda iniciado', R, 'timer'),
             I('Oferta aprovada para lançamento recebida', 'EST', 'message'),
             I('Resposta ao pedido de recurso recebida', 'GES', 'message'),
             I('Revisão do plano de demanda pedida', R, 'message')],
    fins=[F('Plano de demanda aprovado e publicado', R)],
    etapas=[
        E('Reunir o que orienta a demanda do ciclo', 'Relações', 'Autopiloto', 'baixo',
          [(DIRECAO, 'Estratégia'), (ALVOS, 'Estratégia'), (OFERTA_LANC, 'Estratégia'), (MANDATO, 'Estratégia'),
           (OFERTA_CAT, 'Inteligência'), (POS_OFERTA, 'Inteligência'), (POSIC, 'Identidade'), (LEITURA, 'Inteligência'),
           (PAINEL, 'Inteligência'), ('Plano de lançamento da oferta', 'Integração'), ('Resposta ao pedido de recurso adicional', 'Gestão'),
           (RES_DEM, 'RE-02'), ('Pedido de revisão do plano de demanda', 'RE-02'), (FUNIL, 'RE-03'), (CX, 'RE-04')],
          [T('Reunir direção, alvos, ofertas, lançamentos, leitura de mercado e resultado anterior', R),
           T('Comparar o resultado do ciclo anterior com os alvos e apontar o que funcionou', A)],
          [('Diagnóstico de demanda do ciclo', ['etapa 2'])]),
        E('Definir públicos, ofertas, canais, ações e alvos de demanda', 'Relações, ouvidos Negócios e o executivo', 'Assistido', 'médio',
          [('Diagnóstico de demanda do ciclo', 'etapa 1'), ('Ajustes pedidos ao plano de demanda', 'etapa 3')],
          [T('Propor públicos, ofertas prioritárias, canais, ações e calendário de cada empresa', A),
           PAR([T('Opinar sobre a capacidade de atender as oportunidades previstas', 'NEG')],
               [T('Opinar sobre os públicos e as ofertas prioritárias da empresa', 'EXE')]),
           T('Decidir públicos, canais, ações e alvos de demanda, ouvidos Negócios e o executivo', P),
           T('Definir para cada ação o alvo, a medida de resultado e a medida de alcance', P),
           T('Combinar com Negócios o critério de oportunidade qualificada do ciclo', P, 'manual'),
           D('Relações e Negócios chegaram a acordo sobre o critério?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Decidir o critério de oportunidade qualificada da empresa, sem acordo', 'EXE')])])],
          [('Proposta de plano de demanda', ['etapa 3'])]),
        E('Conferir o orçamento e aprovar o plano', 'Relações, com Gestão', 'Copiloto', 'médio',
          [('Proposta de plano de demanda', 'etapa 2'), ('Orçamento de demanda do ciclo', 'Gestão')],
          [T('Somar o custo das ações e comparar com o orçamento de demanda do ciclo', A),
           T('Conferir o custo das ações com o orçamento aprovado', 'GES'),
           D('O plano cabe no orçamento?', P,
             [S('Sim', 'seg'),
              S('Não, ajustar o plano', 'E2'),
              S('Não: seguir com o que cabe e pedir recurso', 'seg',
                via=[T('Pedir à Gestão recurso adicional, com o efeito esperado nos alvos', R)])]),
           T('Aprovar o plano de demanda do ciclo', P)],
          [('Plano de demanda aprovado', ['etapa 4']),
           ('Ajustes pedidos ao plano de demanda', ['etapa 2']),
           ('Pedido de recurso adicional para demanda', ['Gestão'])]),
        E('Publicar o plano e avisar quem executa', 'Relações', 'Autômato', 'baixo',
          [('Plano de demanda aprovado', 'etapa 3')],
          [T('Registrar a versão do plano, o critério combinado e o calendário de ações', R),
           T('Avisar Negócios, Integração, os executivos e quem executa as ações do plano', R)],
          [(PLANO_DEM, ['RE-02', 'RE-07', 'Negócios', 'Integração', 'Executivos', 'Gestão']),
           (CRITERIO, ['RE-03', 'Negócios'])]),
    ]))

JORNADAS.append(dict(
    code='RE-02',
    nome='Executar as ações de demanda e medir o resultado',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Levar cada ação do plano aos públicos certos, com material conforme os padrões de identidade e só para quem pode ser abordado, captar os contatos com a base legal e medir o resultado de cada ação contra o alvo, e não só pelo alcance; e recolher o material em circulação quando a marca sai de uso ou o material vence.',
    frequencia='Por ação do plano de demanda, no calendário, e por evento: ação fora do plano pedida, marca retirada de uso ou material vencido',
    automacao=('média (alta na execução, média na preparação)', 'Redigir, montar o público, publicar, registrar e medir são de agente e automação; aprovar a ação, o material e o público é de pessoa. Preço e condições passam por Negócios; o que fala em nome da empresa, pelo executivo.'),
    base=['apqc', 'barcelona'],
    lanes=['SOL', 'IDE', 'NEG', 'GES', 'GOV', 'EXE', 'ITG', P, A, R],
    inicios=[I('Ação do plano de demanda iniciada', R, 'timer'),
             I('Ação fora do plano pedida', 'SOL', 'message'),
             I('Marca retirada ou material vencido avisado', 'IDE', 'message')],
    fins=[F('Ação concluída e medida', R), F('Ação recusada, com o motivo', R),
          F('Material recolhido e substituído', R)],
    etapas=[
        E('Preparar a ação: mensagem, público, canal e material', 'Relações', 'Copiloto', 'médio',
          [(PLANO_DEM, 'RE-01'), ('Pedido de ação fora do plano', 'Solicitante'), (BASE_REL, 'RE-03'), (POSIC, 'Identidade'),
           (PACOTE_MARCA, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade'), (MAT_VENC, 'Identidade'),
           (MARCA_RET, 'Identidade'), (LACUNAS_EXEC, 'Identidade'), (POS_OFERTA, 'Inteligência'), (OFERTA_CAT, 'Inteligência'),
           ('Tabela de preços e política comercial vigentes', 'Negócios')],
          [D('O que abriu o trabalho?', R,
             [S('Ação do plano', 'seg'),
              S('Ação fora do plano', 'seg',
                via=[T('Conferir com a Gestão o custo da ação fora do plano', 'GES'),
                     T('Decidir se a ação fora do plano entra, com o recurso conferido', P)]),
              S('Marca retirada ou material vencido', 'F3',
                via=[T('Listar o material em circulação com a marca retirada ou vencido', A),
                     T('Retirar o material dos canais e trocar pelo vigente', R),
                     T('Conferir a troca e avisar quem usa o material', P)])]),
           D('A ação vai ser feita?', P,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Avisar quem pediu de que a ação não será feita, com o motivo', R)])]),
           T('Redigir mensagem e material, corrigindo as lacunas de execução já apontadas', A),
           T('Montar o público da ação na base, só com quem pode ser abordado', A),
           T('Conferir mensagem e material com os padrões de identidade', A),
           D('O material está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o material no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o material não coberto pelos padrões', 'IDE', 'call')])]),
           D('A ação traz preço ou condição comercial?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o preço e as condições com a tabela e a política comercial', 'NEG')])]),
           D('A ação traz promessa, dado pessoal ou comparação com concorrente?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir a promessa, a comparação e o uso de dados da ação', 'GOV')])]),
           D('A ação fala em nome da empresa ou de quem a dirige?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Aprovar o que a ação diz em nome da empresa', 'EXE')])]),
           T('Aprovar a ação, o material e o público', P)],
          [('Ação pronta para execução', ['etapa 2']),
           ('Resposta ao pedido de ação fora do plano', ['Solicitante']),
           (CONSULTA, ['Identidade'])]),
        E('Executar a ação nos canais e captar os contatos', 'Relações, com Integração', 'Autômato', 'médio',
          [('Ação pronta para execução', 'etapa 1')],
          [T('Preparar nos sistemas o registro das respostas e dos contatos da ação', 'ITG'),
           T('Publicar ou enviar a ação aprovada nos canais escolhidos, no calendário', R),
           T('Registrar as respostas e os contatos captados, com o consentimento dado', R)],
          [('Contatos captados pela ação, com o consentimento', ['RE-03']),
           ('Registros da ação executada', ['etapa 3'])]),
        E('Medir o resultado da ação e registrar o que aprender', 'Relações', 'Copiloto', 'baixo',
          [('Registros da ação executada', 'etapa 2'), (FUNIL, 'RE-03')],
          [T('Medir alcance, respostas, oportunidades geradas e resultado contra o alvo da ação', A),
           T('Concluir o que funcionou e o que mudar nas próximas ações', P),
           D('O resultado pede rever o plano de demanda?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Pedir a revisão do plano de demanda, com a evidência', R)])])],
          [(RES_DEM, ['RE-01', 'Executivos', 'Inteligência']),
           ('Pedido de revisão do plano de demanda', ['RE-01'])]),
    ]))

JORNADAS.append(dict(
    code='RE-03',
    nome='Qualificar os contatos e entregar a Negócios as oportunidades qualificadas',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Fazer com que cada contato entre na base de relacionamento com a origem e a base legal, receba conteúdo já aprovado pelo interesse que mostra, seja qualificado pelo critério combinado com Negócios e, quando qualificado, chegue a Negócios com o histórico; e manter a base confiável, executando os pedidos dos titulares que a Governança decide.',
    frequencia='Por evento: contato captado, contato de interessado, indicação de cliente, contato de parceiro, interação de contato em nutrição ou pedido de titular; e a cada ciclo de nutrição e revisão da base (cadência: nutrição contínua, por evento; revisão da base semestral)',
    automacao=('alta no registro e na nutrição, baixa na qualificação', 'Registrar, juntar duplicados, nutrir, pontuar e entregar rodam com agente e automação; a conversa de qualificação e a aprovação do que se faz na base são de pessoa; a resposta ao titular é decidida pela Governança.'),
    base=['apqc', 'lgpd'],
    lanes=['SOL', 'NEG', 'GOV', 'EXE', P, A, R],
    inicios=[I('Contato captado por ação de demanda', R, 'message'),
             I('Contato de interessado recebido', 'SOL', 'message'),
             I('Indicação ou contato de parceiro recebido', R, 'message'),
             I('Interação de contato em nutrição registrada', R, 'signal'),
             I('Ciclo de nutrição atingido', R, 'timer'),
             I('Pedido de titular decidido pela Governança', 'GOV', 'message'),
             I('Revisão periódica da base iniciada', R, 'timer')],
    fins=[F('Oportunidade aceita por Negócios', R), F('Contato em nutrição', R),
          F('Contato encerrado, com o motivo', R), F('Pedido do titular cumprido ou base revisada', R),
          F('Oportunidade sem resposta, escalada ao executivo', R)],
    etapas=[
        E('Registrar o contato com a origem e a base legal', 'Relações', 'Autopiloto', 'médio',
          [('Contatos captados pela ação, com o consentimento', 'RE-02'), ('Contato de interessado', 'Solicitante'),
           (INDICACAO, 'RE-05'), (CONTATOS_PARC, 'RE-06'), (SIGILO, 'Governança')],
          [D('O que abriu o trabalho?', R,
             [S('Contato novo, indicação ou contato de parceiro', 'seg'),
              S('Interação ou ciclo de contato em nutrição', 'E2'),
              S('Pedido de titular ou revisão periódica da base', 'E5')]),
           T('Localizar o contato na base de relacionamento e juntar os registros duplicados', R),
           T('Registrar a origem, a base legal do tratamento e o consentimento, quando é a base', R),
           D('O contato tem base legal para ser abordado?', A,
             [S('Sim', 'prox'),
              S('Dúvida', 'seg', via=[T('Decidir se o contato tem base legal para ser abordado', P)]),
              S('Não', 'F3', via=[T('Registrar o contato sem abordagem e o motivo', R)])]),
           D('A pessoa confirmou a base legal?', P,
             [S('Sim', 'prox'),
              S('Não', 'F3', via=[T('Registrar o contato sem abordagem e o motivo da pessoa', R)])])],
          [('Contato registrado, com a base legal', ['etapa 2'])]),
        E('Nutrir o contato e pontuar o interesse', 'Relações', 'Autopiloto', 'médio',
          [('Contato registrado, com a base legal', 'etapa 1'),
           (OFERTA_CAT, 'Inteligência'), (CRITERIO, 'RE-01')],
          [T('Enviar ao contato material já aprovado nas ações, conforme o interesse dele', A),
           T('Registrar as interações e pontuar o interesse pelo critério de qualificação', R, 'rule'),
           D('O contato atingiu o critério para a conversa de qualificação?', R,
             [S('Sim', 'prox'),
              S('Ainda não', 'F2', via=[T('Manter o contato na nutrição até a próxima interação ou ciclo', R)]),
              S('Não tem interesse ou pediu para sair', 'F3', via=[T('Registrar a saída e parar as abordagens', R)])])],
          [('Contato com interesse pontuado', ['etapa 3'])]),
        E('Qualificar a oportunidade com o contato', 'Relações', 'Assistido', 'médio',
          [('Contato com interesse pontuado', 'etapa 2'), (CRITERIO, 'RE-01'), ('Oportunidade devolvida no aceite, com o motivo', 'etapa 4')],
          [T('Preparar a conversa: necessidade, porte, prazo e quem decide no cliente', A),
           T('Conversar com o contato para confirmar necessidade, prazo e quem decide', P, 'manual'),
           T('Avaliar a oportunidade contra o critério combinado com Negócios', P),
           D('A oportunidade está qualificada?', P,
             [S('Sim', 'prox'),
              S('Ainda não', 'F2', via=[T('Devolver o contato à nutrição, com o que falta', R)]),
              S('Não', 'F3', via=[T('Registrar o motivo e encerrar a abordagem', R)])])],
          [('Oportunidade qualificada pela conversa', ['etapa 4'])]),
        E('Entregar a oportunidade a Negócios e acompanhar o aceite', 'Relações', 'Autômato', 'baixo',
          [('Oportunidade qualificada pela conversa', 'etapa 3'), ('Aceite ou devolução da oportunidade, com o motivo', 'Negócios')],
          [T('Entregar a Negócios a oportunidade com o histórico, a necessidade e a origem', R),
           T('Registrar a entrega no funil de contatos e oportunidades', R),
           T('Receber de Negócios o aceite, a devolução ou o vencimento do prazo combinado', R, 'receive'),
           D('Negócios aceitou a oportunidade?', R,
             [S('Sim', 'F1', via=[T('Registrar o aceite no funil e na base de relacionamento', R)]),
              S('Não, devolveu com o motivo', 'E3'),
              S('Sem resposta no prazo', 'F5', via=[T('Apontar a oportunidade sem resposta a Negócios e ao executivo', R)])])],
          [(OPORT_Q, ['Negócios']),
           (FUNIL, ['RE-01', 'RE-02', 'Negócios', 'Inteligência']),
           ('Oportunidade sem resposta no prazo', ['Negócios', 'Executivos']),
           ('Oportunidade devolvida no aceite, com o motivo', ['etapa 3'])]),
        E('Executar os pedidos dos titulares e manter a base confiável', 'Relações, com Governança', 'Copiloto', 'alto',
          [('Pedido de titular, com a resposta decidida pela Governança', 'Governança'), (SIGILO, 'Governança')],
          [D('O que abriu o trabalho na base?', R,
             [S('Pedido de titular de dados', 'seg',
                via=[T('Localizar os registros do titular em toda a base de relacionamento', R),
                     T('Listar o que muda na base para cumprir a resposta decidida pela Governança', A)]),
              S('Revisão periódica da base', 'seg',
                via=[T('Apontar duplicidade, dado vencido e consentimento expirado pela regra da ficha', A)])]),
           T('Aprovar o que será corrigido, anonimizado, eliminado ou revogado na base', P),
           T('Executar na base e nos sistemas o que foi aprovado', R),
           T('Informar à Governança o que foi feito, com a data', R)],
          [('Pedido do titular cumprido, com a data', ['Governança']),
           (BASE_REL, ['RE-02', 'RE-05', 'Negócios', 'Inteligência'])]),
    ]))
