
# ================================================================ CLIENTES
JORNADAS.append(dict(
    code='RE-04',
    nome='Desenhar a experiência do cliente: personas, mapa da jornada e padrões de experiência',
    dominio='Clientes', classe='essencial', onda=1,
    objetivo='Ter, para cada empresa, uma estratégia de experiência do cliente escrita e validada com clientes: quem são os clientes (personas), por onde passam (mapa da jornada), o que vivem em cada ponto de contato e que padrão de experiência cada etapa tem de cumprir, coerente com os valores e o posicionamento da marca. Operações, Negócios e Integração dizem se conseguem cumprir; Relações decide, ouvidos o executivo e os clientes.',
    frequencia='A cada revisão da experiência (cadência: anual) e por evento: oferta aprovada para lançamento ou lacuna de experiência apontada',
    automacao=('média', 'Reunir reclamações, saúde, percepção e indicadores, propor personas e o mapa e conferir com os padrões são de agente; ouvir clientes, desenhar os pontos de contato com Operações e decidir os padrões são de pessoas.'),
    base=['nng_journey', 'nng_blueprint', 'apqc'],
    lanes=['SOL', 'CLI', 'EST', 'EXE', 'OPE', 'NEG', 'ITG', 'IDE', P, A, R],
    inicios=[I('Revisão da experiência iniciada', R, 'timer'),
             I('Oferta aprovada para lançamento recebida', 'EST', 'message'),
             I('Lacuna de experiência apontada', 'SOL', 'message')],
    fins=[F('Estratégia de experiência publicada', R), F('Revisão encerrada sem mudança', R)],
    etapas=[
        E('Avaliar a experiência atual dos clientes', 'Relações, com Operações', 'Copiloto', 'médio',
          [(OFERTA_LANC, 'Estratégia'), (OFERTA_CAT, 'Inteligência'), (LEITURA, 'Inteligência'), (PAINEL, 'Inteligência'),
           (RECLAMACOES, 'Operações'), (LACUNAS_EXEC, 'Identidade'), ('Lacuna de experiência apontada', 'Solicitante'),
           ('Saúde dos clientes e motivos de perda', 'RE-05'), (PERCEP, 'RE-08')],
          [T('Reunir reclamações, saúde, percepção e indicadores por etapa da jornada do cliente', A),
           T('Ouvir clientes sobre a experiência em cada etapa', P, 'manual'),
           T('Apontar as lacunas de experiência e as causas prováveis de cada uma', A),
           T('Concluir as lacunas de experiência e as causas', P),
           D('As lacunas pedem mudar a estratégia de experiência?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a avaliação sem mudança e avisar quem apontou a lacuna', R)])])],
          [('Avaliação da experiência, com lacunas e causas', ['etapa 2']),
           ('Avaliação da experiência sem mudança', ['Solicitante', 'Operações', 'Executivos'])]),
        E('Desenhar personas, mapa da jornada e padrões de experiência', 'Relações, com Operações, Negócios e Integração', 'Copiloto', 'médio',
          [('Avaliação da experiência, com lacunas e causas', 'etapa 1'), ('Ajustes pedidos à estratégia de experiência', 'etapa 3'),
           (POSIC, 'Identidade'), (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Propor personas e o mapa da jornada: fases, ações, modos de pensar, emoções e oportunidades', A),
           T('Desenhar com Operações os pontos de contato e o que acontece por trás deles', P, 'manual'),
           T('Definir o padrão de experiência de cada etapa da jornada do cliente', P),
           PAR([T('Dizer se a operação consegue cumprir os padrões de experiência', 'OPE')],
               [T('Dizer se a venda e a renovação conseguem cumprir os padrões', 'NEG')],
               [T('Apontar os sistemas e os agentes que os padrões de experiência pedem', 'ITG')]),
           D('Operações, Negócios e Integração conseguem cumprir os padrões?', P,
             [S('Sim', 'seg'), S('Não, ajustar os padrões', 'E2')]),
           T('Conferir a experiência com os valores, o posicionamento e os padrões da marca', A),
           D('A experiência está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir a experiência no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre a experiência não coberta pelos padrões', 'IDE', 'call')])])],
          [('Proposta de estratégia de experiência', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Validar com clientes e decidir a estratégia de experiência', 'Relações, ouvidos clientes e o executivo', 'Assistido', 'médio',
          [('Proposta de estratégia de experiência', 'etapa 2')],
          [T('Avaliar o mapa da jornada e os padrões propostos', 'CLI'),
           T('Conduzir a validação com clientes e registrar o que confirmaram', P, 'manual'),
           T('Opinar sobre a estratégia de experiência da empresa', 'EXE'),
           T('Decidir a estratégia de experiência, ouvidos clientes e o executivo', P),
           D('A estratégia de experiência está pronta para publicar?', P,
             [S('Sim', 'prox'), S('Não, ajustar', 'E2')])],
          [('Estratégia de experiência decidida', ['etapa 4']),
           ('Ajustes pedidos à estratégia de experiência', ['etapa 2'])]),
        E('Publicar a estratégia e entregar a quem atende, vende e desenha ofertas', 'Relações', 'Autômato', 'baixo',
          [('Estratégia de experiência decidida', 'etapa 3')],
          [T('Publicar a estratégia de experiência com versão e data de revisão', R),
           T('Avisar Operações, Negócios, Integração e os executivos do que mudou', R),
           T('Apontar a estratégia publicada à base de conhecimento da Inteligência', R)],
          [(CX, ['RE-01', 'RE-05', 'Operações', 'Negócios', 'Integração', 'Executivos', 'Inteligência']),
           ('Conteúdo novo apontado', ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='RE-05',
    nome='Acompanhar o sucesso de cada cliente, da entrada à renovação, à expansão ou à perda',
    dominio='Clientes', classe='essencial', onda=1,
    objetivo='Fazer com que cada cliente tenha um plano de sucesso combinado, que a saúde de cada cliente seja medida a cada ciclo, que o risco de perda seja tratado antes da perda, que o resultado seja apresentado ao cliente e que a renovação, a expansão, a indicação ou a lição da perda cheguem a quem age. Negócios negocia a renovação e a expansão e informa o resultado; Operações atende e entrega. Os clientes só são avisados de uma saída quando a data está confirmada.',
    frequencia='Por evento: contrato de cliente assinado, empresa adquirida, sinal de risco, vencimento de contrato, resultado da renovação, decisão de encerrar oferta ou data de saída confirmada; e a cada ciclo de acompanhamento do cliente (cadência: trimestral, por cliente)',
    automacao=('média', 'Reunir os dados, calcular a saúde, montar o relatório e apontar oportunidades são de agente e automação; combinar o plano, apresentar o resultado, tratar o risco e decidir o próximo passo são de pessoas de Relações, ouvido o executivo.'),
    base=['apqc'],
    lanes=['CLI', 'EST', 'NEG', 'OPE', 'EXE', 'IDE', P, A, R],
    inicios=[I('Contrato de cliente assinado', 'NEG', 'message'),
             I('Empresa adquirida no portfólio', 'EST', 'message'),
             I('Ciclo de acompanhamento do cliente iniciado', R, 'timer'),
             I('Sinal de risco do cliente detectado', R, 'signal'),
             I('Vencimento ou resultado da renovação informado', 'NEG', 'message'),
             I('Encerramento de oferta ou saída de empresa decidida', 'EST', 'message'),
             I('Mandato da empresa recebido', 'EST', 'message'),
             I('Oferta mantida, em espera ou devolvida depois da revisão', 'EST', 'message')],
    fins=[F('Ciclo de acompanhamento concluído', R),
          F('Oportunidade de renovação ou de expansão entregue a Negócios', R),
          F('Cliente perdido, com a lição registrada', R),
          F('Clientes avisados da saída e em transição', R),
          F('Clientes afetados listados, à espera da data de saída', R),
          F('Mandato registrado, sem aviso aos clientes', R),
          F('Oferta mantida; transição desfeita, quando houver', R)],
    etapas=[
        E('Receber o cliente e combinar o plano de sucesso', 'Relações, com Negócios, Operações e o cliente', 'Copiloto', 'médio',
          [('Contrato de cliente assinado, com o escopo vendido', 'Negócios'), ('Plano de implantação do cliente', 'Integração'),
           (CX, 'RE-04'), (BASE_REL, 'RE-03'), (DEC_ENCERRAR, 'Estratégia'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'),
           (OFERTA_FORA, 'Inteligência'), ('Plano de saída de clientes e contratos', 'Integração'),
           ('Aposta mantida depois da revisão', 'Estratégia'), ('Aposta em espera ou devolvida', 'Estratégia')],
          [D('O que abriu o trabalho?', R,
             [S('Cliente novo ou clientes de empresa adquirida', 'seg'),
              S('Ciclo, sinal de risco, vencimento ou resultado da renovação', 'E2'),
              S('Decisão de encerrar, ainda sem data de saída', 'F5',
                via=[T('Listar os clientes afetados pela oferta que será encerrada', R),
                     T('Preparar com Operações e Integração a transição, sem avisar os clientes ainda', P, 'manual')]),
              S('Data de saída confirmada, ou venda fechada ou encerramento de empresa', 'F4',
                via=[T('Listar os clientes afetados pela oferta ou pela empresa que sai', R),
                     T('Combinar com Operações e Integração a transição de cada cliente', P, 'manual'),
                     T('Avisar cada cliente da saída, na data confirmada, com a transição combinada', P, 'manual')]),
              S('Mandato de busca de comprador, de criação ou de mudança de mandato', 'F6',
                via=[T('Registrar o mandato e os clientes que ele alcança, sob sigilo e sem avisar os clientes', R)]),
              S('Oferta mantida, em espera ou devolvida depois da revisão', 'F7',
                via=[T('Desfazer com Operações e Integração a transição preparada, quando houver, sem avisar os clientes', P, 'manual')])]),
           T('Conferir o que foi vendido, os resultados que o cliente espera e quem decide nele', A),
           T('Combinar com o cliente o plano de sucesso: resultados, marcos e contatos', P, 'manual'),
           T('Confirmar o plano de sucesso e os contatos do cliente', 'CLI'),
           T('Registrar o plano de sucesso e avisar Operações e Negócios', R)],
          [(PLANO_SUC, ['etapa 2', 'etapa 3', 'Operações', 'Negócios']),
           ('Clientes avisados da saída, com a transição combinada', ['Operações', 'Negócios', 'Integração'])]),
        E('Medir a saúde do cliente e apontar o risco de perda', 'Relações', 'Autopiloto', 'baixo',
          [(PLANO_SUC, 'etapa 1'), (PAINEL, 'Inteligência'), ('Registros de entrega, atendimento e reclamações do cliente', 'Operações'),
           ('Situação de faturas e pagamentos do cliente', 'Gestão'), ('Vencimento do contrato e resultado da renovação', 'Negócios')],
          [T('Reunir uso, entregas, reclamações, pagamentos, contrato e interações do cliente', R),
           T('Calcular a saúde do cliente pela regra e comparar com o plano de sucesso', R, 'rule'),
           D('O cliente está em risco?', A,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Apontar o risco, a causa provável e a ação sugerida', A)])])],
          [('Saúde do cliente, com o risco e a causa provável', ['etapa 3']),
           ('Saúde dos clientes e motivos de perda', ['RE-04', 'Executivos'])]),
        E('Apresentar o resultado ao cliente e agir sobre o risco', 'Relações, com Operações, ouvido o executivo', 'Copiloto', 'médio',
          [('Saúde do cliente, com o risco e a causa provável', 'etapa 2'), (PLANO_SUC, 'etapa 1'), (PADROES_ID, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Montar o relatório de resultado do cliente contra o plano de sucesso', A),
           T('Conferir o relatório com os padrões de identidade', A),
           D('O relatório está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o relatório no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o relatório não coberto pelos padrões', 'IDE', 'call')])]),
           T('Apresentar ao cliente o resultado e ouvir a avaliação dele', P, 'manual'),
           T('Avaliar o resultado apresentado e dizer o que espera a seguir', 'CLI'),
           D('Há risco de perda a tratar?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Opinar sobre o plano de recuperação do cliente', 'EXE'),
                                    T('Combinar com Operações o plano de recuperação do cliente', P, 'manual'),
                                    T('Registrar o plano de recuperação e acompanhá-lo até o próximo ciclo', R)])])],
          [('Resultado apresentado e avaliação do cliente', ['etapa 4']),
           ('Plano de recuperação do cliente', ['Operações', 'Executivos']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir o próximo passo com o cliente: renovar, ampliar, indicar ou registrar a perda', 'Relações, ouvido o executivo', 'Copiloto', 'médio',
          [('Resultado apresentado e avaliação do cliente', 'etapa 3'), ('Vencimento do contrato e resultado da renovação', 'Negócios')],
          [T('Apontar oportunidade de renovação, de expansão ou de indicação pelo histórico do cliente', A),
           T('Opinar sobre o próximo passo com o cliente', 'EXE'),
           T('Decidir o próximo passo com o cliente, ouvido o executivo', P),
           D('Qual é o próximo passo com o cliente?', P,
             [S('Seguir acompanhando', 'seg'),
              S('Renovação ou expansão', 'F2',
                via=[T('Entregar a Negócios a oportunidade de renovação ou de expansão, com o histórico', R)]),
              S('Indicação ou caso de cliente', 'seg',
                via=[T('Pedir ao cliente a indicação, com o aceite do indicado, ou a autorização do caso', P, 'manual'),
                     T('Enviar a indicação ao registro de contatos e o caso autorizado à comunicação', R)]),
              S('Cliente perdido: não renovou ou cancelou', 'F3',
                via=[T('Ouvir o cliente sobre os motivos da perda', P, 'manual'),
                     T('Registrar a lição da perda, sem dado sigiloso', A)])]),
           T('Registrar o ciclo, os sinais do relacionamento e as lições do cliente', R)],
          [('Oportunidade de renovação ou de expansão, com o histórico', ['Negócios']),
           (INDICACAO, ['RE-03']),
           (CASO_CLI, ['RE-07']),
           (LICOES_CLI, ['Inteligência']),
           (SINAIS, ['Inteligência'])]),
    ]))
