
# ============================================== PARCERIAS E INSTITUIÇÕES
JORNADAS.append(dict(
    code='RE-06',
    nome='Formar e cuidar de parcerias e relações institucionais e autorizar o uso da marca por terceiros',
    dominio='Parcerias e instituições', classe='essencial', onda=2,
    objetivo='Fazer cada parceria ou relação institucional nascer de uma avaliação de encaixe, ser formalizada com objetivos, papéis e indicadores, por contrato ou por termo institucional conferido pela Governança e aprovado pelo executivo, ser ativada, acompanhada e, quando deixa de servir, encerrada com ordem; e decidir quem de fora pode usar as marcas, pela regra da Identidade, com a exceção decidida por Relações, ouvida a Identidade, e liberada pela Governança. A parceria acima da alçada sobe aos sócios pela Governança; a que muda o portfólio vai à Estratégia como aposta.',
    frequencia='Por evento: parceria proposta, pedido de uso da marca por terceiro, marca retirada de uso ou encerramento pedido; e na revisão de cada parceria (cadência: semestral, por parceria)',
    automacao=('média', 'Registrar, avaliar o parceiro, conferir com a regra e medir o resultado são de agente e automação; negociar, decidir e capacitar são de pessoas; o contrato e a liberação da exceção à regra da marca são da Governança.'),
    base=['iso44001', 'apqc'],
    lanes=['SOL', 'EST', 'IDE', 'PRC', 'EXE', 'GES', 'GOV', 'SOC', P, A, R],
    inicios=[I('Parceria ou relação institucional proposta', 'SOL', 'message'),
             I('Pedido de uso da marca por terceiro recebido', 'SOL', 'message'),
             I('Marca retirada de uso avisada', 'IDE', 'message'),
             I('Encerramento de parceria pedido', 'SOL', 'message'),
             I('Revisão da parceria iniciada', R, 'timer'),
             I('Parceria aprovada no portão da Estratégia', 'EST', 'message'),
             I('Parceria não aprovada no portão da Estratégia', 'EST', 'message')],
    fins=[F('Uso da marca decidido e registrado', R), F('Parceria não seguiu, com o motivo', R),
          F('Parceria avaliada e mantida', R), F('Parceria encerrada', R),
          F('Parceria levada à Estratégia como aposta', R), F('Autorizações da marca retirada revogadas', R),
          F('Uso da marca recusado, com o motivo', R)],
    etapas=[
        E('Registrar o pedido e avaliar o encaixe da parceria', 'Relações', 'Copiloto', 'médio',
          [('Proposta de parceria ou de relação institucional', 'Solicitante'), ('Pedido de uso da marca por terceiro', 'Solicitante'),
           ('Pedido de encerramento de parceria', 'Solicitante'), (MARCA_RET, 'Identidade'), (DIRECAO, 'Estratégia'),
           (LEITURA, 'Inteligência'), ('Parceria aprovada no portão, para formalizar', 'Estratégia'),
           ('Aposta em espera ou devolvida', 'Estratégia'), ('Lição da aposta encerrada', 'Estratégia')],
          [T('Registrar o pedido, quem pede e o que abriu o trabalho', R),
           D('O que abriu o trabalho?', R,
             [S('Parceria ou relação institucional nova', 'seg'),
              S('Uso da marca por terceiro', 'E5'),
              S('Revisão ou encerramento de parceria', 'E4'),
              S('Parceria aprovada no portão da Estratégia', 'E2',
                via=[T('Reunir a avaliação da parceria e a decisão do portão', R)]),
              S('Parceria encerrada, em espera ou devolvida no portão da Estratégia', 'F2',
                via=[T('Avisar o parceiro e quem propôs da decisão do portão, com o motivo', R)]),
              S('Marca retirada de uso', 'F6',
                via=[T('Revogar as autorizações de uso da marca retirada e avisar os terceiros', R)])]),
           T('Avaliar o parceiro: reputação, encaixe com a direção, capacidade e risco', A),
           T('Decidir se a parceria avança', P),
           D('A parceria avança?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Responder a quem propôs que a parceria não segue, com o motivo', R)])])],
          [('Parceria avaliada para negociação', ['etapa 2']),
           ('Resposta à proposta de parceria', ['Solicitante'])]),
        E('Negociar e formalizar a parceria', 'Relações, com Governança; acima da alçada, os sócios', 'Copiloto', 'alto',
          [('Parceria avaliada para negociação', 'etapa 1'), ('Mudança pedida nos termos da parceria', 'etapa 4'),
           (ALCADAS, 'Governança'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Combinar com o parceiro objetivos, papéis, contrapartidas e indicadores', P, 'manual'),
           T('Conferir os termos e o material conjunto com os padrões de identidade', A),
           D('Os termos estão conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir os termos no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre os termos não cobertos pelos padrões', 'IDE', 'call')])]),
           D('A parceria tem contrapartida financeira?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o custo, a receita e o efeito no orçamento da parceria', 'GES')])]),
           T('Aplicar a tabela de alçadas à parceria', R, 'rule'),
           D('Quem decide a parceria?', R,
             [S('Relações, dentro da alçada', 'seg', via=[T('Decidir a parceria, ouvido o executivo', P)]),
              S('Os sócios, acima da alçada', 'seg', via=[T('Levar a parceria à decisão dos sócios', 'GOV', 'call'),
                                                          T('Decidir a parceria pelos sócios', 'SOC', 'manual')]),
              S('Já aprovada no portão da Estratégia', 'seg'),
              S('A Estratégia: a parceria muda o portfólio', 'F5',
                via=[T('Levar a parceria à Estratégia como aposta, com a avaliação', R)])]),
           D('A parceria foi aprovada?', P,
             [S('Sim, ou já aprovada no portão da Estratégia', 'seg'),
              S('Não', 'F2', via=[T('Avisar o parceiro e quem propôs de que a parceria não segue', R)])]),
           D('A parceria pede contrato?', P,
             [S('Sim', 'seg', via=[T('Preparar e revisar o contrato de parceria', 'GOV', 'call'),
                                   T('Assinar o contrato de parceria em nome da empresa', 'EXE')]),
              S('Não: termo ou protocolo institucional', 'seg',
                via=[T('Conferir o termo institucional e o risco jurídico', 'GOV', 'call'),
                     T('Aprovar o termo institucional em nome da empresa', 'EXE')])])],
          [('Parceria formalizada, com plano conjunto e indicadores', ['etapa 3']),
           ('Ideia ou aposta nova', ['Estratégia']),
           (CONSULTA, ['Identidade'])]),
        E('Ativar a parceria', 'Relações, com o parceiro', 'Copiloto', 'médio',
          [('Parceria formalizada, com plano conjunto e indicadores', 'etapa 2'),
           (PACOTE_MARCA, 'Identidade'), (OFERTA_CAT, 'Inteligência')],
          [T('Montar o plano de ativação: contatos, materiais do pacote de marca, capacitação e calendário', A),
           T('Capacitar o parceiro nas ofertas e no uso da marca', P, 'manual'),
           T('Confirmar o plano de ativação e os contatos do parceiro', 'PRC'),
           T('Registrar a parceria e os contatos na base de relacionamento', R)],
          [('Parceria ativa, com plano de ativação', ['etapa 4', 'Negócios', 'Operações']),
           (CONTATOS_PARC, ['RE-03'])]),
        E('Acompanhar a parceria e decidir manter, mudar ou encerrar', 'Relações, com o parceiro', 'Assistido', 'médio',
          [('Parceria ativa, com plano de ativação', 'etapa 3'), ('Pedido de encerramento de parceria', 'Solicitante'),
           (PAINEL, 'Inteligência')],
          [T('Medir o resultado da parceria contra os indicadores combinados', A),
           T('Avaliar com o parceiro o resultado e o que mudar', P, 'manual'),
           T('Decidir manter, mudar ou encerrar a parceria', P),
           D('Qual é a decisão sobre a parceria?', P,
             [S('Manter', 'F3', via=[T('Registrar a avaliação e a data da próxima revisão', R)]),
              S('Mudar os termos', 'E2'),
              S('Encerrar', 'F4',
                via=[T('Combinar com o parceiro a saída e o que fica pendente', P, 'manual'),
                     T('Encerrar o contrato ou o termo de parceria', 'GOV', 'call'),
                     T('Retirar o uso da marca pelo parceiro e avisar Negócios e Operações', R)])])],
          [('Resultado da parceria', ['Executivos', 'Negócios']),
           ('Mudança pedida nos termos da parceria', ['etapa 2']),
           (SINAIS, ['Inteligência'])]),
        E('Decidir e registrar o uso da marca por terceiro', 'Relações; a exceção, ouvida a Identidade e liberada pela Governança', 'Copiloto', 'médio',
          [('Pedido de uso da marca por terceiro', 'Solicitante'), (REGRA_MARCA, 'Identidade'), (PACOTE_MARCA, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Conferir o pedido com a regra de uso da marca por terceiros', A),
           D('O uso está coberto pela regra?', A,
             [S('Sim', 'seg'),
              S('Não: pede exceção à regra', 'seg',
                via=[T('Responder à consulta sobre o uso fora da regra', 'IDE', 'call')])]),
           D('A exceção pode ser concedida?', P,
             [S('Não se aplica: uso coberto pela regra', 'seg'),
              S('Sim', 'seg', via=[T('Liberar os termos e o risco do uso fora da regra', 'GOV')]),
              S('Não', 'F7', via=[T('Recusar o pedido e responder a quem pediu, com o motivo', R)])]),
           D('O uso pode seguir?', P,
             [S('Sim: coberto pela regra ou liberado pela Governança', 'seg'),
              S('Não: a Governança não liberou', 'F7',
                via=[T('Recusar o pedido sem liberação e responder a quem pediu, com o motivo', R)])]),
           T('Decidir o uso da marca dentro da regra ou da exceção aceita: autorizar ou recusar', P),
           T('Registrar a decisão, o prazo e as condições e responder a quem pediu', R)],
          [('Resposta ao pedido de uso da marca', ['Solicitante']),
           ('Autorizações de uso da marca por terceiros, com prazo', ['Governança']),
           (CONSULTA, ['Identidade'])]),
    ]))

# ================================================= COMUNICAÇÃO E REPUTAÇÃO
JORNADAS.append(dict(
    code='RE-07',
    nome='Comunicar para fora: pauta, conteúdo, imprensa e porta-vozes',
    dominio='Comunicação e reputação', classe='essencial', onda=1,
    objetivo='Comunicar aos públicos externos, com uma só voz e dentro dos padrões de identidade, os fatos, as mudanças, os lançamentos e os casos que importam, preparar quem fala pela empresa e medir o efeito de cada tema contra o alvo, e não só a exposição. O executivo aprova o que se diz em nome da empresa; a Governança confere o risco jurídico. A comunicação interna é da Gestão.',
    frequencia='A cada ciclo de pauta (cadência: pauta mensal) e por evento: fato a comunicar ou pedido de imprensa',
    automacao=('média', 'Reunir fatos, propor a pauta, redigir, conferir, publicar e medir são de agente e automação; decidir a pauta, revisar, aprovar e preparar os porta-vozes são de pessoas.'),
    base=['barcelona', 'apqc'],
    lanes=['SOL', 'EXE', 'GOV', 'IDE', P, A, R],
    inicios=[I('Ciclo de pauta iniciado', R, 'timer'),
             I('Fato a comunicar recebido', 'SOL', 'message'),
             I('Pedido de imprensa recebido', 'SOL', 'message')],
    fins=[F('Conteúdo publicado e medido', R), F('Pauta sem tema a comunicar', R),
          F('Conteúdo não publicado, com o motivo', R)],
    etapas=[
        E('Decidir a pauta: o que comunicar, a quem e com que alvo', 'Relações, ouvido o executivo', 'Copiloto', 'baixo',
          [(PLANO_DEM, 'RE-01'), (MUD_DECL, 'Identidade'), (MUD_EST, 'Estratégia'), (OFERTA_LANC, 'Estratégia'), (MANDATO, 'Estratégia'),
           (MARCA_RET, 'Identidade'), (LACUNAS_EXEC, 'Identidade'), (CASO_CLI, 'RE-05'), (RES_COM, 'etapa 4'),
           ('Fato a comunicar', 'Solicitante'), ('Pedido de imprensa', 'Solicitante')],
          [T('Reunir fatos, mudanças, lançamentos, casos e pedidos de imprensa do período', R),
           T('Propor a pauta: tema, público, canal, mensagem-chave e alvo de cada tema', A),
           T('Opinar sobre os temas que falam em nome da empresa', 'EXE'),
           T('Decidir a pauta, ouvido o executivo', P),
           D('Há tema a comunicar?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a pauta sem tema e responder aos pedidos recebidos', R)])])],
          [('Pauta decidida, com o alvo de cada tema', ['etapa 2'])]),
        E('Produzir o conteúdo e conferir com os padrões de identidade', 'Relações', 'Copiloto', 'médio',
          [('Pauta decidida, com o alvo de cada tema', 'etapa 1'), ('Ajustes pedidos ao conteúdo', 'etapa 3'),
           (POSIC, 'Identidade'), (PADROES_ID, 'Identidade'), (PACOTE_MARCA, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Redigir o conteúdo de cada tema no guia de voz e com a casa de mensagens', A),
           T('Conferir o conteúdo com os padrões de identidade', A),
           D('O conteúdo está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o conteúdo no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o conteúdo não coberto pelos padrões', 'IDE', 'call')])]),
           T('Revisar o conteúdo e a fonte de cada afirmação', P)],
          [('Conteúdo pronto para aprovação', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Aprovar o conteúdo e preparar os porta-vozes', 'Relações, com o executivo e a Governança', 'Assistido', 'médio',
          [('Conteúdo pronto para aprovação', 'etapa 2'), (SIGILO, 'Governança')],
          [D('O conteúdo fala em nome da empresa?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Aprovar o que a empresa diz e quem fala por ela', 'EXE')])]),
           D('O conteúdo traz risco jurídico ou pede sigilo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o risco jurídico e o que pode ser dito', 'GOV')])]),
           T('Aprovar o conteúdo final, com o que o executivo e a Governança disseram', P),
           D('O conteúdo está aprovado?', P,
             [S('Sim', 'seg'),
              S('Não, ajustar', 'E2'),
              S('Não: não deve ser publicado', 'F3', via=[T('Registrar o motivo e responder a quem pediu o tema', R)])]),
           D('O tema pede porta-voz?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Preparar o porta-voz com as mensagens, as perguntas difíceis e os limites', P, 'manual')])])],
          [('Conteúdo aprovado', ['etapa 4']),
           ('Ajustes pedidos ao conteúdo', ['etapa 2'])]),
        E('Publicar o conteúdo, atender a imprensa e medir o efeito', 'Relações', 'Autopiloto', 'médio',
          [('Conteúdo aprovado', 'etapa 3')],
          [T('Publicar o conteúdo aprovado nos canais da empresa e enviar à imprensa, no calendário', R),
           T('Registrar os pedidos de imprensa, as entrevistas e o que foi publicado', R),
           T('Medir alcance, resultado e efeito de cada tema contra o alvo, além da exposição', A)],
          [('Conteúdo externo publicado', ['Públicos externos', 'Gestão']),
           (RES_COM, ['etapa 1', 'RE-08', 'Executivos'])]),
    ]))

JORNADAS.append(dict(
    code='RE-08',
    nome='Monitorar a percepção dos públicos e a reputação e acionar a resposta a crises',
    dominio='Comunicação e reputação', classe='essencial', onda=1,
    objetivo='Saber, a cada ciclo, como os públicos percebem as marcas, encaminhar cada lacuna a quem pode agir e detectar cedo o que pode virar crise. Relações apura os fatos e leva ao comitê da Governança todo sinal grave ou em dúvida; o comitê declara a crise, decide a posição e o porta-voz e a encerra; Relações redige e publica a comunicação da posição decidida.',
    frequencia='A cada ciclo de monitoramento (cadência: coleta contínua; análise mensal) e por evento: sinal de reputação detectado',
    automacao=('média (alta na coleta, baixa na crise)', 'Coletar, classificar, agrupar e publicar são de agente e automação; apurar os fatos, concluir a percepção e comunicar na crise são de pessoas; declarar e encerrar a crise e decidir a posição são da Governança, com o executivo.'),
    base=['reptrak', 'iso22361', 'barcelona', 'apqc'],
    lanes=['GOV', 'EXE', P, A, R],
    inicios=[I('Ciclo de monitoramento iniciado', R, 'timer'),
             I('Sinal de reputação detectado', R, 'signal')],
    fins=[F('Percepção dos públicos publicada', R), F('Sinal sem crise, encaminhado ao dono', R),
          F('Crise encerrada, com as lições registradas', R), F('Sinal guardado para o ciclo', R)],
    etapas=[
        E('Coletar e classificar os sinais sobre as marcas', 'Relações', 'Autopiloto', 'médio',
          [(PROTOCOLO, 'Identidade'), (POSIC, 'Identidade'), (RES_COM, 'RE-07'), (LEITURA, 'Inteligência'), (RECLAMACOES, 'Operações')],
          [T('Coletar menções, reclamações públicas, imprensa e conversas sobre as marcas', R),
           T('Classificar cada sinal por fator de reputação, público, gravidade e marca', A),
           D('O trabalho é o ciclo de monitoramento?', R,
             [S('Sim', 'E4', via=[T('Abrir como sinal avulso cada sinal grave ou em dúvida do ciclo', R)]),
              S('Não: sinal avulso', 'seg')]),
           D('O sinal pode virar crise pelo critério do protocolo?', A,
             [S('Sim, gravidade alta ou dúvida', 'prox'),
              S('Não', 'F4', via=[T('Guardar o sinal classificado para a análise do ciclo', R)])])],
          [(SINAIS_CL, ['etapa 2', 'etapa 4'])]),
        E('Apurar o sinal e levar ao comitê de crise', 'Relações, com o comitê de crise da Governança', 'Copiloto', 'alto',
          [(SINAIS_CL, 'etapa 1'), (PROTOCOLO, 'Identidade'),
           ('Declaração, posição e encerramento da crise decididos pelo comitê', 'Governança')],
          [T('Apurar os fatos do sinal com quem está perto do caso', P, 'manual'),
           T('Levar ao comitê de crise da Governança os fatos apurados', R),
           T('Levar ao dono da crise a declaração, a posição e o porta-voz, pelo comitê', 'GOV', 'call'),
           D('O dono da crise declarou crise?', 'GOV',
             [S('Não', 'F2', via=[T('Encaminhar o sinal ao dono do tema: Operações, Negócios ou o executivo', R)]),
              S('Sim', 'prox')])],
          [('Alerta de crise, com os fatos apurados', ['Governança', 'Executivos']),
           ('Crise declarada, com a posição e o porta-voz decididos', ['etapa 3'])]),
        E('Comunicar a posição decidida até o encerramento da crise', 'Relações, com o executivo e o comitê de crise', 'Copiloto', 'alto',
          [('Crise declarada, com a posição e o porta-voz decididos', 'etapa 2'), (PROTOCOLO, 'Identidade'), (PADROES_ID, 'Identidade'),
           ('Declaração, posição e encerramento da crise decididos pelo comitê', 'Governança')],
          [T('Redigir a comunicação da posição decidida, no protocolo de crise e nos padrões', A),
           T('Conferir a comunicação com o protocolo de crise e com o que o comitê decidiu', P),
           T('Aprovar a comunicação da posição da empresa', 'EXE'),
           T('Publicar a comunicação e acompanhar a reação dos públicos', R),
           T('Receber do comitê o encerramento da crise ou uma nova posição', R, 'receive'),
           D('O comitê encerrou a crise?', P,
             [S('Sim', 'F3', via=[T('Registrar as lições da crise, sem dado sigiloso', P)]),
              S('Não: há nova posição a comunicar', 'E3')])],
          [('Comunicação da posição sobre a crise', ['Públicos externos']),
           ('Lições da crise', ['Governança']),
           ('Lição apontada', ['Inteligência'])]),
        E('Analisar a percepção dos públicos e entregar a quem pode agir', 'Relações', 'Copiloto', 'baixo',
          [(SINAIS_CL, 'etapa 1'), (RESUMO_PAD, 'Identidade'), (LACUNAS_EXEC, 'Identidade')],
          [T('Agrupar os sinais do ciclo nos sete fatores de reputação e comparar com o anterior', A),
           T('Concluir a percepção dos públicos e o que mudou', P),
           T('Encaminhar cada lacuna a quem pode agir: Operações, Negócios, executivo ou círculo', R),
           T('Publicar a percepção e a escuta dos públicos', R)],
          [(PERCEP, ['Identidade', 'Inteligência', 'RE-04', 'Executivos']),
           (ESCUTA, ['Identidade']),
           ('Lacunas de percepção encaminhadas ao dono', ['Executivos', 'Operações', 'Negócios'])]),
    ]))
