
# ========================================================== TECNOLOGIA
JORNADAS.append(dict(
    code='IT-07',
    nome='Operar a tecnologia: pedidos, incidentes, acessos, mudanças e fornecedores',
    dominio='Tecnologia e jornadas', classe='essencial', onda=1,
    objetivo='Fazer cada pedido, incidente ou risco de tecnologia ser resolvido no prazo; cada acesso a dados e sistemas ser dado e retirado pela classificação do dado e pelo pedido; cada mudança em sistema ser testada, aprovada e reversível; cada incidente de segurança ou de dados pessoais ser tratado com a Governança; e cada fornecedor e licença de tecnologia ser escolhido, contratado e controlado com a Gestão e a Governança. A Integração opera e protege; a Governança define a política e verifica; a Gestão compra e paga.',
    frequencia='Por evento: pedido, incidente ou risco de tecnologia, contrato de cliente encerrado, pedido de acesso ou de retirada vindo de outra jornada, pedido de fornecedor ou licença, renovação próxima',
    automacao=('média', 'Receber, classificar, resolver o que é conhecido, conceder e retirar acessos pela regra, testar e implantar mudanças padrão e registrar são de agente e automação; resolver o caso novo, aprovar mudança e escolher fornecedor são de pessoa da Integração.'),
    base=['iso27001', 'apqc'],
    lanes=['SOL', 'INT', 'NEG', 'GOV', 'GES', P, A, R],
    inicios=[I('Pedido, incidente ou risco de tecnologia recebido', 'SOL', 'message'),
             I('Contrato de cliente encerrado', 'NEG', 'message'),
             I('Renovação de licença ou de contrato de tecnologia próxima', R, 'timer'),
             I('Pedido de acesso ou de mudança vindo de outra jornada', R, 'message')],
    fins=[F('Item de tecnologia resolvido ou contratado e registrado', R),
          F('Mudança desfeita, com o motivo', R)],
    etapas=[
        E('Receber e classificar o pedido, o incidente ou o risco', 'Integração', 'Autopiloto', 'baixo',
          [('Pedido, incidente ou risco de tecnologia', 'Solicitante'), (CAT_DADOS, 'Inteligência'), (DADO_RET, 'Inteligência'),
           (CONTR_FIM, 'Negócios'), (PED_ACESSO, 'IT-02'), (PED_ACESSO, 'IT-04'), (PED_ACESSO, 'IT-08'), (SIGILO, 'Governança')],
          [T('Registrar o item, quem pede, o sistema e o dado afetados', R),
           T('Classificar o tipo, a urgência, o risco e o prazo', A),
           D('É incidente de segurança ou de dados pessoais?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Tratar o incidente de segurança ou de dados pessoais com a Governança', 'GOV', 'call')])]),
           D('O que o item pede?', R,
             [S('Acesso, retirada de acesso, solução conhecida ou mudança', 'prox'),
              S('Fornecedor, licença ou serviço de tecnologia novo, ou renovação', 'E3')])],
          [('Item classificado e priorizado', ['etapa 2', 'etapa 3'])]),
        E('Resolver o item e implantar a mudança', 'Integração; a mudança de risco, com a Governança', 'Copiloto', 'médio',
          [('Item classificado e priorizado', 'etapa 1')],
          [D('O item pede mudança em sistema?', R,
             [S('Não: acesso ou solução conhecida', 'seg',
                via=[T('Conceder ou retirar o acesso pela classificação do dado, ou aplicar a solução conhecida', R)]),
              S('Sim', 'seg', via=[T('Preparar e testar a mudança, com o caminho de volta', A),
                                   T('Aprovar a mudança e a janela de implantação', P)])]),
           D('A mudança mexe em dado pessoal, acesso privilegiado ou segurança?', P,
             [S('Não, ou não há mudança', 'seg'),
              S('Sim', 'seg', via=[T('Conferir a mudança contra a política de segurança e de dados pessoais', 'GOV')])]),
           T('Resolver o caso novo que o agente não resolve', P),
           T('Implantar a mudança ou fechar o item e avisar quem pediu', R),
           D('O item foi resolvido?', P,
             [S('Sim', 'E4'),
              S('Não: a mudança falhou', 'F2', via=[T('Desfazer a mudança, voltar ao estado anterior e registrar o motivo', R)])])],
          [('Item resolvido', ['etapa 4']),
           ('Agente ou acesso não entregue, com o motivo', ['IT-02'])]),
        E('Escolher e contratar fornecedor ou licença de tecnologia', 'Integração, com a Gestão e a Governança', 'Copiloto', 'médio',
          [('Item classificado e priorizado', 'etapa 1')],
          [T('Comparar fornecedores e licenças, ou o uso da que vence: requisito, segurança, custo e saída', A),
           T('Escolher o fornecedor ou a licença, ou decidir renovar', P),
           T('Revisar o contrato de tecnologia, licença ou dados e a segurança', 'GOV'),
           T('Conferir o custo e o orçamento', 'GES'),
           D('A contratação foi aprovada?', P,
             [S('Sim', 'seg'),
              S('Não', 'E3', via=[T('Rever a escolha com o motivo da recusa', A)])]),
           T('Fazer a compra ou a renovação', 'GES'),
           T('Registrar o fornecedor, a licença, o custo e a data de renovação', R)],
          [('Fornecedor ou licença contratado', ['etapa 4']),
           ('Contrato de tecnologia para guardar', ['Governança'])]),
        E('Registrar e medir o serviço de tecnologia', 'Integração', 'Autômato', 'baixo',
          [('Item resolvido', 'etapa 2'), ('Fornecedor ou licença contratado', 'etapa 3')],
          [T('Registrar o item, o tempo, a causa e o custo', R),
           T('Medir disponibilidade, erros, custo e prazo dos serviços de tecnologia', R)],
          [(REGISTROS, ['Inteligência']),
           ('Item de tecnologia resolvido para quem pediu', ['IT-02']),
           ('Custo de tecnologia por empresa e por círculo', ['Gestão'])]),
    ]))

# ===================================================== JORNADAS PONTA A PONTA
JORNADAS.append(dict(
    code='IT-08',
    nome='Medir e redesenhar as jornadas ponta a ponta e manter o catálogo de jornadas',
    dominio='Tecnologia e jornadas', classe='essencial', onda=2,
    objetivo='Fazer cada jornada ponta a ponta ser medida, ter o gargalo achado com evidência, ser redesenhada com o círculo dono e com os círculos por onde passa, ter o redesenho decidido pelo líder do círculo dono e conferido pela Governança quando mexe em alçada, regra ou contrato, ser implantada e ter o ganho conferido; e manter o catálogo de jornadas, etapas e tarefas íntegro e versionado. A Integração mede, propõe e implanta; o líder do círculo dono decide.',
    frequencia='A cada ciclo de melhoria (cadência: trimestral) e por evento: recomendação de melhoria, lacuna de execução ou mudança aprovada em outra jornada',
    automacao=('alta', 'Medir, achar o gargalo, versionar o catálogo e conferir o ganho são de agente e automação; propor o redesenho é de pessoa da Integração; decidir é do líder do círculo dono.'),
    base=['apqc'],
    lanes=['INT', 'IDE', 'GOV', 'LCI', P, A, R],
    inicios=[I('Ciclo de melhoria das jornadas iniciado', R, 'timer'),
             I('Capacidade do redesenho não criada', R, 'message'),
             I('Recomendação de melhoria recebida', 'INT', 'message'),
             I('Lacunas de execução apontadas recebidas', 'IDE', 'message'),
             I('Projeto do redesenho entregue', R, 'message')],
    fins=[F('Jornada redesenhada, implantada e com o ganho conferido', R),
          F('Redesenho não aprovado, com o motivo', R),
          F('Jornada sem gargalo que justifique mudança', R),
          F('Redesenho à espera do projeto', R),
          F('Redesenho sem a capacidade pedida, com o motivo', R)],
    etapas=[
        E('Medir a jornada e achar o gargalo', 'Integração, com a Inteligência', 'Copiloto', 'baixo',
          [(PAINEL, 'Inteligência'), (RECOMENDACAO, 'Inteligência'), (LACUNAS_EXEC, 'Identidade'), (CX, 'Relações'),
           ('Entrega do projeto a quem o pediu', 'IT-01'), ('Capacidade não criada, com o motivo', 'IT-05')],
          [D('O que abriu o trabalho?', R,
             [S('Ciclo, recomendação ou lacuna', 'seg'),
              S('Entrega do projeto de um redesenho aprovado', 'E3', via=[T('Retomar o redesenho com a entrega do projeto', R)]),
              S('Capacidade pedida pelo redesenho não foi criada', 'F5',
                via=[T('Suspender o projeto do redesenho e avisar o líder do círculo dono, com o motivo', R)])]),
           T('Propor as jornadas do ciclo pela recomendação, pela lacuna e pelos indicadores', A),
           T('Decidir as jornadas do ciclo', P),
           T('Medir volume, custo, qualidade, tempo e resultado da jornada', R),
           T('Analisar tempos, filas e retrabalho e apontar o gargalo, com a causa provável', A),
           D('Há gargalo que justifica mudar a jornada?', A,
             [S('Sim', 'prox'),
              S('Não', 'F3', via=[T('Registrar a medida da jornada e responder a quem recomendou', R)])])],
          [('Gargalo da jornada, com evidência', ['etapa 2']),
           ('Projeto suspenso ou encerrado por outra jornada', ['IT-01'])]),
        E('Redesenhar a jornada com o círculo dono', 'Integração; decide o líder do círculo dono', 'Assistido', 'médio',
          [('Gargalo da jornada, com evidência', 'etapa 1'), (ALCADAS, 'Governança')],
          [T('Propor o redesenho: etapas, tarefas, executores, entradas e saídas e o ganho esperado', P),
           T('Montar o fluxo do redesenho e conferir as trocas com os outros círculos', A),
           D('O redesenho mexe em alçada, regra ou contrato?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o redesenho contra as alçadas, as regras e os contratos', 'GOV')])]),
           T('Confirmar a parte do redesenho que passa por cada círculo afetado', 'LCI'),
           T('Decidir o redesenho da jornada do seu círculo', 'LCI'),
           D('O líder do círculo dono aprovou o redesenho?', P,
             [S('Sim', 'prox'),
              S('Não, ajustar', 'E2'),
              S('Não: fica como está', 'F2', via=[T('Registrar o motivo e responder a quem recomendou', R)])])],
          [('Redesenho aprovado', ['etapa 3'])]),
        E('Implantar o redesenho e atualizar o catálogo de jornadas', 'Integração', 'Autômato', 'baixo',
          [('Redesenho aprovado', 'etapa 2')],
          [D('O redesenho pede capacidade, agente, sistema ou projeto ainda não entregue?', R,
             [S('Não, ou o projeto já foi entregue', 'seg'),
              S('Sim', 'F4', via=[T('Abrir o projeto do redesenho e pedir a capacidade, o agente ou a mudança em sistema', R)])]),
           T('Versionar a jornada no catálogo e refazer as ligações com etapas, tarefas e donos', R),
           T('Avisar os círculos por onde a jornada passa', R)],
          [(PROJETO, ['IT-01']),
           ('Redesenho que pede capacidade nova ou mudada', ['IT-05']),
           (PED_ACESSO, ['IT-07']),
           ('Catálogo de jornadas atualizado', [TODOS]),
           ('Jornada implantada', ['etapa 4'])]),
        E('Conferir o ganho do redesenho', 'Integração, com a Inteligência', 'Copiloto', 'baixo',
          [('Jornada implantada', 'etapa 3'), (PAINEL, 'Inteligência')],
          [T('Medir a jornada depois do redesenho e comparar com o ganho esperado', A),
           T('Concluir se o ganho veio e o que aprender', P),
           D('O ganho esperado veio?', P,
             [S('Sim', 'prox', via=[T('Registrar o ganho conferido', R)]),
              S('Não', 'prox', via=[T('Registrar a lição e levar à Inteligência', R)])])],
          [(LICAO_AP, ['Inteligência'])]),
    ]))
