# -*- coding: utf-8 -*-
"""Fonte única do Círculo 1 · Identidade (proposta em debate, 01/10/2026).
Daqui saem: as fichas das jornadas, os fluxos BPMN e os testes de integridade.
"""

# ---------------------------------------------------------------- raias
LANES = {
    'IDP': 'Identidade · pessoa',
    'IDA': 'Identidade · agente',
    'IDR': 'Identidade · automação',
    'EST': 'Estratégia', 'INT': 'Inteligência', 'REL': 'Relações', 'NEG': 'Negócios',
    'ITG': 'Integração', 'OPE': 'Operações', 'GES': 'Gestão', 'GOV': 'Governança',
    'SOC': 'Sócios', 'EXE': 'Executivo da empresa', 'LID': 'Líder da equipe',
    'PES': 'Pessoa', 'SOL': 'Solicitante', 'ASS': 'Assessoria externa',
}
CIRCULOS = ['EST', 'INT', 'REL', 'NEG', 'ITG', 'OPE', 'GES', 'GOV']
PAPEIS = ['SOC', 'EXE', 'LID', 'PES', 'SOL']

# quem pode gerar entrada ou receber saída fora do círculo
PARTES = ['Estratégia', 'Inteligência', 'Relações', 'Negócios', 'Integração', 'Operações',
          'Gestão', 'Governança', 'Sócios', 'Executivos', 'Líderes', 'Pessoas', 'Solicitante',
          'Assessoria externa', 'Todos (pessoas e agentes)']


def T(nome, lane, tipo=None):
    """Tarefa. tipo: user | manual | service | rule | script | call | task"""
    if lane == 'IDP':
        ex, tp = 'P', 'user'
    elif lane == 'IDA':
        ex, tp = 'A', 'service'
    elif lane == 'IDR':
        ex, tp = 'R', 'script'
    elif lane in CIRCULOS:
        ex, tp = 'C', 'task'
    elif lane == 'ASS':
        ex, tp = 'X', 'task'
    else:
        ex, tp = 'H', 'user'      # pessoa fora do círculo: sócio, executivo, líder, pessoa, solicitante
    return {'k': 'T', 'nome': nome, 'lane': lane, 'exec': ex, 'tipo': tipo or tp}


def PAR(*ramos):
    return {'k': 'PAR', 'ramos': [list(r) for r in ramos]}


def S(rotulo, destino, via=None):
    return {'rotulo': rotulo, 'destino': destino, 'via': via or []}


def D(pergunta, lane, saidas):
    return {'k': 'D', 'pergunta': pergunta, 'lane': lane, 'saidas': saidas}


def E(nome, dono, modo, risco, entradas, fluxo, saidas):
    return {'nome': nome, 'dono': dono, 'modo': modo, 'risco': risco,
            'entradas': entradas, 'fluxo': fluxo, 'saidas': saidas}


def I(nome, lane, tipo):
    return {'nome': nome, 'lane': lane, 'tipo': tipo}


def F(nome, lane):
    return {'nome': nome, 'lane': lane}


# nomes de produtos usados em mais de uma jornada (evita erro de digitação)
DECL = 'Declaração de identidade vigente'
PADROES = 'Padrões de identidade vigentes'
PACOTE = 'Pacote de marca publicado'
POSIC = 'Posicionamento e casa de mensagens vigentes'
RELAT = 'Relatório de alinhamento'
LICOES = 'Lições da crise'
DIRECAO = 'Direção estratégica e públicos prioritários'
ALVOS = 'Alvos e resultados do ciclo'
ESCUTA = 'Escuta dos públicos'
REGISTROS = 'Registros de entregas de pessoas e agentes'
REG_USO = 'Registro de pedidos e autorizações de uso'
TODOS = 'Todos (pessoas e agentes)'

JORNADAS = []

# ============================================================ FUNDAMENTO
JORNADAS.append(dict(
    code='ID-01',
    nome='Definir e revisar propósito, visão, missão, princípios e valores',
    dominio='Fundamento', classe='essencial', onda=1,
    objetivo='Manter uma declaração de identidade única, aprovada pelos sócios, que diga o que vale para todo o Ecossistema e o que é próprio de cada empresa.',
    frequencia='Rara: por evento (empresa nova) ou quando o diagnóstico da ID-12 aponta lacuna',
    automacao=('baixa', 'Decisão humana e pouco frequente. O fluxo serve de roteiro, não de automação.'),
    base=['collins', 'iso37000', 'quinn', 'apqc'],
    lanes=['EST', 'SOC', 'GOV', 'EXE', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pedido de identidade para empresa nova recebido', 'EST', 'message'),
             I('Lacuna de identidade apontada', 'IDR', 'message')],
    fins=[F('Declaração aprovada e publicada', 'IDR'), F('Revisão encerrada sem mudança', 'IDP')],
    etapas=[
        E('Reunir evidências', 'Identidade', 'Copiloto', 'médio',
          [(RELAT, 'ID-12'), (DIRECAO, 'Estratégia'), (ESCUTA, 'Relações'),
           ('Pedido de identidade para empresa nova', 'Estratégia')],
          [T('Consolidar evidências e apontar lacunas', 'IDA'),
           T('Entrevistar sócios, líderes e executivos', 'IDP', 'manual'),
           T('Definir o que precisa mudar na declaração', 'IDP'),
           D('Há mudança a propor?', 'IDP', [S('Sim', 'prox'), S('Não', 'F2')])],
          [('Parecer de revisão', ['etapa 2'])]),
        E('Redigir a proposta de declaração', 'Identidade', 'Copiloto', 'médio',
          [('Parecer de revisão', 'etapa 1')],
          [T('Propor redações alternativas', 'IDA'),
           T('Escolher e ajustar a redação', 'IDP'),
           T('Separar o que é do Ecossistema e o que é de cada empresa', 'IDP')],
          [('Proposta de declaração', ['etapa 3'])]),
        E('Validar com líderes e executivos', 'Identidade, com os executivos', 'Assistido', 'médio',
          [('Proposta de declaração', 'etapa 2')],
          [T('Conduzir a validação com líderes e executivos', 'IDP', 'manual'),
           T('Apontar objeções e ajustes', 'EXE'),
           T('Consolidar objeções e ajustes', 'IDA'),
           D('Há objeção que muda a proposta?', 'IDP', [S('Não', 'prox'), S('Sim', 'E2')])],
          [('Proposta validada', ['etapa 4'])]),
        E('Aprovar com os sócios', 'Governança', 'Assistido', 'alto',
          [('Proposta validada', 'etapa 3')],
          [T('Levar a proposta à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a declaração', 'SOC', 'manual'),
           D('Declaração aprovada?', 'SOC', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Decisão dos sócios registrada', ['etapa 5', 'Governança'])]),
        E('Publicar a versão e avisar quem depende dela', 'Identidade', 'Autopiloto', 'baixo',
          [('Decisão dos sócios registrada', 'etapa 4')],
          [T('Registrar a versão e a data de vigência', 'IDR'),
           T('Listar padrões, materiais e agentes afetados', 'IDA'),
           T('Avisar os donos afetados', 'IDR')],
          [(DECL, [TODOS, 'ID-02', 'ID-03', 'ID-08', 'ID-12', 'ID-13']),
           ('Lista de padrões e materiais afetados', ['ID-02']),
           ('Mudança na declaração a comunicar', ['ID-09'])]),
    ]))

JORNADAS.append(dict(
    code='ID-02',
    nome='Transformar a identidade em regras práticas para pessoas e agentes',
    dominio='Fundamento', classe='essencial', onda=1,
    objetivo='Converter a declaração em padrões que qualquer pessoa ou agente aplica sem consultar o fundador: critérios de decisão, comportamentos por valor, perfil de pessoa, rituais, protocolo de crise, guia de voz, persona dos agentes e casos de teste.',
    frequencia='Por evento: nova versão da declaração, agente ou canal novo, padrão ambíguo',
    automacao=('média', 'A redação é de copiloto; a publicação e a carga nos agentes são automáticas.'),
    base=['mckinsey', 'nng', 'google_persona', 'dmn', 'iso37000'],
    lanes=['SOC', 'ITG', 'GOV', 'GES', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Padrão pedido para agente ou canal novo', 'ITG', 'message'),
             I('Padrão ambíguo apontado pela auditoria', 'IDA', 'message'),
             I('Nova versão da declaração publicada', 'IDR', 'message')],
    fins=[F('Padrões publicados e implantados', 'IDR')],
    etapas=[
        E('Delimitar o que precisa de padrão', 'Identidade', 'Copiloto', 'baixo',
          [(DECL, 'ID-01'), ('Lista de padrões e materiais afetados', 'ID-01'),
           ('Padrão ambíguo apontado', 'ID-11'), (LICOES, 'ID-10'),
           ('Pedido de padrão para agente ou canal novo', 'Integração')],
          [T('Comparar a declaração com os padrões vigentes e listar o que muda', 'IDA'),
           T('Priorizar o que será escrito agora', 'IDP')],
          [('Escopo de padrões a escrever', ['etapa 2'])]),
        E('Escrever os padrões em três frentes paralelas', 'Identidade, com Governança, Gestão e Integração', 'Copiloto', 'alto',
          [('Escopo de padrões a escrever', 'etapa 1'), ('Regras e alçadas vigentes', 'Governança')],
          [PAR(
              [T('Rascunhar os critérios de decisão em forma de tabela', 'IDA'),
               T('Conferir os critérios com alçadas e regras', 'GOV'),
               T('Decidir os critérios e as exceções', 'IDP')],
              [T('Rascunhar comportamentos por valor, perfil de pessoa, rituais e protocolo de crise', 'IDA'),
               T('Conferir o uso em seleção, avaliação e reconhecimento', 'GES'),
               T('Validar os comportamentos com os líderes', 'IDP', 'manual')],
              [T('Rascunhar o guia de voz e a persona dos agentes', 'IDA'),
               T('Conferir a viabilidade nos agentes', 'ITG'),
               T('Aprovar voz, persona e limites dos agentes', 'IDP')])],
          [('Padrões redigidos', ['etapa 3'])]),
        E('Testar os padrões em casos reais', 'Identidade, com os sócios', 'Copiloto', 'alto',
          [('Padrões redigidos', 'etapa 2'), (REGISTROS, 'Integração')],
          [T('Aplicar os padrões a uma amostra de casos passados', 'IDA'),
           T('Julgar os casos de fronteira nos testes', 'IDP'),
           D('Os padrões separam o certo do errado?', 'IDP', [S('Sim', 'seg'), S('Não', 'E2')]),
           D('Mudou critério de decisão ou limite de agente?', 'IDP',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Aprovar os critérios e os limites novos', 'SOC', 'manual')])])],
          [('Padrões testados e casos de teste', ['etapa 4'])]),
        E('Publicar e implantar', 'Identidade, com Integração e Gestão', 'Autopiloto', 'baixo',
          [('Padrões testados e casos de teste', 'etapa 3')],
          [T('Versionar os padrões no catálogo', 'IDR'),
           T('Carregar padrões e casos de teste nos agentes', 'ITG'),
           T('Incorporar comportamentos e perfil nos instrumentos de pessoas', 'GES'),
           T('Marcar como vencidos os materiais afetados e pedir a atualização', 'IDR'),
           T('Avisar pessoas e donos de agentes', 'IDR')],
          [(PADROES, [TODOS, 'ID-03', 'ID-04', 'ID-05', 'ID-06', 'ID-07', 'ID-09', 'ID-10', 'ID-11',
                      'Integração', 'Gestão', 'Governança', 'Relações']),
           ('Pedidos de atualização de materiais vencidos', ['ID-04']),
           ('Mudança nos padrões a comunicar', ['ID-09'])]),
    ]))

# ================================================================= MARCA
JORNADAS.append(dict(
    code='ID-03',
    nome='Criar ou rever e registrar a marca de uma empresa, oferta ou projeto',
    dominio='Marca', classe='essencial', onda=2,
    objetivo='Decidir se o negócio novo usa uma marca existente ou ganha marca própria e, quando ganha, entregá-la criada, protegida e pronta para uso por pessoas e agentes. Vale também para a revisão de uma marca existente.',
    frequencia='Por evento: empresa, oferta ou projeto novo',
    automacao=('média', 'Pesquisa, alternativas e pacote são de agente; arquitetura, nome e registro são decisão humana.'),
    base=['aaker', 'wheeler', 'inpi', 'apqc'],
    lanes=['SOL', 'EST', 'EXE', 'ASS', 'GOV', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pedido de marca recebido', 'SOL', 'message')],
    fins=[F('Marca pronta para uso', 'IDR')],
    etapas=[
        E('Entender o pedido e pesquisar público, concorrentes e marcas', 'Identidade', 'Copiloto', 'baixo',
          [('Pedido de marca', 'Solicitante'), ('Posicionamento da oferta e público-alvo', 'Inteligência'),
           (PACOTE, 'ID-03'), (DECL, 'ID-01'), (POSIC, 'ID-08'), (PADROES, 'ID-02')],
          [T('Fechar o briefing com quem pediu', 'IDP'),
           T('Pesquisar público, concorrentes e marcas do portfólio', 'IDA')],
          [('Briefing e pesquisa de marca', ['etapa 2'])]),
        E('Decidir se o negócio usa marca existente ou ganha marca própria', 'Identidade, com Estratégia e o executivo', 'Copiloto', 'alto',
          [('Briefing e pesquisa de marca', 'etapa 1'), (DIRECAO, 'Estratégia')],
          [T('Aplicar os critérios de escolha entre marca existente e marca própria e recomendar', 'IDA'),
           T('Avaliar a recomendação à luz do portfólio', 'EST'),
           T('Decidir com o executivo o papel da marca', 'IDP'),
           D('Que marca o negócio terá?', 'IDP',
             [S('Marca nova', 'prox'), S('Marca existente', 'E6'), S('Revisão da marca atual', 'E4')])],
          [('Decisão sobre a marca do negócio', ['etapa 3', 'etapa 4', 'etapa 6', 'Estratégia', 'Solicitante'])]),
        E('Definir a essência da marca e o nome', 'Identidade, com assessoria de propriedade intelectual', 'Copiloto', 'médio',
          [('Decisão sobre a marca do negócio', 'etapa 2')],
          [T('Gerar a essência da marca e nomes candidatos', 'IDA'),
           T('Verificar no INPI se já existe marca igual ou parecida e se os domínios estão livres', 'IDA'),
           T('Avaliar o risco de registro dos nomes', 'ASS'),
           T('Escolher o nome com o executivo', 'IDP'),
           D('Nome livre e aprovado?', 'IDP',
             [S('Sim', 'prox', via=[T('Reservar os domínios do nome aprovado', 'IDR')]), S('Não', 'E3')])],
          [('Essência da marca e nome aprovado', ['etapa 4'])]),
        E('Desenhar a identidade visual e verbal', 'Identidade', 'Copiloto', 'médio',
          [('Essência da marca e nome aprovado', 'etapa 3'), ('Decisão sobre a marca do negócio', 'etapa 2')],
          [T('Gerar alternativas de identidade visual e verbal', 'IDA'),
           T('Refinar as alternativas', 'IDP'),
           T('Escolher a identidade', 'EXE'),
           D('Identidade aprovada?', 'EXE', [S('Sim', 'prox'), S('Não', 'E4')])],
          [('Identidade visual e verbal aprovada', ['etapa 5'])]),
        E('Proteger a marca', 'Identidade e Governança', 'Copiloto', 'alto',
          [('Identidade visual e verbal aprovada', 'etapa 4')],
          [T('Decidir o que proteger: tipo de marca, classes e domínios', 'IDP'),
           T('Registrar os perfis da marca', 'IDR'),
           T('Depositar o pedido de registro no INPI', 'GOV'),
           T('Assumir os prazos de acompanhamento e renovação', 'GOV')],
          [('Pedido de registro depositado e prazos', ['etapa 6', 'Governança'])]),
        E('Montar o pacote de marca', 'Identidade', 'Copiloto', 'baixo',
          [('Decisão sobre a marca do negócio', 'etapa 2'),
           ('Pedido de registro depositado e prazos', 'etapa 5')],
          [T('Montar manual, modelos e arquivos para pessoas e agentes', 'IDA'),
           T('Conferir o pacote contra o padrão', 'IDR', 'rule'),
           T('Revisar o pacote', 'IDP')],
          [('Pacote de marca', ['etapa 7'])]),
        E('Publicar e entregar', 'Identidade', 'Autômato', 'baixo',
          [('Pacote de marca', 'etapa 6')],
          [T('Publicar no repositório de marca', 'IDR'),
           T('Avisar quem pediu, Relações, Negócios e Integração', 'IDR')],
          [(PACOTE, ['Solicitante', 'Relações', 'Negócios', 'Integração', 'ID-03', 'ID-04'])]),
    ]))

JORNADAS.append(dict(
    code='ID-04',
    nome='Atender pedidos de material de marca e de autorização de uso',
    dominio='Marca', classe='essencial', onda=1,
    objetivo='Entregar rápido e dentro do padrão qualquer material de marca pedido, e controlar quem de fora pode usar as marcas.',
    frequencia='Contínua',
    automacao=('alta', 'Volume alto e regra clara: classificar, produzir, conferir e entregar rodam sem pessoa; a pessoa entra em material de grande alcance e em caso fora da regra.'),
    base=['wheeler', 'dmn'],
    lanes=['SOL', 'GOV', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pedido de material ou de uso da marca recebido', 'SOL', 'message'),
             I('Material vencido ou autorização a vencer', 'IDR', 'timer')],
    fins=[F('Pedido atendido', 'IDR'), F('Pedido negado com motivo', 'IDR')],
    etapas=[
        E('Receber e classificar o pedido', 'Identidade', 'Autopiloto', 'baixo',
          [('Pedido de material ou de uso da marca', 'Solicitante'),
           ('Pedido de uso da marca por parceiro', 'Relações'),
           ('Pedidos de atualização de materiais vencidos', 'ID-02'),
           (PACOTE, 'ID-03'), (PADROES, 'ID-02'), (POSIC, 'ID-08')],
          [T('Registrar o pedido', 'IDR'),
           T('Classificar o pedido e procurar material existente', 'IDA'),
           D('Qual é o tipo de pedido?', 'IDA',
             [S('Material novo ou adaptação', 'prox'), S('Material existente atende', 'E4'),
              S('Uso por terceiro', 'E3')])],
          [('Pedido classificado', ['etapa 2', 'etapa 3', 'etapa 4'])]),
        E('Produzir o material no padrão', 'Identidade', 'Autopiloto', 'baixo',
          [('Pedido classificado', 'etapa 1')],
          [T('Produzir o material', 'IDA'),
           T('Conferir marca, voz e mensagens do material', 'IDA'),
           D('Material conforme o padrão?', 'IDA',
             [S('Sim', 'seg'), S('Não', 'E4', via=[T('Corrigir o material reprovado', 'IDP')])]),
           D('Material de grande alcance ou aplicação nova?', 'IDR',
             [S('Não', 'E4'), S('Sim', 'E4', via=[T('Revisar e aprovar o material de grande alcance', 'IDP')])])],
          [('Material aprovado', ['etapa 4'])]),
        E('Avaliar o uso por terceiro', 'Identidade, com Governança', 'Autopiloto', 'médio',
          [('Pedido classificado', 'etapa 1'), ('Contrato ou parceria vigente com o terceiro', 'Governança')],
          [T('Aplicar a regra de uso por terceiros', 'IDR', 'rule'),
           D('A regra resolve o caso?', 'IDR',
             [S('Sim', 'seg'), S('Não', 'seg', via=[T('Decidir o caso fora da regra', 'IDP')])]),
           D('Uso autorizado?', 'IDR',
             [S('Sim', 'prox', via=[T('Emitir o termo de uso com validade', 'GOV', 'call')]),
              S('Não', 'F2', via=[T('Informar a negativa com o motivo', 'IDR')])])],
          [('Termo de uso da marca', ['etapa 4', 'Solicitante', 'Relações']),
           ('Negativa com motivo', ['Solicitante'])]),
        E('Entregar e registrar', 'Identidade', 'Autômato', 'baixo',
          [('Pedido classificado', 'etapa 1'), ('Material aprovado', 'etapa 2'),
           ('Termo de uso da marca', 'etapa 3')],
          [T('Entregar ao solicitante e publicar no repositório', 'IDR'),
           T('Registrar o pedido e a validade da autorização', 'IDR')],
          [('Material de marca entregue', ['Solicitante']),
           (REG_USO, ['ID-10', 'ID-11'])]),
    ]))

# =============================================================== CULTURA
JORNADAS.append(dict(
    code='ID-05',
    nome='Integrar pessoas novas à cultura',
    dominio='Cultura', classe='essencial', onda=1,
    objetivo='Fazer cada pessoa nova entender o propósito, os valores e os comportamentos esperados, e sentir-se parte, antes de responder sozinha pelo seu papel.',
    frequencia='Por evento: contratação, mudança de papel ou empresa incorporada',
    automacao=('alta', 'A trilha, a verificação e os registros rodam com agente e automação; a conversa com o líder continua humana.'),
    base=['apqc', 'mckinsey', 'schein'],
    lanes=['EST', 'GES', 'LID', 'PES', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Pessoa contratada ou que mudou de papel', 'GES', 'message'),
             I('Empresa incorporada com pessoas a integrar', 'EST', 'message')],
    fins=[F('Pessoa integrada à cultura', 'IDR'), F('Pessoa não integrada: caso devolvido à Gestão', 'IDR')],
    etapas=[
        E('Preparar a trilha de integração', 'Identidade', 'Autopiloto', 'baixo',
          [('Aviso de pessoa contratada ou que mudou de papel, com papel e líder', 'Gestão'),
           ('Lista de pessoas da empresa incorporada', 'Estratégia'), (PADROES, 'ID-02')],
          [T('Abrir a integração e agendar os marcos', 'IDR'),
           T('Montar a trilha conforme o papel', 'IDA')],
          [('Trilha de integração', ['etapa 2', 'Pessoas', 'Líderes'])]),
        E('Apresentar propósito, valores e comportamentos', 'Identidade, com o líder', 'Copiloto', 'baixo',
          [('Trilha de integração', 'etapa 1')],
          [T('Conduzir a trilha e tirar dúvidas', 'IDA'),
           T('Conversar sobre como os valores aparecem no dia a dia da função', 'LID', 'manual'),
           T('Concluir a trilha', 'PES')],
          [('Trilha concluída', ['etapa 3'])]),
        E('Conectar a pessoa à comunidade', 'Líder da equipe', 'Assistido', 'baixo',
          [('Trilha concluída', 'etapa 2')],
          [T('Indicar um padrinho ou uma madrinha', 'LID'),
           T('Participar do primeiro ritual', 'PES', 'manual')],
          [('Vínculos iniciais registrados', ['etapa 4'])]),
        E('Verificar a integração', 'Identidade, com o líder', 'Copiloto', 'médio',
          [('Vínculos iniciais registrados', 'etapa 3')],
          [T('Aplicar a verificação de entendimento e de pertencimento', 'IDA'),
           T('Confirmar os comportamentos observados', 'LID'),
           D('Pessoa integrada?', 'LID',
             [S('Sim', 'prox'),
              S('Não, na primeira verificação', 'E2', via=[T('Combinar o reforço com o líder', 'IDP')]),
              S('Não, depois do reforço', 'F2', via=[T('Avisar a Gestão de que a pessoa não se integrou', 'IDR')])])],
          [('Resultado da verificação', ['etapa 5']),
           ('Pessoa não integrada', ['Gestão'])]),
        E('Registrar a conclusão e avisar a Gestão e o líder', 'Identidade', 'Autômato', 'baixo',
          [('Resultado da verificação', 'etapa 4')],
          [T('Registrar a conclusão e avisar Gestão e líder', 'IDR'),
           T('Enviar os dados agregados ao diagnóstico', 'IDR')],
          [('Integração concluída', ['Gestão', 'Líderes']),
           ('Dados de integração', ['ID-12']),
           ('Pessoa integrada', ['ID-07'])]),
    ]))

JORNADAS.append(dict(
    code='ID-06',
    nome='Realizar os rituais de cultura e o reconhecimento de pessoas e equipes',
    dominio='Cultura', classe='essencial', onda=2,
    objetivo='Reforçar, com cadência fixa, os comportamentos que os valores pedem, com reconhecimento baseado em evidência.',
    frequencia='Recorrente: conforme o calendário de rituais',
    automacao=('média', 'Preparação, conferência das indicações e registro são de agente; a decisão e o ritual são de pessoas.'),
    base=['schein', 'mckinsey', 'apqc'],
    lanes=['LID', 'GES', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Prazo de preparação do ritual chegou', 'IDR', 'timer')],
    fins=[F('Ritual realizado e registrado', 'IDR')],
    etapas=[
        E('Preparar o ritual', 'Identidade', 'Autopiloto', 'baixo',
          [(PADROES, 'ID-02'), ('Indicações de reconhecimento', 'Líderes'), (ALVOS, 'Estratégia')],
          [T('Abrir a preparação e colher as indicações', 'IDR'),
           T('Montar o roteiro e o material do ritual', 'IDA')],
          [('Roteiro do ritual e lista de indicações', ['etapa 2'])]),
        E('Avaliar as indicações de reconhecimento', 'Identidade, com os líderes', 'Copiloto', 'médio',
          [('Roteiro do ritual e lista de indicações', 'etapa 1')],
          [T('Conferir cada indicação com os critérios', 'IDA'),
           T('Decidir os reconhecimentos com os líderes', 'IDP'),
           D('Algum reconhecimento envolve recompensa financeira?', 'IDP',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Aprovar e processar a recompensa', 'GES')])])],
          [('Reconhecimentos aprovados', ['etapa 3']),
           ('Retorno sobre as indicações', ['Líderes'])]),
        E('Realizar o ritual', 'Líder da equipe, com a Identidade', 'Assistido', 'baixo',
          [('Reconhecimentos aprovados', 'etapa 2')],
          [T('Conduzir o ritual', 'LID', 'manual'),
           T('Apoiar a condução e registrar as histórias', 'IDP')],
          [('Histórias registradas', ['etapa 4'])]),
        E('Comunicar e registrar', 'Identidade', 'Autopiloto', 'baixo',
          [('Histórias registradas', 'etapa 3')],
          [T('Selecionar as histórias e os reconhecimentos a comunicar', 'IDA'),
           T('Registrar participação e reconhecimentos', 'IDR')],
          [('Histórias e reconhecimentos a comunicar', ['ID-09']),
           ('Registro de participação em rituais', ['ID-12']),
           ('Reconhecimentos concedidos', ['Gestão'])]),
    ]))

JORNADAS.append(dict(
    code='ID-07',
    nome='Ajudar cada pessoa a ligar o seu propósito ao seu papel',
    dominio='Cultura', classe='recomendada', onda=3,
    objetivo='Dar a cada pessoa que quiser um propósito pessoal declarado, ligado ao seu papel e a um plano de desenvolvimento. A participação é voluntária, a declaração fica com a pessoa e ela escolhe o que compartilha.',
    frequencia='Por evento (pessoa integrada, mudança de papel) e a cada ciclo de desenvolvimento',
    automacao=('média', 'O agente guia a reflexão e propõe o plano; a conversa entre pessoa e líder é humana.'),
    base=['craig', 'quinn'],
    lanes=['GES', 'LID', 'PES', 'IDA', 'IDR'],
    inicios=[I('Ciclo de desenvolvimento aberto', 'GES', 'message'),
             I('Pessoa integrada à cultura', 'IDR', 'message')],
    fins=[F('Plano de propósito registrado', 'IDR'), F('Pessoa optou por não participar', 'PES')],
    etapas=[
        E('Convidar a pessoa', 'Identidade', 'Autopiloto', 'baixo',
          [('Pessoa integrada', 'ID-05'), ('Ciclo de desenvolvimento aberto', 'Gestão'), (PADROES, 'ID-02')],
          [T('Convidar a pessoa e explicar que a participação é voluntária', 'IDR'),
           T('Aceitar ou recusar o convite', 'PES'),
           D('Pessoa quer participar?', 'PES', [S('Sim', 'prox'), S('Não', 'F2')])],
          [('Convite aceito', ['etapa 2'])]),
        E('Descobrir o propósito pessoal', 'Pessoa, com o agente', 'Copiloto', 'baixo',
          [('Convite aceito', 'etapa 1')],
          [T('Guiar a reflexão sobre histórias, valores e forças', 'IDA'),
           T('Escrever a declaração de propósito pessoal', 'PES')],
          [('Declaração de propósito pessoal', ['Pessoas']),
           ('Propósito que a pessoa decidiu compartilhar', ['etapa 3'])]),
        E('Ligar o propósito ao papel', 'Pessoa e líder da equipe', 'Assistido', 'médio',
          [('Propósito que a pessoa decidiu compartilhar', 'etapa 2')],
          [T('Conversar com o líder sobre propósito e papel', 'PES', 'manual'),
           D('Pessoa e líder concordam que o papel serve ao propósito?', 'PES',
             [S('Sim', 'prox'), S('Não', 'prox', via=[T('Avaliar ajuste de papel, com o acordo da pessoa', 'GES')])])],
          [('Acordo sobre propósito e papel', ['etapa 4']),
           ('Pedido de ajuste de papel', ['Gestão'])]),
        E('Montar o plano de ações ligado ao propósito', 'Pessoa, com o líder', 'Copiloto', 'baixo',
          [('Acordo sobre propósito e papel', 'etapa 3')],
          [T('Propor ações e desenvolvimento a partir do propósito', 'IDA'),
           T('Fechar o plano com o líder', 'PES'),
           T('Registrar o plano no ciclo de desenvolvimento', 'IDR')],
          [('Plano de ações ligado ao propósito', ['Gestão', 'Líderes'])]),
    ]))

# ============================================== REPUTAÇÃO E COMUNICAÇÃO
JORNADAS.append(dict(
    code='ID-08',
    nome='Definir o posicionamento institucional e as mensagens para cada público',
    dominio='Reputação e comunicação', classe='essencial', onda=2,
    objetivo='Definir uma promessa clara e as mensagens principais para cada público, no nível do Ecossistema e de cada empresa, para uso de pessoas e agentes.',
    frequencia='A cada ciclo estratégico e por evento',
    automacao=('média', 'Síntese e redação são de agente; escolha e aprovação são humanas.'),
    base=['apqc', 'hatch'],
    lanes=['EST', 'REL', 'GES', 'ITG', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Direção estratégica do ciclo aprovada', 'EST', 'message'),
             I('Lacuna de imagem apontada', 'IDP', 'message'),
             I('Nova versão da declaração publicada', 'IDR', 'message')],
    fins=[F('Posicionamento e mensagens publicados', 'IDR')],
    etapas=[
        E('Levantar os insumos', 'Identidade', 'Copiloto', 'baixo',
          [(DECL, 'ID-01'), (DIRECAO, 'Estratégia'), ('Leitura de mercado e concorrentes', 'Inteligência'),
           (RELAT, 'ID-12')],
          [T('Reunir e resumir os insumos', 'IDA'),
           T('Definir os públicos e as perguntas a responder', 'IDP')],
          [('Síntese de insumos', ['etapa 2'])]),
        E('Formular o posicionamento e a promessa por público', 'Identidade', 'Copiloto', 'médio',
          [('Síntese de insumos', 'etapa 1')],
          [T('Propor posicionamento e promessa para cada público', 'IDA'),
           T('Separar o que é do Ecossistema e o que é de cada empresa', 'IDP'),
           T('Escolher e ajustar a proposta', 'IDP')],
          [('Proposta de posicionamento', ['etapa 3'])]),
        E('Validar o posicionamento com Estratégia, Relações, Gestão e executivos', 'Identidade, com Estratégia, Relações e Gestão', 'Assistido', 'médio',
          [('Proposta de posicionamento', 'etapa 2')],
          [PAR([T('Conferir a coerência com a estratégia', 'EST')],
               [T('Conferir o uso em marketing e relacionamento', 'REL')],
               [T('Conferir a promessa para pessoas', 'GES')]),
           T('Fechar o posicionamento com os executivos', 'IDP', 'manual'),
           D('Posicionamento aprovado?', 'IDP', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Posicionamento aprovado', ['etapa 4'])]),
        E('Montar as mensagens principais e a narrativa por público', 'Identidade', 'Copiloto', 'médio',
          [('Posicionamento aprovado', 'etapa 3')],
          [T('Redigir mensagens-chave, provas e narrativa por público', 'IDA'),
           T('Revisar e aprovar as mensagens', 'IDP')],
          [('Casa de mensagens e narrativa', ['etapa 5'])]),
        E('Publicar e preparar os porta-vozes', 'Identidade, com Integração', 'Copiloto', 'baixo',
          [('Casa de mensagens e narrativa', 'etapa 4')],
          [T('Publicar no repositório e avisar os círculos', 'IDR'),
           T('Carregar as mensagens nos agentes que falam com os públicos', 'ITG'),
           T('Preparar os porta-vozes', 'IDP', 'manual')],
          [(POSIC, ['Relações', 'Negócios', 'Gestão', 'Integração', 'ID-03', 'ID-04', 'ID-09', 'ID-10', 'ID-11', 'ID-12'])]),
    ]))

JORNADAS.append(dict(
    code='ID-09',
    nome='Planejar e publicar a comunicação interna e institucional',
    dominio='Reputação e comunicação', classe='essencial', onda=2,
    objetivo='Manter as pessoas informadas e alinhadas e comunicar os fatos importantes com uma só voz, dentro e fora do Ecossistema.',
    frequencia='Contínua: ciclo de pauta e fatos importantes',
    automacao=('alta', 'Pauta, redação, conferência, publicação e medição rodam com agente e automação; a pessoa decide a pauta e aprova o que é sensível.'),
    base=['apqc'],
    lanes=['GOV', 'REL', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Fato importante a comunicar recebido', 'IDA', 'message'),
             I('Ciclo de pauta iniciado', 'IDR', 'timer')],
    fins=[F('Comunicação publicada e medida', 'IDR')],
    etapas=[
        E('Planejar a pauta', 'Identidade', 'Copiloto', 'baixo',
          [('Decisões e fatos a comunicar', 'Governança'), (ALVOS, 'Estratégia'),
           ('Fatos de pessoas a comunicar', 'Gestão'), ('Fatos de negócios a comunicar', 'Negócios'),
           ('Fatos de entregas a comunicar', 'Operações'),
           ('Histórias e reconhecimentos a comunicar', 'ID-06'),
           ('Mudança na declaração a comunicar', 'ID-01'), ('Mudança nos padrões a comunicar', 'ID-02'),
           ('Plano de correção aprovado', 'ID-12'), ('Relato de impacto publicado', 'ID-13'),
           (POSIC, 'ID-08'), (PADROES, 'ID-02'), ('Medição da comunicação', 'etapa 4')],
          [T('Propor pauta e calendário a partir dos fatos', 'IDA'),
           T('Decidir pauta, público, canal e o que é sensível', 'IDP')],
          [('Pauta e calendário aprovados', ['etapa 2'])]),
        E('Produzir o conteúdo', 'Identidade', 'Autopiloto', 'baixo',
          [('Pauta e calendário aprovados', 'etapa 1')],
          [T('Redigir o conteúdo na voz do Ecossistema', 'IDA'),
           T('Conferir o conteúdo com o guia de voz e as mensagens', 'IDA'),
           D('Conteúdo conforme o padrão?', 'IDA',
             [S('Sim', 'seg'), S('Não', 'seg', via=[T('Corrigir o conteúdo reprovado', 'IDP')])]),
           D('Pauta marcada como sensível?', 'IDR',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Validar o conteúdo sensível', 'GOV')])]),
           D('Conteúdo sensível ou para público externo?', 'IDR',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Aprovar o conteúdo', 'IDP')])])],
          [('Conteúdo aprovado', ['etapa 3'])]),
        E('Publicar nos canais', 'Identidade, com Relações', 'Autopiloto', 'baixo',
          [('Conteúdo aprovado', 'etapa 2')],
          [T('Publicar nos canais internos', 'IDR'),
           D('Vai para públicos externos?', 'IDR',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Publicar nos canais externos', 'REL')])])],
          [('Comunicação publicada', ['etapa 4', 'Pessoas', 'Relações'])]),
        E('Medir e registrar', 'Identidade', 'Autopiloto', 'baixo',
          [('Comunicação publicada', 'etapa 3')],
          [T('Medir alcance e entendimento', 'IDA'),
           T('Registrar a medição para o próximo ciclo', 'IDR')],
          [('Medição da comunicação', ['etapa 1', 'ID-12'])]),
    ]))

JORNADAS.append(dict(
    code='ID-10',
    nome='Monitorar a reputação e responder a incidentes e crises',
    dominio='Reputação e comunicação', classe='essencial', onda=1,
    objetivo='Detectar cedo o que ameaça a reputação, encaminhar ao dono e, em crise, responder com fatos, uma só voz e reparação.',
    frequencia='Contínua no monitoramento; rara na crise',
    automacao=('alta no monitoramento, baixa na crise', 'Detectar e propor a gravidade rodam sem pessoa; o que não é claramente baixo passa por uma pessoa. Crise é decisão humana de risco alto. Sinal que cresce depois entra de novo como sinal.'),
    base=['iso22361', 'reptrak', 'apqc'],
    lanes=['SOC', 'EXE', 'GOV', 'ASS', 'REL', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Incidente relatado', 'EXE', 'message'),
             I('Sinal de reputação detectado', 'IDA', 'signal')],
    fins=[F('Sinal registrado sem ação', 'IDR'), F('Sinal encaminhado ao dono', 'IDR'),
          F('Crise encerrada com lições registradas', 'IDR')],
    etapas=[
        E('Detectar e classificar o sinal', 'Identidade', 'Copiloto', 'médio',
          [('Menções, notícias e reclamações públicas', 'Relações'),
           ('Incidente relatado', 'Executivos'), ('Incidente de entrega relatado', 'Operações'),
           ('Incidente com agente relatado', 'Integração'),
           (REG_USO, 'ID-04'), (POSIC, 'ID-08'), (PADROES, 'ID-02')],
          [T('Reunir o sinal e o contexto', 'IDA'),
           T('Propor a gravidade pelo protocolo de crise', 'IDA'),
           D('A gravidade proposta é baixa e clara?', 'IDA',
             [S('Não', 'seg'), S('Sim', 'F1', via=[T('Registrar o sinal', 'IDR')])]),
           T('Confirmar a gravidade e o dono do sinal', 'IDP'),
           D('É crise?', 'IDP',
             [S('Sim', 'prox'), S('Não', 'F2', via=[T('Encaminhar o sinal ao dono e pedir retorno', 'IDR')])])],
          [('Sinal classificado', ['etapa 2']),
           ('Sinal encaminhado', ['Relações', 'Governança', 'Operações'])]),
        E('Acionar o comitê e apurar os fatos', 'Identidade, com o executivo', 'Copiloto', 'alto',
          [('Sinal classificado', 'etapa 1'), ('Fatos da área envolvida', 'Executivos')],
          [T('Convocar o comitê de crise', 'IDR'),
           T('Reunir fatos, cronologia e repercussão', 'IDA'),
           T('Confirmar os fatos com a área envolvida', 'EXE')],
          [('Relato de fatos', ['etapa 3'])]),
        E('Decidir a posição e o porta-voz', 'Executivo ou sócios, com Governança e Identidade', 'Assistido', 'alto',
          [('Relato de fatos', 'etapa 2')],
          [T('Orientar sobre riscos jurídicos e de imagem', 'ASS'),
           T('Avaliar os riscos jurídicos da posição', 'GOV'),
           D('A crise envolve o executivo ou mais de uma empresa?', 'GOV',
             [S('Não', 'prox', via=[T('Decidir a posição, a reparação e o porta-voz', 'EXE', 'manual')]),
              S('Sim', 'prox', via=[T('Decidir a posição, a reparação e o porta-voz pelos sócios', 'SOC', 'manual')])])],
          [('Posição oficial e porta-voz', ['etapa 4'])]),
        E('Comunicar aos públicos', 'Identidade, com Relações', 'Copiloto', 'alto',
          [('Posição oficial e porta-voz', 'etapa 3')],
          [T('Redigir os comunicados por público, começando pelos internos', 'IDA'),
           T('Revisar os comunicados e preparar o porta-voz', 'IDP'),
           T('Aprovar os comunicados', 'EXE'),
           T('Publicar o comunicado interno', 'IDR'),
           T('Publicar e atender os públicos externos', 'REL')],
          [('Comunicados de crise', ['etapa 5', 'Pessoas', 'Relações'])]),
        E('Acompanhar e reparar', 'Executivo, com a Identidade', 'Copiloto', 'alto',
          [('Comunicados de crise', 'etapa 4')],
          [T('Acompanhar a repercussão', 'IDA'),
           T('Executar a reparação decidida', 'EXE'),
           D('Crise controlada?', 'EXE', [S('Sim', 'prox'), S('Não', 'E3')])],
          [('Crise controlada', ['etapa 6'])]),
        E('Encerrar e registrar as lições', 'Identidade', 'Copiloto', 'médio',
          [('Crise controlada', 'etapa 5')],
          [T('Conduzir a revisão pós-crise com o comitê', 'IDP', 'manual'),
           T('Registrar e encaminhar as lições', 'IDR')],
          [(LICOES, ['Inteligência', 'Governança', 'ID-02', 'ID-12'])]),
    ]))

# ============================================================ VERIFICAÇÃO
JORNADAS.append(dict(
    code='ID-11',
    nome='Auditar se as entregas de pessoas e agentes seguem a identidade',
    dominio='Verificação', classe='essencial', onda=1,
    objetivo='Medir por amostra se o que sai (propostas, mensagens, conteúdos e decisões) respeita critérios, voz e marca, e corrigir a causa dos desvios.',
    frequencia='Contínua: ciclo de auditoria e reclamações',
    automacao=('alta', 'Sorteio, comparação, roteamento e índice rodam sem pessoa; a pessoa julga só os casos de fronteira e confirma a causa.'),
    base=['iso20671', 'iso10010'],
    lanes=['REL', 'ITG', 'LID', 'GOV', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Reclamação de incoerência recebida', 'REL', 'message'),
             I('Ciclo de auditoria iniciado', 'IDR', 'timer')],
    fins=[F('Índice de coerência publicado', 'IDR')],
    etapas=[
        E('Sortear a amostra', 'Identidade', 'Autômato', 'baixo',
          [(REGISTROS, 'Integração'), ('Propostas enviadas', 'Negócios'),
           ('Conteúdos publicados', 'Relações'), ('Entregas ao cliente', 'Operações'),
           ('Reclamação de incoerência', 'Relações'), (REG_USO, 'ID-04'), (PADROES, 'ID-02'), (POSIC, 'ID-08')],
          [T('Sortear a amostra e incluir os itens reclamados', 'IDR')],
          [('Amostra de entregas', ['etapa 2'])]),
        E('Comparar com os padrões', 'Identidade', 'Autopiloto', 'baixo',
          [('Amostra de entregas', 'etapa 1')],
          [T('Aplicar os padrões e os casos de teste a cada item', 'IDA'),
           T('Separar conformes, desvios e casos de fronteira', 'IDR', 'rule'),
           D('Há desvio ou caso de fronteira?', 'IDR', [S('Sim', 'prox'), S('Não', 'E5')])],
          [('Itens com desvio ou de fronteira', ['etapa 3']),
           ('Resultado da comparação', ['etapa 5'])]),
        E('Julgar os casos e achar a causa', 'Identidade', 'Copiloto', 'médio',
          [('Itens com desvio ou de fronteira', 'etapa 2')],
          [T('Julgar os casos de fronteira', 'IDP'),
           D('Há desvio confirmado?', 'IDP', [S('Sim', 'seg'), S('Não', 'E5')]),
           T('Agrupar os desvios e apontar a causa provável', 'IDA'),
           T('Confirmar a causa de cada grupo', 'IDP')],
          [('Desvios com causa confirmada', ['etapa 4']),
           ('Casos julgados sem desvio', ['etapa 5'])]),
        E('Encaminhar e acompanhar a correção', 'Identidade, com o dono da causa', 'Autopiloto', 'baixo',
          [('Desvios com causa confirmada', 'etapa 3')],
          [T('Pedir a correção ou a retirada do item ao dono da entrega', 'IDR'),
           D('Qual é a causa do grupo de desvios?', 'IDR',
             [S('Agente mal configurado', 'seg', via=[T('Corrigir o agente', 'ITG')]),
              S('Pessoa sem preparo', 'seg', via=[T('Reforçar o preparo da pessoa', 'LID')]),
              S('Indício de conduta proibida', 'seg', via=[T('Tratar o indício de conduta', 'GOV', 'call')]),
              S('Padrão ambíguo', 'seg', via=[T('Abrir a revisão do padrão', 'IDP')]),
              S('Outra causa', 'seg', via=[T('Tratar a causa não prevista', 'IDP')])]),
           T('Registrar o dono e o prazo de cada correção', 'IDR')],
          [('Pedido de correção de agente', ['Integração']),
           ('Pedido de reforço para a pessoa', ['Líderes']),
           ('Indício de conduta proibida', ['Governança']),
           ('Padrão ambíguo apontado', ['ID-02']),
           ('Correções encaminhadas', ['etapa 5'])]),
        E('Publicar o índice e as lições', 'Identidade', 'Autopiloto', 'baixo',
          [('Resultado da comparação', 'etapa 2'), ('Casos julgados sem desvio', 'etapa 3'),
           ('Correções encaminhadas', 'etapa 4')],
          [T('Calcular e publicar o índice de coerência', 'IDR'),
           T('Resumir as lições do ciclo e responder às reclamações', 'IDA')],
          [('Índice de coerência e lições', ['ID-12', 'Inteligência', 'Líderes']),
           ('Resposta à reclamação de incoerência', ['Relações'])]),
    ]))

JORNADAS.append(dict(
    code='ID-12',
    nome='Medir o alinhamento entre identidade, cultura e imagem e planejar a correção das lacunas',
    dominio='Verificação', classe='essencial', onda=2,
    objetivo='Saber com dados onde o que declaramos, o que vivemos e como somos vistos não batem, e ter um plano com dono e alvo para cada lacuna. A execução do plano é acompanhada nos alvos da Estratégia e medida no ciclo seguinte.',
    frequencia='A cada ciclo (sugestão: anual) e após crise, incorporação ou troca de liderança',
    automacao=('média', 'Coleta e cálculo são de agente e automação; interpretação e plano são humanos.'),
    base=['hatch', 'iso10010', 'iso20671', 'reptrak', 'apqc'],
    lanes=['EST', 'INT', 'REL', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Crise, incorporação ou troca de liderança ocorrida', 'IDP', 'message'),
             I('Ciclo de diagnóstico iniciado', 'IDR', 'timer')],
    fins=[F('Plano de correção aprovado e distribuído', 'IDR')],
    etapas=[
        E('Planejar o diagnóstico', 'Identidade, com Inteligência', 'Copiloto', 'baixo',
          [(DECL, 'ID-01'), (POSIC, 'ID-08'), ('Método de pesquisa e amostra', 'Inteligência'),
           ('Índice de coerência e lições', 'ID-11'), ('Dados de integração', 'ID-05'),
           ('Registro de participação em rituais', 'ID-06'), ('Medição da comunicação', 'ID-09'),
           (LICOES, 'ID-10'), ('Relato de impacto publicado', 'ID-13')],
          [T('Propor públicos, instrumentos e amostra', 'IDA'),
           T('Conferir o método e a amostra', 'INT'),
           T('Aprovar o plano do diagnóstico', 'IDP')],
          [('Plano do diagnóstico', ['etapa 2'])]),
        E('Coletar a visão dos sócios, a cultura vivida e a imagem externa', 'Identidade, com Relações', 'Copiloto', 'baixo',
          [('Plano do diagnóstico', 'etapa 1'), ('Percepção dos públicos externos', 'Relações'),
           ('Dados de pessoas: rotatividade, clima e avaliação de comportamentos', 'Gestão')],
          [PAR([T('Aplicar a pesquisa de cultura com as pessoas', 'IDR')],
               [T('Colher a percepção dos públicos externos', 'REL')],
               [T('Ouvir sócios e executivos sobre a visão', 'IDP', 'manual')]),
           T('Consolidar os dados das três leituras', 'IDA')],
          [('Base de dados do diagnóstico', ['etapa 3'])]),
        E('Analisar as lacunas entre visão, cultura e imagem', 'Identidade', 'Copiloto', 'médio',
          [('Base de dados do diagnóstico', 'etapa 2')],
          [T('Calcular as lacunas entre visão, cultura e imagem', 'IDA'),
           T('Interpretar e priorizar as lacunas', 'IDP')],
          [(RELAT, ['etapa 4', 'ID-01', 'ID-08', 'Estratégia', 'Sócios', 'Líderes'])]),
        E('Definir o plano de correção com os donos', 'Identidade, com líderes e executivos', 'Assistido', 'médio',
          [(RELAT, 'etapa 3')],
          [T('Combinar ações, donos e alvos com líderes e executivos', 'IDP', 'manual'),
           D('Que revisão a lacuna principal pede?', 'IDP',
             [S('Nenhuma', 'prox'),
              S('Da declaração', 'prox', via=[T('Abrir a revisão da declaração', 'IDR')]),
              S('Do posicionamento', 'prox', via=[T('Abrir a revisão do posicionamento', 'IDR')])])],
          [('Plano de correção proposto', ['etapa 5'])]),
        E('Incluir o plano nos alvos e distribuir', 'Identidade, com Estratégia', 'Copiloto', 'médio',
          [('Plano de correção proposto', 'etapa 4')],
          [T('Incluir as ações nos alvos e no orçamento do ciclo', 'EST'),
           T('Calcular os indicadores de marca, cultura e reputação', 'IDA'),
           T('Distribuir o plano e publicar os indicadores', 'IDR')],
          [('Plano de correção aprovado', ['Líderes', 'Executivos', 'Estratégia', 'ID-09']),
           ('Indicadores de marca, cultura e reputação', ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='ID-13',
    nome='Apurar e publicar o relato anual de impacto',
    dominio='Verificação', classe='recomendada', onda=3,
    objetivo='Provar com dados o impacto gerado pelo Ecossistema na vida das pessoas e prestar contas aos públicos, incluindo o que não foi alcançado.',
    frequencia='Ciclo anual: temas e indicadores no início; coleta e relato no fim',
    automacao=('média', 'Coleta, análise e redação são de agente; temas, interpretação e aprovação são humanos.'),
    base=['impact', 'pas808', 'iso37000'],
    lanes=['SOC', 'GOV', 'EST', 'INT', 'EXE', 'REL', 'IDP', 'IDA', 'IDR'],
    inicios=[I('Ciclo anual de relato iniciado', 'IDR', 'timer')],
    fins=[F('Relato de impacto publicado', 'IDR')],
    etapas=[
        E('Definir os temas e os indicadores de impacto', 'Identidade, com Estratégia', 'Copiloto', 'médio',
          [(DECL, 'ID-01'), (ALVOS, 'Estratégia'), (ESCUTA, 'Relações')],
          [T('Propor temas e indicadores pelas cinco dimensões de impacto', 'IDA'),
           T('Conferir os temas com os alvos do ciclo', 'EST'),
           T('Decidir temas e indicadores', 'IDP')],
          [('Temas e indicadores de impacto', ['etapa 2'])]),
        E('Coletar os dados', 'Identidade, com Inteligência e os executivos', 'Copiloto', 'baixo',
          [('Temas e indicadores de impacto', 'etapa 1'), ('Indicadores de impacto', 'Inteligência'),
           ('Evidências e casos de impacto', 'Executivos')],
          [PAR([T('Fornecer os indicadores', 'INT')],
               [T('Fornecer evidências e casos da empresa', 'EXE')]),
           T('Consolidar os dados e apontar falhas', 'IDA'),
           D('Dados completos e verificáveis?', 'IDA',
             [S('Sim', 'prox'), S('Não', 'prox', via=[T('Retirar o indicador sem dado ou registrar a ressalva', 'IDP')])])],
          [('Base de dados de impacto', ['etapa 3'])]),
        E('Analisar o impacto', 'Identidade', 'Copiloto', 'médio',
          [('Base de dados de impacto', 'etapa 2')],
          [T('Analisar o que mudou, para quem, quanto, qual foi a nossa contribuição e qual é o risco', 'IDA'),
           T('Interpretar o resultado, incluindo o que não foi alcançado', 'IDP')],
          [('Análise de impacto', ['etapa 4'])]),
        E('Redigir e validar o relato', 'Identidade, com Governança e os sócios', 'Copiloto', 'alto',
          [('Análise de impacto', 'etapa 3')],
          [T('Redigir o relato', 'IDA'),
           T('Conferir os dados e as afirmações', 'GOV'),
           T('Aprovar a publicação', 'SOC', 'manual'),
           D('Relato aprovado?', 'SOC', [S('Sim', 'prox'), S('Não', 'E4')])],
          [('Relato de impacto aprovado', ['etapa 5'])]),
        E('Publicar o relato e levá-lo aos públicos', 'Identidade, com Relações', 'Autopiloto', 'baixo',
          [('Relato de impacto aprovado', 'etapa 4')],
          [T('Publicar o relato', 'IDR'),
           T('Levar o relato aos públicos externos', 'REL')],
          [('Relato de impacto publicado', ['Sócios', 'Relações', 'Estratégia', 'ID-09', 'ID-12'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Fundamento', 'Dizer quem somos e transformar isso em regra aplicável.'),
    ('Marca', 'Criar, proteger e aplicar as marcas do Ecossistema e das empresas.'),
    ('Cultura', 'Fazer os valores virarem comportamento de pessoas.'),
    ('Reputação e comunicação', 'Cuidar do que dizemos e de como somos vistos.'),
    ('Verificação', 'Conferir se o que declaramos é o que praticamos, e provar.'),
]

# ------------------------------------------------------------------ fontes
# conf: como foi conferida nesta sessão (01/10/2026)
FONTES = {
    'apqc': dict(
        ref='APQC, Process Classification Framework (PCF), cross-industry',
        uso='Mostra que os processos de identidade estão espalhados por estratégia (1.1.4, 1.2.1), marketing (3.2.1.2, 3.2.1.4), pessoas (7.1.1.9, 7.3.1.1, 7.5.1, 7.8) e relações externas (categoria 12.0). Não existe categoria de identidade.',
        conf='PDF da versão 7.4 (agosto de 2024) aberto em dois endereços; os elementos das categorias 1, 3 e 7 foram conferidos um a um, por mim e por um revisor independente. A leitura do PDF parou na categoria 9: os grupos de relações externas (12.4, questões legais e éticas; 12.5, relações públicas) só foram vistos em cópia de versão anterior e por isso não são citados pelo número. A versão 8.0 (27/02/2026) foi conferida só nas 13 categorias, na página da coleção de definições da APQC.',
        links=[('PCF 7.4 (PDF, cópia 1)', 'https://www.business-analysis.com.au/wp-content/uploads/2025/04/K014750_APQC-Process-Classification-Framework-PCF-Cross-Industry-PDF-Version-7.4_January-2025.pdf'),
               ('PCF 7.4 (PDF, cópia 2)', 'https://solutions.ifrc.org/sites/default/files/2024-10/K014750_APQC%20Process%20Classification%20Framework%20(PCF)%20-%20Cross%20Industry%20-%20PDF%20Version%207.4.pdf'),
               ('PCF 8.0 (página oficial)', 'https://www.apqc.org/resource-library/resource-listing/apqc-process-classification-framework-pcf-cross-industry-excel-12'),
               ('PCF 8.0, 13 categorias', 'https://www.apqc.org/resource-library/resource-collection/pcf-version-80-process-definitions-and-key-measures-collection'),
               ('cópia de versão anterior', 'https://waleriabueno.wordpress.com/wp-content/uploads/2021/02/apqc-pcf-7.pdf')]),
    'collins': dict(
        ref='Jim Collins e Jerry Porras, Building Your Company’s Vision, Harvard Business Review, set.–out. 1996',
        uso='A visão tem duas partes: ideologia central (valores e propósito) e futuro imaginado. Base da ID-01.',
        conf='Página oficial do artigo aberta; o texto completo é pago, a definição citada está visível.',
        links=[('hbr.org', 'https://hbr.org/1996/09/building-your-companys-vision')]),
    'iso37000': dict(
        ref='ISO 37000:2021, Governance of organizations — Guidance',
        uso='O propósito é o primeiro dos 11 princípios de governança; os valores informam o propósito e o modo de alcançá-lo. Base da aprovação pelos sócios na ID-01.',
        conf='Página do comitê ISO/TC 309 aberta; a norma completa é paga e não foi lida.',
        links=[('committee.iso.org', 'https://committee.iso.org/ISO_37000_Governance')]),
    'pas808': dict(
        ref='BSI, PAS 808:2022, Purpose-driven organizations. Worldviews, principles and behaviours for delivering sustainability. Guide',
        uso='Guia para organizações orientadas a propósito, incluindo prestação de contas aos públicos. Base da ID-13.',
        conf='Página oficial da BSI aberta (publicada em 30/07/2022); o texto completo é pago e não foi lido.',
        links=[('knowledge.bsigroup.com', 'https://knowledge.bsigroup.com/products/purpose-driven-organizations-worldviews-principles-and-behaviours-for-delivering-sustainability-guide')]),
    'quinn': dict(
        ref='Robert Quinn e Anjan Thakor, Creating a Purpose-Driven Organization, Harvard Business Review, jul.–ago. 2018',
        uso='Oito passos; usamos “descobrir o propósito”, “estimular o aprendizado individual” e “conectar as pessoas ao propósito”. Base das ID-01 e ID-07.',
        conf='Página oficial aberta (título, autores e data); os oito passos foram conferidos em cópia do artigo hospedada pela FAO.',
        links=[('hbr.org', 'https://hbr.org/2018/07/creating-a-purpose-driven-organization'),
               ('cópia (FAO)', 'https://www.fao.org/fileadmin/templates/library/pdf/Harvard_Business_Review.pdf')]),
    'hatch': dict(
        ref='Mary Jo Hatch e Majken Schultz, Are the Strategic Stars Aligned for Your Corporate Brand?, Harvard Business Review, fev. 2001, v. 79, n. 2, p. 129–134',
        uso='Marca corporativa pede alinhamento entre visão, cultura e imagem; as três lacunas são visão–cultura, imagem–cultura e imagem–visão. Base da ID-12.',
        conf='Página oficial aberta (texto pago); o resumo com as três lacunas foi conferido no registro da Copenhagen Business School.',
        links=[('hbr.org', 'https://hbr.org/2001/02/are-the-strategic-stars-aligned-for-your-corporate-brand'),
               ('registro CBS', 'https://research.cbs.dk/en/publications/are-the-strategic-stars-aligned-for-your-corporate-brand/')]),
    'aaker': dict(
        ref='David Aaker e Erich Joachimsthaler, The Brand Relationship Spectrum, California Management Review, v. 42, n. 4, 2000',
        uso='Arquitetura de marca em quatro estratégias: casa de marcas (house of brands), marcas endossadas (endorsed brands), submarcas (subbrands) e casa com marca (branded house, em que a marca-mãe domina); perguntas para escolher. Base da etapa 2 da ID-03.',
        conf='Registro do artigo aberto na Case Centre; estratégias e perguntas conferidas em cópia do artigo hospedada por terceiro. As páginas não são citadas: a cópia mostra 8–22 e há citação como 8–23.',
        links=[('The Case Centre', 'https://www.thecasecentre.org/products/view?id=5390'),
               ('cópia do artigo', 'https://ngovietliem.com/wp-content/uploads/2022/12/Reading-4.2-Brand-relationship-spectrum.pdf')]),
    'wheeler': dict(
        ref='Alina Wheeler, Designing Brand Identity',
        uso='Processo em cinco fases: pesquisa, estratégia, desenho da identidade, pontos de contato e gestão dos ativos. Base das ID-03 e ID-04.',
        conf='As cinco fases foram conferidas em entrevista da autora; o livro não foi lido.',
        links=[('entrevista (Logo Geek)', 'https://logogeek.uk/podcast/design-a-brand-identity-with-alina-wheeler/')]),
    'inpi': dict(
        ref='INPI, serviço de prorrogação de registro de marca (gov.br)',
        uso='O registro de marca vale 10 anos, renováveis; a prorrogação é pedida no último ano de vigência ou em até seis meses depois. Base da etapa 5 da ID-03.',
        conf='Página oficial do serviço aberta. O artigo da Lei 9.279/1996 não foi conferido no texto da lei.',
        links=[('gov.br', 'https://www.gov.br/pt-br/servicos/solicitar-a-prorrogacao-de-registro-de-marca-e-expedicao-de-certificado-de-registro')]),
    'iso20671': dict(
        ref='ISO 20671-1:2021, Brand evaluation — Part 1: Principles and fundamentals',
        uso='Avaliação de marca com elementos de entrada, dimensões de saída e indicadores. Base das ID-11 e ID-12.',
        conf='Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida.',
        links=[('iso.org', 'https://www.iso.org/standard/81739.html')]),
    'iso10010': dict(
        ref='ISO 10010:2022, Quality management — Guidance to understand, evaluate and improve organizational quality culture',
        uso='Orientação para entender, avaliar e melhorar a cultura de qualidade, com exemplos de ferramentas de autoavaliação. Base das ID-11 e ID-12.',
        conf='Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida. O foco da norma é cultura de qualidade; usamos a sequência entender, avaliar e melhorar, que está no título, não o conteúdo.',
        links=[('iso.org', 'https://www.iso.org/standard/38457.html')]),
    'mckinsey': dict(
        ref='Tessa Basford e Bill Schaninger, The four building blocks of change, McKinsey, 11/04/2016',
        uso='Quatro alavancas para mudar comportamento: exemplo dos líderes, entendimento e convicção, desenvolvimento de habilidades e mecanismos formais. Base das ID-02, ID-05 e ID-06.',
        conf='Artigo aberto no site da McKinsey.',
        links=[('mckinsey.com', 'https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/the-four-building-blocks--of-change')]),
    'schein': dict(
        ref='Edgar Schein, modelo de cultura organizacional em três níveis',
        uso='Cultura em três níveis: artefatos e comportamentos, valores declarados e pressupostos básicos. Explica por que os elementos visíveis da cultura contam. Tratar rituais como artefatos é leitura nossa; o verbete não fala em rituais. Base das ID-05 e ID-06.',
        conf='Fonte secundária: verbete da Wikipédia. O livro não foi lido.',
        links=[('Wikipédia', 'https://en.wikipedia.org/wiki/Edgar_Schein')]),
    'craig': dict(
        ref='Nick Craig e Scott Snook, From Purpose to Impact, Harvard Business Review, v. 92, n. 5, maio de 2014',
        uso='Declaração de propósito pessoal seguida de um plano para transformar o propósito em impacto. Base da ID-07.',
        conf='Registro do artigo aberto no site da Harvard Business School e página do artigo na HBR (resumo); o texto completo não foi lido. As páginas não são citadas: os registros divergem entre 104–111 e 105–111.',
        links=[('hbs.edu', 'https://www.hbs.edu/faculty/Pages/item.aspx?num=47372'), ('hbr.org', 'https://hbr.org/2014/05/from-purpose-to-impact')]),
    'reptrak': dict(
        ref='RepTrak, Global RepTrak 100 (2026)',
        uso='Sete fatores de reputação: produtos e serviços, desempenho, inovação, liderança, conduta, cidadania e ambiente de trabalho. Usados como temas na ID-10 e na ID-12.',
        conf='Página oficial aberta.',
        links=[('reptrak.com', 'https://www.reptrak.com/globalreptrak/')]),
    'iso22361': dict(
        ref='ISO 22361:2022, Security and resilience — Crisis management — Guidelines',
        uso='Diretrizes para a capacidade de gestão de crises. Base da ID-10.',
        conf='Página oficial da ISO aberta (resumo); a norma completa é paga e não foi lida.',
        links=[('iso.org', 'https://www.iso.org/standard/50267.html')]),
    'nng': dict(
        ref='Kate Moran, The Four Dimensions of Tone of Voice, Nielsen Norman Group, 17/07/2016',
        uso='Quatro dimensões de tom: formal ou casual, sério ou divertido, respeitoso ou irreverente, sóbrio ou entusiasmado. Base do guia de voz na ID-02.',
        conf='Artigo aberto no site da NN/g.',
        links=[('nngroup.com', 'https://www.nngroup.com/articles/tone-of-voice-dimensions/')]),
    'google_persona': dict(
        ref='Google, Conversation Design: Create a persona',
        uso='Passos para definir a persona de um agente de conversa. Base da persona dos agentes na ID-02.',
        conf='Página oficial aberta. A plataforma a que o guia se refere foi descontinuada em 13/06/2023; o método de persona continua aplicável.',
        links=[('developers.google.com', 'https://developers.google.com/assistant/conversation-design/create-a-persona')]),
    'impact': dict(
        ref='Impact Frontiers, Five Dimensions of Impact (Impact Management Norms)',
        uso='Cinco dimensões de impacto: o quê, quem, quanto, contribuição e risco. Base da ID-13.',
        conf='Página oficial aberta.',
        links=[('impactfrontiers.org', 'https://impactfrontiers.org/norms/five-dimensions-of-impact/')]),
    'bpmn': dict(
        ref='OMG, Business Process Model and Notation (BPMN) 2.0.2; ISO/IEC 19510:2013',
        uso='Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio e script, além da atividade de chamada.',
        conf='Páginas oficiais da OMG e da ISO abertas; a lista de tipos de tarefa foi conferida no BPMN Quick Guide; a atividade de chamada foi aceita pelo metamodelo usado nos testes. A especificação completa não foi lida.',
        links=[('omg.org', 'https://www.omg.org/spec/BPMN/2.0.2/About-BPMN'),
               ('iso.org', 'https://www.iso.org/standard/62652.html'),
               ('BPMN Quick Guide', 'https://www.bpmnquickguide.com/quickguide/bpmn-quick-guide/tasks')]),
    'camunda': dict(
        ref='Camunda, Best Practices: Naming BPMN elements',
        uso='Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
        conf='Documentação oficial aberta.',
        links=[('docs.camunda.io', 'https://docs.camunda.io/docs/components/best-practices/modeling/naming-bpmn-elements/')]),
    'dmn': dict(
        ref='OMG, Decision Model and Notation (DMN)',
        uso='Padrão de modelagem de decisões, que inclui tabelas de decisão e foi desenhado para uso ao lado do BPMN. Usado para regras como gravidade do sinal e uso da marca por terceiros.',
        conf='Página oficial da OMG aberta.',
        links=[('omg.org', 'https://www.omg.org/spec/DMN')]),
    'sipoc': dict(
        ref='ASQ, SIPOC+CM Diagram',
        uso='Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
        conf='Página oficial da ASQ aberta.',
        links=[('asq.org', 'https://asq.org/quality-resources/sipoc')]),
}

# ----------------------------------------------- relação com a proposta anterior
MUDANCAS = [
    ('C2 · Do propósito ao padrão', 'ID-01 e ID-02', 'Dividida: declarar é raro e dos sócios; traduzir em padrão é frequente e operacional.'),
    ('C11 · Da marca à reputação', 'ID-08, ID-09, ID-10 e ID-12', 'Dividida em posicionar, comunicar, responder a crises e medir.'),
    ('C12 · Do valor declarado à cultura vivida', 'ID-02, ID-05, ID-06 e ID-12', 'Dividida em definir comportamentos, integrar, reforçar e medir.'),
    ('I-ID1 · Da amostra à coerência', 'ID-11', 'Mesmo conteúdo, nome didático.'),
    ('I-ID2 · Do pedido ao material de marca', 'ID-04', 'Ganha a autorização de uso por terceiros.'),
    ('I-ID3 · Da escuta à nova edição do Soul Brand', 'ID-01', 'Deixa de ser sobre o livro. O Soul Brand é a saída atual desta jornada.'),
    ('C14 · Do autoconhecimento à alta performance', 'ID-07', 'Vira recomendada, voluntária.'),
    ('Sem equivalente', 'ID-03', 'Nova: marca de empresa, oferta ou projeto novo. Antes era um workflow de proteção de nomes.'),
    ('Sem equivalente', 'ID-13', 'Nova e recomendada: relato anual de impacto.'),
    ('Nível “workflow”', 'Etapa', 'Mesmo nível, nome mais simples. Vale para os próximos círculos se você aprovar.'),
    ('Códigos C, I-ID e V', 'ID-01 a ID-13', 'Um código por círculo. Os códigos antigos continuam no documento até o círculo ser fechado.'),
    ('Separação entre próprias e cross', 'Fica para o fim', 'Doze das treze jornadas têm tarefa de outro círculo. A classificação será feita com os nove círculos listados, como combinado.'),
]


# --------------------------------------------------- o que a Identidade não faz
FRONTEIRAS = [
    ('Escolher onde atuar e fixar os alvos', 'Estratégia',
     'A Identidade registra a escolha na declaração e no posicionamento.'),
    ('Posicionar cada oferta e gerar demanda', 'Inteligência e Relações',
     'A Identidade entrega o posicionamento institucional e a casa de mensagens.'),
    ('Publicar em canais externos e responder ao público', 'Relações',
     'A Identidade entrega o conteúdo institucional e, em crise, os comunicados.'),
    ('Ciclo da pessoa: vaga, contrato, avaliação e remuneração', 'Gestão',
     'A Identidade entrega perfil, comportamentos, integração cultural e reconhecimento simbólico.'),
    ('Código de conduta, canal de relato e tratamento de violações', 'Governança',
     'A Identidade entrega os comportamentos esperados e aponta os indícios achados na auditoria.'),
    ('Construir, testar e liberar agentes', 'Integração',
     'A Identidade entrega persona, voz, limites e casos de teste. A Integração roda os testes antes de liberar o agente.'),
    ('Registrar e renovar marcas; contratos de uso', 'Governança',
     'A Identidade decide o que proteger e quem pode usar.'),
    ('Decidir a posição da empresa numa crise', 'Executivo da empresa',
     'A Identidade monitora, apura, redige e comunica.'),
]

# ------------------------------------------------------------ pontos a decidir
PONTOS = [
    ('Comunicação interna fica na Identidade?',
     'Sim (ID-09). A Identidade responde pela pauta e pela voz; Relações publica fora.',
     'O referencial da APQC põe a comunicação com as pessoas em recursos humanos (7.8). A alternativa é a Gestão executar e a Identidade entregar pauta e voz.'),
    ('Reconhecimento fica na Identidade?',
     'O reconhecimento simbólico fica na Identidade (ID-06); a recompensa financeira fica na Gestão.',
     'A APQC põe recompensa e reconhecimento juntos em recursos humanos (7.5.1). Separar exige uma regra clara de quando há dinheiro.'),
    ('Uma auditoria ou três?',
     'Manter a ID-11 agora e decidir quando as jornadas entre círculos forem consolidadas.',
     'Identidade (coerência), Governança (alçadas dos agentes) e Operações (qualidade) vão amostrar as mesmas entregas. Um motor de amostragem com três critérios custa menos que três auditorias.'),
    ('As duas jornadas recomendadas entram?',
     'ID-07 e ID-13 ficam para a onda 3.',
     'A ID-07 pode viver dentro do ciclo de desenvolvimento da Gestão; a ID-13 pode viver na prestação de contas da Governança. Cortar as duas deixa o círculo com 11 jornadas.'),
]

ONDAS = {
    1: 'O que o modelo precisa para rodar com pessoas e agentes',
    2: 'O que sustenta marca, cultura e reputação',
    3: 'O que é recomendado, depois que o resto estiver rodando',
}
