
# ======================================================== PREÇO E PLANO COMERCIAL
JORNADAS.append(dict(
    code='NE-01',
    nome='Manter a tabela de preços, a política comercial e o material de venda de cada empresa',
    dominio='Preço e plano comercial', classe='essencial', onda=1,
    objetivo='Ter, em cada empresa, uma tabela de preços e uma política comercial vigentes (preço de cada oferta, descontos, condições de pagamento e faixa de desconto de quem vende) que pessoas e agentes usam, a partir do preço-base decidido pela Inteligência e do papel de cada oferta no portfólio-alvo, com o material de venda de cada oferta conforme os padrões de identidade; e parar a venda da oferta encerrada. Negócios decide a tabela e a política, ouvidos o executivo e a Gestão; a faixa de desconto e as condições que mexem nos modelos de contrato são aprovadas pela Governança, dona das alçadas. O preço de tabela fica no preço-base ou acima dele; abaixo, só depois de a Inteligência rever o preço-base.',
    frequencia='Por evento: oferta nova ou preço-base alterado no catálogo, resposta a pedido sobre o preço-base, decisão de encerrar oferta, data de saída, material vencido ou marca retirada; e na revisão da tabela (cadência: semestral, e sempre que um preço-base mudar)',
    automacao=('média', 'Reunir as entradas, comparar o preço praticado com o preço-base, propor a tabela, conferir as alçadas e os padrões, preparar o material e publicar são de agente e automação; decidir a tabela e a política é de pessoa de Negócios.'),
    base=['apqc', 'dmn'],
    lanes=['EST', 'INT', 'IDE', 'GES', 'GOV', 'EXE', P, A, R],
    inicios=[I('Oferta nova ou preço-base alterado no catálogo', 'INT', 'message'),
             I('Resposta ao pedido sobre o preço-base recebida', 'INT', 'message'),
             I('Decisão de encerrar oferta ou data de saída recebida', 'EST', 'message'),
             I('Material vencido ou marca retirada avisados', 'IDE', 'message'),
             I('Revisão da tabela iniciada', R, 'timer')],
    fins=[F('Tabela, política e material de venda publicados', R),
          F('Venda da oferta bloqueada, à espera da data de saída', R)],
    etapas=[
        E('Reunir as ofertas, o preço-base e o desempenho de preço', 'Negócios', 'Autopiloto', 'baixo',
          [(OFERTA_CAT, 'Inteligência'), (OFERTA_FORA, 'Inteligência'), (RESP_OFERTA, 'Inteligência'),
           (OFERTA_LANC, 'Estratégia'), (PORTALVO, 'Estratégia'), (DEC_ENCERRAR, 'Estratégia'), (DATA_SAIDA, 'Estratégia'),
           (MAT_VENC, 'Identidade'), (MARCA_RET, 'Identidade'), ('Plano de lançamento da oferta', 'Integração'),
           (ALCADAS, 'Governança'), (DESEMP_PRECO, 'NE-04'), (MOTIVOS, 'NE-03'), (MOTIVOS, 'NE-04'), (MOTIVOS, 'NE-05'), (MOTIVOS, 'NE-06')],
          [T('Registrar o que abriu o trabalho e as ofertas afetadas', R),
           D('O que abriu o trabalho?', R,
             [S('Oferta nova, preço-base alterado, resposta da Inteligência ou revisão da tabela', 'seg'),
              S('Decisão de encerrar oferta, ainda sem data de saída', 'F2',
                via=[T('Bloquear novas propostas da oferta, sem mudar a tabela publicada nem avisar fora', R)]),
              S('Data de saída confirmada', 'E3',
                via=[T('Marcar na tabela a oferta que não pode mais ser vendida, com a data', R)]),
              S('Material vencido ou marca retirada', 'E3',
                via=[T('Listar o material de venda afetado e retirá-lo de uso', R)])]),
           T('Comparar o preço-base, o preço praticado, os descontos dados e as perdas por preço', A)],
          [('Diagnóstico de preço das ofertas', ['etapa 2'])]),
        E('Decidir o preço de tabela e a política comercial', 'Negócios, ouvidos o executivo e a Gestão; a faixa de desconto, a Governança', 'Copiloto', 'médio',
          [('Diagnóstico de preço das ofertas', 'etapa 1'), (MODELOS, 'Governança')],
          [T('Propor preço de tabela, descontos, condições de pagamento e faixa de desconto por oferta', A),
           T('Conferir a proposta com o preço-base e com as alçadas vigentes', R, 'rule'),
           D('Algum preço de tabela fica abaixo do preço-base?', R,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir à Inteligência a revisão do preço-base, com a evidência de mercado e de perdas', R),
                                   T('Manter a oferta afetada no preço vigente até a resposta', P)])]),
           PAR([T('Opinar sobre o preço e a política comercial da empresa', 'EXE')],
               [T('Conferir a margem e o efeito no caixa das condições de pagamento', 'GES')]),
           T('Decidir a tabela de preços e a política comercial, ouvidos o executivo e a Gestão', P),
           D('A política muda a faixa de desconto de quem vende ou uma condição dos modelos de contrato?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Aprovar a faixa de desconto e as condições na tabela de alçadas e nos modelos', 'GOV')])])],
          [('Tabela e política decididas', ['etapa 3']),
           (PED_OFERTA, ['Inteligência'])]),
        E('Publicar a tabela e o material de venda e avisar quem vende', 'Negócios', 'Autopiloto', 'baixo',
          [('Tabela e política decididas', 'etapa 2'), (PACOTE_MARCA, 'Identidade'), (PADROES_ID, 'Identidade'), (POSIC, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Preparar o material de venda das ofertas novas ou mudadas com o pacote de marca', A),
           T('Conferir o material de venda com os padrões de identidade', A),
           D('O material de venda está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o material no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o material de venda não coberto pelos padrões', 'IDE', 'call')])]),
           T('Publicar a tabela, a política comercial e o material de venda com versão e vigência', R),
           T('Avisar quem vende, os parceiros de venda e os círculos que usam a tabela', R)],
          [(TABELA, ['Relações', 'Inteligência', 'Gestão', 'Operações', 'NE-02', 'NE-03', 'NE-04', 'NE-05', 'NE-06', 'NE-07']),
           ('Material de venda das ofertas', ['NE-03', 'NE-07']),
           (CONSULTA, ['Identidade'])]),
    ]))

JORNADAS.append(dict(
    code='NE-02',
    nome='Planejar as vendas do ciclo e prever a receita',
    dominio='Preço e plano comercial', classe='essencial', onda=1,
    objetivo='Ter, a cada ciclo, os alvos de venda de cada empresa por oferta e canal, desdobrados dos alvos do ciclo, os clientes-chave com o plano de conta de cada um, e uma previsão de receita e de vendas atualizada a cada período a partir do funil, das propostas, dos contratos, das atas e das renovações, entregue a quem precisa dela para o orçamento, o caixa, a capacidade e a implantação. Negócios decide o desdobramento e a previsão, ouvido o executivo; o desvio contra os alvos vai ao executivo e à Gestão.',
    frequencia='A cada ciclo de vendas e a cada período de previsão (cadências: ciclo de vendas trimestral; previsão mensal) e por evento: alvos do ciclo publicados',
    automacao=('média', 'Reunir o funil, as propostas e os contratos, calcular a previsão e comparar com os alvos são de agente e automação; desdobrar os alvos, escolher os clientes-chave e concluir a previsão são de pessoa de Negócios.'),
    base=['apqc'],
    lanes=['EST', 'OPE', 'ITG', 'EXE', P, A, R],
    inicios=[I('Ciclo de vendas iniciado', R, 'timer'),
             I('Período de previsão encerrado', R, 'timer'),
             I('Alvos do ciclo publicados', 'EST', 'message')],
    fins=[F('Plano de vendas e previsão publicados', R)],
    etapas=[
        E('Reunir alvos, demanda, funil e carteira', 'Negócios', 'Autopiloto', 'baixo',
          [(ALVOS, 'Estratégia'), (PORTALVO, 'Estratégia'), (MANDATO, 'Estratégia'),
           (PLANO_DEM, 'Relações'), (CRITERIO, 'Relações'), (FUNIL, 'Relações'), (LACUNAS_PERC, 'Relações'),
           (LEITURA, 'Inteligência'), (PAINEL, 'Inteligência'), (LACUNAS_EXEC, 'Identidade'),
           (TABELA, 'NE-01'), (REGISTROS, 'NE-03'), (REGISTROS, 'NE-04'), (ATA, 'NE-05'), (REGISTROS, 'NE-06'),
           (VENC, 'NE-06'), ('Resultado da venda com parceiros e conjunta', 'NE-07')],
          [T('Reunir alvos, plano de demanda, funil, propostas, contratos, atas e vencimentos do período', R),
           T('Calcular a previsão de receita e de vendas por empresa, oferta, canal e período', A),
           T('Comparar a previsão com os alvos e apontar desvios e lacunas que afetam a venda', A)],
          [('Previsão proposta, com os desvios', ['etapa 2'])]),
        E('Decidir os alvos de venda, os clientes-chave e a previsão', 'Negócios, ouvido o executivo', 'Assistido', 'médio',
          [('Previsão proposta, com os desvios', 'etapa 1')],
          [T('Propor o desdobramento dos alvos de venda por oferta e canal e as ações para os desvios', A),
           PAR([T('Opinar sobre os alvos de venda e a previsão da empresa', 'EXE')],
               [T('Confirmar a capacidade de entrega para o volume previsto', 'OPE')],
               [T('Confirmar a capacidade de implantação para o volume previsto', 'ITG')]),
           T('Decidir os alvos de venda e a previsão, ouvido o executivo', P),
           T('Escolher os clientes-chave e definir o plano de conta de cada um', P),
           T('Incluir no plano as correções das lacunas de execução e de percepção que cabem a Negócios', P),
           D('A previsão fica abaixo dos alvos do ciclo?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Apontar o desvio ao executivo e à Gestão, com as ações de recuperação', R)])])],
          [('Alvos de venda e previsão decididos', ['etapa 3']),
           ('Desvio da previsão contra os alvos, com as ações', ['Executivos', 'Gestão'])]),
        E('Publicar o plano de vendas e a previsão', 'Negócios', 'Autômato', 'baixo',
          [('Alvos de venda e previsão decididos', 'etapa 2')],
          [T('Publicar o plano de vendas do ciclo, os planos de conta e a previsão com versão e data', R),
           T('Avisar quem vende, o executivo, a Gestão, Operações e a Integração', R)],
          [(PLANO_VEN, ['NE-03', 'NE-05', 'NE-07', 'Executivos', 'Gestão']),
           ('Plano de conta dos clientes-chave', ['NE-06']),
           (PREVISAO, ['Gestão', 'Operações', 'Integração', 'Executivos'])]),
    ]))
