
# =================================================================== VENDA
JORNADAS.append(dict(
    code='NE-03',
    nome='Aceitar a oportunidade, desenhar a solução e fazer a proposta',
    dominio='Venda', classe='essencial', onda=1,
    objetivo='Fazer cada oportunidade qualificada receber aceite ou devolução com o motivo no prazo combinado com Relações e, aceita, virar uma proposta com escopo que a operação e a implantação conseguem entregar, preço pela tabela, concessão dentro da alçada, conforme os padrões de identidade e no modelo da Governança. A oportunidade de parceiro ou de oferta conjunta já aceita na NE-07 entra direto no escopo, que é confirmado com o cliente. O que foge do catálogo vai à Inteligência ou à Estratégia, e a resposta da Inteligência retoma a proposta; o contato que chega direto a Negócios vai a Relações para ser qualificado.',
    frequencia='Por evento: oportunidade qualificada, oportunidade sem resposta no prazo, oportunidade de parceiro ou de oferta conjunta, mudança de escopo pedida na negociação, resposta da Inteligência ou pedido que chega direto do cliente',
    automacao=('média', 'Registrar, conferir com o critério, montar o escopo, calcular o preço, redigir, conferir os padrões e enviar são de agente e automação; aceitar, conversar com o cliente, decidir o escopo e aprovar a proposta são de pessoa de Negócios.'),
    base=['apqc', 'dmn'],
    lanes=['REL', 'INT', 'CLI', 'OPE', 'ITG', 'IDE', 'GOV', 'EXE', 'SOC', P, A, R],
    inicios=[I('Oportunidade qualificada recebida', 'REL', 'message'),
             I('Oportunidade sem resposta no prazo escalada', 'REL', 'message'),
             I('Oportunidade de parceiro ou de oferta conjunta recebida', R, 'message'),
             I('Mudança de escopo recebida da negociação', R, 'message'),
             I('Resposta da Inteligência sobre o escopo recebida', 'INT', 'message'),
             I('Pedido de proposta recebido do cliente', 'CLI', 'message')],
    fins=[F('Proposta aceita ou em negociação, passada ao contrato', R),
          F('Oportunidade devolvida a Relações, com o motivo', R),
          F('Escopo fora do catálogo levado à Inteligência ou à Estratégia', R),
          F('Contato passado a Relações para qualificar', R),
          F('Pedido levado à jornada de contas e contratos', R),
          F('Edital levado à jornada de licitações', R),
          F('Proposta perdida, com o motivo', R)],
    etapas=[
        E('Receber a oportunidade e decidir o aceite', 'Negócios', 'Copiloto', 'médio',
          [(OPORT_Q, 'Relações'), (OPORT_SEM, 'Relações'), (CRITERIO, 'Relações'), (BASE_REL, 'Relações'),
           ('Pedido de proposta do cliente', 'Clientes'), (OPORT_PARC, 'NE-07'), (MUD_ESCOPO, 'NE-04'), (RESP_OFERTA, 'Inteligência'),
           (PLANO_VEN, 'NE-02'), (TABELA, 'NE-01')],
          [T('Registrar a oportunidade, a origem e o prazo de aceite combinado', R),
           D('O que abriu o trabalho?', R,
             [S('Oportunidade qualificada por Relações, ou escalada sem resposta', 'seg'),
              S('Oportunidade de parceiro ou de oferta conjunta aceita na NE-07', 'E2',
                via=[T('Registrar quem conduz a venda, indicado na NE-07', R)]),
              S('Mudança de escopo pedida na negociação ou resposta da Inteligência ao pedido de ajuste', 'E2',
                via=[T('Retomar a oportunidade com a mudança pedida ou com a resposta recebida', R)]),
              S('Pedido de cliente sem contrato, que não passou por Relações', 'F4',
                via=[T('Passar o contato a Relações para qualificar, com o que o cliente pediu', R)]),
              S('Pedido de cliente com contrato vigente', 'F5',
                via=[T('Levar o pedido à jornada de contas e contratos', R)]),
              S('Edital, ou pedido de cotação de órgão público', 'F6',
                via=[T('Levar o edital ou o pedido de cotação à jornada de licitações', R)])]),
           T('Conferir a oportunidade com o critério combinado, o plano de vendas e as ofertas vendáveis', A),
           T('Decidir o aceite ou a devolução, com o motivo, no prazo combinado', P),
           D('Negócios aceita a oportunidade?', P,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Devolver a oportunidade a Relações, com o motivo', R)])]),
           T('Avisar Relações do aceite e designar quem conduz a venda', R)],
          [(ACEITE, ['Relações']),
           (CONTATO, ['Relações']),
           (PED_CARTEIRA, ['NE-06']),
           (EDITAL, ['NE-05']),
           ('Oportunidade aceita, com quem conduz a venda', ['etapa 2'])]),
        E('Entender a necessidade e desenhar a solução', 'Negócios, com Operações e Integração', 'Assistido', 'médio',
          [('Oportunidade aceita, com quem conduz a venda', 'etapa 1'), (OFERTA_CAT, 'Inteligência'), (CX, 'Relações'),
           ('Mudança de escopo pedida pelo cliente', 'etapa 4')],
          [T('Confirmar com o cliente a necessidade, o resultado esperado, quem decide e o prazo', P, 'manual'),
           T('Montar o escopo com as ofertas do catálogo e o que o cliente pediu', A),
           D('O escopo cabe nas ofertas do catálogo?', P,
             [S('Sim', 'seg'),
              S('Não: pede ajuste de oferta ou oferta nova', 'F3',
                via=[T('Levar o ajuste à Inteligência ou a oferta nova à Estratégia, com a necessidade do cliente', R),
                     T('Avisar o cliente do caminho e do prazo da resposta', P, 'manual')])]),
           PAR([T('Confirmar que consegue entregar o escopo no prazo pedido', 'OPE')],
               [T('Confirmar o que a implantação pede: sistemas, prazos e pessoas', 'ITG')]),
           T('Decidir o escopo da solução, com o que Operações e a Integração confirmaram', P),
           D('Operações e a Integração conseguem entregar o escopo?', P,
             [S('Sim', 'prox'),
              S('Não, mas há escopo menor que serve ao cliente', 'E2'),
              S('Não há escopo que se consiga entregar', 'F7',
                via=[T('Registrar a perda por falta de escopo entregável e avisar o cliente', R)])])],
          [('Escopo da solução confirmado', ['etapa 3']),
           (PED_OFERTA, ['Inteligência']),
           (IDEIA, ['Estratégia']),
           (MOTIVOS, ['Inteligência', 'NE-01'])]),
        E('Precificar e redigir a proposta', 'Negócios; a concessão acima da alçada, o executivo ou os sócios', 'Copiloto', 'médio',
          [('Escopo da solução confirmado', 'etapa 2'), (TABELA, 'NE-01'), ('Material de venda das ofertas', 'NE-01'),
           (ALCADAS, 'Governança'), (MODELOS, 'Governança'),
           (PADROES_ID, 'Identidade'), (PACOTE_MARCA, 'Identidade'), (POSIC, 'Identidade'), (MAT_VENC, 'Identidade'),
           (MARCA_RET, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Calcular o preço pela tabela e pela política comercial', R, 'rule'),
           D('A concessão pedida está dentro da alçada de quem vende?', R,
             [S('Sim, ou não há concessão', 'seg'),
              S('Acima, dentro da alçada do executivo', 'seg',
                via=[T('Decidir a concessão acima da alçada de quem vende', 'EXE')]),
              S('Acima da alçada do executivo', 'seg',
                via=[T('Levar a concessão à decisão dos sócios', 'GOV', 'call'),
                     T('Decidir a concessão pelos sócios', 'SOC', 'manual')])]),
           T('Redigir a proposta no modelo, com o escopo, o preço, as condições e a validade', A),
           T('Conferir a proposta com os padrões de identidade e com os materiais vencidos ou de marca retirada', A),
           D('A proposta está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir a proposta no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre a proposta não coberta pelos padrões', 'IDE', 'call')])]),
           D('A proposta tem cláusula fora do modelo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Revisar a cláusula fora do modelo e o risco', 'GOV')])]),
           T('Revisar e aprovar a proposta', P)],
          [('Proposta aprovada para envio', ['etapa 4']),
           (CONSULTA, ['Identidade'])]),
        E('Enviar a proposta e acompanhar a resposta do cliente', 'Negócios', 'Autômato', 'baixo',
          [('Proposta aprovada para envio', 'etapa 3'), ('Resposta do cliente à proposta', 'Clientes')],
          [T('Enviar a proposta ao cliente e registrar o envio', R),
           T('Receber a resposta do cliente ou o fim da validade da proposta', R, 'receive'),
           D('Qual foi a resposta do cliente?', R,
             [S('Aceitou ou quer negociar', 'prox',
                via=[T('Passar a proposta à negociação e ao contrato', R)]),
              S('Pediu mudança no escopo', 'E2'),
              S('Recusou, ou a validade venceu sem resposta', 'F7',
                via=[T('Registrar a perda e o motivo dado pelo cliente', R)])])],
          [(PROP_NEG, ['NE-04']),
           ('Mudança de escopo pedida pelo cliente', ['etapa 2']),
           (MOTIVOS, ['Inteligência', 'NE-01']),
           (REGISTROS, ['Inteligência', 'NE-02'])]),
    ]))

JORNADAS.append(dict(
    code='NE-04',
    nome='Negociar e fechar o contrato com o cliente',
    dominio='Venda', classe='essencial', onda=1,
    objetivo='Fazer cada proposta aceita ou em negociação terminar em contrato assinado no modelo da Governança, com as concessões dentro das alçadas, ou em perda registrada com o motivo; e passar o contrato a quem implanta, entrega, fatura e acompanha o cliente. Contratos e aditivos seguem o modelo da Governança, que já traz os padrões de identidade. O executivo assina pela empresa; a Governança revisa o que foge do modelo, confere os poderes de quem assina e guarda.',
    frequencia='Por evento: proposta aceita ou em negociação',
    automacao=('média', 'Simular concessões, redigir o contrato no modelo, registrar e avisar são de agente e automação; negociar, aprovar concessões e conferir o contrato são de pessoas; assinar é do executivo.'),
    base=['apqc', 'dmn'],
    lanes=['CLI', 'GOV', 'EXE', 'SOC', P, A, R],
    inicios=[I('Proposta aceita ou em negociação recebida', R, 'message')],
    fins=[F('Contrato assinado e passado a quem implanta, entrega, fatura e acompanha', R),
          F('Negociação perdida, com o motivo', R),
          F('Mudança de escopo devolvida à proposta', R)],
    etapas=[
        E('Negociar as condições com o cliente', 'Negócios; a concessão acima da alçada, o executivo ou os sócios', 'Copiloto', 'médio',
          [(PROP_NEG, 'NE-03'), (TABELA, 'NE-01'), (ALCADAS, 'Governança')],
          [T('Negociar com o cliente preço, prazo, condições e cláusulas', P, 'manual'),
           T('Simular o efeito de cada concessão na margem e conferir com a política comercial', A),
           D('A concessão negociada está dentro da alçada de quem vende?', R,
             [S('Sim, ou não há concessão', 'seg'),
              S('Acima, dentro da alçada do executivo', 'seg',
                via=[T('Decidir a concessão negociada acima da alçada de quem vende', 'EXE')]),
              S('Acima da alçada do executivo', 'seg',
                via=[T('Levar a concessão negociada à decisão dos sócios', 'GOV', 'call'),
                     T('Decidir a concessão negociada pelos sócios', 'SOC', 'manual')])]),
           D('O cliente e a empresa chegaram a acordo?', P,
             [S('Sim', 'prox'),
              S('O cliente pede mudar o escopo', 'F3', via=[T('Devolver o pedido de mudança de escopo à proposta', R)]),
              S('Não', 'F2', via=[T('Registrar a perda e o motivo da negociação', R)])])],
          [('Condições acordadas com o cliente', ['etapa 2']),
           (MUD_ESCOPO, ['NE-03']),
           (MOTIVOS, ['Inteligência', 'NE-01'])]),
        E('Formalizar e assinar o contrato', 'Negócios, com a Governança; assina o executivo; matéria da regra 10 dos contratos, os sócios', 'Assistido', 'alto',
          [('Condições acordadas com o cliente', 'etapa 1'), (MODELOS, 'Governança')],
          [T('Redigir o contrato no modelo, com o escopo vendido e as condições acordadas', A),
           D('O contrato foge do modelo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Revisar as cláusulas fora do modelo e o risco do contrato', 'GOV', 'call')]),
              S('Sim, com matéria dos sócios pela regra dos contratos', 'seg',
                via=[T('Revisar a cláusula de matéria dos sócios e propor a redação', 'GOV', 'call'),
                     T('Decidir a cláusula de matéria dos sócios do contrato', 'SOC', 'manual')])]),
           T('Conferir o contrato final com o que foi acordado', P),
           T('Conferir os poderes de quem assina pela empresa e pelo cliente', 'GOV'),
           T('Assinar o contrato em nome da empresa', 'EXE'),
           T('Assinar o contrato', 'CLI'),
           D('O contrato foi assinado pelas duas partes?', P,
             [S('Sim', 'seg'),
              S('Não: o cliente desistiu', 'F2', via=[T('Registrar a desistência do cliente e o motivo', R)])]),
           T('Guardar o contrato assinado', 'GOV')],
          [('Contrato assinado e guardado', ['etapa 3']),
           ('Contrato para conferir e guardar', ['Governança']),
           (MOTIVOS, ['Inteligência', 'NE-01'])]),
        E('Registrar a venda e passar o cliente a quem implanta, entrega, fatura e acompanha', 'Negócios', 'Autômato', 'baixo',
          [('Contrato assinado e guardado', 'etapa 2')],
          [T('Registrar o contrato, o escopo vendido, o valor, a vigência e o vencimento', R),
           T('Avisar a Integração, Operações, a Gestão e Relações do contrato assinado', R),
           T('Registrar os descontos dados e o motivo do ganho', R)],
          [(CONTRATO, ['Relações', 'Integração', 'Operações', 'Gestão', 'NE-06']),
           (REGISTROS, ['Inteligência', 'NE-02', 'NE-07']),
           (MOTIVOS, ['Inteligência', 'NE-01']),
           (DESEMP_PRECO, ['NE-01'])]),
    ]))

JORNADAS.append(dict(
    code='NE-05',
    nome='Disputar licitações e contratar com o setor público',
    dominio='Venda', classe='essencial', onda=1,
    objetivo='Decidir em cada edital se a empresa participa, montar a proposta e os documentos de habilitação nas regras do edital, disputar, acompanhar o julgamento, a habilitação, os recursos e a homologação e, ganhando, assinar o contrato ou a ata de registro de preços; responder ao pedido de cotação para pesquisa de preços; e responder ao órgão não participante que pede para aderir à ata. Negócios decide participar e recorrer, ouvidos o executivo e a Governança; a Governança confere a habilitação e conduz esclarecimentos, impugnações, recursos e contrarrazões; o executivo assina. Prazos e regras de impugnação, recurso, convocação e adesão seguem a lei e o edital e não foram conferidos neste desenho.',
    frequencia='Por evento: edital ou pedido de cotação encontrado ou recebido, resultado da disputa, convocação para assinar, ou pedido de adesão à ata',
    automacao=('média', 'Monitorar editais, conferir exigências, calcular o preço, montar os documentos, enviar e registrar são de agente e automação; decidir participar, dar lances, decidir recorrer e decidir a adesão são de pessoa de Negócios; esclarecer, impugnar e recorrer são da Governança; assinar é do executivo.'),
    base=['l14133', 'apqc'],
    lanes=['CLI', 'OPE', 'IDE', 'GOV', 'EXE', 'SOC', P, A, R],
    inicios=[I('Edital ou pedido de cotação encontrado', R, 'signal'),
             I('Edital ou pedido de cotação recebido', R, 'message'),
             I('Pedido de adesão à ata recebido', 'CLI', 'message')],
    fins=[F('Contrato ou ata assinado e registrado', R),
          F('Edital sem participação, com o motivo', R),
          F('Disputa perdida, com o resultado registrado', R),
          F('Cotação para pesquisa de preços respondida', R),
          F('Adesão recusada, com resposta ao órgão', R)],
    etapas=[
        E('Analisar o edital e decidir participar', 'Negócios, ouvido o executivo, com a Governança', 'Copiloto', 'alto',
          [(EDITAL, 'NE-03'), ('Edital publicado e seus anexos', 'Clientes'), ('Pedido de adesão à ata de órgão não participante', 'Clientes'),
           ('Resposta ao esclarecimento ou à impugnação, ou edital alterado', 'Clientes'),
           (TABELA, 'NE-01'), (OFERTA_CAT, 'Inteligência'), (PLANO_VEN, 'NE-02'), (HABILIT, 'Governança')],
          [T('Registrar o edital ou o pedido, o órgão, o objeto, as datas e as exigências', R),
           D('O que abriu o trabalho?', R,
             [S('Edital de licitação', 'seg'),
              S('Pedido de cotação para pesquisa de preços do órgão', 'F4',
                via=[T('Preparar a resposta à cotação com o preço pela tabela e pela política, sem disputa', A),
                     T('Aprovar e enviar a resposta à cotação', P)]),
              S('Pedido de adesão de órgão não participante', 'E4')]),
           T('Conferir o objeto com as ofertas, a tabela, a capacidade e as exigências de habilitação', A),
           PAR([T('Confirmar a capacidade de entregar o objeto do edital', 'OPE')],
               [T('Conferir as exigências de habilitação e o risco das cláusulas do edital', 'GOV')]),
           D('O edital tem exigência que pede esclarecimento ou impugnação?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir esclarecimento ou impugnar o edital, nos prazos da lei e do edital', 'GOV', 'call'),
                                   T('Receber a resposta ao esclarecimento ou à impugnação', R, 'receive'),
                                   T('Atualizar a análise com a resposta e com o edital alterado, quando houver', A)])]),
           T('Opinar sobre a participação da empresa no edital', 'EXE'),
           T('Decidir se a empresa participa, ouvido o executivo', P),
           D('A empresa participa?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar o motivo de não participar', R)])])],
          [('Edital analisado, com a decisão de participar', ['etapa 2']),
           ('Resposta à cotação para pesquisa de preços', ['Clientes'])]),
        E('Montar a proposta e os documentos de habilitação', 'Negócios, com a Governança; assina o executivo', 'Copiloto', 'alto',
          [('Edital analisado, com a decisão de participar', 'etapa 1'), (ALCADAS, 'Governança'), (HABILIT, 'Governança'),
           (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Calcular o preço pela tabela e pela política, com os custos que o edital impõe', R, 'rule'),
           T('Fixar o menor preço aceito na disputa', P),
           D('O menor preço aceito está dentro da alçada de quem vende?', R,
             [S('Sim', 'seg'),
              S('Acima, dentro da alçada do executivo', 'seg',
                via=[T('Decidir o menor preço da disputa acima da alçada de quem vende', 'EXE')]),
              S('Acima da alçada do executivo', 'seg',
                via=[T('Levar o menor preço da disputa à decisão dos sócios', 'GOV', 'call'),
                     T('Decidir o menor preço da disputa pelos sócios', 'SOC', 'manual')])]),
           T('Montar a proposta e a parte técnica, quando houver, nas regras do edital', A),
           D('A parte livre da proposta está conforme os padrões de identidade?', A,
             [S('Sim, ou o edital fixa todo o formato', 'seg'),
              S('Não', 'seg', via=[T('Corrigir a parte livre da proposta no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre a proposta de licitação não coberta pelos padrões', 'IDE', 'call')])]),
           T('Reunir e conferir os documentos de habilitação pedidos no edital', 'GOV'),
           T('Assinar a proposta e os documentos pedidos no edital em nome da empresa', 'EXE')],
          [('Proposta e habilitação prontas para a disputa', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Disputar e acompanhar o julgamento, a habilitação e os recursos', 'Negócios, com a Governança', 'Copiloto', 'alto',
          [('Proposta e habilitação prontas para a disputa', 'etapa 2'), ('Resultado do julgamento, da habilitação e dos recursos', 'Clientes')],
          [T('Enviar a proposta e os documentos pelo meio e no prazo do edital', R),
           T('Dar os lances na disputa, sem passar do menor preço aceito', P),
           T('Receber o resultado do julgamento e da habilitação', R, 'receive'),
           D('Qual é o resultado da disputa?', P,
             [S('Vencedora e habilitada, sem recurso de concorrente', 'prox'),
              S('Vencedora, com recurso de concorrente', 'seg',
                via=[T('Apresentar contrarrazões ao recurso do concorrente', 'GOV', 'call')]),
              S('Perdeu, desclassificada ou inabilitada, e Negócios decide recorrer, ouvida a Governança', 'seg',
                via=[T('Apresentar o recurso da empresa', 'GOV', 'call')]),
              S('Perdeu, e a empresa não recorre', 'F3',
                via=[T('Registrar o resultado, o preço vencedor e o motivo da perda', R)])]),
           T('Receber a decisão do recurso', R, 'receive'),
           D('A decisão do recurso favorece a empresa?', P,
             [S('Sim', 'prox'),
              S('Não', 'F3', via=[T('Registrar a decisão do recurso e o motivo da perda', R)])])],
          [('Resultado favorável da disputa', ['etapa 4']),
           (MOTIVOS, ['Inteligência', 'NE-01']),
           (REGISTROS, ['Inteligência'])]),
        E('Assinar o contrato ou a ata e responder às adesões', 'Negócios; assina o executivo; a Governança confere e guarda', 'Copiloto', 'alto',
          [('Resultado favorável da disputa', 'etapa 3'), ('Homologação e convocação para assinar', 'Clientes'),
           ('Pedido de adesão à ata de órgão não participante', 'Clientes')],
          [T('Conferir os poderes de quem assina pela empresa', 'GOV'),
           D('O que se assina?', P,
             [S('Contrato com o órgão', 'seg',
                via=[T('Receber a homologação e a convocação para assinar o contrato', R, 'receive'),
                     T('Assinar o contrato com o órgão em nome da empresa', 'EXE')]),
              S('Ata de registro de preços', 'seg',
                via=[T('Receber a homologação e a convocação para assinar a ata', R, 'receive'),
                     T('Assinar a ata de registro de preços em nome da empresa', 'EXE')]),
              S('Adesão de órgão não participante à ata', 'seg',
                via=[T('Decidir se aceita fornecer ao órgão não participante, nas regras da ata e da lei', P)])]),
           D('Há adesão a responder?', P,
             [S('Não', 'seg'),
              S('Sim, aceita', 'seg', via=[T('Assinar o contrato da adesão em nome da empresa', 'EXE')]),
              S('Sim, recusada', 'F5', via=[T('Responder ao órgão não participante que a empresa não adere, com o motivo', R)])]),
           T('Conferir o documento assinado com o resultado da disputa ou com a adesão aceita', P),
           T('Guardar o contrato ou a ata', 'GOV'),
           T('Registrar o contrato ou a ata, o saldo, a vigência e os órgãos participantes', R),
           T('Avisar a Integração, Operações, a Gestão e Relações do que foi assinado', R)],
          [(CONTRATO, ['Relações', 'Integração', 'Operações', 'Gestão', 'NE-06']),
           (ATA, ['NE-06', 'NE-02', 'Gestão', 'Operações'])]),
    ]))
