
# ===================================================== CONTAS E CONTRATOS
JORNADAS.append(dict(
    code='NE-06',
    nome='Cuidar dos contratos dos clientes: renovar, ampliar, aditar e encerrar',
    dominio='Contas e contratos', classe='essencial', onda=1,
    objetivo='Fazer cada contrato de cliente ser renovado, ampliado ou aditado no tempo certo, com as concessões dentro das alçadas e com o escopo novo confirmado por Operações e pela Integração, a partir da oportunidade que Relações aponta, do pedido do cliente e do plano de conta; tratar o pedido de cancelamento com uma negociação de retenção e, perdido o cliente ou vencida a vigência sem renovação, formalizar o fim do contrato e avisar quem entrega, implanta e fatura; atender a contratação de órgão participante pela ata; e, quando uma oferta é encerrada ou uma empresa sai, encerrar ou transferir os contratos pelo plano de saída coordenado pela Integração. O vencimento próximo só avisa Relações, que decide se abre a renovação. Relações acompanha o sucesso do cliente; Negócios negocia e formaliza; o executivo assina.',
    frequencia='Por evento: oportunidade de renovação ou de expansão, vencimento próximo, pedido do cliente, contratação pela ata, pedido de cancelamento, decisão de encerrar oferta, data de saída ou mandato',
    automacao=('média', 'Vigiar vencimentos e saldos, preparar a proposta de renovação, redigir o aditivo, registrar e avisar são de agente e automação; negociar, decidir concessões, conferir e executar a parte de Negócios do plano de saída são de pessoas; assinar é do executivo.'),
    base=['apqc', 'dmn', 'l14133'],
    lanes=['REL', 'EST', 'CLI', 'OPE', 'ITG', 'IDE', 'GOV', 'EXE', 'SOC', P, A, R],
    inicios=[I('Oportunidade de renovação ou de expansão recebida', 'REL', 'message'),
             I('Vencimento de contrato próximo', R, 'timer'),
             I('Fim de vigência sem renovação', R, 'timer'),
             I('Pedido de cliente com contrato vigente recebido', R, 'message'),
             I('Pedido de contratação pela ata recebido', 'CLI', 'message'),
             I('Pedido de cancelamento do cliente recebido', 'CLI', 'message'),
             I('Decisão de encerrar oferta, data de saída ou mandato recebido', 'EST', 'message')],
    fins=[F('Renovação, aditivo ou contratação assinada e registrada', R),
          F('Contrato encerrado, com o fim formalizado e avisado', R),
          F('Contratos da saída encerrados ou transferidos', R),
          F('Contratos afetados listados, à espera da data de saída', R),
          F('Mandato registrado, sem mexer nos contratos', R),
          F('Pendência da saída apontada', R),
          F('Vencimento avisado a Relações', R)],
    etapas=[
        E('Reunir a carteira e decidir o que tratar', 'Negócios', 'Autopiloto', 'baixo',
          [(CONTRATO, 'NE-04'), (CONTRATO, 'NE-05'), (ATA, 'NE-05'), (PED_CARTEIRA, 'NE-03'),
           ('Plano de conta dos clientes-chave', 'NE-02'),
           (OPORT_REN, 'Relações'), (PLANO_SUC, 'Relações'), (FATURAS, 'Gestão'),
           ('Pedido de contratação pela ata', 'Clientes'), ('Pedido de cancelamento de contrato', 'Clientes'),
           (DEC_ENCERRAR, 'Estratégia'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'),
           (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Conferir o contrato, o saldo de ata e o que abriu o trabalho', R),
           D('O que abriu o trabalho?', R,
             [S('Oportunidade de renovação ou de expansão, pedido de aditivo ou pedido de cancelamento', 'seg'),
              S('Vencimento próximo de contrato', 'F7',
                via=[T('Avisar Relações e a Gestão do vencimento próximo do contrato', R)]),
              S('Fim de vigência sem renovação', 'E4',
                via=[T('Registrar o fim de vigência sem renovação e a data de fim', R)]),
              S('Pedido de contratação pela ata', 'E4'),
              S('Oferta encerrada, empresa que sai ou mandato', 'E3')]),
           T('Preparar a proposta de renovação, aditivo ou retenção com o histórico, o plano de conta e a tabela', A),
           D('A proposta está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir a proposta de renovação no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre a proposta de renovação não coberta pelos padrões', 'IDE', 'call')])])],
          [(VENC, ['Relações', 'Gestão', 'NE-02']),
           (CONSULTA, ['Identidade']),
           ('Proposta de renovação, expansão ou retenção', ['etapa 2'])]),
        E('Negociar a renovação, a expansão, o aditivo ou a retenção', 'Negócios, com Operações e Integração; a concessão acima da alçada, o executivo ou os sócios', 'Assistido', 'médio',
          [('Proposta de renovação, expansão ou retenção', 'etapa 1'), (TABELA, 'NE-01'), (ALCADAS, 'Governança'), (MODELOS, 'Governança')],
          [T('Negociar com o cliente a renovação, a expansão, o aditivo ou a retenção', P, 'manual'),
           D('O escopo muda?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Confirmar que consegue entregar o escopo renovado ou ampliado', 'OPE'),
                                   T('Confirmar o que a implantação do escopo novo pede', 'ITG')])]),
           D('Operações e a Integração conseguem entregar o escopo combinado?', P,
             [S('Sim, ou o escopo não muda', 'seg'),
              S('Não, renegociar o escopo', 'E2')]),
           D('A concessão da renovação está dentro da alçada de quem vende?', R,
             [S('Sim, ou não há concessão', 'seg'),
              S('Acima, dentro da alçada do executivo', 'seg',
                via=[T('Decidir a concessão da renovação acima da alçada de quem vende', 'EXE')]),
              S('Acima da alçada do executivo', 'seg',
                via=[T('Levar a concessão da renovação à decisão dos sócios', 'GOV', 'call'),
                     T('Decidir a concessão da renovação pelos sócios', 'SOC', 'manual')])]),
           D('Qual é o resultado com o cliente?', P,
             [S('Renovou, ampliou, aditou ou ficou', 'E4'),
              S('Não renovou ou cancelou', 'E4',
                via=[T('Registrar a perda, o motivo e a data de fim do contrato', R)])])],
          [('Condições da renovação acordadas', ['etapa 4']),
           (MOTIVOS, ['Inteligência', 'NE-01'])]),
        E('Encerrar ou transferir os contratos da oferta ou da empresa que sai', 'Negócios, no plano de saída coordenado pela Integração', 'Assistido', 'alto',
          [(DEC_ENCERRAR, 'Estratégia'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'), (EM_CURSO_SAI, 'Inteligência'),
           (PLANO_SAIDA, 'Integração'), (CLI_SAIDA, 'Relações')],
          [T('Listar os contratos, as atas e as propostas afetados', R),
           D('Há data de saída confirmada?', R,
             [S('Sim, ou venda fechada ou encerramento de empresa', 'seg',
                via=[T('Suspender novas propostas da oferta ou da empresa que sai', R)]),
              S('Não: decisão de encerrar, ainda sem data', 'F4',
                via=[T('Mandar à Integração a lista de contratos afetados, sem avisar os clientes', R)]),
              S('Mandato de busca de comprador, de criação ou de mudança de mandato', 'F5',
                via=[T('Registrar o mandato e os contratos que ele alcança, sob sigilo', R)])]),
           T('Executar a parte de Negócios do plano de saída: encerrar, transferir ou manter cada contrato', P, 'manual'),
           T('Encerrar com os clientes as propostas e as negociações em curso', P, 'manual'),
           T('Conferir o encerramento ou a transferência de cada contrato', 'GOV'),
           D('Os contratos foram encerrados ou transferidos como planejado?', P,
             [S('Sim', 'F3', via=[T('Registrar os contratos encerrados ou transferidos e avisar a Integração e a Gestão', R)]),
              S('Não: há pendência', 'F6', via=[T('Apontar a pendência à Integração e ao executivo', R)])])],
          [('Contratos afetados pela saída', ['Integração']),
           ('Contratos encerrados ou transferidos na saída', ['Integração', 'Gestão']),
           ('Pendência de contrato na saída', ['Integração', 'Executivos'])]),
        E('Formalizar a renovação, o aditivo, a contratação pela ata ou o fim do contrato', 'Negócios, com a Governança; assina o executivo', 'Assistido', 'alto',
          [('Condições da renovação acordadas', 'etapa 2'), (MODELOS, 'Governança'), ('Pedido de contratação pela ata', 'Clientes')],
          [T('Redigir a renovação, o aditivo, o contrato pela ata ou o termo de encerramento, no modelo', A),
           D('O documento foge do modelo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Revisar as cláusulas fora do modelo e o risco do aditivo', 'GOV', 'call')])]),
           T('Conferir o documento final com o que foi acordado ou com a ata', P),
           T('Conferir os poderes de quem assina o documento', 'GOV'),
           T('Assinar o documento em nome da empresa', 'EXE'),
           T('Assinar o documento pelo cliente, quando a forma pede', 'CLI'),
           T('Guardar o documento assinado', 'GOV')],
          [('Renovação, aditivo, contratação ou encerramento assinado', ['etapa 5'])]),
        E('Registrar o resultado e avisar quem acompanha, entrega, implanta e fatura', 'Negócios', 'Autômato', 'baixo',
          [('Renovação, aditivo, contratação ou encerramento assinado', 'etapa 4')],
          [T('Registrar o novo escopo, o valor, a vigência e o vencimento, ou a data de fim', R),
           T('Abater do saldo da ata a contratação feita por ela, quando for o caso', R),
           D('O contrato continua?', R,
             [S('Sim', 'prox',
                via=[T('Avisar Relações, Operações, a Integração e a Gestão do que mudou no contrato', R)]),
              S('Não: contrato encerrado', 'F2',
                via=[T('Avisar Relações, Operações, a Integração e a Gestão do fim do contrato', R)])])],
          [(CONTRATO, ['Relações', 'Integração', 'Operações', 'Gestão']),
           ('Contrato encerrado, com a data de fim', ['Operações', 'Integração', 'Gestão']),
           (VENC, ['Relações', 'Gestão', 'NE-02']),
           (REGISTROS, ['Inteligência', 'NE-02'])]),
    ]))

# ===================================================== VENDA CONJUNTA
JORNADAS.append(dict(
    code='NE-07',
    nome='Vender com parceiros e em oferta conjunta entre as empresas',
    dominio='Venda conjunta', classe='essencial', onda=2,
    objetivo='Fazer a oportunidade trazida por um parceiro de venda ativo ser conferida com o critério combinado com Relações e com o funil e, aceita, chegar à proposta sem conflito; montar com outra empresa do Ecossistema a oferta conjunta quando o cliente de uma tem um problema que a outra resolve, com a divisão de receita e de responsabilidade decidida pelos executivos das duas empresas (exceção à regra de que o executivo opina, porque mexe no resultado de duas empresas) e formalizada pela Governança antes da proposta; e medir a venda com parceiros e conjunta. Relações forma, ativa e acompanha o parceiro; Negócios vende com ele.',
    frequencia='Por evento: oportunidade de parceiro ou oportunidade cruzada entre empresas; e na revisão da venda com parceiros (cadência: semestral)',
    automacao=('média', 'Registrar, conferir o funil e o parceiro, calcular o preço conjunto e medir são de agente e automação; aceitar a oportunidade do parceiro, desenhar a oferta conjunta e concluir a revisão são de pessoa de Negócios; a divisão é dos executivos.'),
    base=['apqc'],
    lanes=['PRC', 'EXE', 'GES', 'GOV', P, A, R],
    inicios=[I('Oportunidade indicada por parceiro de venda', 'PRC', 'message'),
             I('Oportunidade cruzada entre empresas apontada', 'EXE', 'message'),
             I('Revisão da venda com parceiros iniciada', R, 'timer')],
    fins=[F('Venda com parceiros e conjunta avaliada', R),
          F('Oportunidade do parceiro recusada, com o motivo', R),
          F('Oportunidade passada à proposta', R),
          F('Oferta conjunta sem acordo, com o motivo', R)],
    etapas=[
        E('Receber a oportunidade do parceiro ou de outra empresa', 'Negócios', 'Copiloto', 'médio',
          [('Oportunidade indicada por parceiro de venda', 'Parceiros'), ('Oportunidade cruzada entre empresas', 'Executivos'),
           (PARC_ATIVA, 'Relações'), (CRITERIO, 'Relações'), (FUNIL, 'Relações'), (BASE_REL, 'Relações'),
           (PLANO_VEN, 'NE-02'), (TABELA, 'NE-01'), ('Material de venda das ofertas', 'NE-01')],
          [T('Registrar a oportunidade, quem indicou e o que abriu o trabalho', R),
           D('O que abriu o trabalho?', R,
             [S('Oportunidade de parceiro de venda', 'seg'),
              S('Oportunidade cruzada entre empresas do Ecossistema', 'E2'),
              S('Revisão periódica da venda com parceiros', 'E3')]),
           T('Conferir a oportunidade com o critério, o funil e a base, e se o parceiro está ativo', A),
           T('Decidir se a oportunidade do parceiro segue para a proposta', P),
           D('A oportunidade é nova, atende ao critério e o parceiro está ativo?', P,
             [S('Sim', 'F3', via=[T('Passar a oportunidade do parceiro à proposta, com a regra de remuneração do parceiro', R)]),
              S('Não', 'F2', via=[T('Responder ao parceiro com o motivo', R)])])],
          [(OPORT_PARC, ['NE-03']),
           ('Resposta ao parceiro sobre a oportunidade', ['Parceiros'])]),
        E('Montar a oferta conjunta e combinar a divisão', 'Negócios das duas empresas; a divisão, os executivos', 'Assistido', 'alto',
          [('Oportunidade cruzada entre empresas', 'Executivos'), (OFERTA_CAT, 'Inteligência'), (TABELA, 'NE-01')],
          [T('Desenhar com a outra empresa o escopo, quem entrega o quê e quem fala com o cliente', P, 'manual'),
           T('Calcular o preço conjunto e propor a divisão de receita e de responsabilidade', A),
           T('Conferir o efeito da divisão no resultado de cada empresa', 'GES'),
           T('Decidir a divisão de receita e de responsabilidade entre as empresas', 'EXE'),
           D('Os executivos das duas empresas chegaram a acordo?', P,
             [S('Sim', 'F3',
                via=[T('Formalizar o acordo entre as empresas: divisão de receita, responsabilidade e rateio', 'GOV', 'call'),
                     T('Passar a oferta conjunta à proposta, com quem conduz a venda em cada empresa', R)]),
              S('Não', 'F4', via=[T('Registrar o motivo e devolver a oportunidade à empresa de origem', R)])])],
          [(OPORT_PARC, ['NE-03']),
           ('Acordo de oferta conjunta entre as empresas', ['Governança', 'Gestão', 'Executivos'])]),
        E('Medir a venda com parceiros e conjunta e rever o que mudar', 'Negócios', 'Copiloto', 'baixo',
          [(RES_PARC, 'Relações'), (REGISTROS, 'NE-04')],
          [T('Medir oportunidades, propostas, contratos e receita por parceiro e por oferta conjunta', A),
           T('Concluir o que manter, mudar ou encerrar na venda com cada parceiro', P),
           D('A venda com algum parceiro pede encerrar a parceria?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Pedir a Relações o encerramento da parceria de venda, com a evidência', R)])])],
          [(ENC_PARC, ['Relações']),
           ('Resultado da venda com parceiros e conjunta', ['Executivos', 'NE-02'])]),
    ]))
