# -*- coding: utf-8 -*-
"""Círculo 2 · Estratégia. Fechado em 01/10/2026, com as 18 mudanças aprovadas às 20:02: seis jornadas.
Regra: a Estratégia formula e propõe a direção, o portfólio, os alvos e a alocação, que os sócios aprovam;
decide, ouvido o executivo e dentro da alçada, a aposta que entra e a oferta que é lançada; e acompanha se as
hipóteses se confirmam. Na formulação, no portão, na mudança de papel e nas correções de execução, o executivo e o líder do círculo
propõem e participam, mas não decidem."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 2, 'Estratégia', 'ES', 'ES'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo2-estrategia'
FECHADO = True
STATUS = 'Fechado em 01/10/2026 · todas as mudanças aprovadas aplicadas em 02/10/2026 · auditoria de execução aplicada em 03/10/2026'
LEAD = ('A Estratégia faz o trabalho de estratégia de ponta a ponta: formula, propõe, desdobra em alvos, decide os '
        'portões dentro da alçada e acompanha as hipóteses. Na formulação, o executivo e o líder do círculo propõem e '
        'participam, mas não decidem. Os sócios aprovam. A Gestão opera a rotina: orçamento e ritual de '
        'acompanhamento. A Integração é o PMO corporativo e coordena projetos, implantações e lançamentos. '
        'São seis jornadas.')
PRINCIPIO = None
MUDOU_INTRO = ('Comparação com o catálogo da rodada 2 (49 jornadas e 216 workflows), que continua no documento do '
               'projeto até cada círculo ser fechado, e com a versão fechada às 15:48. As linhas marcadas “aprovada às '
               '20:02” incluem os acertos feitos em 02/10/2026, depois da revisão independente, para cada proposta '
               'funcionar. Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')

# produtos usados em mais de uma jornada
ESTRAT = 'Estratégia vigente do Ecossistema e das empresas'
DIRECAO = 'Direção estratégica e públicos prioritários'
PORTALVO = 'Portfólio-alvo: papel de cada empresa, oferta e aposta'
HIPOT = 'Hipóteses da estratégia e sinais a vigiar'
METODO = 'Método de estratégia vigente: critérios dos portões, regras de realocação e calendário'
MANTIDA = 'Diagnóstico e decisão de manter a estratégia'
ALOC = 'Alocação de recursos por empresa, oferta e aposta'
ALVOS = 'Alvos e iniciativas do ciclo'
ALVOS_PROP = 'Alvos propostos, para definição das fichas dos indicadores'
CARTEIRA = 'Situação da carteira de apostas'
SAIDA = 'Estudo de saída pedido para empresa, oferta ou aposta'
PORTF = 'Portfólio de empresas atualizado'
CAUSAS = 'Desvios com causa concluída'
AP_OFERTA = 'Aposta aprovada para desenho e validação da oferta, com recursos'
AP_EMPRESA = 'Aposta aprovada para empresa própria, com recursos'
OFERTA_LANC = 'Oferta aprovada para lançamento'
DEC_ENCERRAR = 'Decisão de encerrar aposta em desenvolvimento ou oferta em uso'
DATA_SAIDA = 'Data de saída confirmada da aposta ou da oferta encerrada'
PEDIDO_OFERTA = 'Pedido de ajuste ou de revisão de oferta em uso'
REVISAO_AP = 'Pedido de revisão da aposta ou da oferta'
CASO = 'Caso de criação, aquisição, venda ou encerramento'
ARQUIVADO = 'Caso arquivado, com o motivo'
LICAO_CASO = 'Lição do caso arquivado, sem dado sigiloso'
MANDATO = 'Mandato da empresa'
PERGUNTA = 'Pergunta de decisão, com a decisão apoiada, o risco e o prazo'
CONSULTA = 'Consulta sobre caso não coberto'
# produtos de outros círculos
DECL = 'Declaração de identidade vigente'
PADROES_ID = 'Padrões de identidade vigentes'
RESPOSTA_ID = 'Resposta à consulta'
RELAT = 'Relatório de alinhamento'
RESULT = 'Resultado por empresa e consolidado'
EXEC_ORC = 'Execução do orçamento e da alocação por empresa, oferta e aposta'
CAIXA = 'Posição e projeção de caixa'
INDIC = 'Indicadores e análises por empresa, oferta e aposta'
FICHAS_IND = 'Fichas dos indicadores decididas e confirmadas pelos donos'
RISCOS = 'Relatório de riscos e conformidade'
ALCADAS = 'Regras e alçadas vigentes'
LEITURA = 'Leitura de mercado, clientes e concorrentes'
RESPOSTA_IN = 'Resposta com evidência, fonte e grau de confiança'
DEVOLVIDA_IN = 'Aposta devolvida com evidência e recomendação'
PLANO_SAIDA = 'Plano de saída: clientes, contratos e pessoas'

JORNADAS = []

# ====================================================== DIREÇÃO E RECURSOS
JORNADAS.append(dict(
    code='ES-01',
    nome='Formular e revisar a estratégia do Ecossistema e de cada empresa',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Ter uma estratégia escrita e aprovada, do Ecossistema e de cada empresa, que diga onde atuar, o que não fazer e para quem, com as hipóteses de cada escolha, e que sirva de critério para alocar recursos e fixar alvos. Inclui as escolhas de cada círculo e o método de estratégia, que os sócios aprovam junto com a estratégia. A Estratégia formula; o executivo e o líder do círculo propõem e participam.',
    frequencia='A cada ciclo estratégico (cadência: anual, com revisão no meio do ciclo) e por evento: mudança relevante de cenário, empresa nova no portfólio ou revisão decidida na ES-06',
    automacao=('média', 'Decisão humana, de risco alto e pouco frequente. O agente reúne evidências, monta opções e confere a coerência; a escolha é de pessoas da Estratégia e a aprovação é dos sócios.'),
    base=['apqc', 'rumelt', 'kaplan', 'parenting', 'horizons', 'iia'],
    lanes=['INT', 'SOC', 'GOV', 'EXE', 'LCI', 'IDE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Mudança relevante de cenário apontada', 'INT', 'message'),
             I('Ciclo estratégico iniciado', 'ESR', 'timer'),
             I('Revisão do meio do ciclo iniciada', 'ESR', 'timer'),
             I('Revisão da estratégia decidida', 'ESR', 'message'),
             I('Empresa nova incluída no portfólio', 'ESR', 'message')],
    fins=[F('Estratégia aprovada e publicada', 'ESR'), F('Revisão encerrada sem mudança', 'ESR')],
    etapas=[
        E('Diagnosticar o cenário e a posição atual', 'Estratégia, com sócios, executivos e líderes dos círculos', 'Copiloto', 'médio',
          [(LEITURA, 'Inteligência'), ('Aviso de mudança relevante de cenário', 'Inteligência'),
           ('Aviso de leitura sem novidade', 'Inteligência'),
           (RESULT, 'Gestão'), (RISCOS, 'Governança'), (DECL, 'Identidade'), (RELAT, 'Identidade'),
           (ALOC, 'ES-02'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'), ('Revisão aberta da estratégia', 'ES-06'),
           ('Alvos atuais mantidos pelos sócios', 'ES-03')],
          [T('Abrir o ciclo com o calendário e o método vigentes', 'ESR'),
           T('Definir os participantes e as perguntas do diagnóstico', 'ESP'),
           T('Enviar as perguntas do diagnóstico à Inteligência', 'ESR'),
           T('Receber a leitura da Inteligência ou o aviso de leitura sem novidade', 'ESR', 'receive'),
           T('Reunir os dados internos e juntá-los à leitura da Inteligência', 'ESA'),
           T('Ouvir sócios, executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir o diagnóstico: o desafio central e as suas causas', 'ESP'),
           D('O diagnóstico pede mudar a estratégia?', 'ESP',
             [S('Sim', 'prox'),
              S('Só falta a estratégia de uma empresa nova', 'E3'),
              S('Não', 'E4', via=[T('Propor aos sócios manter a estratégia, com o diagnóstico', 'ESP')])])],
          [('Diagnóstico estratégico', ['etapa 2', 'etapa 3', 'etapa 4']),
           ('Perguntas do diagnóstico', ['Inteligência'])]),
        E('Formular as escolhas do Ecossistema: onde atuar e o que não fazer', 'Estratégia, com os executivos', 'Assistido', 'alto',
          [('Diagnóstico estratégico', 'etapa 1'), ('Decisão dos sócios sobre a estratégia', 'etapa 4'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Montar opções estratégicas e simular as consequências de cada uma', 'ESA'),
           T('Discutir as opções com os executivos', 'ESP', 'manual'),
           T('Escolher onde atuar, o que não fazer e a política que orienta as ações', 'ESP'),
           T('Definir o portfólio-alvo: o papel de cada empresa, oferta e aposta', 'ESP'),
           T('Escrever as hipóteses de cada escolha e os sinais que as confirmam ou refutam', 'ESP'),
           T('Definir os critérios dos portões, as regras de realocação e o critério de desvio grave', 'ESP'),
           T('Conferir as escolhas com a declaração e os critérios de decisão da identidade', 'ESA'),
           D('As escolhas são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E2'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira das escolhas estratégicas', 'IDE', 'call')])]),
           D('A Identidade considera as escolhas coerentes?', 'IDE', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Escolhas estratégicas, portfólio-alvo, hipóteses e método do Ecossistema', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Formular a estratégia de cada empresa e as escolhas de cada círculo', 'Estratégia, com executivos e líderes dos círculos', 'Copiloto', 'médio',
          [('Escolhas estratégicas, portfólio-alvo, hipóteses e método do Ecossistema', 'etapa 2'), ('Diagnóstico estratégico', 'etapa 1'),
           ('Decisão dos sócios sobre a estratégia', 'etapa 4'), (ESTRAT, 'etapa 5'), (PORTALVO, 'etapa 5'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Montar o rascunho da estratégia de cada empresa a partir das escolhas do Ecossistema', 'ESA'),
           PAR([T('Propor as escolhas da empresa: público, oferta e vantagem', 'EXE')],
               [T('Propor as escolhas do círculo: o que é serviço comum, o que construir e o que comprar', 'LCI')]),
           T('Formular a estratégia de cada empresa e de cada círculo, ouvidos o executivo e o líder', 'ESP'),
           D('O ciclo é de empresa nova no portfólio?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Definir o papel da empresa nova no portfólio-alvo', 'ESP')])]),
           T('Conferir a coerência entre empresas, círculos e as escolhas do Ecossistema', 'ESA'),
           D('Há conflito entre empresas, círculos ou com o Ecossistema?', 'ESP',
             [S('Não', 'seg'),
              S('Sim, e há acordo', 'seg', via=[T('Resolver o conflito com os executivos e líderes envolvidos', 'ESP', 'manual')]),
              S('Sim, e não há acordo', 'seg', via=[T('Registrar a divergência e as alternativas para decisão dos sócios', 'ESP')])]),
           T('Conferir as escolhas das empresas e dos círculos com os critérios da identidade', 'ESA'),
           D('As escolhas das empresas e dos círculos são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E3'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira das escolhas da empresa ou do círculo', 'IDE', 'call')])]),
           D('A Identidade considera coerentes as escolhas das empresas e dos círculos?', 'IDE', [S('Sim', 'prox'), S('Não', 'E3')])],
          [('Proposta de estratégia, com as hipóteses, o método e as divergências', ['etapa 4', 'etapa 5']),
           (CONSULTA, ['Identidade'])]),
        E('Aprovar a estratégia, as hipóteses e o método com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estratégia, com as hipóteses, o método e as divergências', 'etapa 3'), ('Diagnóstico estratégico', 'etapa 1')],
          [T('Levar à decisão dos sócios a proposta de estratégia, com as hipóteses e o método, ou a de mantê-la', 'GOV', 'call'),
           T('Decidir sobre a estratégia, as hipóteses, o método e as divergências', 'SOC', 'manual'),
           D('O que os sócios decidem sobre a estratégia?', 'SOC',
             [S('Proposta de mudança: aprovar a nova estratégia', 'prox'),
              S('Proposta de mudança: rever as escolhas do Ecossistema', 'E2'),
              S('Proposta de mudança: rever a estratégia de empresa ou de círculo', 'E3'),
              S('Proposta de mudança: manter a atual (não vale para empresa nova)', 'F2',
                via=[T('Registrar a decisão dos sócios de manter a estratégia atual em vez da proposta', 'ESR'),
                     T('Avisar a Governança, a Inteligência e quem abriu a revisão de que a estratégia se mantém', 'ESR')]),
              S('Proposta de manter: manter a estratégia atual', 'F2',
                via=[T('Registrar o diagnóstico e a decisão dos sócios de manter a estratégia atual', 'ESR'),
                     T('Avisar a Governança, a Inteligência e quem abriu a revisão de que a proposta de manter foi aprovada', 'ESR')]),
              S('Proposta de manter: formular a mudança', 'E2')])],
          [('Decisão dos sócios sobre a estratégia', ['etapa 5', 'etapa 2', 'etapa 3', 'Governança']),
           (MANTIDA, ['Sócios', 'Governança', 'Inteligência', 'ES-06'])]),
        E('Fechar o texto com a decisão dos sócios, publicar a estratégia e avisar quem depende dela', 'Estratégia', 'Copiloto', 'médio',
          [('Decisão dos sócios sobre a estratégia', 'etapa 4'),
           ('Proposta de estratégia, com as hipóteses, o método e as divergências', 'etapa 3')],
          [T('Incorporar ao texto a decisão dos sócios, inclusive sobre as divergências', 'ESA'),
           T('Resumir a direção e os públicos prioritários para cada círculo', 'ESA'),
           T('Aprovar o texto final, o resumo por círculo e o que pode ser dito para fora', 'ESP'),
           T('Registrar a versão e a data de vigência da estratégia', 'ESR'),
           T('Publicar a estratégia, o portfólio-alvo, as hipóteses e o método', 'ESR'),
           T('Avisar círculos e executivos e abrir as jornadas que dependem da estratégia', 'ESR')],
          [(ESTRAT, ['etapa 3', 'ES-02', 'ES-03', 'ES-04', 'ES-05', 'ES-06', 'Sócios', 'Executivos', 'Líderes dos círculos']),
           (DIRECAO, [TODOS, 'Identidade']),
           (PORTALVO, ['etapa 3', 'ES-02', 'ES-04', 'Executivos', 'Negócios', 'Inteligência']),
           (HIPOT, ['ES-06', 'Inteligência']),
           (METODO, ['ES-02', 'ES-03', 'ES-04', 'ES-06', 'Executivos', 'Líderes dos círculos', 'Inteligência', 'Gestão',
                     'Integração', 'Governança']),
           ('Mudança na estratégia a comunicar', ['Gestão', 'Relações'])]),
    ]))

JORNADAS.append(dict(
    code='ES-02',
    nome='Rever o portfólio e realocar recursos entre empresas, ofertas e apostas',
    dominio='Direção e recursos', classe='essencial', onda=2,
    objetivo='Decidir, a cada período, para onde vão dinheiro, pessoas e atenção: o que recebe mais, o que mantém, o que perde recursos e o que deve ter a saída estudada, e o destino do resultado de cada empresa. A proposta sobe sempre aos sócios, mesmo quando é manter a alocação.',
    frequencia='A cada fechamento de período (cadência: semestral) e por evento: estratégia nova ou revisão decidida na ES-06',
    automacao=('média', 'O agente compara o uso de recursos com o portfólio-alvo e simula realocações; a proposta é de pessoas da Estratégia e a decisão é dos sócios.'),
    base=['realloc', 'horizons', 'parenting', 'iia', 'apqc'],
    lanes=['GES', 'ASS', 'IDE', 'GOV', 'SOC', 'EXE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Resultado do período fechado', 'GES', 'message'),
             I('Nova estratégia publicada', 'ESR', 'message'),
             I('Revisão do portfólio decidida', 'ESR', 'message')],
    fins=[F('Alocação decidida ou mantida e comunicada', 'ESR')],
    etapas=[
        E('Ler o resultado e o uso de recursos de cada unidade do portfólio', 'Estratégia, com os executivos', 'Copiloto', 'baixo',
          [(RESULT, 'Gestão'), (EXEC_ORC, 'Gestão'), (INDIC, 'Inteligência'),
           (ESTRAT, 'ES-01'), (PORTALVO, 'ES-01'), (ALVOS, 'ES-03'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'),
           (ARQUIVADO, 'ES-05'), (CAUSAS, 'ES-06'), ('Revisão aberta do portfólio', 'ES-06'),
           ('Alvos atuais mantidos pelos sócios', 'ES-03')],
          [T('Comparar resultado e recursos usados com o papel de cada unidade no portfólio-alvo', 'ESA'),
           T('Interpretar a leitura com cada executivo', 'ESP', 'manual')],
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', ['etapa 2', 'Inteligência'])]),
        E('Propor a alocação e o destino do resultado', 'Estratégia, com assessoria', 'Copiloto', 'médio',
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', 'etapa 1'),
           ('Decisão de alocação e de destino do resultado', 'etapa 3'),
           (CAIXA, 'Gestão'), (METODO, 'ES-01'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Classificar cada unidade: semear, nutrir, podar ou colher', 'ESA'),
           T('Simular realocações de dinheiro, pessoas e capacidade dos círculos', 'ESA'),
           T('Avaliar os efeitos societários, fiscais e contábeis das alternativas', 'ASS'),
           T('Montar a proposta de alocação e de destino do resultado, mesmo quando é manter a atual', 'ESP'),
           D('A proposta muda o papel de alguma empresa, oferta ou aposta?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Opinar sobre a mudança de papel da sua empresa, oferta ou aposta', 'EXE'),
                                   T('Decidir a mudança de papel a propor, ouvido o executivo afetado', 'ESP')])]),
           T('Conferir a proposta com os critérios de decisão da identidade', 'ESA'),
           D('A proposta de alocação é coerente com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E2'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da proposta de alocação', 'IDE', 'call')])]),
           D('A Identidade considera a proposta de alocação coerente?', 'IDE', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Proposta de alocação e de destino do resultado', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir a alocação com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de alocação e de destino do resultado', 'etapa 2')],
          [T('Levar a proposta de alocação à decisão dos sócios', 'GOV', 'call'),
           T('Decidir a alocação e o destino do resultado', 'SOC', 'manual'),
           D('Alocação aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter a atual', 'prox', via=[T('Registrar a decisão dos sócios de manter a alocação atual e o destino do resultado', 'ESR')])])],
          [('Decisão de alocação e de destino do resultado', ['etapa 4', 'etapa 2', 'Governança', 'Gestão'])]),
        E('Comunicar a decisão e encaminhar a execução', 'Estratégia', 'Autopiloto', 'baixo',
          [('Decisão de alocação e de destino do resultado', 'etapa 3')],
          [T('Registrar a decisão e o limite de recursos de cada unidade', 'ESR'),
           T('Atualizar o portfólio-alvo com os papéis decididos', 'ESR'),
           T('Avisar a Gestão, os executivos, os círculos que usam o portfólio-alvo e quem abriu a revisão', 'ESR'),
           D('A alocação muda alvos ou orçamento, ou há desdobramento dos alvos à espera dela?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar a alocação decidida ao desdobramento dos alvos', 'ESR')])]),
           D('A decisão manda estudar a saída de empresa, oferta ou aposta?', 'ESR',
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Comunicar o estudo de saída ao executivo afetado', 'ESP', 'manual'),
                                    T('Abrir o estudo de saída: empresa na ES-05, oferta ou aposta na ES-04', 'ESR')])])],
          [(ALOC, ['ES-01', 'ES-03', 'ES-04', 'ES-06', 'Gestão', 'Executivos']),
           (PORTALVO, ['ES-04', 'Executivos', 'Negócios', 'Inteligência']),
           (SAIDA, ['ES-04', 'ES-05'])]),
    ]))

JORNADAS.append(dict(
    code='ES-03',
    nome='Desdobrar a estratégia em alvos e iniciativas de cada empresa e de cada círculo',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Transformar a estratégia em poucos alvos mensuráveis do Ecossistema, de cada empresa e de cada círculo, com iniciativas, dono e indicador, combinados de cima para baixo e de baixo para cima; pedir à Inteligência a ficha do indicador de cada alvo antes da aprovação; e conferir com a Gestão e a Integração se os alvos cabem nos recursos.',
    frequencia='A cada ciclo de alvos (cadência: anual, com o ciclo) e por evento: estratégia nova, portfólio de empresas atualizado, alocação que muda alvos ou orçamento, ou correção decidida na ES-06',
    automacao=('média', 'O agente desdobra, confere a soma e aponta conflitos; a negociação dos alvos é entre pessoas e a aprovação é dos sócios.'),
    base=['kaplan', 'okr', 'lei', 'rumelt', 'iia', 'apqc'],
    lanes=['SOC', 'GOV', 'EXE', 'LCI', 'IDE', 'GES', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ciclo de alvos iniciado', 'ESR', 'timer'),
             I('Nova estratégia publicada', 'ESR', 'message'),
             I('Portfólio de empresas atualizado', 'ESR', 'message'),
             I('Alocação que muda alvos ou orçamento decidida', 'ESR', 'message'),
             I('Novo desdobramento dos alvos decidido', 'ESR', 'message')],
    fins=[F('Alvos aprovados e publicados', 'ESR'), F('Alvos anteriores mantidos', 'ESR')],
    etapas=[
        E('Propor os alvos do Ecossistema', 'Estratégia', 'Copiloto', 'médio',
          [(ESTRAT, 'ES-01'), (METODO, 'ES-01'), (ALOC, 'ES-02'), (PORTF, 'ES-05'),
           ('Revisão aberta dos alvos', 'ES-06'), (INDIC, 'Inteligência'),
           ('Definição do que conta como impacto', 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [D('O desdobramento espera uma alocação que ainda não chegou?', 'ESR',
             [S('Não', 'seg'),
              S('Sim: estratégia nova ou empresa nova, sem alocação decidida ou mantida', 'seg',
                via=[T('Receber a alocação decidida ou mantida depois da nova estratégia', 'ESR', 'receive')])]),
           T('Traduzir as escolhas em poucos objetivos com resultados mensuráveis', 'ESA'),
           T('Escolher os alvos do Ecossistema e o que fica de fora', 'ESP'),
           T('Conferir os alvos com os critérios da identidade e a definição do que conta como impacto', 'ESA'),
           D('Os alvos propostos são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E1'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira dos alvos propostos', 'IDE', 'call')])]),
           D('A Identidade considera os alvos propostos coerentes?', 'IDE', [S('Sim', 'prox'), S('Não', 'E1')])],
          [('Alvos propostos do Ecossistema', ['etapa 2']),
           (CONSULTA, ['Identidade'])]),
        E('Combinar os alvos e as iniciativas com cada empresa e cada círculo', 'Estratégia, com executivos, líderes dos círculos e Inteligência', 'Assistido', 'médio',
          [('Alvos propostos do Ecossistema', 'etapa 1'), ('O que não cabe nos recursos, a renegociar', 'etapa 3'),
           ('Decisão dos sócios sobre alvos e orçamento', 'etapa 4'), (FICHAS_IND, 'Inteligência')],
          [PAR([T('Propor os alvos e as iniciativas da empresa', 'EXE')],
               [T('Propor os alvos e as iniciativas do círculo', 'LCI')]),
           T('Conferir a soma, os conflitos e as dependências entre os alvos', 'ESA'),
           T('Negociar os ajustes com executivos e líderes dos círculos', 'ESP', 'manual'),
           D('Há alvo novo ou alterado sem ficha de indicador?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar à Inteligência os alvos novos ou alterados, para a ficha do indicador de cada um', 'ESR'),
                                   T('Receber o conjunto das fichas dos indicadores dos alvos propostos', 'ESR', 'receive')])]),
           D('Cada alvo proposto tem indicador com dado confiável?', 'ESP',
             [S('Sim', 'seg'),
              S('Não, trocar o alvo', 'E2'),
              S('Não, manter com ficha provisória ou adiar', 'seg',
                via=[T('Marcar na proposta o alvo com ficha provisória ou adiado', 'ESP')])]),
           D('Os alvos somam e não conflitam?', 'ESP',
             [S('Sim', 'prox'), S('Não, renegociar', 'E2'),
              S('Não, sem acordo', 'prox', via=[T('Registrar a divergência sobre os alvos para decisão dos sócios', 'ESP')])])],
          [('Alvos e iniciativas combinados', ['etapa 3']),
           (ALVOS_PROP, ['Inteligência'])]),
        E('Conferir com a Gestão e a Integração se os alvos cabem nos recursos', 'Estratégia, com Gestão e Integração', 'Copiloto', 'médio',
          [('Alvos e iniciativas combinados', 'etapa 2'), (CAIXA, 'Gestão')],
          [T('Montar o orçamento do ciclo a partir dos alvos e da alocação', 'GES', 'call'),
           T('Conferir a capacidade de executar as iniciativas na carteira de projetos', 'ITG'),
           T('Apontar o que não cabe no orçamento ou na capacidade', 'ESA'),
           T('Confirmar se os alvos e as iniciativas cabem nos recursos', 'ESP'),
           D('Alvos e iniciativas cabem nos recursos?', 'ESP',
             [S('Sim', 'prox'), S('Não, renegociar', 'E2'),
              S('Não, e não há acordo', 'prox', via=[T('Montar as alternativas de alvos e de recursos para decisão dos sócios', 'ESP')])])],
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão e as alternativas', ['etapa 4']),
           ('O que não cabe nos recursos, a renegociar', ['etapa 2'])]),
        E('Aprovar os alvos e o orçamento com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão e as alternativas', 'etapa 3')],
          [T('Levar a proposta de alvos e orçamento à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre os alvos, o orçamento e as divergências', 'SOC', 'manual'),
           D('Alvos e orçamento aprovados?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter os atuais', 'F2', via=[T('Registrar a decisão dos sócios de manter os alvos atuais e avisar quem abriu o desdobramento', 'ESR')])])],
          [('Decisão dos sócios sobre alvos e orçamento', ['etapa 5', 'etapa 2', 'Governança', 'Gestão']),
           ('Alvos atuais mantidos pelos sócios', ['ES-01', 'ES-02', 'ES-06'])]),
        E('Publicar os alvos e entregar ao ritual de acompanhamento', 'Estratégia, com Gestão', 'Autômato', 'baixo',
          [('Decisão dos sócios sobre alvos e orçamento', 'etapa 4')],
          [T('Registrar alvos, iniciativas, donos e indicadores no painel único', 'ESR'),
           T('Avisar executivos, líderes dos círculos e donos das iniciativas', 'ESR'),
           T('Incluir os alvos no ritual de acompanhamento', 'GES')],
          [(ALVOS, [TODOS, 'ES-02', 'ES-06', 'Gestão', 'Integração', 'Inteligência'])]),
    ]))

# ====================================================== APOSTAS E EMPRESAS
JORNADAS.append(dict(
    code='ES-04',
    nome='Decidir em cada portão se uma aposta avança, espera, volta para ajuste ou é encerrada',
    dominio='Apostas e empresas', classe='essencial', onda=2,
    objetivo='Fazer cada ideia, oferta ou negócio novo passar por decisões explícitas antes de receber recursos: entrar na carteira e, depois de produtizada pela Inteligência, ser lançada. Em qualquer portão ou revisão, a aposta pode avançar, seguir como está, esperar, voltar para ajuste ou ser encerrada. A Estratégia decide, ouvido o executivo, dentro da alçada; decidem os sócios quando os recursos passam da alçada, quando se encerra oferta com contratos vigentes e quando a decisão contraria o portfólio-alvo. Encerrar aposta em desenvolvimento ou oferta em uso só termina com o plano de saída conferido, a data de saída decidida por pessoa e a saída conferida.',
    frequencia='Por evento: ideia nova, aposta definida no portfólio-alvo, oferta pronta para lançar, aposta devolvida pela Inteligência, revisão pedida (a de oferta em uso chega pela Inteligência ou pela ES-06), estudo de saída pedido na ES-02, caso de empresa nascido de aposta e arquivado na ES-05, ou data de revisão ou de retomada da aposta',
    automacao=('alta na entrada e na preparação, baixa na decisão', 'Registrar, completar o dossiê, estimar e encaminhar rodam com agente e automação; a decisão do portão e a data de saída são de pessoas.'),
    base=['stagegate', 'horizons', 'dmn', 'apqc'],
    lanes=['SOL', 'INT', 'IDE', 'GOV', 'SOC', 'EXE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ideia ou aposta nova recebida', 'SOL', 'message'),
             I('Revisão de aposta ou pedido sobre oferta em uso recebido', 'SOL', 'message'),
             I('Oferta pronta para lançamento recebida', 'INT', 'message'),
             I('Aposta devolvida pela Inteligência recebida', 'INT', 'message'),
             I('Revisão de oferta em uso enviada pela Inteligência', 'INT', 'message'),
             I('Aposta nova definida no portfólio-alvo', 'ESR', 'message'),
             I('Estudo de saída de oferta ou aposta pedido', 'ESR', 'message'),
             I('Caso de empresa nascido de aposta arquivado', 'ESR', 'message'),
             I('Data de revisão ou de retomada da aposta atingida', 'ESR', 'timer')],
    fins=[F('Aposta aprovada para o estágio seguinte', 'ESR'),
          F('Aposta encerrada com lição registrada', 'ESR'),
          F('Aposta em espera', 'ESR'),
          F('Aposta devolvida para ajuste', 'ESR'),
          F('Aposta mantida depois da revisão', 'ESR'),
          F('Pedido sobre oferta em uso encaminhado à Inteligência', 'ESR'),
          F('Aposta encerrada com pendência de saída apontada', 'ESR')],
    etapas=[
        E('Registrar a aposta e completar o dossiê', 'Estratégia', 'Autopiloto', 'baixo',
          [('Ideia ou aposta nova', 'Solicitante'), (REVISAO_AP, 'Solicitante'), (REVISAO_AP, 'Inteligência'), (REVISAO_AP, 'ES-06'),
           (PEDIDO_OFERTA, 'Solicitante'),
           ('Pacote da oferta pronta para lançamento', 'Inteligência'), (DEVOLVIDA_IN, 'Inteligência'),
           (PORTALVO, 'ES-01'), (PORTALVO, 'ES-02'), (SAIDA, 'ES-02'), (ARQUIVADO, 'ES-05')],
          [T('Registrar a aposta, o que abriu o trabalho e o portão ou a revisão pedida', 'ESR'),
           D('O que abriu o trabalho?', 'ESR',
             [S('Ideia ou aposta nova', 'seg'),
              S('Aposta na carteira, oferta pronta para lançamento ou revisão vinda da Inteligência ou da ES-06', 'E2',
                via=[T('Reunir da carteira o dossiê, a decisão anterior e os recursos já aprovados', 'ESR')]),
              S('Pedido direto sobre oferta em uso, que não passou pela Inteligência', 'F6',
                via=[T('Encaminhar à Inteligência o pedido sobre oferta em uso, para separar ajuste de revisão', 'ESR')])]),
           T('Completar o dossiê: problema, público, hipótese, dono, estágio e recursos pedidos', 'ESA'),
           D('O dossiê tem o mínimo para avaliar?', 'ESA',
             [S('Sim', 'prox'),
              S('Não', 'F4', via=[T('Devolver a aposta a quem propôs com o que falta', 'ESR')])])],
          [('Dossiê da aposta', ['etapa 2']),
           ('Aposta devolvida com o que falta', ['Solicitante']),
           (PEDIDO_OFERTA, ['Inteligência'])]),
        E('Avaliar a aposta contra os critérios do portão', 'Estratégia, com Inteligência', 'Copiloto', 'médio',
          [('Dossiê da aposta', 'etapa 1'), (RESPOSTA_IN, 'Inteligência'), ('Pergunta devolvida com o motivo', 'Inteligência'),
           (INDIC, 'Inteligência'), (EXEC_ORC, 'Gestão'),
           (ESTRAT, 'ES-01'), (METODO, 'ES-01'), (ALOC, 'ES-02'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [D('A avaliação pede evidência que o dossiê não traz?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar à Inteligência a pergunta de decisão do portão, com o risco e o prazo', 'ESR'),
                                   T('Receber a resposta com evidência sobre a aposta, ou a pergunta devolvida', 'ESR', 'receive')])]),
           T('Estimar tamanho, esforço, risco e retorno com a evidência, os indicadores e o gasto', 'ESA'),
           T('Conferir o encaixe com a estratégia, o portfólio-alvo e os critérios da identidade', 'ESA'),
           D('A aposta é coerente com a identidade?', 'ESP',
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Registrar na avaliação o ponto em que a aposta contraria a identidade', 'ESA')]),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da aposta', 'IDE', 'call'),
                                                 T('Registrar na avaliação o parecer da Identidade sobre a aposta', 'ESA')])]),
           T('Conferir os recursos pedidos contra o limite da alocação vigente', 'ESR', 'rule'),
           T('Conferir a evidência contra o critério do portão', 'ESP'),
           T('Recomendar a decisão do portão ou da revisão; o que contraria a identidade não avança', 'ESP')],
          [('Avaliação da aposta com recomendação', ['etapa 3']),
           (PERGUNTA, ['Inteligência']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir o destino da aposta no portão ou na revisão', 'Estratégia, ouvido o executivo, ou os sócios', 'Copiloto', 'alto',
          [('Avaliação da aposta com recomendação', 'etapa 2'), (ALCADAS, 'Governança'),
           ('Plano de saída que mostra que encerrar não é viável', 'etapa 4')],
          [T('Aplicar a tabela de alçadas aos recursos pedidos e ao tipo de decisão', 'ESR', 'rule'),
           T('Marcar a aposta com incoerência registrada com a identidade como impedida de avançar', 'ESR', 'rule'),
           T('Apresentar a avaliação e a recomendação a quem decide', 'ESP', 'manual'),
           D('A decisão passa da alçada da Estratégia pelos recursos ou pelo tipo?', 'ESR',
             [S('Não', 'seg', via=[T('Opinar sobre o destino da aposta e se ela vira oferta ou empresa própria', 'EXE'),
                                   T('Decidir o destino da aposta e se ela vira oferta ou empresa própria, ouvido o executivo', 'ESP')]),
              S('Sim: recursos acima da alçada, encerramento de oferta com contratos vigentes ou decisão contra o portfólio-alvo', 'seg',
                via=[T('Levar a aposta à decisão dos sócios', 'GOV', 'call'),
                                   T('Decidir o destino da aposta pelos sócios', 'SOC', 'manual')])]),
           D('Qual é a decisão do portão ou da revisão?', 'ESR',
             [S('Avança, se não há impedimento de identidade: oferta, lançamento, empresa própria ou parceria levada por Relações', 'E5'),
              S('Encerra aposta em desenvolvimento ou oferta em uso', 'prox',
                via=[T('Enviar a decisão de encerrar a quem desenha, vende e entrega, para parar novas vendas', 'ESR')]),
              S('Encerra aposta que ainda não entrou em desenvolvimento', 'F2',
                via=[T('Registrar na carteira a lição da aposta encerrada e os recursos a devolver', 'ESA')]),
              S('Segue como está', 'F5',
                via=[T('Registrar a revisão e a data da próxima e avisar a Inteligência, a Gestão e Relações', 'ESR')]),
              S('Espera', 'F3',
                via=[T('Registrar a condição e a data de retomada e avisar a Inteligência e a Gestão', 'ESR')]),
              S('Volta para ajuste', 'F4', via=[T('Devolver a aposta com os ajustes pedidos', 'ESR')])])],
          [('Decisão do portão', ['etapa 4', 'etapa 5', 'Governança', 'Integração']),
           (DEC_ENCERRAR, ['Inteligência', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Integração']),
           ('Lição da aposta encerrada', ['Inteligência', 'Solicitante', 'Relações']),
           ('Recursos da aposta encerrada a devolver', ['Gestão']),
           ('Aposta em espera ou devolvida', ['Solicitante', 'Inteligência', 'Gestão', 'Relações']),
           ('Aposta mantida depois da revisão', ['Solicitante', 'Inteligência', 'Gestão', 'Executivos', 'Relações']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
        E('Encerrar aposta em desenvolvimento ou oferta em uso, com o plano de saída', 'Estratégia, ouvido o executivo, com a Integração', 'Copiloto', 'alto',
          [('Decisão do portão', 'etapa 3'), ('Plano de saída da oferta: clientes e contratos', 'Integração'),
           ('Conclusão do plano de saída da oferta', 'Integração')],
          [T('Pedir à Integração o plano de saída dos clientes e dos contratos da aposta ou da oferta', 'ESR'),
           T('Receber o plano de saída coordenado pela Integração', 'ESR', 'receive'),
           T('Opinar sobre o plano de saída e a data de saída', 'EXE'),
           T('Conferir o plano de saída e decidir a data de saída, ouvido o executivo', 'ESP'),
           D('O plano de saída serve?', 'ESP',
             [S('Sim', 'seg'), S('Não, refazer o plano', 'E4'),
              S('Não: o plano mostra que encerrar não é viável', 'E3')]),
           T('Registrar na carteira a lição, a data de saída e os recursos a devolver', 'ESA'),
           T('Enviar a data de saída a quem desenha, vende, entrega e coordena o plano de saída', 'ESR'),
           D('A oferta encerrada tem marca própria?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir à Identidade a retirada da marca da oferta, com a data de efeito', 'ESR')])]),
           T('Receber da Integração a conclusão do plano de saída', 'ESR', 'receive'),
           T('Conferir a saída contra o plano', 'ESP'),
           D('A saída foi concluída como planejado?', 'ESP',
             [S('Sim', 'F2'),
              S('Não', 'F7', via=[T('Registrar a pendência da saída e apontá-la ao executivo e à Integração', 'ESR')])])],
          [(DATA_SAIDA, ['Inteligência', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Integração', 'Gestão']),
           ('Pedido de plano de saída da oferta: clientes e contratos', ['Integração']),
           ('Pedido de retirada de marca', ['Identidade']),
           ('Lição da aposta encerrada', ['Inteligência', 'Solicitante']),
           ('Recursos da aposta encerrada a devolver', ['Gestão']),
           ('Pendência da saída da oferta encerrada', ['Executivos', 'Integração']),
           ('Plano de saída que mostra que encerrar não é viável', ['etapa 3']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
        E('Registrar a decisão e passar a aposta ao dono do estágio seguinte', 'Estratégia', 'Autômato', 'baixo',
          [('Decisão do portão', 'etapa 3')],
          [T('Registrar na carteira a decisão, os recursos aprovados e a data da próxima revisão', 'ESR'),
           D('Qual é o estágio seguinte decidido no portão?', 'ESR',
             [S('Desenho e validação da oferta', 'seg', via=[T('Passar a aposta à Inteligência para desenhar e validar a oferta', 'ESR')]),
              S('Lançamento', 'seg', via=[T('Avisar a Integração, que coordena o lançamento, e o executivo da empresa', 'ESR')]),
              S('Empresa própria', 'seg', via=[T('Abrir a jornada de criação de empresa', 'ESR')]),
              S('Parceria levada por Relações como aposta', 'seg',
                via=[T('Devolver a Relações a parceria aprovada, para formalizar', 'ESR')])]),
           T('Avisar a Gestão dos recursos aprovados', 'ESR')],
          [(AP_OFERTA, ['Inteligência']),
           (AP_EMPRESA, ['ES-05']),
           ('Parceria aprovada no portão, para formalizar', ['Relações']),
           (OFERTA_LANC, ['Integração', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Inteligência']),
           ('Recursos aprovados para a aposta', ['Gestão']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
    ]))

JORNADAS.append(dict(
    code='ES-05',
    nome='Decidir e estruturar a criação, a aquisição, a venda ou o encerramento de uma empresa',
    dominio='Apostas e empresas', classe='essencial', onda=3,
    objetivo='Decidir com um caso escrito se o Ecossistema cria, adquire, vende ou encerra uma empresa; obter dos sócios a autorização para negociar e, depois, a decisão, inclusive a de arquivar o caso que eles mandaram estudar ou cuja negociação autorizaram; firmar o contrato, quando há; emitir o mandato para os círculos que executam; e conferir o cumprimento. A Integração executa o mandato; a Estratégia confere.',
    frequencia='Rara: por evento',
    automacao=('média', 'Decisão dos sócios, rara e de risco alto. O agente monta o caso, os cenários e o mandato e confere a execução.'),
    base=['apqc', 'parenting', 'realloc', 'iia'],
    lanes=['SOL', 'SOC', 'ASS', 'GOV', 'GES', 'IDE', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Oportunidade de aquisição ou de venda recebida', 'SOL', 'message'),
             I('Aposta aprovada para empresa própria', 'ESR', 'message'),
             I('Estudo de saída de empresa pedido', 'ESR', 'message')],
    fins=[F('Mandato cumprido e portfólio atualizado', 'ESR'), F('Caso arquivado com o motivo', 'ESR')],
    etapas=[
        E('Montar o caso: por que criar, adquirir, vender ou encerrar', 'Estratégia, com quem propôs e Inteligência', 'Copiloto', 'médio',
          [(AP_EMPRESA, 'ES-04'), (SAIDA, 'ES-02'), ('Oportunidade de aquisição ou de venda', 'Solicitante'),
           (ESTRAT, 'ES-01'), (RESPOSTA_IN, 'Inteligência'), ('Pergunta devolvida com o motivo', 'Inteligência'),
           (RESULT, 'Gestão'), (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade'),
           ('Decisão dos sócios sobre a empresa', 'etapa 5')],
          [T('Enviar à Inteligência a pergunta de decisão do caso, com o risco e o prazo', 'ESR'),
           T('Receber a resposta com evidência sobre o caso, ou a pergunta devolvida', 'ESR', 'receive'),
           T('Montar o caso e os cenários, incluindo a alternativa de não mudar', 'ESA'),
           T('Conferir se o caso cabe na estratégia', 'ESA'),
           T('Concluir o caso com quem propôs', 'ESP'),
           D('O caso se sustenta?', 'ESP',
             [S('Sim', 'seg'),
              S('Não, e os sócios pediram o estudo ou já autorizaram a negociação', 'E5',
                via=[T('Propor aos sócios arquivar o caso, com o motivo', 'ESP')]),
              S('Não, nos demais casos', 'F2', via=[T('Redigir a lição do caso arquivado, sem dado sigiloso', 'ESP'),
                                                    T('Arquivar o caso com o motivo e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])]),
           T('Conferir o caso com os critérios de decisão da identidade', 'ESA'),
           D('O caso é coerente com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não, rever o caso', 'E1'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da empresa', 'IDE', 'call')])]),
           D('A Identidade considera o caso coerente?', 'IDE', [S('Sim', 'prox'), S('Não, rever o caso', 'E1')])],
          [(CASO, ['etapa 2', 'etapa 3', 'etapa 4', 'etapa 5']),
           ('Proposta de arquivar o caso, com o motivo', ['etapa 5']),
           (PERGUNTA, ['Inteligência']),
           (CONSULTA, ['Identidade']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Obter dos sócios a autorização para negociar, com limites', 'Governança, com os sócios', 'Assistido', 'alto',
          [(CASO, 'etapa 1')],
          [D('O caso é de aquisição ou de venda?', 'ESP', [S('Não', 'prox'), S('Sim', 'seg')]),
           T('Propor os limites de preço e de condições da negociação', 'ESP'),
           T('Levar aos sócios o pedido de autorização para negociar, com os limites propostos', 'GOV', 'call'),
           T('Decidir a autorização para negociar e os limites de preço e de condições', 'SOC', 'manual'),
           D('Os sócios autorizaram a negociação?', 'SOC',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Redigir a lição do caso que os sócios não autorizaram, sem dado sigiloso', 'ESP'),
                                  T('Arquivar o caso sem autorização e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Autorização dos sócios para negociar, com os limites', ['etapa 3', 'Governança']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Apurar a empresa ou o negócio e negociar com a outra parte, quando houver', 'Estratégia, com Governança e Gestão', 'Assistido', 'alto',
          [(CASO, 'etapa 1'), ('Autorização dos sócios para negociar, com os limites', 'etapa 2'),
           ('Decisão dos sócios sobre a empresa', 'etapa 5')],
          [D('Qual é o caso?', 'ESR',
             [S('Criação de empresa nova', 'prox'),
              S('Encerramento, ou venda ainda sem comprador', 'seg'),
              S('Aquisição, ou venda com comprador identificado', 'seg',
                via=[T('Firmar o acordo de confidencialidade com a outra parte', 'GOV', 'call')])]),
           PAR([T('Apurar contratos, obrigações e riscos da empresa ou do negócio', 'GOV', 'call')],
               [T('Apurar contas e pessoas da empresa ou do negócio', 'GES', 'call')]),
           T('Consolidar o resultado da apuração para decidir se o caso segue', 'ESP'),
           D('Há outra parte com quem negociar?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Negociar preço e condições com a outra parte, dentro dos limites dos sócios', 'ESP', 'manual')])]),
           D('A apuração e a negociação mantêm o caso?', 'ESP',
             [S('Sim', 'prox'),
              S('Não, e os sócios autorizaram a negociação ou pediram o estudo', 'E5',
                via=[T('Propor aos sócios arquivar o caso depois da apuração, com o motivo', 'ESP')]),
              S('Não, nos demais casos', 'F2',
                via=[T('Redigir a lição do caso arquivado depois da apuração, sem o que é confidencial', 'ESP'),
                     T('Arquivar o caso depois da apuração e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Resultado da apuração e termos negociados', ['etapa 4', 'etapa 5']),
           ('Proposta de arquivar o caso, com o motivo', ['etapa 5']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Propor a estrutura societária e de governança', 'Estratégia, com Governança e assessoria', 'Assistido', 'alto',
          [(CASO, 'etapa 1'), ('Resultado da apuração e termos negociados', 'etapa 3'),
           ('Decisão dos sócios sobre a empresa', 'etapa 5'), ('Pedido de mudança do mandato', 'etapa 8'),
           (ALCADAS, 'Governança')],
          [T('Comparar estruturas societárias e de governança', 'ESA'),
           T('Avaliar os efeitos jurídicos, fiscais e contábeis', 'ASS'),
           T('Conferir a estrutura com as regras e os riscos', 'GOV'),
           T('Decidir a estrutura e o executivo a propor', 'ESP')],
          [('Proposta de estrutura', ['etapa 5'])]),
        E('Aprovar o caso e a estrutura com os sócios e firmar o contrato, quando houver', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estrutura', 'etapa 4'), ('Proposta de arquivar o caso, com o motivo', 'etapa 1'),
           ('Proposta de arquivar o caso, com o motivo', 'etapa 3'), (CASO, 'etapa 1'),
           ('Resultado da apuração e termos negociados', 'etapa 3')],
          [T('Levar à decisão dos sócios o caso e a estrutura, ou a proposta de arquivar o caso', 'GOV', 'call'),
           T('Decidir sobre a criação, a aquisição, a venda, o encerramento ou o arquivamento do caso', 'SOC', 'manual'),
           D('O que os sócios decidem sobre o caso?', 'SOC',
             [S('Proposta de estrutura: aprovar o caso e a estrutura', 'seg'),
              S('Proposta de estrutura: rever a estrutura', 'E4'),
              S('Proposta de estrutura: renegociar', 'E3'),
              S('Proposta de estrutura: manter o mandato já em execução', 'E7'),
              S('Proposta de arquivar: arquivar', 'F2',
                via=[T('Redigir a lição do caso que os sócios decidiram arquivar, sem dado sigiloso', 'ESP'),
                     T('Registrar o arquivamento pelos sócios e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')]),
              S('Proposta de arquivar: estudar de novo', 'E1'),
              S('Proposta de estrutura: arquivar (só antes de haver mandato em execução)', 'F2', via=[T('Redigir a lição do caso que os sócios decidiram não seguir, sem dado sigiloso', 'ESP'),
                                            T('Registrar a decisão de não seguir e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])]),
           D('O caso aprovado tem contrato a firmar com outra parte?', 'ESR',
             [S('Não: criação, encerramento, venda ainda sem comprador ou contrato já assinado', 'prox'),
              S('Sim: aquisição, ou venda com comprador', 'seg')]),
           T('Preparar o contrato de compra ou venda dentro do que os sócios decidiram', 'GOV', 'call'),
           T('Assinar o contrato de compra ou venda', 'SOC', 'manual'),
           D('O contrato foi assinado?', 'SOC',
             [S('Sim', 'prox'),
              S('Não, renegociar com a outra parte', 'E3'),
              S('Não, desistir', 'F2', via=[T('Redigir a lição do caso em que o contrato não foi assinado, sem o que é confidencial', 'ESP'),
                                            T('Arquivar o caso sem contrato e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Decisão dos sócios sobre a empresa', ['etapa 6', 'etapa 4', 'etapa 3', 'etapa 1', 'Governança']),
           ('Contrato de compra ou venda assinado', ['etapa 6', 'Governança']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Emitir o mandato para os círculos que executam', 'Estratégia', 'Copiloto', 'alto',
          [('Decisão dos sócios sobre a empresa', 'etapa 5'), ('Contrato de compra ou venda assinado', 'etapa 5'),
           (PLANO_SAIDA, 'Integração')],
          [T('Redigir o mandato: objetivo, estrutura, recursos, prazos e donos', 'ESA'),
           T('Definir com a Gestão o responsável e a equipe da execução', 'ESP', 'manual'),
           D('O mandato é novo ou muda um mandato já emitido?', 'ESR',
             [S('Muda um mandato já emitido', 'seg'),
              S('Novo, de busca de comprador para venda ainda sem comprador', 'seg'),
              S('Novo, de criação ou aquisição', 'seg', via=[T('Pedir a identidade e a marca da empresa, com a data de efeito', 'ESR')]),
              S('Novo, de venda com comprador ou de encerramento', 'seg',
                via=[T('Pedir à Integração o plano de saída: clientes, contratos e pessoas', 'ESR'),
                     T('Receber o plano de saída coordenado pela Integração', 'ESR', 'receive'),
                     T('Conferir o plano de saída e incluí-lo no mandato', 'ESP'),
                     T('Pedir a retirada da marca da empresa, com a data de efeito', 'ESR')])]),
           T('Aprovar o mandato', 'ESP'),
           T('Enviar o mandato a cada círculo que executa', 'ESR')],
          [(MANDATO, ['etapa 7', 'etapa 8', 'Integração', 'Governança', 'Gestão', 'Relações', 'Negócios', 'Operações',
                      'Inteligência', 'Executivos']),
           ('Pedido de identidade para empresa nova', ['Identidade']),
           ('Pedido de marca', ['Identidade']),
           ('Lista de pessoas da empresa adquirida', ['Gestão']),
           ('Pedido de plano de saída: clientes, contratos e pessoas', ['Integração']),
           ('Pedido de retirada de marca', ['Identidade'])]),
        E('Executar o mandato até a empresa operar ou sair do portfólio', 'Integração, como PMO corporativo, com Governança e Gestão', 'Assistido', 'alto',
          [(MANDATO, 'etapa 6'), ('Execução do mandato a completar', 'etapa 8'),
           ('Decisão sobre a marca do negócio', 'Identidade'), ('Pacote de marca publicado', 'Identidade'),
           ('Marca retirada de uso', 'Identidade'), (DECL, 'Identidade')],
          [T('Coordenar a execução do mandato, ou do que falta dele, entre os círculos', 'ITG', 'call'),
           T('Registrar a constituição, a alteração ou o encerramento da empresa', 'GOV', 'call'),
           PAR([T('Prover ou desmobilizar responsável, pessoas, contas e orçamento', 'GES', 'call')],
               [T('Ligar a empresa aos círculos ou desligá-la: acessos e acordos de serviço', 'ITG')]),
           D('A Identidade já entregou a marca ou confirmou a retirada?', 'ESR',
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Receber da Identidade a marca pronta ou a confirmação da retirada na data de efeito', 'ESR', 'receive')])]),
           T('Informar à Estratégia a situação da execução do mandato', 'ITG')],
          [('Situação da execução do mandato', ['etapa 8'])]),
        E('Conferir o cumprimento do mandato e atualizar o portfólio', 'Estratégia', 'Copiloto', 'médio',
          [(MANDATO, 'etapa 6'), ('Situação da execução do mandato', 'etapa 7')],
          [T('Conferir a execução contra o mandato', 'ESA'),
           T('Concluir se o mandato foi cumprido', 'ESP'),
           D('Mandato cumprido?', 'ESP',
             [S('Sim', 'seg'), S('Não, falta executar', 'E7'), S('Não, o mandato precisa mudar', 'E4')]),
           T('Atualizar o portfólio e avisar quem depende dele', 'ESR')],
          [(PORTF, ['ES-01', 'ES-02', 'ES-03', 'Identidade', 'Inteligência', 'Gestão', 'Governança']),
           ('Execução do mandato a completar', ['etapa 7']),
           ('Pedido de mudança do mandato', ['etapa 4'])]),
    ]))

# ========================================================== ACOMPANHAMENTO
JORNADAS.append(dict(
    code='ES-06',
    nome='Acompanhar a execução da estratégia e corrigir o rumo',
    dominio='Acompanhamento', classe='essencial', onda=1,
    objetivo='Saber a cada revisão se a estratégia está sendo executada e se as hipóteses continuam de pé, separar falha de execução de hipótese errada, decidir as correções de execução, ouvidos os executivos, abrir só a revisão de nível mais alto que os sócios decidem (a estratégia puxa o portfólio, que puxa os alvos) e prestar contas. Usa as comparações que a Inteligência e a Gestão já fazem, num painel único.',
    frequencia='A cada revisão da estratégia (cadência: trimestral) e por evento, quando o ritual da Gestão aponta desvio grave',
    automacao=('alta', 'O agente reúne os resultados, aponta os desvios e propõe causas; a Inteligência responde com os dados; a decisão de corrigir e a prestação de contas são de pessoas.'),
    base=['kaplan', 'apqc'],
    lanes=['GES', 'EXE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Desvio grave apontado pelo ritual', 'GES', 'message'),
             I('Ciclo de revisão da estratégia iniciado', 'ESR', 'timer')],
    fins=[F('Revisão concluída com correções encaminhadas', 'ESR'), F('Revisão concluída sem correção', 'ESR')],
    etapas=[
        E('Reunir os resultados contra os alvos e as hipóteses', 'Estratégia', 'Autopiloto', 'baixo',
          [(ALVOS, 'ES-03'), (ESTRAT, 'ES-01'), (HIPOT, 'ES-01'), (METODO, 'ES-01'), (MANTIDA, 'ES-01'), (CARTEIRA, 'ES-04'),
           (ALOC, 'ES-02'), ('Alvos atuais mantidos pelos sócios', 'ES-03'),
           ('Desvios e decisões do ritual de acompanhamento', 'Gestão'), ('Desvio grave ou mudança de alvo apontados pelo ritual', 'Gestão'),
           ('Ajuste de oferta feito sem portão, com o motivo da dispensa', 'Inteligência'),
           (INDIC, 'Inteligência'),
           (LEITURA, 'Inteligência'), ('Contestação de indicador de alvo vigente', 'Inteligência'),
           ('Situação das iniciativas na carteira de projetos', 'Integração'), (RISCOS, 'Governança')],
          [T('Reunir no painel único os indicadores, os desvios do ritual e a situação das iniciativas', 'ESR'),
           T('Listar os desvios e os sinais que as comparações da Inteligência e da Gestão já apontam', 'ESA')],
          [('Desvios e sinais apontados no painel único', ['etapa 2'])]),
        E('Separar falha de execução de hipótese errada', 'Estratégia, com executivos e líderes dos círculos', 'Copiloto', 'médio',
          [('Desvios e sinais apontados no painel único', 'etapa 1'), (RESPOSTA_IN, 'Inteligência'),
           ('Pergunta devolvida com o motivo', 'Inteligência')],
          [T('Propor a causa de cada desvio: execução, recurso, alvo ou hipótese', 'ESA'),
           T('Enviar à Inteligência a pergunta sobre as causas propostas, com o risco e o prazo', 'ESR'),
           T('Receber a resposta da Inteligência sobre as causas, ou a pergunta devolvida', 'ESR', 'receive'),
           T('Discutir as causas com executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir a causa de cada desvio', 'ESP'),
           D('Há contestação de indicador de alvo vigente?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Decidir a contestação do indicador de alvo: manter a ficha ou abrir a correção do alvo', 'ESP')])]),
           D('Há correção a fazer?', 'ESP',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a revisão sem correção e avisar quem apontou o desvio', 'ESR')])])],
          [(CAUSAS, ['etapa 3', 'ES-02']),
           (PERGUNTA, ['Inteligência']),
           ('Decisão sobre a contestação do indicador de alvo', ['Inteligência']),
           ('Revisão sem correção registrada', ['Gestão', 'Sócios'])]),
        E('Decidir as correções de execução e abrir a revisão que os sócios decidem', 'Estratégia, ouvidos os executivos', 'Assistido', 'médio',
          [(CAUSAS, 'etapa 2')],
          [T('Propor alternativas de correção e o efeito de cada uma', 'ESA'),
           T('Opinar sobre as alternativas de correção da execução', 'EXE'),
           T('Decidir as correções de execução, ouvidos os executivos', 'ESP'),
           D('Há correção na execução?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Pedir o plano de correção ao dono da execução', 'ESR')])]),
           D('Há correção numa aposta ou numa oferta?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Pedir a revisão da aposta ou da oferta no portão', 'ESR')])]),
           D('Qual é a revisão de nível mais alto a abrir para os sócios?', 'ESP',
             [S('Nenhuma', 'prox'),
              S('Estratégia, porque a hipótese falhou', 'prox',
                via=[T('Abrir só a revisão da estratégia, que puxa a do portfólio e a dos alvos', 'ESR')]),
              S('Portfólio ou recursos', 'prox', via=[T('Abrir só a revisão do portfólio, que puxa a dos alvos', 'ESR')]),
              S('Só os alvos', 'prox', via=[T('Abrir novo desdobramento dos alvos', 'ESR')])])],
          [('Correções de execução decididas, com dono e prazo', ['etapa 4']),
           ('Revisão aberta para decisão dos sócios: alvos, portfólio ou estratégia', ['etapa 4']),
           ('Pedido de plano de correção', ['Executivos', 'Líderes dos círculos', 'Gestão']),
           (REVISAO_AP, ['ES-04']),
           ('Revisão aberta dos alvos', ['ES-03']),
           ('Revisão aberta do portfólio', ['ES-02']),
           ('Revisão aberta da estratégia', ['ES-01'])]),
        E('Registrar as correções e prestar contas da revisão', 'Estratégia', 'Copiloto', 'baixo',
          [('Correções de execução decididas, com dono e prazo', 'etapa 3'),
           ('Revisão aberta para decisão dos sócios: alvos, portfólio ou estratégia', 'etapa 3')],
          [T('Registrar no painel único as correções de execução, os donos e os prazos', 'ESR'),
           T('Resumir o resultado, a revisão aberta para os sócios e as lições da revisão', 'ESA'),
           T('Aprovar a prestação de contas da revisão antes de enviá-la aos sócios', 'ESP'),
           T('Avisar círculos e executivos afetados e enviar o resultado aos sócios', 'ESR')],
          [('Correções de execução publicadas, com dono e prazo', [TODOS, 'Gestão']),
           ('Resultado da revisão da estratégia', ['Sócios', 'Governança']),
           ('Lições da revisão da estratégia', ['Inteligência'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Direção e recursos', 'Escolher onde atuar, alocar os recursos e fixar os alvos.'),
    ('Apostas e empresas', 'Decidir o que entra, o que avança e o que sai do portfólio.'),
    ('Acompanhamento', 'Conferir se a estratégia é executada e se continua certa.'),
]

ONDAS = {
    1: 'O que o modelo precisa para rodar: direção, alvos e correção de rumo',
    2: 'O que cuida do portfólio e das apostas',
    3: 'O que roda por evento raro',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4, categoria 1.0, Develop Vision and Strategy, com quatro grupos: 1.1, conceito de negócio e visão de longo prazo; 1.2, estratégia de negócio; 1.3, iniciativas estratégicas; 1.4, modelos de negócio. A tabela de cobertura, na aba Método, mostra onde cada processo foi parar: nas seis jornadas ou em outro círculo.',
    'kaplan': 'Sistema de gestão em cinco estágios: desenvolver a estratégia, traduzir a estratégia, planejar as operações, monitorar e aprender, testar e adaptar a estratégia. Os autores descrevem três tipos de reunião (revisão operacional, revisão da estratégia e teste e adaptação da estratégia) e pedem pautas distintas para a revisão operacional e a da estratégia, para o curto prazo não expulsar a discussão da estratégia. Base da sequência ES-01, ES-03 e ES-06. Pôr o ritual operacional na Gestão e a revisão da estratégia neste círculo é escolha nossa: os autores dizem que as mesmas pessoas costumam participar das duas reuniões.',
    'rumelt': 'O núcleo de uma boa estratégia tem três partes: diagnóstico, política orientadora e ações coerentes. Um dos sinais de estratégia ruim é confundir alvos com estratégia. Base das etapas 1 e 2 da ES-01 e da separação entre formular (ES-01) e fixar alvos (ES-03).',
    'okr': 'Objetivos ambiciosos e resultados-chave mensuráveis. Base das etapas 1 e 2 da ES-03.',
    'lei': 'Desdobramento da estratégia (hoshin kanri): alinha as funções e atividades da organização, na vertical e na horizontal, com os objetivos estratégicos, num processo de cima para baixo e de baixo para cima. O verbete chama esse diálogo de catchball. Base da etapa 2 da ES-03.',
    'horizons': 'Três horizontes de crescimento, geridos ao mesmo tempo: o negócio principal de hoje (horizonte 1), as oportunidades emergentes (horizonte 2) e as ideias de crescimento futuro (horizonte 3). Usado para dar papel a cada unidade no portfólio-alvo (ES-01 e ES-02) e para situar as apostas (ES-04).',
    'parenting': 'Duas perguntas que, segundo os autores, a maioria dos executivos-chefes deixa de responder na estratégia corporativa: que negócios esta empresa, e não as rivais, deve ter, e por quê; e que estrutura organizacional, processos de gestão e filosofia favorecem o desempenho superior dos seus negócios. Base do portfólio-alvo na ES-01, da leitura do portfólio na ES-02 e do caso na ES-05.',
    'realloc': 'Quatro atividades de alocação: semear (entrar em área de negócio nova, por aquisição ou investimento próprio), nutrir (reforçar um negócio existente), podar (tirar recursos de um negócio existente) e colher (vender negócios inteiros que não cabem mais no portfólio ou separá-los). Quatro recomendações: ter um portfólio-alvo, usar todos os instrumentos de realocação, adotar regras simples para romper o status quo e implantar processos que reduzam a inércia. Numa amostra de mais de 1.600 empresas dos Estados Unidos, de 1990 a 2005, os autores relatam que o terço que mais realocou capital entre unidades de negócio teve, em média, retorno total ao acionista 30% maior por ano que o terço que menos realocou: 10,2% contra 7,8% ao ano no Exhibit 2 do artigo, diferença relativa, não de 30 pontos percentuais. Em períodos de menos de três anos, quem mais realocou teve retorno menor. Base da ES-02 e, na venda de empresa, da ES-05.',
    'stagegate': 'O trabalho de inovação é dividido em estágios, cada um precedido de um portão. Em cada portão, gestores seniores (os gatekeepers) decidem entre Go, Kill, Hold e Recycle. A página lista os quatro resultados sem defini-los; lê-los como avançar, encerrar, esperar e voltar para ajuste é interpretação nossa, e o resultado “segue como está”, da revisão de uma aposta, é acréscimo nosso. A fonte tem cinco estágios e cinco portões, de desenvolvimento de produto; a ES-04 usa a lógica, com dois portões.',
    'iia': 'No modelo, o órgão de governança presta contas pela supervisão da organização e delega responsabilidade e recursos à gestão; as três linhas ficam abaixo dele. Usado por analogia para separar o que os sócios aprovam (ES-01, ES-02, ES-03 e ES-05) do que a Estratégia propõe e decide dentro da alçada.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio, script e recebimento, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'dmn': 'Padrão de modelagem de decisões, que inclui tabelas de decisão. Usado na ES-04 para a tabela de alçadas e para o limite de recursos da alocação.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# ----------------------------------- cobertura do referencial (APQC PCF 7.4, categoria 1.0)
COBERTURA = [
    ('1.1.1', 'Assess the external environment', 'ES-01, etapa 1, com a leitura da Inteligência'),
    ('1.1.2', 'Survey market and determine customer needs and wants', 'Fora: Inteligência'),
    ('1.1.3', 'Assess the internal environment', 'ES-01, etapa 1'),
    ('1.1.4', 'Establish strategic vision', 'Fora: Identidade (ID-01)'),
    ('1.1.5', 'Conduct organization restructuring opportunities', 'ES-05'),
    ('1.2.1', 'Develop overall mission statement', 'Fora: Identidade (ID-01)'),
    ('1.2.2', 'Define and evaluate strategic options to achieve the mission', 'ES-01, etapa 2'),
    ('1.2.3', 'Set/Develop long-term enterprise strategy', 'ES-01 e ES-02. Serviços compartilhados (1.2.3.6) na ES-01, etapa 3; aquisição e saída (1.2.3.3) na ES-05; fusão e cisão não estão desenhadas'),
    ('1.2.4', 'Coordinate and align cross-functional and process strategies', 'ES-01, etapa 3, e ES-03, etapa 2'),
    ('1.2.5', 'Create organizational design', 'Fora: Integração (jornadas e catálogo) e Governança (alçadas)'),
    ('1.2.6', 'Develop and set organizational objectives', 'ES-03'),
    ('1.2.7', 'Formulate business unit strategies', 'ES-01, etapa 3'),
    ('1.2.8', 'Develop customer experience strategy', 'Fora: Relações, por decisão de 01/10/2026; entra no desenho do círculo 4'),
    ('1.2.9', 'Communicate strategies internally and externally', 'Fora: Gestão, para dentro, e Relações, para fora. A ES-01 entrega o que comunicar'),
    ('1.3.1 a 1.3.3', 'Develop strategic initiatives; Evaluate strategic initiatives; Select strategic initiatives', 'ES-03, para as iniciativas dos alvos; ES-04, para as apostas'),
    ('1.3.4', 'Establish high-level measures', 'ES-03, etapa 2, com as fichas dos indicadores que a Inteligência decide na IN-04'),
    ('1.3.5', 'Execute strategic initiatives', 'Fora: executivos e círculos; os projetos ficam na Integração'),
    ('1.3.6 e 1.3.7', 'Review execution of strategic initiatives; Refine strategic initiatives and project plans as needed', 'ES-06'),
    ('1.4', 'Develop and maintain business models', 'Fora: Inteligência, pela decisão D4 da rodada 2'),
]

# --------------------------------------------------- o que a Estratégia não faz
FRONTEIRAS = [
    ('Definir propósito, valores, marca e posicionamento', 'Identidade',
     'A direção e os públicos prioritários. Confere as próprias escolhas com a declaração e os critérios de decisão da Identidade.'),
    ('Ler mercado, clientes e concorrentes e medir indicadores', 'Inteligência',
     'As perguntas do diagnóstico, as hipóteses e os sinais a vigiar (ES-01); os alvos propostos, para a ficha do indicador de cada um (ES-03); e as perguntas de decisão dos portões, dos casos e das causas (ES-04, ES-05 e ES-06).'),
    ('Produtizar a oferta, desenhar o modelo de negócio e decidir o preço-base de cada oferta', 'Inteligência',
     'A decisão em cada portão: a aposta que entra e a oferta que é lançada (ES-04). O método de estratégia leva os critérios dos portões.'),
    ('Executar a estratégia da empresa', 'Executivo da empresa',
     'O método de estratégia, o papel da empresa no portfólio-alvo e a conferência de coerência entre as empresas (ES-01). O executivo propõe as escolhas da empresa e participa; a Estratégia formula e os sócios aprovam.'),
    ('Montar e controlar o orçamento', 'Gestão',
     'A alocação por empresa, oferta e aposta (ES-02) e os alvos e iniciativas (ES-03).'),
    ('Rodar o ritual de acompanhamento dos alvos', 'Gestão',
     'Os alvos, as iniciativas e os donos (ES-03). Recebe de volta os desvios e as decisões do ritual.'),
    ('Executar aportes, distribuição de resultado e ajustes de orçamento', 'Gestão',
     'A decisão de alocação e de destino do resultado (ES-02).'),
    ('Definir e aplicar o critério de rateio do custo dos círculos', 'Governança define, com a Estratégia; Gestão aplica',
     'O que é serviço comum a todas as empresas e o que é de cada uma (ES-01, etapa 3).'),
    ('Gerir os projetos das iniciativas, executar o mandato de empresa e coordenar o lançamento de oferta', 'Integração, como PMO corporativo',
     'As iniciativas aprovadas (ES-03), o mandato da empresa (ES-05), que a Integração executa e a Estratégia confere, e a oferta aprovada para lançamento (ES-04).'),
    ('Montar e executar o plano de saída de clientes, contratos e pessoas', 'Integração, como PMO corporativo, com Relações, Negócios, Operações, Governança e Gestão',
     'O pedido do plano de saída (ES-04 e ES-05). O plano volta à Estratégia, que o confere antes de decidir a data de saída (ES-04) ou de fechar o mandato (ES-05).'),
    ('Manter o painel único de indicadores', 'Inteligência',
     'Os alvos, as iniciativas e as correções, que a Estratégia registra no painel (ES-03 e ES-06).'),
    ('Constituir, alterar e encerrar empresas; registrar as decisões dos sócios; definir as alçadas', 'Governança',
     'O caso, a proposta de estrutura e cada proposta que sobe aos sócios.'),
    ('Priorizar parceiros e gerar demanda', 'Relações',
     'A direção, os públicos prioritários e a oferta aprovada para lançamento.'),
    ('Definir a tabela de preços e a política comercial', 'Negócios',
     'O papel de cada oferta no portfólio-alvo e a oferta aprovada para lançamento.'),
    ('Comunicar a estratégia para dentro e para fora', 'Gestão, para dentro; Relações, para fora',
     'O resumo da direção, já com o que pode ser dito para fora, e o aviso do que mudou.'),
    ('Levar as lições entre empresas ao catálogo', 'Inteligência, com Integração',
     'A leitura do portfólio (ES-02), a lição da aposta encerrada (ES-04), a lição do caso arquivado, sem dado sigiloso (ES-05), e as lições da revisão (ES-06).'),
]

# ------------------------------------------------------- decisões de fechamento
PONTOS = []
DECISOES = [
    ('A Estratégia faz o trabalho de estratégia de ponta a ponta, os sócios aprovam e a Gestão opera a rotina',
     'Regra sua (15:48), sobre a minha proposta',
     'A Estratégia formula, propõe, desdobra, decide os portões dentro da alçada e acompanha. Li “rotina” como montar e controlar o orçamento e rodar o ritual de acompanhamento dos alvos; leitura confirmada por você às 20:11 de 02/10/2026.'),
    ('O executivo e o líder do círculo propõem e participam, mas não decidem',
     'Regra sua (20:02), ao aprovar a proposta 1',
     'Na ES-01, etapa 3, a Estratégia formula a estratégia de cada empresa e as escolhas de cada círculo, ouvidos o executivo e o líder; a divergência sem acordo sobe aos sócios, e a decisão deles é incorporada ao texto na etapa 5. Desde as 20:11 de 02/10/2026 a regra vale também na ES-02 (mudança de papel), na ES-04 (portão e data de saída) e na ES-06 (correções de execução): o executivo opina numa tarefa própria e a Estratégia decide; acima da alçada, decidem os sócios.'),
    ('A Integração é o PMO corporativo, interno e externo',
     'Definição sua (15:48)',
     'Na ES-05 a Integração executa o mandato e a Estratégia confere; na ES-03 confere a capacidade de executar as iniciativas; na ES-04 coordena o lançamento da oferta aprovada (ponto 3 do círculo 3, aprovado às 20:02) e o plano de saída de clientes e contratos. Vale como requisito para o círculo 6.'),
    ('Sobem para os sócios: a estratégia, a alocação e o destino do resultado, os alvos com o orçamento, e criar, adquirir, vender ou encerrar empresa',
     'Proposta minha aprovada (15:48), completada pelas propostas 3, 4, 6 e 13 (20:02) e pelas mudanças aprovadas às 20:11 de 02/10/2026',
     'ES-01, ES-02, ES-03 e ES-05 têm etapa de aprovação pelos sócios. Sobem também o método de estratégia e as hipóteses, a proposta de manter a estratégia e a de manter a alocação, as divergências sem acordo, a autorização para negociar e a proposta de arquivar caso que os sócios mandaram estudar ou cuja negociação autorizaram. Na ES-04 só sobe o que passa da alçada da Estratégia.'),
    ('Os sócios autorizam a negociação, com limites, antes de ela começar',
     'Proposta 13, aprovada por você (20:02)',
     'A ES-05 ganha a etapa 2. O contrato de compra ou venda é preparado pela Governança e assinado depois da decisão dos sócios e antes do mandato (etapa 5).'),
    ('Uma aposta atravessa dois portões: a entrada na carteira e o lançamento',
     'Sua decisão D4 da rodada 2, confirmada (15:48)',
     'A validação com clientes é marco da jornada da Inteligência. Encerrar é resultado possível de qualquer portão ou revisão.'),
    ('A estratégia de experiência do cliente é de Relações',
     'Proposta minha aprovada (15:48)',
     'Fica fora das jornadas da Estratégia. Entra no desenho do círculo 4, com Operações no círculo 7.'),
    ('Vender ou encerrar uma empresa inclui retirar a marca de uso',
     'Decorre da proposta 1 do círculo 1, aprovada por você (15:48)',
     'A ES-05 pede a retirada à Identidade, com a data de efeito, e a ES-04 faz o mesmo pedido quando encerra oferta com marca própria. Desde as 20:11 de 02/10/2026, a ID-03 agenda a retirada para a data de efeito do pedido.'),
    ('As 18 propostas de mudança deste círculo foram aprovadas',
     'Sua resposta das 20:02',
     'Estão aplicadas nesta versão. Cada uma aparece na aba O que mudou com a marca “aprovada às 20:02”.'),
    ('As cinco propostas da revisão de 02/10/2026 foram aprovadas',
     'Sua resposta das 20:11 de 02/10/2026 (“Tudo 100% aprovado”)',
     'Estão aplicadas nesta versão, menos a troca do nome do método: o nome é recebido pela Inteligência (círculo 3) e ficou como estava. Cada uma aparece na aba O que mudou.'),
    ('Auditoria de execução: modo de cada etapa e nível de automação pelo que as tarefas fazem',
     'Itens 1 a 14 da auditoria, aprovados por você (12:33 de 03/10/2026)',
     'ES-05 etapa 3: acrescentada a tarefa da pessoa da Estratégia "Consolidar o resultado da apuração para decidir se o caso segue" (item 1). ES-03 etapa 3: acrescentada a tarefa da pessoa da Estratégia "Confirmar se os alvos e as iniciativas cabem nos recursos"; o modo segue Copiloto (item 2). De Assistido para Copiloto, pelas tarefas: ES-04 etapa 3, ES-04 etapa 4. De Autopiloto para Autômato, pelas tarefas: ES-03 etapa 5. De Copiloto para Assistido, pelas tarefas: ES-01 etapa 2, ES-03 etapa 2, ES-05 etapa 4, ES-06 etapa 3. Nível de automação pela faixa: ES-01 baixa → média; ES-05 baixa → média; ES-06 média → alta.'),
    ('Método de estratégia: calendário, portões, realocação e hipóteses',
     'Aprovado por você (13:51 de 03/10/2026)',
     'Calendário: ES-01 anual com revisão no meio do ciclo, ES-02 semestral, ES-03 anual, ES-06 trimestral, GE-02 mensal, ES-04 por evento. Portão 1 (entrar na carteira): problema e público claros, coerência com a identidade, hipótese testável com indicador, próximo passo dentro da reserva, dono. Portão 2 (lançar): evidência de demanda, preço-base que cobre o custo, capacidade confirmada, contrato no modelo, indicadores definidos. Realocação por resultado contra o alvo e coerência: crescer, manter, reduzir ou estudar a saída. Alçada da aposta: cada aposta dentro da reserva dos sócios, até um terço dela.'),
    ('Correções da auditoria geral',
     'Aprovado por você (16:05 de 03/10/2026)',
     'ES-01: a revisão do meio do ciclo ganha evento de início (L4). ES-04, etapa 3: vão aos sócios, além dos recursos acima da alçada, o encerramento de oferta com contratos vigentes e a decisão que contraria o portfólio-alvo (M10). ES-06: recebe da GE-02 o desvio grave e a mudança de alvo, e da IN-07 o ajuste feito sem portão (M9, L1, L8). Método: critério de desvio grave e um só vocabulário de realocação, semear, nutrir, podar ou colher (M9, L2).'),
]

# propostas de mudança em conteúdo já aprovado: só entram com a sua aprovação
PROPOSTAS = []

ALERTAS = [
    ('Integração como PMO corporativo', 'A definição pede, no círculo 6, as jornadas de carteira de projetos internos e externos, a execução de mandato de empresa e a coordenação de lançamento de oferta. A ES-03, a ES-04 e a ES-05 já contam com elas.'),
    ('Plano de saída', 'O plano de saída de clientes, contratos e pessoas (ES-05) e o de clientes e contratos de oferta encerrada (ES-04) são pedidos à Integração, que coordena Relações, Negócios, Operações, Governança e Gestão. Viram requisito dos círculos 4 a 9. A Integração como dona do plano e a data de saída decidida pela Estratégia, ouvido o executivo, são escolhas do desenho para a proposta 10 funcionar. Confirmado por você às 20:11 de 02/10/2026.'),
    ('Alçadas e sócios', 'Resolvido em 03/10/2026: a alçada da ES-04 vale por recursos e por tipo de decisão (encerrar oferta com contratos vigentes e contrariar o portfólio-alvo vão aos sócios), e a tabela matéria × órgão diz quando decidem os sócios do Ecossistema e quando os de cada empresa (aba Propostas de parâmetros, seção 5).'),
    ('Cadências', 'Fixadas pelo método de estratégia aprovado em 03/10/2026: estratégia anual, com revisão no meio do ciclo; portfólio semestral; alvos anuais; revisão da execução trimestral. Recalibrar com dados no gate G9.'),
    ('Método de estratégia', 'Escrito e aprovado em 03/10/2026 (13:51; desvio grave e vocabulário às 16:05): calendário, critérios dos dois portões, revisão, realocação, registro de hipóteses e critério de desvio grave (aba Propostas de parâmetros, seção 2). Os sócios ratificam no gate G6.'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'C1 · Da estratégia ao resultado', 'ES-01, ES-03 e ES-06',
     'Dividida em formular, desdobrar e acompanhar. O ritual de acompanhamento (W-C1.4) continua na Gestão.'),
    ('Ajustado', 'E4 · Do resultado da empresa à decisão do Ecossistema', 'ES-02',
     'Vira revisão do portfólio e realocação de recursos. Executar a decisão (W-E4.3) fica na Gestão; levar as lições ao catálogo (W-E4.4), na Inteligência.'),
    ('Ajustado', 'I-ES1 · Da ideia à aposta priorizada', 'ES-04',
     'Vira decisão por portões. A revisão da carteira (W-ES1.4) passa à ES-02, que só pede o estudo de saída; quem decide é o portão.'),
    ('Ajustado', 'W-V1.6 · Decidir o lançamento, dentro da V1', 'ES-04',
     'O lançamento vira o segundo portão. A V1 continua liderada pela Inteligência.'),
    ('Ajustado', 'E5 · Da aposta à empresa nova', 'ES-05',
     'Passa a cobrir também aquisição, venda e encerramento. Constituir e registrar (W-E5.3) fica na Governança; ligar aos círculos (W-E5.5), na Integração.'),
    ('Ajustado', 'Decisão D4: a Estratégia decide a aposta que entra e a oferta que é lançada', 'ES-04',
     'Mantida, com um limite: a Estratégia decide com o executivo dentro da alçada; acima dela, decidem os sócios. Desde 20:11 de 02/10/2026, a Estratégia decide ouvido o executivo.'),
    ('Acrescentado', 'Sem equivalente', 'Portfólio-alvo, hipóteses e método de estratégia',
     'Três produtos novos da ES-01. O portfólio-alvo é a referência da ES-02; as hipóteses e os sinais são o que a ES-06 acompanha; o método traz os critérios dos portões e as regras de realocação.'),
    ('Acrescentado', 'Sem equivalente', 'Escolhas de cada círculo',
     'Na ES-01, etapa 3, cada líder de círculo propõe o que é serviço comum, o que construir e o que comprar.'),
    ('Acrescentado', 'Sem equivalente', 'Ponto de conferência com a identidade',
     'Da ES-01 à ES-05, o agente confere as propostas com os padrões da Identidade, uma pessoa decide se são coerentes e o caso de fronteira vira consulta à ID-02.'),
    ('Acrescentado', 'Sem equivalente', 'Raia e parte “Líder do círculo”',
     'Papel novo no vocabulário do modelo: na ES-01 e na ES-03, cada líder de círculo propõe as escolhas e os alvos do seu círculo.'),
    ('Ajustado', 'ES-01, etapa 3: o executivo decidia as escolhas da empresa', 'A Estratégia formula; o executivo e o líder propõem',
     'A divergência sem acordo sobe aos sócios, e a decisão deles é incorporada ao texto e aprovada por pessoa, na etapa 5, antes de publicar. Proposta 1, aprovada às 20:02.'),
    ('Ajustado', 'ES-01, etapa 1: o diagnóstico usava a leitura no mesmo passo em que a pedia', 'Espera a leitura da Inteligência ou o aviso de leitura sem novidade',
     'A empresa nova usa a estratégia vigente e passa pela conferência de identidade; manter a estratégia gera aviso. Proposta 2, aprovada às 20:02.'),
    ('Ajustado', 'ES-01, etapas 2 a 5: método e hipóteses fora da aprovação', 'Os sócios aprovam também as hipóteses e o método',
     'O método vai também à Inteligência, aos líderes dos círculos, à Gestão, à Integração e à Governança. Proposta 3, aprovada às 20:02.'),
    ('Ajustado', 'ES-02, etapa 2: a revisão podia terminar sem ir aos sócios', 'A proposta sobe sempre aos sócios',
     'Vale também para manter a alocação e para o destino do resultado. A decisão de manter também é comunicada, e a jornada passa a ter um fim só. Proposta 4, aprovada às 20:02.'),
    ('Ajustado', 'ES-02, etapa 4: portfólio-alvo atualizado só para a ES-04 e os executivos', 'Mesmos destinos da ES-01',
     'A alocação que muda alvos ou orçamento abre a ES-03. Proposta 5, aprovada às 20:02.'),
    ('Ajustado', 'ES-03, etapas 2 e 3: a Inteligência conferia o indicador antes de a ficha existir', 'A ES-03 pede as fichas à IN-04 e espera',
     'A ES-03 negocia antes e pede só as fichas dos alvos novos ou alterados. O que não cabe nos recursos e não tem acordo sobe aos sócios com as alternativas. Proposta 6, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-03: inícios “Nova estratégia publicada” e “Portfólio de empresas atualizado”',
     'Os alvos deixam de valer até o próximo ciclo quando a estratégia ou o portfólio mudam. Quando o início é estratégia nova ou empresa nova, o desdobramento espera a alocação. Proposta 7, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-04: caminho de revisão da aposta',
     'Inícios para a aposta devolvida pela Inteligência, a revisão pedida, o caso arquivado e a retomada; a avaliação usa os indicadores e o gasto realizado; a revisão pode terminar em “segue como está”; a decisão da revisão vai também à Inteligência e à Gestão. Proposta 8, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, etapas 3 e 4: “empresa própria” escolhida por automação depois do portão', 'Decidida no portão, por pessoa',
     'O caso nascido de aposta e arquivado na ES-05 volta à ES-04. Proposta 9, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-04, etapa 4: encerramento de aposta em desenvolvimento ou de oferta em uso',
     'A decisão de encerrar sai no portão, para parar o desenvolvimento e as novas vendas. Na etapa nova, a Integração coordena o plano de saída de clientes e contratos; a Estratégia o confere, decide a data de saída com o executivo, pede a retirada da marca própria e confere a saída no fim. A retomada da aposta em espera fica só na ES-04. Proposta 10, aprovada às 20:02. Desde 20:11 de 02/10/2026, a Estratégia decide a data de saída ouvido o executivo.'),
    ('Ajustado', 'ES-04, ES-05 e ES-06: a resposta da Inteligência era esperada sem pergunta', 'Pergunta de decisão explícita e espera da resposta',
     'A IN-02 começa por uma pergunta. A espera aceita também a pergunta devolvida. Na ES-06 sai a raia da Inteligência. Proposta 11, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, última etapa: oferta aprovada sem dono do lançamento', 'A Integração coordena o lançamento, com o executivo',
     'O pacote é entregue só pela IN-07, e a decisão do portão vai também à Integração. Proposta 12, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-05, etapa 2: autorização dos sócios para negociar, com limites',
     'A apuração vale também para o encerramento; o contrato é preparado pela Governança e assinado antes do mandato; há um só aviso de caso arquivado, e a lição sai sem dado sigiloso. Proposta 13, aprovada às 20:02.'),
    ('Ajustado', 'ES-05, etapas 5 e 6: marca pedida duas vezes e sem data; execução e conferência na mesma etapa', 'Um pedido com data de efeito; executar (etapa 7) separado de conferir (etapa 8)',
     'O plano de saída, coordenado pela Integração, volta e é conferido antes de fechar o mandato, que vai também a Negócios, Operações e Inteligência. Proposta 14, aprovada às 20:02.'),
    ('Ajustado', 'ES-06: três painéis e comparações refeitas', 'Painel único, com as comparações da Inteligência e da Gestão',
     'As correções de execução ficam separadas das revisões que só os sócios decidem; a prestação de contas é aprovada por pessoa. Proposta 15, aprovada às 20:02.'),
    ('Ajustado', 'ES-02 a ES-05: conferência de identidade sem decisão', 'Decisão e consulta à Identidade, como na ES-01',
     'Na ES-04, a incoerência fica registrada na avaliação e impede a recomendação de avançar. Proposta 16, aprovada às 20:02.'),
    ('Ajustado', 'Nomes “Oferta aprovada no portfólio” e “Indicação de saída”', '“Oferta aprovada para lançamento” e “Estudo de saída pedido”',
     'Fusão e cisão saem do objetivo da ES-05 e viram limite declarado. Proposta 17, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-06, etapa 2: decisão da contestação de indicador de alvo vigente',
     'A Estratégia mantém a ficha ou abre a correção do alvo, e a resposta volta à IN-04. Proposta 18, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, etapa 3: aposta mantida, em espera, devolvida ou encerrada avisada a quem pediu, à Inteligência e à Gestão', 'Também a Relações',
     'A RE-05 desfaz a transição de clientes preparada quando o encerramento é revertido, e a RE-06 responde ao parceiro quando a parceria levada como aposta não é aprovada. Proposta do círculo 4, aceita às 19:05 de 02/10/2026.'),
    ('Acrescentado', 'Sem equivalente', 'ES-04, etapa 5: parceria aprovada no portão devolvida a Relações',
     'A parceria que Relações levou como aposta volta à RE-06 para ser formalizada. Proposta do círculo 4, aceita às 19:05 de 02/10/2026.'),
    ('Ajustado', 'ES-02, ES-04 e ES-06: a Estratégia decidia “com o executivo” a mudança de papel, o portão, a data de saída e as correções de execução', 'A Estratégia decide, ouvido o executivo',
     'O executivo opina numa tarefa própria, na raia do executivo, e a pessoa da Estratégia decide; acima da alçada, continuam os sócios. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ES-05, etapas 1 e 3: a Estratégia arquivava sozinha o estudo de saída pedido pelos sócios e o caso com negociação autorizada', 'O arquivamento sobe aos sócios como proposta',
     'A etapa 5 passa a decidir também a proposta de arquivar, com o caso e o resultado da apuração; os sócios arquivam ou mandam estudar de novo. O caso que os sócios não pediram nem autorizaram continua arquivado pela Estratégia, com aviso. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ES-01, etapa 1: quando o diagnóstico não pedia mudança, a Estratégia decidia manter e avisava', 'Manter a estratégia sobe aos sócios como proposta',
     'Como já acontece com manter a alocação na ES-02. O diagnóstico vai à etapa 4, que separa as opções da proposta de manter das da proposta de mudança. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ES-06, etapa 3: as revisões da estratégia, do portfólio e dos alvos podiam abrir juntas', 'Abre só a revisão de nível mais alto',
     'A estratégia puxa o portfólio, que puxa os alvos. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'Ramos “manter” da ES-01, da ES-02 e da ES-03 sem aviso a quem abriu a revisão', 'Avisam quem abriu a revisão',
     'A ES-03 ganha a saída “Alvos atuais mantidos pelos sócios”, e a alocação vai também à ES-06. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Ajustado', 'ES-06, etapa 3: “Decisão de rever a estratégia”, “Decisão de rever o portfólio” e “Decisão de corrigir os alvos”', '“Revisão aberta da estratégia”, “Revisão aberta do portfólio” e “Revisão aberta dos alvos”',
     'Os três nomes só circulam dentro do círculo. Aprovada por você às 20:11 de 02/10/2026.'),
    ('Retirado', 'Fronteira “Captar dinheiro de fora ou admitir sócio numa empresa”', 'Fora do desenho, em Limites',
     'A ES-05 não tem ramo para essas operações. Aprovada por você às 20:11 de 02/10/2026.'),
]

LIMITES = [
    'Os fluxos rodam no motor próprio sobre o Supabase, por enquanto em simulação (piloto: Identidade). Falta trocar os adaptadores simulados pelos sistemas reais.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'As cadências vêm do método de estratégia aprovado em 03/10/2026: ciclo estratégico anual, com revisão no meio do ciclo (ES-01); portfólio semestral (ES-02); alvos anuais, com o ciclo (ES-03); revisão da execução trimestral (ES-06). São escolha de desenho, sem fonte externa: recalibrar com dados depois de dois ciclos.',
    'O método de estratégia foi aprovado em 03/10/2026 e ainda não foi ratificado pelos sócios (gate G6).',
    'A raia “Sócios” é uma só nos fluxos; quem decide em cada matéria, os sócios do Ecossistema ou os de cada empresa, está na tabela matéria × órgão (aba Propostas de parâmetros, seção 5).',
    'Fusão e cisão de empresas não estão desenhadas: a ES-05 cobre criação, aquisição, venda e encerramento.',
    'O plano de saída de clientes, contratos e pessoas é pedido à Integração e conferido pela Estratégia; como ele é montado só será desenhado nos círculos 4 a 9.',
    'Captar dinheiro de fora ou admitir sócio numa empresa ficam fora do desenho: a ES-05 não tem ramo para essas operações.',
    'A ES-06 abre só a revisão de nível mais alto. Se essa revisão termina sem mudança (os sócios mantêm a estratégia ou a alocação), a de nível abaixo não é aberta por ela; volta na revisão seguinte da ES-06.',
    'Quando uma mensagem pode tanto retomar uma jornada em espera quanto abrir outra (a alocação que chega à ES-03, a decisão do portão que chega à IN-07), a correlação fica para o motor de execução.',
    'Um laço de volta refaz a etapa inteira: o desenho não marca o que já foi feito na passagem anterior.',
    'As esperas por outro círculo (plano de saída, fichas dos indicadores, resposta da Inteligência) não têm prazo desenhado.',
    'Na venda decidida sem comprador, a busca do comprador não está desenhada: o mandato a descreve, e a oportunidade volta à ES-05 quando houver comprador.',
    'A ES-04 registra a incoerência com a identidade na avaliação e não recomenda avançar; a decisão do portão continua sendo de pessoas.',
    'As ofertas de uma empresa adquirida não têm caminho desenhado até o catálogo de ofertas.',
    'Com os nove círculos fechados (03/10/2026), as trocas com os outros oito foram conferidas dos dois lados pelo nome: 411 trocas, sem problema (410 até 03/10/2026, 21:05; a troca nova é o racional financeiro do contrato, de Negócios para a Gestão).',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = [
    'Um revisor independente leu a primeira versão das seis jornadas e apontou 33 achados, 6 graves. Todos foram tratados antes do fechamento das 15:48; os que dependiam de escolha sua viraram pontos para decidir.',
    'Um segundo revisor reabriu as dez fontes deste círculo: sete confirmadas e três confirmadas em parte. As correções de redação foram aplicadas na aba Fontes.',
    'Depois do fechamento, um terceiro revisor independente leu a versão fechada junto com os círculos 1 e 3 e apontou 30 achados, 4 graves. Vinte e oito viraram 17 propostas, e a décima oitava veio do cruzamento com o círculo 3. Você aprovou as 18 às 20:02.',
    'Em 02/10/2026, um quarto revisor independente leu a versão com as 18 mudanças aplicadas: 13 aplicadas por inteiro, 4 em parte e 1 além do aprovado, com 25 achados, 2 graves. Os dois graves e os demais defeitos da aplicação foram corrigidos; a extensão da regra do executivo à ES-02, à ES-04 e à ES-06 foi desfeita e virou proposta; o que mudava conteúdo que você já tinha fechado virou as cinco propostas da aba Decisões.',
    'Dois verificadores independentes conferiram as correções em seguida. O primeiro achou 10 defeitos criados por elas, 1 grave (a ES-03 podia ficar parada à espera da alocação), todos tratados. O segundo não confirmou nenhum grave e apontou 4 defeitos médios neste círculo, também tratados. Esses últimos acertos passaram por todos os testes automáticos, mas não por nova revisão independente.',
    'As cinco propostas daquela revisão foram aprovadas por você às 20:11 de 02/10/2026 e estão aplicadas, menos a troca do nome do método, que a Inteligência recebe com o nome atual. Uma revisão independente dessas mudanças apontou sete defeitos de aplicação (textos com “com o executivo”, opções de decisão misturadas na ES-01 e na ES-05, entradas que faltavam na ES-05 e arquivamentos que subiam aos sócios sem ter passado por eles); seis foram corrigidos aqui e um virou proposta no círculo 1.',
]
