# -*- coding: utf-8 -*-
"""Círculo 4 · Relações. Fechado em 02/10/2026: oito jornadas.
Regra do círculo: Relações decide o que é do seu ofício (o plano de demanda, a qualificação das oportunidades,
a estratégia de experiência do cliente, a pauta e o conteúdo externo e as parcerias dentro da alçada), ouvidos o
executivo e Negócios. Negócios vende e renova; Operações atende e entrega; a Identidade dá a marca e os padrões;
a Governança conduz o comitê de crise, e o dono da crise decide; a Governança cuida dos contratos e das regras de dados pessoais."""
from dsl import configurar, T, PAR, S, D, E, I, F, TODOS

NUM, NOME, SIGLA, PREF = 4, 'Relações', 'RE', 'RE'
LANES, PARTES = configurar(NOME, SIGLA, PREF)
SLUG = 'circulo4-relacoes'
FECHADO = True
STATUS = 'Fechado em 02/10/2026 · auditoria de execução aplicada em 03/10/2026'
LEAD = ('Relações constrói e cuida das relações com o mercado, os clientes, os parceiros e as instituições, antes e '
        'depois do contrato. Gera demanda e entrega a Negócios oportunidades qualificadas, desenha a experiência do '
        'cliente, acompanha o sucesso de cada cliente, forma parcerias, comunica para fora e vigia a reputação. '
        'Não vende, não atende, não define a marca e não decide a crise. São oito jornadas.')
PRINCIPIO = ('Regra do círculo, aprovada às 19:05: Relações decide o que é do seu ofício (o plano de demanda, a qualificação '
             'das oportunidades, a estratégia de experiência do cliente, a pauta e o conteúdo externo e as parcerias '
             'dentro da alçada), ouvidos o executivo da empresa e Negócios. O executivo aprova o que se diz em nome da '
             'empresa e quem fala por ela. Negócios vende e renova; Operações atende e entrega; a Identidade dá a marca e '
             'os padrões; a Governança conduz o comitê de crise, e o dono da crise decide; a Governança cuida dos contratos e das regras de dados pessoais.')
MUDOU_INTRO = ('Comparação com o catálogo da rodada 2 (49 jornadas e 216 workflows), que continua no documento do '
               'projeto até cada círculo ser fechado, e com as jornadas que o círculo 1 transferiu para Relações. '
               'Azul: acrescentado. Verde: ajustado. Vermelho: retirado.')
COBERTURA_TXT = ('Processos do APQC PCF 7.4 ligados às funções de Relações, grupo a grupo: onde cada um está neste '
                 'modelo. Os nomes estão como no referencial.')

P, A, R = 'REP', 'REA', 'RER'

# produtos de Relações usados em mais de uma jornada
PLANO_DEM = 'Plano de demanda do ciclo: públicos, ofertas, canais, ações, alvos e orçamento'
RES_DEM = 'Resultado das ações de demanda por canal e oferta'
FUNIL = 'Situação do funil: contatos, oportunidades entregues, aceitas e devolvidas'
OPORT_Q = 'Oportunidade qualificada, com o contato, a necessidade e a origem'
CRITERIO = 'Critério de oportunidade qualificada combinado com Negócios'
BASE_REL = 'Base de relacionamento atualizada, com a base legal e o histórico'
CX = 'Estratégia de experiência do cliente: personas, mapa da jornada e padrões de experiência'
PLANO_SUC = 'Plano de sucesso do cliente: resultados esperados, marcos e contatos'
INDICACAO = 'Indicação de cliente, com o consentimento do indicado'
CASO_CLI = 'Caso de cliente autorizado para comunicação'
CONTATOS_PARC = 'Contatos de parceiros e de relações institucionais'
RES_COM = 'Resultado da comunicação externa'
SINAIS_CL = 'Sinais classificados por tema de reputação, público e gravidade'
# produtos que Relações entrega a círculos já fechados (nomes que eles já esperam)
ESCUTA = 'Escuta dos públicos'
PERCEP = 'Percepção dos públicos e sinais de reputação'
SINAIS = 'Sinais de clientes, parceiros e concorrentes vistos no relacionamento'
LICOES_CLI = 'Lições de clientes perdidos, renovados e ampliados'
CONSULTA = 'Consulta sobre caso não coberto'
# produtos de outros círculos
DIRECAO = 'Direção estratégica e públicos prioritários'
ALVOS = 'Alvos e iniciativas do ciclo'
OFERTA_LANC = 'Oferta aprovada para lançamento'
DEC_ENCERRAR = 'Decisão de encerrar aposta em desenvolvimento ou oferta em uso'
DATA_SAIDA = 'Data de saída confirmada da aposta ou da oferta encerrada'
MANDATO = 'Mandato da empresa'
MUD_EST = 'Mudança na estratégia a comunicar'
OFERTA_CAT = 'Oferta no catálogo de ofertas: escopo, método, conteúdo-base, preço-base e indicadores'
OFERTA_FORA = 'Aposta ou oferta encerrada e fora do catálogo de ofertas'
POS_OFERTA = 'Posicionamento da oferta e público-alvo'
LEITURA = 'Leitura de mercado, clientes e concorrentes'
PAINEL = 'Painel de indicadores de cada círculo, com dono e análise'
DECL = 'Declaração de identidade vigente'
MUD_DECL = 'Mudança na declaração a comunicar'
PADROES_ID = 'Padrões de identidade vigentes'
RESPOSTA_ID = 'Resposta à consulta'
PROTOCOLO = 'Protocolo de crise'
REGRA_MARCA = 'Regra de uso da marca por terceiros'
MAT_VENC = 'Aviso de materiais vencidos'
PACOTE_MARCA = 'Pacote de marca publicado'
MARCA_RET = 'Marca retirada de uso'
POSIC = 'Posicionamento e casa de mensagens vigentes'
LACUNAS_EXEC = 'Lacunas de execução apontadas'
RESUMO_PAD = 'Resumo da avaliação dos padrões'
SIGILO = 'Regras de sigilo e de dados pessoais'
ALCADAS = 'Regras e alçadas vigentes'
RECLAMACOES = 'Reclamações e incidentes de clientes, com a causa'

JORNADAS = []

# ================================================================ DEMANDA
JORNADAS.append(dict(
    code='RE-01',
    nome='Planejar a geração de demanda do ciclo por público, oferta e canal',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Ter, a cada ciclo, um plano de demanda de cada empresa que diga a que públicos falar, com que ofertas, por quais canais e ações, com que alvo e com que orçamento, a partir da direção, dos alvos, das ofertas no catálogo e do resultado do ciclo anterior, e com o critério de oportunidade qualificada combinado com Negócios. Relações decide o plano, ouvidos Negócios e o executivo; a Gestão confere o orçamento.',
    frequencia='A cada ciclo de demanda (cadência: trimestral) e por evento: oferta aprovada para lançamento, revisão pedida pelo resultado das ações ou resposta da Gestão a pedido de recurso',
    automacao=('média', 'Reunir as entradas, comparar com os alvos, propor o plano e somar o custo são de agente e automação; decidir públicos, canais, ações e alvos e combinar o critério com Negócios são de pessoa de Relações.'),
    base=['barcelona', 'apqc'],
    lanes=['EST', 'GES', 'NEG', 'EXE', P, A, R],
    inicios=[I('Ciclo de demanda iniciado', R, 'timer'),
             I('Oferta aprovada para lançamento recebida', 'EST', 'message'),
             I('Resposta ao pedido de recurso recebida', 'GES', 'message'),
             I('Revisão do plano de demanda pedida', R, 'message')],
    fins=[F('Plano de demanda aprovado e publicado', R)],
    etapas=[
        E('Reunir o que orienta a demanda do ciclo', 'Relações', 'Autopiloto', 'baixo',
          [(DIRECAO, 'Estratégia'), (ALVOS, 'Estratégia'), (OFERTA_LANC, 'Estratégia'), (MANDATO, 'Estratégia'),
           (OFERTA_CAT, 'Inteligência'), (POS_OFERTA, 'Inteligência'), (POSIC, 'Identidade'), (LEITURA, 'Inteligência'),
           (PAINEL, 'Inteligência'), ('Plano de lançamento da oferta', 'Integração'), ('Resposta ao pedido de recurso adicional', 'Gestão'),
           (RES_DEM, 'RE-02'), ('Pedido de revisão do plano de demanda', 'RE-02'), (FUNIL, 'RE-03'), (CX, 'RE-04')],
          [T('Reunir direção, alvos, ofertas, lançamentos, leitura de mercado e resultado anterior', R),
           T('Comparar o resultado do ciclo anterior com os alvos e apontar o que funcionou', A)],
          [('Diagnóstico de demanda do ciclo', ['etapa 2'])]),
        E('Definir públicos, ofertas, canais, ações e alvos de demanda', 'Relações, ouvidos Negócios e o executivo', 'Assistido', 'médio',
          [('Diagnóstico de demanda do ciclo', 'etapa 1'), ('Ajustes pedidos ao plano de demanda', 'etapa 3')],
          [T('Propor públicos, ofertas prioritárias, canais, ações e calendário de cada empresa', A),
           PAR([T('Opinar sobre a capacidade de atender as oportunidades previstas', 'NEG')],
               [T('Opinar sobre os públicos e as ofertas prioritárias da empresa', 'EXE')]),
           T('Decidir públicos, canais, ações e alvos de demanda, ouvidos Negócios e o executivo', P),
           T('Definir para cada ação o alvo, a medida de resultado e a medida de alcance', P),
           T('Combinar com Negócios o critério de oportunidade qualificada do ciclo', P, 'manual'),
           D('Relações e Negócios chegaram a acordo sobre o critério?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Decidir o critério de oportunidade qualificada da empresa, sem acordo', 'EXE')])])],
          [('Proposta de plano de demanda', ['etapa 3'])]),
        E('Conferir o orçamento e aprovar o plano', 'Relações, com Gestão', 'Copiloto', 'médio',
          [('Proposta de plano de demanda', 'etapa 2'), ('Orçamento de demanda do ciclo', 'Gestão')],
          [T('Somar o custo das ações e comparar com o orçamento de demanda do ciclo', A),
           T('Conferir o custo das ações com o orçamento aprovado', 'GES'),
           D('O plano cabe no orçamento?', P,
             [S('Sim', 'seg'),
              S('Não, ajustar o plano', 'E2'),
              S('Não: seguir com o que cabe e pedir recurso', 'seg',
                via=[T('Pedir à Gestão recurso adicional, com o efeito esperado nos alvos', R)])]),
           T('Aprovar o plano de demanda do ciclo', P)],
          [('Plano de demanda aprovado', ['etapa 4']),
           ('Ajustes pedidos ao plano de demanda', ['etapa 2']),
           ('Pedido de recurso adicional para demanda', ['Gestão'])]),
        E('Publicar o plano e avisar quem executa', 'Relações', 'Autômato', 'baixo',
          [('Plano de demanda aprovado', 'etapa 3')],
          [T('Registrar a versão do plano, o critério combinado e o calendário de ações', R),
           T('Avisar Negócios, Integração, os executivos e quem executa as ações do plano', R)],
          [(PLANO_DEM, ['RE-02', 'RE-07', 'Negócios', 'Integração', 'Executivos', 'Gestão']),
           (CRITERIO, ['RE-03', 'Negócios'])]),
    ]))

JORNADAS.append(dict(
    code='RE-02',
    nome='Executar as ações de demanda e medir o resultado',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Levar cada ação do plano aos públicos certos, com material conforme os padrões de identidade e só para quem pode ser abordado, captar os contatos com a base legal e medir o resultado de cada ação contra o alvo, e não só pelo alcance; e recolher o material em circulação quando a marca sai de uso ou o material vence.',
    frequencia='Por ação do plano de demanda, no calendário, e por evento: ação fora do plano pedida, marca retirada de uso ou material vencido',
    automacao=('média (alta na execução, média na preparação)', 'Redigir, montar o público, publicar, registrar e medir são de agente e automação; aprovar a ação, o material e o público é de pessoa. Preço e condições passam por Negócios; o que fala em nome da empresa, pelo executivo.'),
    base=['apqc', 'barcelona'],
    lanes=['SOL', 'IDE', 'NEG', 'GES', 'GOV', 'EXE', 'ITG', P, A, R],
    inicios=[I('Ação do plano de demanda iniciada', R, 'timer'),
             I('Ação fora do plano pedida', 'SOL', 'message'),
             I('Marca retirada ou material vencido avisado', 'IDE', 'message')],
    fins=[F('Ação concluída e medida', R), F('Ação recusada, com o motivo', R),
          F('Material recolhido e substituído', R)],
    etapas=[
        E('Preparar a ação: mensagem, público, canal e material', 'Relações', 'Copiloto', 'médio',
          [(PLANO_DEM, 'RE-01'), ('Pedido de ação fora do plano', 'Solicitante'), (BASE_REL, 'RE-03'), (POSIC, 'Identidade'),
           (PACOTE_MARCA, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade'), (MAT_VENC, 'Identidade'),
           (MARCA_RET, 'Identidade'), (LACUNAS_EXEC, 'Identidade'), (POS_OFERTA, 'Inteligência'), (OFERTA_CAT, 'Inteligência'),
           ('Tabela de preços e política comercial vigentes', 'Negócios')],
          [D('O que abriu o trabalho?', R,
             [S('Ação do plano', 'seg'),
              S('Ação fora do plano', 'seg',
                via=[T('Conferir com a Gestão o custo da ação fora do plano', 'GES'),
                     T('Decidir se a ação fora do plano entra, com o recurso conferido', P)]),
              S('Marca retirada ou material vencido', 'F3',
                via=[T('Listar o material em circulação com a marca retirada ou vencido', A),
                     T('Retirar o material dos canais e trocar pelo vigente', R),
                     T('Conferir a troca e avisar quem usa o material', P)])]),
           D('A ação vai ser feita?', P,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Avisar quem pediu de que a ação não será feita, com o motivo', R)])]),
           T('Redigir mensagem e material, corrigindo as lacunas de execução já apontadas', A),
           T('Montar o público da ação na base, só com quem pode ser abordado', A),
           T('Conferir mensagem e material com os padrões de identidade', A),
           D('O material está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o material no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o material não coberto pelos padrões', 'IDE', 'call')])]),
           D('A ação traz preço ou condição comercial?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o preço e as condições com a tabela e a política comercial', 'NEG')])]),
           D('A ação traz promessa, dado pessoal ou comparação com concorrente?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir a promessa, a comparação e o uso de dados da ação', 'GOV')])]),
           D('A ação fala em nome da empresa ou de quem a dirige?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Aprovar o que a ação diz em nome da empresa', 'EXE')])]),
           T('Aprovar a ação, o material e o público', P)],
          [('Ação pronta para execução', ['etapa 2']),
           ('Resposta ao pedido de ação fora do plano', ['Solicitante']),
           (CONSULTA, ['Identidade'])]),
        E('Executar a ação nos canais e captar os contatos', 'Relações, com Integração', 'Autômato', 'médio',
          [('Ação pronta para execução', 'etapa 1')],
          [T('Preparar nos sistemas o registro das respostas e dos contatos da ação', 'ITG'),
           T('Publicar ou enviar a ação aprovada nos canais escolhidos, no calendário', R),
           T('Registrar as respostas e os contatos captados, com o consentimento dado', R)],
          [('Contatos captados pela ação, com o consentimento', ['RE-03']),
           ('Registros da ação executada', ['etapa 3'])]),
        E('Medir o resultado da ação e registrar o que aprender', 'Relações', 'Copiloto', 'baixo',
          [('Registros da ação executada', 'etapa 2'), (FUNIL, 'RE-03')],
          [T('Medir alcance, respostas, oportunidades geradas e resultado contra o alvo da ação', A),
           T('Concluir o que funcionou e o que mudar nas próximas ações', P),
           D('O resultado pede rever o plano de demanda?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Pedir a revisão do plano de demanda, com a evidência', R)])])],
          [(RES_DEM, ['RE-01', 'Executivos', 'Inteligência']),
           ('Pedido de revisão do plano de demanda', ['RE-01'])]),
    ]))

JORNADAS.append(dict(
    code='RE-03',
    nome='Qualificar os contatos e entregar a Negócios as oportunidades qualificadas',
    dominio='Demanda', classe='essencial', onda=1,
    objetivo='Fazer com que cada contato entre na base de relacionamento com a origem e a base legal, receba conteúdo já aprovado pelo interesse que mostra, seja qualificado pelo critério combinado com Negócios e, quando qualificado, chegue a Negócios com o histórico; e manter a base confiável, executando os pedidos dos titulares que a Governança decide.',
    frequencia='Por evento: contato captado, contato de interessado, indicação de cliente, contato de parceiro, interação de contato em nutrição ou pedido de titular; e a cada ciclo de nutrição e revisão da base (cadência: nutrição contínua, por evento; revisão da base semestral)',
    automacao=('alta no registro e na nutrição, baixa na qualificação', 'Registrar, juntar duplicados, nutrir, pontuar e entregar rodam com agente e automação; a conversa de qualificação e a aprovação do que se faz na base são de pessoa; a resposta ao titular é decidida pela Governança.'),
    base=['apqc', 'lgpd'],
    lanes=['SOL', 'NEG', 'GOV', 'EXE', P, A, R],
    inicios=[I('Contato captado por ação de demanda', R, 'message'),
             I('Contato de interessado recebido', 'SOL', 'message'),
             I('Indicação ou contato de parceiro recebido', R, 'message'),
             I('Interação de contato em nutrição registrada', R, 'signal'),
             I('Ciclo de nutrição atingido', R, 'timer'),
             I('Pedido de titular decidido pela Governança', 'GOV', 'message'),
             I('Revisão periódica da base iniciada', R, 'timer')],
    fins=[F('Oportunidade aceita por Negócios', R), F('Contato em nutrição', R),
          F('Contato encerrado, com o motivo', R), F('Pedido do titular cumprido ou base revisada', R),
          F('Oportunidade sem resposta, escalada ao executivo', R)],
    etapas=[
        E('Registrar o contato com a origem e a base legal', 'Relações', 'Autopiloto', 'médio',
          [('Contatos captados pela ação, com o consentimento', 'RE-02'), ('Contato de interessado', 'Solicitante'),
           (INDICACAO, 'RE-05'), (CONTATOS_PARC, 'RE-06'), (SIGILO, 'Governança')],
          [D('O que abriu o trabalho?', R,
             [S('Contato novo, indicação ou contato de parceiro', 'seg'),
              S('Interação ou ciclo de contato em nutrição', 'E2'),
              S('Pedido de titular ou revisão periódica da base', 'E5')]),
           T('Localizar o contato na base de relacionamento e juntar os registros duplicados', R),
           T('Registrar a origem, a base legal do tratamento e o consentimento, quando é a base', R),
           D('O contato tem base legal para ser abordado?', A,
             [S('Sim', 'prox'),
              S('Dúvida', 'seg', via=[T('Decidir se o contato tem base legal para ser abordado', P)]),
              S('Não', 'F3', via=[T('Registrar o contato sem abordagem e o motivo', R)])]),
           D('A pessoa confirmou a base legal?', P,
             [S('Sim', 'prox'),
              S('Não', 'F3', via=[T('Registrar o contato sem abordagem e o motivo da pessoa', R)])])],
          [('Contato registrado, com a base legal', ['etapa 2'])]),
        E('Nutrir o contato e pontuar o interesse', 'Relações', 'Autopiloto', 'médio',
          [('Contato registrado, com a base legal', 'etapa 1'),
           (OFERTA_CAT, 'Inteligência'), (CRITERIO, 'RE-01')],
          [T('Enviar ao contato material já aprovado nas ações, conforme o interesse dele', A),
           T('Registrar as interações e pontuar o interesse pelo critério de qualificação', R, 'rule'),
           D('O contato atingiu o critério para a conversa de qualificação?', R,
             [S('Sim', 'prox'),
              S('Ainda não', 'F2', via=[T('Manter o contato na nutrição até a próxima interação ou ciclo', R)]),
              S('Não tem interesse ou pediu para sair', 'F3', via=[T('Registrar a saída e parar as abordagens', R)])])],
          [('Contato com interesse pontuado', ['etapa 3'])]),
        E('Qualificar a oportunidade com o contato', 'Relações', 'Assistido', 'médio',
          [('Contato com interesse pontuado', 'etapa 2'), (CRITERIO, 'RE-01'), ('Oportunidade devolvida no aceite, com o motivo', 'etapa 4')],
          [T('Preparar a conversa: necessidade, porte, prazo e quem decide no cliente', A),
           T('Conversar com o contato para confirmar necessidade, prazo e quem decide', P, 'manual'),
           T('Avaliar a oportunidade contra o critério combinado com Negócios', P),
           D('A oportunidade está qualificada?', P,
             [S('Sim', 'prox'),
              S('Ainda não', 'F2', via=[T('Devolver o contato à nutrição, com o que falta', R)]),
              S('Não', 'F3', via=[T('Registrar o motivo e encerrar a abordagem', R)])])],
          [('Oportunidade qualificada pela conversa', ['etapa 4'])]),
        E('Entregar a oportunidade a Negócios e acompanhar o aceite', 'Relações', 'Autômato', 'baixo',
          [('Oportunidade qualificada pela conversa', 'etapa 3'), ('Aceite ou devolução da oportunidade, com o motivo', 'Negócios')],
          [T('Entregar a Negócios a oportunidade com o histórico, a necessidade e a origem', R),
           T('Registrar a entrega no funil de contatos e oportunidades', R),
           T('Receber de Negócios o aceite, a devolução ou o vencimento do prazo combinado', R, 'receive'),
           D('Negócios aceitou a oportunidade?', R,
             [S('Sim', 'F1', via=[T('Registrar o aceite no funil e na base de relacionamento', R)]),
              S('Não, devolveu com o motivo', 'E3'),
              S('Sem resposta no prazo', 'F5', via=[T('Apontar a oportunidade sem resposta a Negócios e ao executivo', R)])])],
          [(OPORT_Q, ['Negócios']),
           (FUNIL, ['RE-01', 'RE-02', 'Negócios', 'Inteligência']),
           ('Oportunidade sem resposta no prazo', ['Negócios', 'Executivos']),
           ('Oportunidade devolvida no aceite, com o motivo', ['etapa 3'])]),
        E('Executar os pedidos dos titulares e manter a base confiável', 'Relações, com Governança', 'Copiloto', 'alto',
          [('Pedido de titular, com a resposta decidida pela Governança', 'Governança'), (SIGILO, 'Governança')],
          [D('O que abriu o trabalho na base?', R,
             [S('Pedido de titular de dados', 'seg',
                via=[T('Localizar os registros do titular em toda a base de relacionamento', R),
                     T('Listar o que muda na base para cumprir a resposta decidida pela Governança', A)]),
              S('Revisão periódica da base', 'seg',
                via=[T('Apontar duplicidade, dado vencido e consentimento expirado pela regra da ficha', A)])]),
           T('Aprovar o que será corrigido, anonimizado, eliminado ou revogado na base', P),
           T('Executar na base e nos sistemas o que foi aprovado', R),
           T('Informar à Governança o que foi feito, com a data', R)],
          [('Pedido do titular cumprido, com a data', ['Governança']),
           (BASE_REL, ['RE-02', 'RE-05', 'Negócios', 'Inteligência'])]),
    ]))

# ================================================================ CLIENTES
JORNADAS.append(dict(
    code='RE-04',
    nome='Desenhar a experiência do cliente: personas, mapa da jornada e padrões de experiência',
    dominio='Clientes', classe='essencial', onda=1,
    objetivo='Ter, para cada empresa, uma estratégia de experiência do cliente escrita e validada com clientes: quem são os clientes (personas), por onde passam (mapa da jornada), o que vivem em cada ponto de contato e que padrão de experiência cada etapa tem de cumprir, coerente com os valores e o posicionamento da marca. Operações, Negócios e Integração dizem se conseguem cumprir; Relações decide, ouvidos o executivo e os clientes.',
    frequencia='A cada revisão da experiência (cadência: anual) e por evento: oferta aprovada para lançamento ou lacuna de experiência apontada',
    automacao=('média', 'Reunir reclamações, saúde, percepção e indicadores, propor personas e o mapa e conferir com os padrões são de agente; ouvir clientes, desenhar os pontos de contato com Operações e decidir os padrões são de pessoas.'),
    base=['nng_journey', 'nng_blueprint', 'apqc'],
    lanes=['SOL', 'CLI', 'EST', 'EXE', 'OPE', 'NEG', 'ITG', 'IDE', P, A, R],
    inicios=[I('Revisão da experiência iniciada', R, 'timer'),
             I('Oferta aprovada para lançamento recebida', 'EST', 'message'),
             I('Lacuna de experiência apontada', 'SOL', 'message')],
    fins=[F('Estratégia de experiência publicada', R), F('Revisão encerrada sem mudança', R)],
    etapas=[
        E('Avaliar a experiência atual dos clientes', 'Relações, com Operações', 'Copiloto', 'médio',
          [(OFERTA_LANC, 'Estratégia'), (OFERTA_CAT, 'Inteligência'), (LEITURA, 'Inteligência'), (PAINEL, 'Inteligência'),
           (RECLAMACOES, 'Operações'), (LACUNAS_EXEC, 'Identidade'), ('Lacuna de experiência apontada', 'Solicitante'),
           ('Saúde dos clientes e motivos de perda', 'RE-05'), (PERCEP, 'RE-08')],
          [T('Reunir reclamações, saúde, percepção e indicadores por etapa da jornada do cliente', A),
           T('Ouvir clientes sobre a experiência em cada etapa', P, 'manual'),
           T('Apontar as lacunas de experiência e as causas prováveis de cada uma', A),
           T('Concluir as lacunas de experiência e as causas', P),
           D('As lacunas pedem mudar a estratégia de experiência?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a avaliação sem mudança e avisar quem apontou a lacuna', R)])])],
          [('Avaliação da experiência, com lacunas e causas', ['etapa 2']),
           ('Avaliação da experiência sem mudança', ['Solicitante', 'Operações', 'Executivos'])]),
        E('Desenhar personas, mapa da jornada e padrões de experiência', 'Relações, com Operações, Negócios e Integração', 'Copiloto', 'médio',
          [('Avaliação da experiência, com lacunas e causas', 'etapa 1'), ('Ajustes pedidos à estratégia de experiência', 'etapa 3'),
           (POSIC, 'Identidade'), (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Propor personas e o mapa da jornada: fases, ações, modos de pensar, emoções e oportunidades', A),
           T('Desenhar com Operações os pontos de contato e o que acontece por trás deles', P, 'manual'),
           T('Definir o padrão de experiência de cada etapa da jornada do cliente', P),
           PAR([T('Dizer se a operação consegue cumprir os padrões de experiência', 'OPE')],
               [T('Dizer se a venda e a renovação conseguem cumprir os padrões', 'NEG')],
               [T('Apontar os sistemas e os agentes que os padrões de experiência pedem', 'ITG')]),
           D('Operações, Negócios e Integração conseguem cumprir os padrões?', P,
             [S('Sim', 'seg'), S('Não, ajustar os padrões', 'E2')]),
           T('Conferir a experiência com os valores, o posicionamento e os padrões da marca', A),
           D('A experiência está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir a experiência no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre a experiência não coberta pelos padrões', 'IDE', 'call')])])],
          [('Proposta de estratégia de experiência', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Validar com clientes e decidir a estratégia de experiência', 'Relações, ouvidos clientes e o executivo', 'Assistido', 'médio',
          [('Proposta de estratégia de experiência', 'etapa 2')],
          [T('Avaliar o mapa da jornada e os padrões propostos', 'CLI'),
           T('Conduzir a validação com clientes e registrar o que confirmaram', P, 'manual'),
           T('Opinar sobre a estratégia de experiência da empresa', 'EXE'),
           T('Decidir a estratégia de experiência, ouvidos clientes e o executivo', P),
           D('A estratégia de experiência está pronta para publicar?', P,
             [S('Sim', 'prox'), S('Não, ajustar', 'E2')])],
          [('Estratégia de experiência decidida', ['etapa 4']),
           ('Ajustes pedidos à estratégia de experiência', ['etapa 2'])]),
        E('Publicar a estratégia e entregar a quem atende, vende e desenha ofertas', 'Relações', 'Autômato', 'baixo',
          [('Estratégia de experiência decidida', 'etapa 3')],
          [T('Publicar a estratégia de experiência com versão e data de revisão', R),
           T('Avisar Operações, Negócios, Integração e os executivos do que mudou', R),
           T('Apontar a estratégia publicada à base de conhecimento da Inteligência', R)],
          [(CX, ['RE-01', 'RE-05', 'Operações', 'Negócios', 'Integração', 'Executivos', 'Inteligência']),
           ('Conteúdo novo apontado', ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='RE-05',
    nome='Acompanhar o sucesso de cada cliente, da entrada à renovação, à expansão ou à perda',
    dominio='Clientes', classe='essencial', onda=1,
    objetivo='Fazer com que cada cliente tenha um plano de sucesso combinado, que a saúde de cada cliente seja medida a cada ciclo, que o risco de perda seja tratado antes da perda, que o resultado seja apresentado ao cliente e que a renovação, a expansão, a indicação ou a lição da perda cheguem a quem age. Negócios negocia a renovação e a expansão e informa o resultado; Operações atende e entrega. Os clientes só são avisados de uma saída quando a data está confirmada.',
    frequencia='Por evento: contrato de cliente assinado, empresa adquirida, sinal de risco, vencimento de contrato, resultado da renovação, decisão de encerrar oferta ou data de saída confirmada; e a cada ciclo de acompanhamento do cliente (cadência: trimestral, por cliente)',
    automacao=('média', 'Reunir os dados, calcular a saúde, montar o relatório e apontar oportunidades são de agente e automação; combinar o plano, apresentar o resultado, tratar o risco e decidir o próximo passo são de pessoas de Relações, ouvido o executivo.'),
    base=['apqc'],
    lanes=['CLI', 'EST', 'NEG', 'OPE', 'EXE', 'IDE', P, A, R],
    inicios=[I('Contrato de cliente assinado', 'NEG', 'message'),
             I('Empresa adquirida no portfólio', 'EST', 'message'),
             I('Ciclo de acompanhamento do cliente iniciado', R, 'timer'),
             I('Sinal de risco do cliente detectado', R, 'signal'),
             I('Vencimento ou resultado da renovação informado', 'NEG', 'message'),
             I('Encerramento de oferta ou saída de empresa decidida', 'EST', 'message'),
             I('Mandato da empresa recebido', 'EST', 'message'),
             I('Oferta mantida, em espera ou devolvida depois da revisão', 'EST', 'message')],
    fins=[F('Ciclo de acompanhamento concluído', R),
          F('Oportunidade de renovação ou de expansão entregue a Negócios', R),
          F('Cliente perdido, com a lição registrada', R),
          F('Clientes avisados da saída e em transição', R),
          F('Clientes afetados listados, à espera da data de saída', R),
          F('Mandato registrado, sem aviso aos clientes', R),
          F('Oferta mantida; transição desfeita, quando houver', R)],
    etapas=[
        E('Receber o cliente e combinar o plano de sucesso', 'Relações, com Negócios, Operações e o cliente', 'Copiloto', 'médio',
          [('Contrato de cliente assinado, com o escopo vendido', 'Negócios'), ('Plano de implantação do cliente', 'Integração'),
           (CX, 'RE-04'), (BASE_REL, 'RE-03'), (DEC_ENCERRAR, 'Estratégia'), (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'),
           (OFERTA_FORA, 'Inteligência'), ('Plano de saída de clientes e contratos', 'Integração'),
           ('Aposta mantida depois da revisão', 'Estratégia'), ('Aposta em espera ou devolvida', 'Estratégia')],
          [D('O que abriu o trabalho?', R,
             [S('Cliente novo ou clientes de empresa adquirida', 'seg'),
              S('Ciclo, sinal de risco, vencimento ou resultado da renovação', 'E2'),
              S('Decisão de encerrar, ainda sem data de saída', 'F5',
                via=[T('Listar os clientes afetados pela oferta que será encerrada', R),
                     T('Preparar com Operações e Integração a transição, sem avisar os clientes ainda', P, 'manual')]),
              S('Data de saída confirmada, ou venda fechada ou encerramento de empresa', 'F4',
                via=[T('Listar os clientes afetados pela oferta ou pela empresa que sai', R),
                     T('Combinar com Operações e Integração a transição de cada cliente', P, 'manual'),
                     T('Avisar cada cliente da saída, na data confirmada, com a transição combinada', P, 'manual')]),
              S('Mandato de busca de comprador, de criação ou de mudança de mandato', 'F6',
                via=[T('Registrar o mandato e os clientes que ele alcança, sob sigilo e sem avisar os clientes', R)]),
              S('Oferta mantida, em espera ou devolvida depois da revisão', 'F7',
                via=[T('Desfazer com Operações e Integração a transição preparada, quando houver, sem avisar os clientes', P, 'manual')])]),
           T('Conferir o que foi vendido, os resultados que o cliente espera e quem decide nele', A),
           T('Combinar com o cliente o plano de sucesso: resultados, marcos e contatos', P, 'manual'),
           T('Confirmar o plano de sucesso e os contatos do cliente', 'CLI'),
           T('Registrar o plano de sucesso e avisar Operações e Negócios', R)],
          [(PLANO_SUC, ['etapa 2', 'etapa 3', 'Operações', 'Negócios']),
           ('Clientes avisados da saída, com a transição combinada', ['Operações', 'Negócios', 'Integração'])]),
        E('Medir a saúde do cliente e apontar o risco de perda', 'Relações', 'Autopiloto', 'baixo',
          [(PLANO_SUC, 'etapa 1'), (PAINEL, 'Inteligência'), ('Registros de entrega, atendimento e reclamações do cliente', 'Operações'),
           ('Situação de faturas e pagamentos do cliente', 'Gestão'), ('Vencimento do contrato e resultado da renovação', 'Negócios')],
          [T('Reunir uso, entregas, reclamações, pagamentos, contrato e interações do cliente', R),
           T('Calcular a saúde do cliente pela regra e comparar com o plano de sucesso', R, 'rule'),
           D('O cliente está em risco?', A,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Apontar o risco, a causa provável e a ação sugerida', A)])])],
          [('Saúde do cliente, com o risco e a causa provável', ['etapa 3']),
           ('Saúde dos clientes e motivos de perda', ['RE-04', 'Executivos'])]),
        E('Apresentar o resultado ao cliente e agir sobre o risco', 'Relações, com Operações, ouvido o executivo', 'Copiloto', 'médio',
          [('Saúde do cliente, com o risco e a causa provável', 'etapa 2'), (PLANO_SUC, 'etapa 1'), (PADROES_ID, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Montar o relatório de resultado do cliente contra o plano de sucesso', A),
           T('Conferir o relatório com os padrões de identidade', A),
           D('O relatório está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o relatório no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o relatório não coberto pelos padrões', 'IDE', 'call')])]),
           T('Apresentar ao cliente o resultado e ouvir a avaliação dele', P, 'manual'),
           T('Avaliar o resultado apresentado e dizer o que espera a seguir', 'CLI'),
           D('Há risco de perda a tratar?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Opinar sobre o plano de recuperação do cliente', 'EXE'),
                                    T('Combinar com Operações o plano de recuperação do cliente', P, 'manual'),
                                    T('Registrar o plano de recuperação e acompanhá-lo até o próximo ciclo', R)])])],
          [('Resultado apresentado e avaliação do cliente', ['etapa 4']),
           ('Plano de recuperação do cliente', ['Operações', 'Executivos']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir o próximo passo com o cliente: renovar, ampliar, indicar ou registrar a perda', 'Relações, ouvido o executivo', 'Copiloto', 'médio',
          [('Resultado apresentado e avaliação do cliente', 'etapa 3'), ('Vencimento do contrato e resultado da renovação', 'Negócios')],
          [T('Apontar oportunidade de renovação, de expansão ou de indicação pelo histórico do cliente', A),
           T('Opinar sobre o próximo passo com o cliente', 'EXE'),
           T('Decidir o próximo passo com o cliente, ouvido o executivo', P),
           D('Qual é o próximo passo com o cliente?', P,
             [S('Seguir acompanhando', 'seg'),
              S('Renovação ou expansão', 'F2',
                via=[T('Entregar a Negócios a oportunidade de renovação ou de expansão, com o histórico', R)]),
              S('Indicação ou caso de cliente', 'seg',
                via=[T('Pedir ao cliente a indicação, com o aceite do indicado, ou a autorização do caso', P, 'manual'),
                     T('Enviar a indicação ao registro de contatos e o caso autorizado à comunicação', R)]),
              S('Cliente perdido: não renovou ou cancelou', 'F3',
                via=[T('Ouvir o cliente sobre os motivos da perda', P, 'manual'),
                     T('Registrar a lição da perda, sem dado sigiloso', A)])]),
           T('Registrar o ciclo, os sinais do relacionamento e as lições do cliente', R)],
          [('Oportunidade de renovação ou de expansão, com o histórico', ['Negócios']),
           (INDICACAO, ['RE-03']),
           (CASO_CLI, ['RE-07']),
           (LICOES_CLI, ['Inteligência']),
           (SINAIS, ['Inteligência'])]),
    ]))

# ============================================== PARCERIAS E INSTITUIÇÕES
JORNADAS.append(dict(
    code='RE-06',
    nome='Formar e cuidar de parcerias e relações institucionais e autorizar o uso da marca por terceiros',
    dominio='Parcerias e instituições', classe='essencial', onda=2,
    objetivo='Fazer cada parceria ou relação institucional nascer de uma avaliação de encaixe, ser formalizada com objetivos, papéis e indicadores, por contrato ou por termo institucional conferido pela Governança e aprovado pelo executivo, ser ativada, acompanhada e, quando deixa de servir, encerrada com ordem; e decidir quem de fora pode usar as marcas, pela regra da Identidade, com a exceção decidida por Relações, ouvida a Identidade, e liberada pela Governança. A parceria acima da alçada sobe aos sócios pela Governança; a que muda o portfólio vai à Estratégia como aposta.',
    frequencia='Por evento: parceria proposta, pedido de uso da marca por terceiro, marca retirada de uso ou encerramento pedido; e na revisão de cada parceria (cadência: semestral, por parceria)',
    automacao=('média', 'Registrar, avaliar o parceiro, conferir com a regra e medir o resultado são de agente e automação; negociar, decidir e capacitar são de pessoas; o contrato e a liberação da exceção à regra da marca são da Governança.'),
    base=['iso44001', 'apqc'],
    lanes=['SOL', 'EST', 'IDE', 'PRC', 'EXE', 'GES', 'GOV', 'SOC', P, A, R],
    inicios=[I('Parceria ou relação institucional proposta', 'SOL', 'message'),
             I('Pedido de uso da marca por terceiro recebido', 'SOL', 'message'),
             I('Marca retirada de uso avisada', 'IDE', 'message'),
             I('Encerramento de parceria pedido', 'SOL', 'message'),
             I('Revisão da parceria iniciada', R, 'timer'),
             I('Parceria aprovada no portão da Estratégia', 'EST', 'message'),
             I('Parceria não aprovada no portão da Estratégia', 'EST', 'message')],
    fins=[F('Uso da marca decidido e registrado', R), F('Parceria não seguiu, com o motivo', R),
          F('Parceria avaliada e mantida', R), F('Parceria encerrada', R),
          F('Parceria levada à Estratégia como aposta', R), F('Autorizações da marca retirada revogadas', R),
          F('Uso da marca recusado, com o motivo', R)],
    etapas=[
        E('Registrar o pedido e avaliar o encaixe da parceria', 'Relações', 'Copiloto', 'médio',
          [('Proposta de parceria ou de relação institucional', 'Solicitante'), ('Pedido de uso da marca por terceiro', 'Solicitante'),
           ('Pedido de encerramento de parceria', 'Solicitante'), (MARCA_RET, 'Identidade'), (DIRECAO, 'Estratégia'),
           (LEITURA, 'Inteligência'), ('Parceria aprovada no portão, para formalizar', 'Estratégia'),
           ('Aposta em espera ou devolvida', 'Estratégia'), ('Lição da aposta encerrada', 'Estratégia')],
          [T('Registrar o pedido, quem pede e o que abriu o trabalho', R),
           D('O que abriu o trabalho?', R,
             [S('Parceria ou relação institucional nova', 'seg'),
              S('Uso da marca por terceiro', 'E5'),
              S('Revisão ou encerramento de parceria', 'E4'),
              S('Parceria aprovada no portão da Estratégia', 'E2',
                via=[T('Reunir a avaliação da parceria e a decisão do portão', R)]),
              S('Parceria encerrada, em espera ou devolvida no portão da Estratégia', 'F2',
                via=[T('Avisar o parceiro e quem propôs da decisão do portão, com o motivo', R)]),
              S('Marca retirada de uso', 'F6',
                via=[T('Revogar as autorizações de uso da marca retirada e avisar os terceiros', R)])]),
           T('Avaliar o parceiro: reputação, encaixe com a direção, capacidade e risco', A),
           T('Decidir se a parceria avança', P),
           D('A parceria avança?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Responder a quem propôs que a parceria não segue, com o motivo', R)])])],
          [('Parceria avaliada para negociação', ['etapa 2']),
           ('Resposta à proposta de parceria', ['Solicitante'])]),
        E('Negociar e formalizar a parceria', 'Relações, com Governança; acima da alçada, os sócios', 'Copiloto', 'alto',
          [('Parceria avaliada para negociação', 'etapa 1'), ('Mudança pedida nos termos da parceria', 'etapa 4'),
           (ALCADAS, 'Governança'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Combinar com o parceiro objetivos, papéis, contrapartidas e indicadores', P, 'manual'),
           T('Conferir os termos e o material conjunto com os padrões de identidade', A),
           D('Os termos estão conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir os termos no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre os termos não cobertos pelos padrões', 'IDE', 'call')])]),
           D('A parceria tem contrapartida financeira?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o custo, a receita e o efeito no orçamento da parceria', 'GES')])]),
           T('Aplicar a tabela de alçadas à parceria', R, 'rule'),
           D('Quem decide a parceria?', R,
             [S('Relações, dentro da alçada', 'seg', via=[T('Decidir a parceria, ouvido o executivo', P)]),
              S('Os sócios, acima da alçada', 'seg', via=[T('Levar a parceria à decisão dos sócios', 'GOV', 'call'),
                                                          T('Decidir a parceria pelos sócios', 'SOC', 'manual')]),
              S('Já aprovada no portão da Estratégia', 'seg'),
              S('A Estratégia: a parceria muda o portfólio', 'F5',
                via=[T('Levar a parceria à Estratégia como aposta, com a avaliação', R)])]),
           D('A parceria foi aprovada?', P,
             [S('Sim, ou já aprovada no portão da Estratégia', 'seg'),
              S('Não', 'F2', via=[T('Avisar o parceiro e quem propôs de que a parceria não segue', R)])]),
           D('A parceria pede contrato?', P,
             [S('Sim', 'seg', via=[T('Preparar e revisar o contrato de parceria', 'GOV', 'call'),
                                   T('Assinar o contrato de parceria em nome da empresa', 'EXE')]),
              S('Não: termo ou protocolo institucional', 'seg',
                via=[T('Conferir o termo institucional e o risco jurídico', 'GOV', 'call'),
                     T('Aprovar o termo institucional em nome da empresa', 'EXE')])])],
          [('Parceria formalizada, com plano conjunto e indicadores', ['etapa 3']),
           ('Ideia ou aposta nova', ['Estratégia']),
           (CONSULTA, ['Identidade'])]),
        E('Ativar a parceria', 'Relações, com o parceiro', 'Copiloto', 'médio',
          [('Parceria formalizada, com plano conjunto e indicadores', 'etapa 2'),
           (PACOTE_MARCA, 'Identidade'), (OFERTA_CAT, 'Inteligência')],
          [T('Montar o plano de ativação: contatos, materiais do pacote de marca, capacitação e calendário', A),
           T('Capacitar o parceiro nas ofertas e no uso da marca', P, 'manual'),
           T('Confirmar o plano de ativação e os contatos do parceiro', 'PRC'),
           T('Registrar a parceria e os contatos na base de relacionamento', R)],
          [('Parceria ativa, com plano de ativação', ['etapa 4', 'Negócios', 'Operações']),
           (CONTATOS_PARC, ['RE-03'])]),
        E('Acompanhar a parceria e decidir manter, mudar ou encerrar', 'Relações, com o parceiro', 'Assistido', 'médio',
          [('Parceria ativa, com plano de ativação', 'etapa 3'), ('Pedido de encerramento de parceria', 'Solicitante'),
           (PAINEL, 'Inteligência')],
          [T('Medir o resultado da parceria contra os indicadores combinados', A),
           T('Avaliar com o parceiro o resultado e o que mudar', P, 'manual'),
           T('Decidir manter, mudar ou encerrar a parceria', P),
           D('Qual é a decisão sobre a parceria?', P,
             [S('Manter', 'F3', via=[T('Registrar a avaliação e a data da próxima revisão', R)]),
              S('Mudar os termos', 'E2'),
              S('Encerrar', 'F4',
                via=[T('Combinar com o parceiro a saída e o que fica pendente', P, 'manual'),
                     T('Encerrar o contrato ou o termo de parceria', 'GOV', 'call'),
                     T('Retirar o uso da marca pelo parceiro e avisar Negócios e Operações', R)])])],
          [('Resultado da parceria', ['Executivos', 'Negócios']),
           ('Mudança pedida nos termos da parceria', ['etapa 2']),
           (SINAIS, ['Inteligência'])]),
        E('Decidir e registrar o uso da marca por terceiro', 'Relações; a exceção, ouvida a Identidade e liberada pela Governança', 'Copiloto', 'médio',
          [('Pedido de uso da marca por terceiro', 'Solicitante'), (REGRA_MARCA, 'Identidade'), (PACOTE_MARCA, 'Identidade'),
           (RESPOSTA_ID, 'Identidade')],
          [T('Conferir o pedido com a regra de uso da marca por terceiros', A),
           D('O uso está coberto pela regra?', A,
             [S('Sim', 'seg'),
              S('Não: pede exceção à regra', 'seg',
                via=[T('Responder à consulta sobre o uso fora da regra', 'IDE', 'call')])]),
           D('A exceção pode ser concedida?', P,
             [S('Não se aplica: uso coberto pela regra', 'seg'),
              S('Sim', 'seg', via=[T('Liberar os termos e o risco do uso fora da regra', 'GOV')]),
              S('Não', 'F7', via=[T('Recusar o pedido e responder a quem pediu, com o motivo', R)])]),
           D('O uso pode seguir?', P,
             [S('Sim: coberto pela regra ou liberado pela Governança', 'seg'),
              S('Não: a Governança não liberou', 'F7',
                via=[T('Recusar o pedido sem liberação e responder a quem pediu, com o motivo', R)])]),
           T('Decidir o uso da marca dentro da regra ou da exceção aceita: autorizar ou recusar', P),
           T('Registrar a decisão, o prazo e as condições e responder a quem pediu', R)],
          [('Resposta ao pedido de uso da marca', ['Solicitante']),
           ('Autorizações de uso da marca por terceiros, com prazo', ['Governança']),
           (CONSULTA, ['Identidade'])]),
    ]))

# ================================================= COMUNICAÇÃO E REPUTAÇÃO
JORNADAS.append(dict(
    code='RE-07',
    nome='Comunicar para fora: pauta, conteúdo, imprensa e porta-vozes',
    dominio='Comunicação e reputação', classe='essencial', onda=1,
    objetivo='Comunicar aos públicos externos, com uma só voz e dentro dos padrões de identidade, os fatos, as mudanças, os lançamentos e os casos que importam, preparar quem fala pela empresa e medir o efeito de cada tema contra o alvo, e não só a exposição. O executivo aprova o que se diz em nome da empresa; a Governança confere o risco jurídico. A comunicação interna é da Gestão.',
    frequencia='A cada ciclo de pauta (cadência: pauta mensal) e por evento: fato a comunicar ou pedido de imprensa',
    automacao=('média', 'Reunir fatos, propor a pauta, redigir, conferir, publicar e medir são de agente e automação; decidir a pauta, revisar, aprovar e preparar os porta-vozes são de pessoas.'),
    base=['barcelona', 'apqc'],
    lanes=['SOL', 'EXE', 'GOV', 'IDE', P, A, R],
    inicios=[I('Ciclo de pauta iniciado', R, 'timer'),
             I('Fato a comunicar recebido', 'SOL', 'message'),
             I('Pedido de imprensa recebido', 'SOL', 'message')],
    fins=[F('Conteúdo publicado e medido', R), F('Pauta sem tema a comunicar', R),
          F('Conteúdo não publicado, com o motivo', R)],
    etapas=[
        E('Decidir a pauta: o que comunicar, a quem e com que alvo', 'Relações, ouvido o executivo', 'Copiloto', 'baixo',
          [(PLANO_DEM, 'RE-01'), (MUD_DECL, 'Identidade'), (MUD_EST, 'Estratégia'), (OFERTA_LANC, 'Estratégia'), (MANDATO, 'Estratégia'),
           (MARCA_RET, 'Identidade'), (LACUNAS_EXEC, 'Identidade'), (CASO_CLI, 'RE-05'), (RES_COM, 'etapa 4'),
           ('Fato a comunicar', 'Solicitante'), ('Pedido de imprensa', 'Solicitante')],
          [T('Reunir fatos, mudanças, lançamentos, casos e pedidos de imprensa do período', R),
           T('Propor a pauta: tema, público, canal, mensagem-chave e alvo de cada tema', A),
           T('Opinar sobre os temas que falam em nome da empresa', 'EXE'),
           T('Decidir a pauta, ouvido o executivo', P),
           D('Há tema a comunicar?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a pauta sem tema e responder aos pedidos recebidos', R)])])],
          [('Pauta decidida, com o alvo de cada tema', ['etapa 2'])]),
        E('Produzir o conteúdo e conferir com os padrões de identidade', 'Relações', 'Copiloto', 'médio',
          [('Pauta decidida, com o alvo de cada tema', 'etapa 1'), ('Ajustes pedidos ao conteúdo', 'etapa 3'),
           (POSIC, 'Identidade'), (PADROES_ID, 'Identidade'), (PACOTE_MARCA, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Redigir o conteúdo de cada tema no guia de voz e com a casa de mensagens', A),
           T('Conferir o conteúdo com os padrões de identidade', A),
           D('O conteúdo está conforme os padrões de identidade?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Corrigir o conteúdo no que não está conforme os padrões', P)]),
              S('Há ponto que os padrões não cobrem', 'seg',
                via=[T('Responder à consulta sobre o conteúdo não coberto pelos padrões', 'IDE', 'call')])]),
           T('Revisar o conteúdo e a fonte de cada afirmação', P)],
          [('Conteúdo pronto para aprovação', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Aprovar o conteúdo e preparar os porta-vozes', 'Relações, com o executivo e a Governança', 'Assistido', 'médio',
          [('Conteúdo pronto para aprovação', 'etapa 2'), (SIGILO, 'Governança')],
          [D('O conteúdo fala em nome da empresa?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Aprovar o que a empresa diz e quem fala por ela', 'EXE')])]),
           D('O conteúdo traz risco jurídico ou pede sigilo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o risco jurídico e o que pode ser dito', 'GOV')])]),
           T('Aprovar o conteúdo final, com o que o executivo e a Governança disseram', P),
           D('O conteúdo está aprovado?', P,
             [S('Sim', 'seg'),
              S('Não, ajustar', 'E2'),
              S('Não: não deve ser publicado', 'F3', via=[T('Registrar o motivo e responder a quem pediu o tema', R)])]),
           D('O tema pede porta-voz?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Preparar o porta-voz com as mensagens, as perguntas difíceis e os limites', P, 'manual')])])],
          [('Conteúdo aprovado', ['etapa 4']),
           ('Ajustes pedidos ao conteúdo', ['etapa 2'])]),
        E('Publicar o conteúdo, atender a imprensa e medir o efeito', 'Relações', 'Autopiloto', 'médio',
          [('Conteúdo aprovado', 'etapa 3')],
          [T('Publicar o conteúdo aprovado nos canais da empresa e enviar à imprensa, no calendário', R),
           T('Registrar os pedidos de imprensa, as entrevistas e o que foi publicado', R),
           T('Medir alcance, resultado e efeito de cada tema contra o alvo, além da exposição', A)],
          [('Conteúdo externo publicado', ['Públicos externos', 'Gestão']),
           (RES_COM, ['etapa 1', 'RE-08', 'Executivos'])]),
    ]))

JORNADAS.append(dict(
    code='RE-08',
    nome='Monitorar a percepção dos públicos e a reputação e acionar a resposta a crises',
    dominio='Comunicação e reputação', classe='essencial', onda=1,
    objetivo='Saber, a cada ciclo, como os públicos percebem as marcas, encaminhar cada lacuna a quem pode agir e detectar cedo o que pode virar crise. Relações apura os fatos e leva ao comitê da Governança todo sinal grave ou em dúvida; o comitê declara a crise, decide a posição e o porta-voz e a encerra; Relações redige e publica a comunicação da posição decidida.',
    frequencia='A cada ciclo de monitoramento (cadência: coleta contínua; análise mensal) e por evento: sinal de reputação detectado',
    automacao=('média (alta na coleta, baixa na crise)', 'Coletar, classificar, agrupar e publicar são de agente e automação; apurar os fatos, concluir a percepção e comunicar na crise são de pessoas; declarar e encerrar a crise e decidir a posição são da Governança, com o executivo.'),
    base=['reptrak', 'iso22361', 'barcelona', 'apqc'],
    lanes=['GOV', 'EXE', P, A, R],
    inicios=[I('Ciclo de monitoramento iniciado', R, 'timer'),
             I('Sinal de reputação detectado', R, 'signal')],
    fins=[F('Percepção dos públicos publicada', R), F('Sinal sem crise, encaminhado ao dono', R),
          F('Crise encerrada, com as lições registradas', R), F('Sinal guardado para o ciclo', R)],
    etapas=[
        E('Coletar e classificar os sinais sobre as marcas', 'Relações', 'Autopiloto', 'médio',
          [(PROTOCOLO, 'Identidade'), (POSIC, 'Identidade'), (RES_COM, 'RE-07'), (LEITURA, 'Inteligência'), (RECLAMACOES, 'Operações')],
          [T('Coletar menções, reclamações públicas, imprensa e conversas sobre as marcas', R),
           T('Classificar cada sinal por fator de reputação, público, gravidade e marca', A),
           D('O trabalho é o ciclo de monitoramento?', R,
             [S('Sim', 'E4', via=[T('Abrir como sinal avulso cada sinal grave ou em dúvida do ciclo', R)]),
              S('Não: sinal avulso', 'seg')]),
           D('O sinal pode virar crise pelo critério do protocolo?', A,
             [S('Sim, gravidade alta ou dúvida', 'prox'),
              S('Não', 'F4', via=[T('Guardar o sinal classificado para a análise do ciclo', R)])])],
          [(SINAIS_CL, ['etapa 2', 'etapa 4'])]),
        E('Apurar o sinal e levar ao comitê de crise', 'Relações, com o comitê de crise da Governança', 'Copiloto', 'alto',
          [(SINAIS_CL, 'etapa 1'), (PROTOCOLO, 'Identidade'),
           ('Declaração, posição e encerramento da crise decididos pelo comitê', 'Governança')],
          [T('Apurar os fatos do sinal com quem está perto do caso', P, 'manual'),
           T('Levar ao comitê de crise da Governança os fatos apurados', R),
           T('Levar ao dono da crise a declaração, a posição e o porta-voz, pelo comitê', 'GOV', 'call'),
           D('O dono da crise declarou crise?', 'GOV',
             [S('Não', 'F2', via=[T('Encaminhar o sinal ao dono do tema: Operações, Negócios ou o executivo', R)]),
              S('Sim', 'prox')])],
          [('Alerta de crise, com os fatos apurados', ['Governança', 'Executivos']),
           ('Crise declarada, com a posição e o porta-voz decididos', ['etapa 3'])]),
        E('Comunicar a posição decidida até o encerramento da crise', 'Relações, com o executivo e o comitê de crise', 'Copiloto', 'alto',
          [('Crise declarada, com a posição e o porta-voz decididos', 'etapa 2'), (PROTOCOLO, 'Identidade'), (PADROES_ID, 'Identidade'),
           ('Declaração, posição e encerramento da crise decididos pelo comitê', 'Governança')],
          [T('Redigir a comunicação da posição decidida, no protocolo de crise e nos padrões', A),
           T('Conferir a comunicação com o protocolo de crise e com o que o comitê decidiu', P),
           T('Aprovar a comunicação da posição da empresa', 'EXE'),
           T('Publicar a comunicação e acompanhar a reação dos públicos', R),
           T('Receber do comitê o encerramento da crise ou uma nova posição', R, 'receive'),
           D('O comitê encerrou a crise?', P,
             [S('Sim', 'F3', via=[T('Registrar as lições da crise, sem dado sigiloso', P)]),
              S('Não: há nova posição a comunicar', 'E3')])],
          [('Comunicação da posição sobre a crise', ['Públicos externos']),
           ('Lições da crise', ['Governança']),
           ('Lição apontada', ['Inteligência'])]),
        E('Analisar a percepção dos públicos e entregar a quem pode agir', 'Relações', 'Copiloto', 'baixo',
          [(SINAIS_CL, 'etapa 1'), (RESUMO_PAD, 'Identidade'), (LACUNAS_EXEC, 'Identidade')],
          [T('Agrupar os sinais do ciclo nos sete fatores de reputação e comparar com o anterior', A),
           T('Concluir a percepção dos públicos e o que mudou', P),
           T('Encaminhar cada lacuna a quem pode agir: Operações, Negócios, executivo ou círculo', R),
           T('Publicar a percepção e a escuta dos públicos', R)],
          [(PERCEP, ['Identidade', 'Inteligência', 'RE-04', 'Executivos']),
           (ESCUTA, ['Identidade']),
           ('Lacunas de percepção encaminhadas ao dono', ['Executivos', 'Operações', 'Negócios'])]),
    ]))

# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Demanda', 'Planejar e executar a geração de demanda e entregar a Negócios oportunidades qualificadas.'),
    ('Clientes', 'Desenhar a experiência do cliente e cuidar do sucesso de cada cliente depois da venda.'),
    ('Parcerias e instituições', 'Formar e cuidar de parcerias e relações institucionais e decidir o uso da marca por terceiros.'),
    ('Comunicação e reputação', 'Comunicar para fora e vigiar como os públicos percebem as marcas.'),
]

ONDAS = {
    1: 'O que os círculos fechados já esperam de Relações e o que gera demanda e cuida dos clientes',
    2: 'O que amplia o alcance: parcerias, relações institucionais e uso da marca por terceiros',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4. Os processos das funções de Relações estão em quatro blocos: 1.2.8, estratégia de experiência do cliente; 3.2 e 3.3, estratégia e planos de marketing; 3.4.2, 3.5.1, 3.5.2 e 3.5.5, oportunidades, clientes e parceiros; 12.2 e 12.5, relações com governo, entidades e imprensa. A tabela de cobertura, na aba Método, mostra onde cada um foi parar.',
    'barcelona': 'Sete princípios de medição da comunicação, de 2020. Os que usamos: fixar alvos é pré-requisito do planejamento e da medição; medir resultado e efeito, e não só a entrega; medir de forma qualitativa e quantitativa; a equivalência em valor de anúncio (AVE) não é o valor da comunicação. Base dos alvos e das medidas de cada ação na RE-01 e na RE-02, da medição do efeito de cada tema na RE-07 e da leitura da percepção na RE-08. Os princípios tratam de comunicação; usá-los também nas ações de demanda é leitura nossa.',
    'nng_journey': 'O mapa da jornada é a visualização do processo que uma pessoa percorre para atingir um objetivo. Cinco elementos: o ator, o cenário e as expectativas, as fases da jornada, as ações, os modos de pensar (mindsets) e as emoções, e as oportunidades. Base do mapa da jornada na RE-04.',
    'nng_blueprint': 'Mapa de serviço com quatro elementos: ações do cliente, ações à vista do cliente, ações de bastidor e processos. Base do desenho dos pontos de contato com Operações na etapa 2 da RE-04.',
    'iso44001': 'Norma de requisitos para identificar, desenvolver e gerir relações de negócio colaborativas dentro das organizações ou entre elas. Lemos só o resumo; a norma completa é paga e está em revisão. Usada como referência do ciclo de vida da parceria na RE-06, do encaixe à saída; as etapas da jornada vêm do APQC (3.4.2, 3.5.5 e 12.2.3).',
    'reptrak': 'Sete fatores de reputação, que formam a dimensão “Think” do modelo da RepTrak: produtos e serviços, desempenho, inovação, liderança, conduta, cidadania e ambiente de trabalho. Usados como temas para agrupar os sinais e a percepção dos públicos na RE-08.',
    'iso22361': 'Diretrizes para a capacidade de gestão de crises. Base do protocolo de crise da Identidade, que a RE-08 usa para classificar o sinal e acionar o comitê da Governança. Lemos só o resumo.',
    'lgpd': 'Bases legais do tratamento, entre elas o consentimento, a execução de contrato e o legítimo interesse (art. 7º); consentimento por escrito ou por meio que demonstre a vontade do titular, revogável a qualquer momento (art. 8º); acesso facilitado às informações do tratamento (art. 9º); direitos do titular, entre eles confirmar a existência do tratamento, acessar, corrigir, anonimizar, bloquear ou eliminar dados desnecessários ou excessivos, portar, eliminar os dados tratados com consentimento e revogar o consentimento (art. 18, I a VI e IX). Base do registro com a base legal, da saída do contato e da execução dos pedidos dos titulares na RE-03. Quem define a regra é a Governança.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio, script e recebimento, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# ----------------------------------- cobertura do referencial (APQC PCF 7.4)
COBERTURA = [
    ('1.2.8', 'Develop customer experience strategy', 'RE-04. Avaliar (1.2.8.1) na etapa 1; personas, mapa da jornada, validação com clientes e alinhamento aos valores da marca (1.2.8.2) nas etapas 2 e 3'),
    ('3.2.3', 'Define and manage channel strategy', 'RE-01, etapa 2, para os canais de demanda. Os canais de venda são de Negócios'),
    ('3.2.5', 'Develop marketing communication strategy', 'RE-01 e RE-07. A comunicação interna (3.2.5.4) é da Gestão'),
    ('3.2.6', 'Design and manage customer loyalty program', 'Não desenhado: nenhum círculo pediu programa de fidelidade'),
    ('3.3.1', 'Establish goals, objectives, and measures for products/services by channel/segment', 'RE-01, etapa 2: alvo e medida de cada ação'),
    ('3.3.2', 'Establish marketing budgets', 'RE-01, etapa 3, com a Gestão'),
    ('3.3.4', 'Develop and manage promotional activities', 'RE-02'),
    ('3.3.5', 'Track customer management measures', 'RE-05, etapa 2 (saúde do cliente), com os indicadores da Inteligência'),
    ('3.3.6', 'Analyze and respond to customer insight', 'RE-08 (redes e menções) e RE-03 (interações); a análise de dados é da Inteligência'),
    ('3.3.8', 'Develop go-to-market strategy', 'RE-01, para cada oferta aprovada para lançamento. A coordenação do lançamento é da Integração'),
    ('3.3.9', 'Manage product marketing material', 'RE-02, etapa 1: quem usa a marca produz o material, com o pacote de marca da Identidade'),
    ('3.4.2', 'Develop sales partner/alliance relationships', 'RE-06, etapas 1 a 3'),
    ('3.5.1', 'Manage leads/opportunities', 'RE-03 até a oportunidade qualificada (3.5.1.1 a 3.5.1.3). Daí em diante (3.5.1.4 em diante), Negócios'),
    ('3.5.2', 'Manage customers and accounts', 'RE-05 (relacionamento e plano do cliente) e RE-03, etapa 5 (dados mestres do cliente). Plano de conta de venda: Negócios'),
    ('3.5.5', 'Manage sales partners and alliances', 'RE-06, etapas 3 e 4'),
    ('6.2.3 e 6.5', 'Manage customer complaints; Evaluate customer service operations and customer satisfaction', 'Fora: Operações. Relações recebe as reclamações e incidentes com a causa (RE-04, RE-08) e mede a saúde do cliente (RE-05)'),
    ('12.2', 'Manage government and industry relationships', 'RE-06, para relações institucionais e com entidades. Lobby (12.2.4) não está desenhado'),
    ('12.5', 'Manage public relations program', 'RE-07 (imprensa e comunicados) e RE-06 (comunidade)'),
]

# --------------------------------------------------- o que Relações não faz
FRONTEIRAS = [
    ('Vender: proposta, negociação, contrato e renovação comercial; tabela de preços e política comercial', 'Negócios',
     'A oportunidade qualificada (RE-03), a oportunidade de renovação ou de expansão com o histórico (RE-05) e o plano de demanda (RE-01).'),
    ('Atender o cliente, tratar reclamações e entregar', 'Operações',
     'A estratégia de experiência do cliente (RE-04), o plano de sucesso e o plano de recuperação de cada cliente (RE-05) e as lacunas de percepção (RE-08).'),
    ('Definir a marca, os padrões, o posicionamento institucional e a regra de uso da marca por terceiros', 'Identidade',
     'A escuta e a percepção dos públicos (RE-08). Confere com os padrões o material, o conteúdo, a experiência e o relatório ao cliente e consulta a Identidade no caso não coberto.'),
    ('Decidir a posição na crise e o porta-voz', 'Governança, com o executivo da empresa',
     'O alerta de crise com os fatos apurados, a comunicação da posição decidida e as lições da crise (RE-08).'),
    ('Fazer e guardar contratos, definir as regras de dados pessoais, decidir a resposta ao titular, definir as alçadas e levar aos sócios', 'Governança',
     'Os termos da parceria e a parceria acima da alçada (RE-06), a liberação do uso da marca fora da regra (RE-06, etapa 5) e a execução, na base de relacionamento, da resposta ao titular decidida pela Governança (RE-03, etapa 5).'),
    ('Responder à consulta sobre o uso da marca fora da regra', 'Identidade',
     'O pedido de uso fora da regra, conferido pelo agente (RE-06, etapa 5). Relações decide a exceção ouvida a resposta, como o círculo 1 prevê.'),
    ('Ler o mercado, tornar o dado confiável e medir os indicadores', 'Inteligência',
     'A percepção dos públicos, os sinais do relacionamento e as lições de clientes (RE-05, RE-06 e RE-08).'),
    ('Desenhar a oferta, o modelo de negócio e o preço-base', 'Inteligência',
     'Indica clientes para conversar e para o piloto e confere o desenho da entrega com a estratégia de experiência (IN-07).'),
    ('Decidir a parceria que muda o portfólio', 'Estratégia',
     'A parceria que muda o portfólio, levada como aposta ao portão de entrada com a avaliação (RE-06, etapa 2); a aprovada volta à RE-06 para ser formalizada. A parceria acima da alçada sobe aos sócios pela Governança.'),
    ('Vender com o parceiro de venda', 'Negócios',
     'O parceiro formado, ativado e capacitado nas ofertas e no uso da marca (RE-06, etapas 2 e 3).'),
    ('Montar sistemas, agentes e canais e implantar o cliente; coordenar o plano de saída', 'Integração',
     'O que os padrões de experiência pedem (RE-04), a configuração das ações nos canais (RE-02) e a transição dos clientes quando uma oferta ou empresa sai (RE-05).'),
    ('Comunicar para dentro', 'Gestão',
     'O conteúdo externo publicado (RE-07, etapa 4), para a Gestão reproduzir para as pessoas quando precisar.'),
    ('Montar o orçamento', 'Gestão',
     'O custo das ações do plano de demanda e o pedido de recurso adicional (RE-01).'),
]

# -------------------------------------------------------- pontos para decidir
PONTOS = []
DECISOES = [
    ('Relações decide o que é do seu ofício; o executivo e Negócios opinam',
     'Ponto 1, aprovado por você (19:05)',
     'Relações decide o plano de demanda, a qualificação de cada oportunidade, a estratégia de experiência do cliente, a pauta e o conteúdo externo e as parcerias dentro da alçada. O executivo aprova o que se diz em nome da empresa e quem fala por ela.'),
    ('O critério de oportunidade qualificada é combinado com Negócios; sem acordo, decide o executivo',
     'Ponto 2, aprovado por você (19:05)',
     'Relações e Negócios combinam o critério a cada ciclo de demanda (RE-01, etapa 2). Negócios aceita ou devolve cada oportunidade com o motivo (RE-03). É a única exceção do círculo à regra de que o executivo opina e não decide.'),
    ('Relações acompanha o sucesso do cliente; Negócios renova e amplia; Operações atende e entrega',
     'Ponto 3, aprovado por você (19:05)',
     'O plano de sucesso (RE-05) é a referência comum dos três círculos que falam com o cliente.'),
    ('O executivo aprova o que fala em nome da empresa; a Governança confere o risco jurídico',
     'Ponto 4, aprovado por você (19:05)',
     'Relações decide a pauta e aprova o conteúdo dentro dos padrões (RE-07). Na crise, a posição é do comitê da Governança, com o executivo (RE-08).'),
    ('O uso da marca por terceiros fica na RE-06, etapa 5',
     'Ponto 5, aprovado por você (19:05)',
     'A regra é da Identidade. Relações decide o uso coberto pela regra e, fora dela, a exceção ouvida a Identidade; a Governança libera antes da autorização.'),
    ('Relações forma e acompanha o parceiro de venda; Negócios vende com ele',
     'Ponto 6, aprovado por você (19:05)',
     'A relação institucional sem contrato segue a mesma jornada e a mesma alçada; a Governança confere o termo e o executivo o aprova (RE-06).'),
    ('Oito jornadas',
     'Ponto 7, decidido por mim, como você pediu (19:05)',
     'Mantive a proposta. Planejar e executar a demanda têm cadência diferente (ciclo e ação), e desenhar a experiência de todos os clientes é trabalho distinto de cuidar de cada cliente. Juntar daria seis jornadas maiores, com gatilhos misturados.'),
    ('As três propostas aos círculos 2 e 3 foram aceitas e aplicadas',
     'Decisão sua (19:05)',
     'IN-07, etapa 4, recebe a estratégia de experiência do cliente (RE-04). IN-03, etapa 2, recebe a situação do funil e a base de relacionamento (RE-03) e o resultado das ações de demanda (RE-02). ES-04 avisa Relações da aposta mantida, em espera, devolvida ou encerrada (etapa 3): a RE-05 desfaz a transição preparada e a RE-06 responde ao parceiro. A parceria aprovada no portão volta a Relações (etapa 5) e a RE-06 a formaliza.'),
    ('Auditoria de execução: modo de cada etapa e nível de automação pelo que as tarefas fazem',
     'Itens 1 a 14 da auditoria, aprovados por você (12:33 de 03/10/2026)',
     'RE-03 etapa 1: na dúvida sobre a base legal, a pessoa de Relações decide (item 8). De Assistido para Copiloto, pelas tarefas: RE-06 etapa 2. De Autopiloto para Autômato, pelas tarefas: RE-02 etapa 2, RE-03 etapa 4. De Copiloto para Assistido, pelas tarefas: RE-01 etapa 2, RE-03 etapa 3, RE-06 etapa 4. Nível de automação pela faixa: RE-02 alta na execução, média na preparação → média (alta na execução, média na preparação); RE-08 alta na coleta, baixa na crise → média (alta na coleta, baixa na crise).'),
    ('Alçada de parceria',
     'Aprovado por você (13:51 de 03/10/2026)',
     'Relações decide parceria sem exclusividade, com remuneração na regra dos sócios, marca pelo pacote, prazo até o fim do ciclo estratégico e sem obrigação além do orçamento do círculo; fora disso, os sócios.'),
    ('Cadências e conteúdos validados; gates de implantação',
     'Validado por você (14:07 de 03/10/2026)',
     'Cadências de RE-01 a RE-08; critério de oportunidade qualificada (quatro condições), regra de saúde do cliente (três sinais) e critério de crise (quatro gatilhos). O que depende de dado real ficou nos gates G1 a G9.'),
]

# ------------------- propostas de mudança em círculos já fechados (as três foram aplicadas no fechamento)
PROPOSTAS = []

ALERTAS = [
    ('Negócios (círculo 5)', 'Relações espera de Negócios: o aceite ou a devolução de cada oportunidade com o motivo e no prazo combinado, a tabela de preços para as ações, o contrato de cliente assinado com o escopo vendido e o vencimento e o resultado de cada renovação. Entrega o critério combinado, a oportunidade qualificada e a oportunidade de renovação ou de expansão.'),
    ('Integração (círculo 6)', 'Relações espera o plano de implantação de cada cliente, o plano de lançamento de cada oferta, o plano de saída de clientes e contratos e os sistemas e canais que as ações e os padrões de experiência pedem.'),
    ('Operações (círculo 7)', 'Relações espera as reclamações e os incidentes de clientes com a causa e os registros de entrega e atendimento de cada cliente. Entrega a estratégia de experiência e os planos de sucesso e de recuperação.'),
    ('Gestão (círculo 8)', 'Relações espera o orçamento de demanda do ciclo e a situação de faturas e pagamentos de cada cliente.'),
    ('Governança (círculo 9)', 'Relações espera as regras de dados pessoais, os pedidos dos titulares com a resposta decidida, as alçadas, a decisão dos sócios sobre a parceria acima da alçada, o comitê de crise da Governança (o dono da crise, executivo, Administrador do IMTS.OS ou sócios, declara, decide a posição e encerra a crise; GO-08) e os contratos de parceria. Entrega os pedidos cumpridos, as autorizações de uso da marca com prazo, o alerta de crise e as lições da crise.'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'V2 · Do mercado à oportunidade', 'RE-01, RE-02 e RE-03',
     'Dividida em planejar a demanda, executar as ações e qualificar os contatos. A oportunidade qualificada passa a Negócios, que pode devolvê-la com o motivo.'),
    ('Ajustado', 'V7 · Do resultado à renovação', 'RE-05',
     'Vira acompanhamento do sucesso de cada cliente. A renovação e a expansão comerciais ficam com Negócios; a lição da perda vai à Inteligência.'),
    ('Ajustado', 'C4 · Do contato à parceria ativa', 'RE-06',
     'Mantida em Relações, com o contrato na Governança, a parceria acima da alçada com os sócios e a que muda o portfólio como aposta no portão de entrada da Estratégia.'),
    ('Ajustado', 'I-RE1 · Da pauta ao conteúdo publicado', 'RE-07',
     'Passa a ser a comunicação externa inteira: pauta, conteúdo, aprovação, porta-vozes, imprensa e medição do efeito.'),
    ('Ajustado', 'I-RE2 · Do contato ao relacionamento registrado', 'RE-03',
     'O registro com a base legal, a higiene da base e os pedidos dos titulares entram na jornada de contatos.'),
    ('Acrescentado', 'Transferida do círculo 1: antiga ID-09, comunicação externa', 'RE-07',
     'A comunicação interna ficou na Gestão; a externa, em Relações, como você decidiu às 12:29.'),
    ('Acrescentado', 'Transferida do círculo 1: antiga ID-10, reputação e crise', 'RE-08',
     'Relações monitora e comunica; o comitê da Governança, com o executivo, decide a posição, como você aprovou às 12:59.'),
    ('Acrescentado', 'Transferida do círculo 1: antiga ID-04, uso da marca por terceiros', 'RE-06, etapa 5',
     'O material de marca é produzido por quem usa (RE-02); o uso por terceiros é decidido por Relações, com a Governança, como você aprovou às 12:59.'),
    ('Acrescentado', 'Decisão de 01/10/2026, às 15:48: a estratégia de experiência do cliente é de Relações', 'RE-04',
     'Jornada nova, com Operações, Negócios e Integração conferindo se conseguem cumprir os padrões.'),
    ('Acrescentado', 'Sem equivalente', 'Raias e partes “Cliente”, “Parceiro” e “Públicos externos”',
     'Papéis novos no vocabulário do modelo, para as tarefas feitas por clientes e parceiros e para o que é publicado fora. Os círculos fechados não mudam.'),
    ('Acrescentado', 'Propostas aos círculos 2 e 3, aceitas às 19:05', 'RE-02, RE-03, RE-04, RE-05 e RE-06',
     'O outro lado das trocas aplicadas na IN-03, na IN-07 e na ES-04: o funil, a base de relacionamento e o resultado das ações vão à Inteligência; a estratégia de experiência também; a RE-05 desfaz a transição quando a oferta não é encerrada; a RE-06 formaliza a parceria aprovada no portão ou responde ao parceiro quando ela não é aprovada.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'As cadências foram validadas em 03/10/2026 (aba Parâmetros em aberto); o líder do círculo ajusta na implantação e a calibração com dados é o gate G9.',
    'Os rascunhos de critério de oportunidade qualificada, regra de saúde do cliente e critério de crise foram validados em 03/10/2026 (aba Gates de implantação); o texto final é o gate G8, e os números que dependem de dado real ficam nos gates G3 e G9.',
    'O referencial de processos é o APQC PCF 7.4, de agosto de 2024. Da ISO 44001 e da ISO 22361 lemos só o resumo; o texto dos Barcelona Principles 3.0 foi lido numa transcrição da MEPRA, porque a página da AMEC só os oferece em anexos.',
    'Onde faltava o outro lado, as três propostas aos círculos 2 e 3 foram aceitas e aplicadas às 19:05. Com os nove círculos fechados (03/10/2026), as trocas com os outros oito foram conferidas dos dois lados pelo nome: 410 trocas, sem problema.',
    'A tarefa de quem não é do círculo (cliente, parceiro, executivo, outro círculo) está desenhada como participação; o detalhe dela fica no círculo dono.',
    'As aprovações e conferências sem decisão desenhada não têm ramo de recusa: a recusa devolve o trabalho a quem preparou.',
    'Programa de fidelidade e lobby não estão desenhados: nenhum círculo pediu.',
    'As autorizações de uso da marca têm prazo registrado, mas o vencimento não tem vigia desenhada: só a marca retirada de uso revoga as autorizações.',
    'Quando Relações indica clientes para conversar e para o piloto (IN-07), usa a base de relacionamento da RE-03; o detalhe dessa tarefa fica no círculo 3.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = [
    'Um revisor independente (agente que não participou do desenho) leu a primeira versão das oito jornadas e apontou 30 achados, 6 graves. Todos foram tratados na segunda versão.',
    'Um verificador independente reabriu as 8 fontes do círculo: 5 confirmadas e 3 confirmadas em parte. As correções de texto foram aplicadas.',
    'Um segundo revisor leu a segunda versão: 17 achados resolvidos, 9 em parte, nenhum grave, e 8 defeitos médios novos. Os 8 foram tratados: 7 no fluxo e 1 como proposta à ES-04, aceita e aplicada no fechamento.',
    'Um terceiro revisor conferiu esses 8 e deu 6 por resolvidos e 2 em parte. Apontou 5 defeitos novos, 1 grave: a exceção ao uso da marca estava com a Identidade, contra o círculo 1, que a dá a Relações com a Governança. Os 5 foram corrigidos e passaram por todos os testes automáticos, mas não por nova revisão independente.',
    'No fechamento, às 19:05, um quarto revisor conferiu as três trocas aplicadas nos círculos 2 e 3 e os textos de fechamento. Apontou 6 defeitos, nenhum grave: a parceria não aprovada no portão e a oferta posta em espera não voltavam a Relações, e a base de relacionamento tinha ficado fora da IN-03. Os 6 foram corrigidos e passaram por todos os testes automáticos.',
]
