
# ====================================================== DIREÇÃO E RECURSOS
JORNADAS.append(dict(
    code='ES-01',
    nome='Formular e revisar a estratégia do Ecossistema e de cada empresa',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Ter uma estratégia escrita e aprovada, do Ecossistema e de cada empresa, que diga onde atuar, o que não fazer e para quem, com as hipóteses de cada escolha, e que sirva de critério para alocar recursos e fixar alvos. Inclui as escolhas de cada círculo e o método de estratégia, que os sócios aprovam junto com a estratégia. A Estratégia formula; o executivo e o líder do círculo propõem e participam.',
    frequencia='A cada ciclo estratégico (cadência a definir) e por evento: mudança relevante de cenário, empresa nova no portfólio ou revisão decidida na ES-06',
    automacao=('baixa', 'Decisão humana, de risco alto e pouco frequente. O agente reúne evidências, monta opções e confere a coerência; a escolha é de pessoas da Estratégia e a aprovação é dos sócios.'),
    base=['apqc', 'rumelt', 'kaplan', 'parenting', 'horizons', 'iia'],
    lanes=['INT', 'SOC', 'GOV', 'EXE', 'LCI', 'IDE', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Mudança relevante de cenário apontada', 'INT', 'message'),
             I('Ciclo estratégico iniciado', 'ESR', 'timer'),
             I('Revisão da estratégia decidida', 'ESR', 'message'),
             I('Empresa nova incluída no portfólio', 'ESR', 'message')],
    fins=[F('Estratégia aprovada e publicada', 'ESR'), F('Revisão encerrada sem mudança', 'ESR')],
    etapas=[
        E('Diagnosticar o cenário e a posição atual', 'Estratégia, com sócios, executivos e líderes dos círculos', 'Copiloto', 'médio',
          [(LEITURA, 'Inteligência'), ('Aviso de mudança relevante de cenário', 'Inteligência'),
           ('Aviso de leitura sem novidade', 'Inteligência'),
           (RESULT, 'Gestão'), (RISCOS, 'Governança'), (DECL, 'Identidade'), (RELAT, 'Identidade'),
           (ALOC, 'ES-02'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'), ('Decisão de rever a estratégia', 'ES-06')],
          [T('Abrir o ciclo com o calendário e o método vigentes', 'ESR'),
           T('Definir os participantes e as perguntas do diagnóstico', 'ESP'),
           T('Enviar as perguntas do diagnóstico à Inteligência', 'ESR'),
           T('Receber a leitura da Inteligência ou o aviso de leitura sem novidade', 'ESR', 'receive'),
           T('Reunir os dados internos e juntá-los à leitura da Inteligência', 'ESA'),
           T('Ouvir sócios, executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir o diagnóstico: o desafio central e as suas causas', 'ESP'),
           D('O diagnóstico pede mudar a estratégia?', 'ESP',
             [S('Sim', 'prox'),
              S('Só falta a estratégia de uma empresa nova', 'E3'),
              S('Não', 'F2', via=[T('Registrar o diagnóstico e a decisão de manter a estratégia', 'ESR'),
                                  T('Avisar os sócios, a Governança e quem apontou a mudança de que a estratégia se mantém', 'ESR')])])],
          [('Diagnóstico estratégico', ['etapa 2', 'etapa 3']),
           ('Perguntas do diagnóstico', ['Inteligência']),
           (MANTIDA, ['Sócios', 'Governança', 'Inteligência', 'ES-06'])]),
        E('Formular as escolhas do Ecossistema: onde atuar e o que não fazer', 'Estratégia, com os executivos', 'Copiloto', 'alto',
          [('Diagnóstico estratégico', 'etapa 1'), ('Decisão dos sócios sobre a estratégia', 'etapa 4'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Montar opções estratégicas e simular as consequências de cada uma', 'ESA'),
           T('Discutir as opções com os executivos', 'ESP', 'manual'),
           T('Escolher onde atuar, o que não fazer e a política que orienta as ações', 'ESP'),
           T('Definir o portfólio-alvo: o papel de cada empresa, oferta e aposta', 'ESP'),
           T('Escrever as hipóteses de cada escolha e os sinais que as confirmam ou refutam', 'ESP'),
           T('Definir os critérios dos portões, as regras de realocação e o critério de desvio grave', 'ESP'),
           T('Conferir as escolhas com a declaração e os critérios de decisão da identidade', 'ESA'),
           D('As escolhas são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E2'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira das escolhas estratégicas', 'IDE', 'call')])]),
           D('A Identidade considera as escolhas coerentes?', 'IDE', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Escolhas estratégicas, portfólio-alvo, hipóteses e método do Ecossistema', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Formular a estratégia de cada empresa e as escolhas de cada círculo', 'Estratégia, com executivos e líderes dos círculos', 'Copiloto', 'médio',
          [('Escolhas estratégicas, portfólio-alvo, hipóteses e método do Ecossistema', 'etapa 2'), ('Diagnóstico estratégico', 'etapa 1'),
           ('Decisão dos sócios sobre a estratégia', 'etapa 4'), (ESTRAT, 'etapa 5'), (PORTALVO, 'etapa 5'),
           (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Montar o rascunho da estratégia de cada empresa a partir das escolhas do Ecossistema', 'ESA'),
           PAR([T('Propor as escolhas da empresa: público, oferta e vantagem', 'EXE')],
               [T('Propor as escolhas do círculo: o que é serviço comum, o que construir e o que comprar', 'LCI')]),
           T('Formular a estratégia de cada empresa e de cada círculo, ouvidos o executivo e o líder', 'ESP'),
           D('O ciclo é de empresa nova no portfólio?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Definir o papel da empresa nova no portfólio-alvo', 'ESP')])]),
           T('Conferir a coerência entre empresas, círculos e as escolhas do Ecossistema', 'ESA'),
           D('Há conflito entre empresas, círculos ou com o Ecossistema?', 'ESP',
             [S('Não', 'seg'),
              S('Sim, e há acordo', 'seg', via=[T('Resolver o conflito com os executivos e líderes envolvidos', 'ESP', 'manual')]),
              S('Sim, e não há acordo', 'seg', via=[T('Registrar a divergência e as alternativas para decisão dos sócios', 'ESP')])]),
           T('Conferir as escolhas das empresas e dos círculos com os critérios da identidade', 'ESA'),
           D('As escolhas das empresas e dos círculos são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E3'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira das escolhas da empresa ou do círculo', 'IDE', 'call')])]),
           D('A Identidade considera coerentes as escolhas das empresas e dos círculos?', 'IDE', [S('Sim', 'prox'), S('Não', 'E3')])],
          [('Proposta de estratégia, com as hipóteses, o método e as divergências', ['etapa 4', 'etapa 5']),
           (CONSULTA, ['Identidade'])]),
        E('Aprovar a estratégia, as hipóteses e o método com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estratégia, com as hipóteses, o método e as divergências', 'etapa 3')],
          [T('Levar a proposta de estratégia, com as hipóteses e o método, à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a estratégia, as hipóteses, o método e as divergências', 'SOC', 'manual'),
           D('Estratégia aprovada?', 'SOC',
             [S('Sim', 'prox'),
              S('Não, rever as escolhas do Ecossistema', 'E2'),
              S('Não, rever a estratégia de empresa ou de círculo', 'E3'),
              S('Não, manter a atual (não vale para empresa nova)', 'F2', via=[T('Registrar a decisão dos sócios de manter a estratégia atual', 'ESR')])])],
          [('Decisão dos sócios sobre a estratégia', ['etapa 5', 'etapa 2', 'etapa 3', 'Governança'])]),
        E('Fechar o texto com a decisão dos sócios, publicar a estratégia e avisar quem depende dela', 'Estratégia', 'Copiloto', 'médio',
          [('Decisão dos sócios sobre a estratégia', 'etapa 4'),
           ('Proposta de estratégia, com as hipóteses, o método e as divergências', 'etapa 3')],
          [T('Incorporar ao texto a decisão dos sócios, inclusive sobre as divergências', 'ESA'),
           T('Resumir a direção e os públicos prioritários para cada círculo', 'ESA'),
           T('Aprovar o texto final, o resumo por círculo e o que pode ser dito para fora', 'ESP'),
           T('Registrar a versão e a data de vigência da estratégia', 'ESR'),
           T('Publicar a estratégia, o portfólio-alvo, as hipóteses e o método', 'ESR'),
           T('Avisar círculos e executivos e abrir as jornadas que dependem da estratégia', 'ESR')],
          [(ESTRAT, ['etapa 3', 'ES-02', 'ES-03', 'ES-04', 'ES-05', 'ES-06', 'Sócios', 'Executivos', 'Líderes dos círculos']),
           (DIRECAO, [TODOS, 'Identidade']),
           (PORTALVO, ['etapa 3', 'ES-02', 'ES-04', 'Executivos', 'Negócios', 'Inteligência']),
           (HIPOT, ['ES-06', 'Inteligência']),
           (METODO, ['ES-02', 'ES-03', 'ES-04', 'ES-06', 'Executivos', 'Líderes dos círculos', 'Inteligência', 'Gestão',
                     'Integração', 'Governança']),
           ('Mudança na estratégia a comunicar', ['Gestão', 'Relações'])]),
    ]))
