
JORNADAS.append(dict(
    code='ES-02',
    nome='Rever o portfólio e realocar recursos entre empresas, ofertas e apostas',
    dominio='Direção e recursos', classe='essencial', onda=2,
    objetivo='Decidir, a cada período, para onde vão dinheiro, pessoas e atenção: o que recebe mais, o que mantém, o que perde recursos e o que deve ter a saída estudada, e o destino do resultado de cada empresa. A proposta sobe sempre aos sócios, mesmo quando é manter a alocação.',
    frequencia='A cada fechamento de período (cadência a definir) e por evento: estratégia nova ou revisão decidida na ES-06',
    automacao=('média', 'O agente compara o uso de recursos com o portfólio-alvo e simula realocações; a proposta é de pessoas da Estratégia e a decisão é dos sócios.'),
    base=['realloc', 'horizons', 'parenting', 'iia', 'apqc'],
    lanes=['GES', 'ASS', 'IDE', 'GOV', 'SOC', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Resultado do período fechado', 'GES', 'message'),
             I('Nova estratégia publicada', 'ESR', 'message'),
             I('Revisão do portfólio decidida', 'ESR', 'message')],
    fins=[F('Alocação decidida ou mantida e comunicada', 'ESR')],
    etapas=[
        E('Ler o resultado e o uso de recursos de cada unidade do portfólio', 'Estratégia, com os executivos', 'Copiloto', 'baixo',
          [(RESULT, 'Gestão'), (EXEC_ORC, 'Gestão'), (INDIC, 'Inteligência'),
           (ESTRAT, 'ES-01'), (PORTALVO, 'ES-01'), (ALVOS, 'ES-03'), (CARTEIRA, 'ES-04'), (PORTF, 'ES-05'),
           (ARQUIVADO, 'ES-05'), (CAUSAS, 'ES-06'), ('Decisão de rever o portfólio', 'ES-06')],
          [T('Comparar resultado e recursos usados com o papel de cada unidade no portfólio-alvo', 'ESA'),
           T('Interpretar a leitura com cada executivo', 'ESP', 'manual')],
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', ['etapa 2', 'Inteligência'])]),
        E('Propor a alocação e o destino do resultado', 'Estratégia, com assessoria', 'Copiloto', 'médio',
          [('Leitura do portfólio: resultado, recursos e papel de cada unidade', 'etapa 1'),
           ('Decisão de alocação e de destino do resultado', 'etapa 3'),
           (CAIXA, 'Gestão'), (METODO, 'ES-01'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Classificar cada unidade: semear, nutrir, podar ou colher', 'ESA'),
           T('Simular realocações de dinheiro, pessoas e capacidade dos círculos', 'ESA'),
           T('Avaliar os efeitos societários, fiscais e contábeis das alternativas', 'ASS'),
           T('Montar a proposta de alocação e de destino do resultado, mesmo quando é manter a atual', 'ESP'),
           D('A proposta muda o papel de alguma empresa, oferta ou aposta?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Combinar a mudança de papel com o executivo afetado', 'ESP', 'manual')])]),
           T('Conferir a proposta com os critérios de decisão da identidade', 'ESA'),
           D('A proposta de alocação é coerente com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E2'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da proposta de alocação', 'IDE', 'call')])]),
           D('A Identidade considera a proposta de alocação coerente?', 'IDE', [S('Sim', 'prox'), S('Não', 'E2')])],
          [('Proposta de alocação e de destino do resultado', ['etapa 3']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir a alocação com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de alocação e de destino do resultado', 'etapa 2')],
          [T('Levar a proposta de alocação à decisão dos sócios', 'GOV', 'call'),
           T('Decidir a alocação e o destino do resultado', 'SOC', 'manual'),
           D('Alocação aprovada?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter a atual', 'prox', via=[T('Registrar a decisão dos sócios de manter a alocação atual e o destino do resultado', 'ESR')])])],
          [('Decisão de alocação e de destino do resultado', ['etapa 4', 'etapa 2', 'Governança', 'Gestão'])]),
        E('Comunicar a decisão e encaminhar a execução', 'Estratégia', 'Autopiloto', 'baixo',
          [('Decisão de alocação e de destino do resultado', 'etapa 3')],
          [T('Registrar a decisão e o limite de recursos de cada unidade', 'ESR'),
           T('Atualizar o portfólio-alvo com os papéis decididos', 'ESR'),
           T('Avisar a Gestão, os executivos e os círculos que usam o portfólio-alvo', 'ESR'),
           D('A alocação muda alvos ou orçamento, ou há desdobramento dos alvos à espera dela?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar a alocação decidida ao desdobramento dos alvos', 'ESR')])]),
           D('A decisão manda estudar a saída de empresa, oferta ou aposta?', 'ESR',
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Comunicar o estudo de saída ao executivo afetado', 'ESP', 'manual'),
                                    T('Abrir o estudo de saída: empresa na ES-05, oferta ou aposta na ES-04', 'ESR')])])],
          [(ALOC, ['ES-01', 'ES-03', 'ES-04', 'Gestão', 'Executivos']),
           (PORTALVO, ['ES-04', 'Executivos', 'Negócios', 'Inteligência']),
           (SAIDA, ['ES-04', 'ES-05'])]),
    ]))
