
JORNADAS.append(dict(
    code='ES-03',
    nome='Desdobrar a estratégia em alvos e iniciativas de cada empresa e de cada círculo',
    dominio='Direção e recursos', classe='essencial', onda=1,
    objetivo='Transformar a estratégia em poucos alvos mensuráveis do Ecossistema, de cada empresa e de cada círculo, com iniciativas, dono e indicador, combinados de cima para baixo e de baixo para cima; pedir à Inteligência a ficha do indicador de cada alvo antes da aprovação; e conferir com a Gestão e a Integração se os alvos cabem nos recursos.',
    frequencia='A cada ciclo de alvos (cadência a definir) e por evento: estratégia nova, portfólio de empresas atualizado, alocação que muda alvos ou orçamento, ou correção decidida na ES-06',
    automacao=('média', 'O agente desdobra, confere a soma e aponta conflitos; a negociação dos alvos é entre pessoas e a aprovação é dos sócios.'),
    base=['kaplan', 'okr', 'lei', 'rumelt', 'iia', 'apqc'],
    lanes=['SOC', 'GOV', 'EXE', 'LCI', 'IDE', 'GES', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ciclo de alvos iniciado', 'ESR', 'timer'),
             I('Nova estratégia publicada', 'ESR', 'message'),
             I('Portfólio de empresas atualizado', 'ESR', 'message'),
             I('Alocação que muda alvos ou orçamento decidida', 'ESR', 'message'),
             I('Novo desdobramento dos alvos decidido', 'ESR', 'message')],
    fins=[F('Alvos aprovados e publicados', 'ESR'), F('Alvos anteriores mantidos', 'ESR')],
    etapas=[
        E('Propor os alvos do Ecossistema', 'Estratégia', 'Copiloto', 'médio',
          [(ESTRAT, 'ES-01'), (METODO, 'ES-01'), (ALOC, 'ES-02'), (PORTF, 'ES-05'),
           ('Decisão de corrigir os alvos', 'ES-06'), (INDIC, 'Inteligência'),
           ('Definição do que conta como impacto', 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [D('O desdobramento espera uma alocação que ainda não chegou?', 'ESR',
             [S('Não', 'seg'),
              S('Sim: estratégia nova ou empresa nova, sem alocação decidida ou mantida', 'seg',
                via=[T('Receber a alocação decidida ou mantida depois da nova estratégia', 'ESR', 'receive')])]),
           T('Traduzir as escolhas em poucos objetivos com resultados mensuráveis', 'ESA'),
           T('Escolher os alvos do Ecossistema e o que fica de fora', 'ESP'),
           T('Conferir os alvos com os critérios da identidade e a definição do que conta como impacto', 'ESA'),
           D('Os alvos propostos são coerentes com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não', 'E1'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira dos alvos propostos', 'IDE', 'call')])]),
           D('A Identidade considera os alvos propostos coerentes?', 'IDE', [S('Sim', 'prox'), S('Não', 'E1')])],
          [('Alvos propostos do Ecossistema', ['etapa 2']),
           (CONSULTA, ['Identidade'])]),
        E('Combinar os alvos e as iniciativas com cada empresa e cada círculo', 'Estratégia, com executivos, líderes dos círculos e Inteligência', 'Copiloto', 'médio',
          [('Alvos propostos do Ecossistema', 'etapa 1'), ('O que não cabe nos recursos, a renegociar', 'etapa 3'),
           ('Decisão dos sócios sobre alvos e orçamento', 'etapa 4'), (FICHAS_IND, 'Inteligência')],
          [PAR([T('Propor os alvos e as iniciativas da empresa', 'EXE')],
               [T('Propor os alvos e as iniciativas do círculo', 'LCI')]),
           T('Conferir a soma, os conflitos e as dependências entre os alvos', 'ESA'),
           T('Negociar os ajustes com executivos e líderes dos círculos', 'ESP', 'manual'),
           D('Há alvo novo ou alterado sem ficha de indicador?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar à Inteligência os alvos novos ou alterados, para a ficha do indicador de cada um', 'ESR'),
                                   T('Receber o conjunto das fichas dos indicadores dos alvos propostos', 'ESR', 'receive')])]),
           D('Cada alvo proposto tem indicador com dado confiável?', 'ESP',
             [S('Sim', 'seg'),
              S('Não, trocar o alvo', 'E2'),
              S('Não, manter com ficha provisória ou adiar', 'seg',
                via=[T('Marcar na proposta o alvo com ficha provisória ou adiado', 'ESP')])]),
           D('Os alvos somam e não conflitam?', 'ESP',
             [S('Sim', 'prox'), S('Não, renegociar', 'E2'),
              S('Não, sem acordo', 'prox', via=[T('Registrar a divergência sobre os alvos para decisão dos sócios', 'ESP')])])],
          [('Alvos e iniciativas combinados', ['etapa 3']),
           (ALVOS_PROP, ['Inteligência'])]),
        E('Conferir com a Gestão e a Integração se os alvos cabem nos recursos', 'Estratégia, com Gestão e Integração', 'Copiloto', 'médio',
          [('Alvos e iniciativas combinados', 'etapa 2'), (CAIXA, 'Gestão')],
          [T('Montar o orçamento do ciclo a partir dos alvos e da alocação', 'GES', 'call'),
           T('Conferir a capacidade de executar as iniciativas na carteira de projetos', 'ITG'),
           T('Apontar o que não cabe no orçamento ou na capacidade', 'ESA'),
           D('Alvos e iniciativas cabem nos recursos?', 'ESP',
             [S('Sim', 'prox'), S('Não, renegociar', 'E2'),
              S('Não, e não há acordo', 'prox', via=[T('Montar as alternativas de alvos e de recursos para decisão dos sócios', 'ESP')])])],
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão e as alternativas', ['etapa 4']),
           ('O que não cabe nos recursos, a renegociar', ['etapa 2'])]),
        E('Aprovar os alvos e o orçamento com os sócios', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de alvos e iniciativas, com o orçamento da Gestão e as alternativas', 'etapa 3')],
          [T('Levar a proposta de alvos e orçamento à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre os alvos, o orçamento e as divergências', 'SOC', 'manual'),
           D('Alvos e orçamento aprovados?', 'SOC',
             [S('Sim', 'prox'), S('Não, rever', 'E2'),
              S('Não, manter os atuais', 'F2', via=[T('Registrar a decisão dos sócios de manter os alvos atuais', 'ESR')])])],
          [('Decisão dos sócios sobre alvos e orçamento', ['etapa 5', 'etapa 2', 'Governança', 'Gestão'])]),
        E('Publicar os alvos e entregar ao ritual de acompanhamento', 'Estratégia, com Gestão', 'Autopiloto', 'baixo',
          [('Decisão dos sócios sobre alvos e orçamento', 'etapa 4')],
          [T('Registrar alvos, iniciativas, donos e indicadores no painel único', 'ESR'),
           T('Avisar executivos, líderes dos círculos e donos das iniciativas', 'ESR'),
           T('Incluir os alvos no ritual de acompanhamento', 'GES')],
          [(ALVOS, [TODOS, 'ES-02', 'ES-06', 'Gestão', 'Integração', 'Inteligência'])]),
    ]))
