
# ====================================================== APOSTAS E EMPRESAS
JORNADAS.append(dict(
    code='ES-04',
    nome='Decidir em cada portão se uma aposta avança, espera, volta para ajuste ou é encerrada',
    dominio='Apostas e empresas', classe='essencial', onda=2,
    objetivo='Fazer cada ideia, oferta ou negócio novo passar por decisões explícitas antes de receber recursos: entrar na carteira e, depois de produtizada pela Inteligência, ser lançada. Em qualquer portão ou revisão, a aposta pode avançar, seguir como está, esperar, voltar para ajuste ou ser encerrada. A Estratégia decide com o executivo, dentro da alçada; acima dela, decidem os sócios. Encerrar aposta em desenvolvimento ou oferta em uso só termina com o plano de saída conferido, a data de saída decidida por pessoa e a saída conferida.',
    frequencia='Por evento: ideia nova, aposta definida no portfólio-alvo, oferta pronta para lançar, aposta devolvida pela Inteligência, revisão pedida (a de oferta em uso chega pela Inteligência ou pela ES-06), estudo de saída pedido na ES-02, caso de empresa nascido de aposta e arquivado na ES-05, ou data de revisão ou de retomada da aposta',
    automacao=('alta na entrada e na preparação, baixa na decisão', 'Registrar, completar o dossiê, estimar e encaminhar rodam com agente e automação; a decisão do portão e a data de saída são de pessoas.'),
    base=['stagegate', 'horizons', 'dmn', 'apqc'],
    lanes=['SOL', 'INT', 'IDE', 'GOV', 'SOC', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Ideia ou aposta nova recebida', 'SOL', 'message'),
             I('Revisão de aposta ou pedido sobre oferta em uso recebido', 'SOL', 'message'),
             I('Oferta pronta para lançamento recebida', 'INT', 'message'),
             I('Aposta devolvida pela Inteligência recebida', 'INT', 'message'),
             I('Revisão de oferta em uso enviada pela Inteligência', 'INT', 'message'),
             I('Aposta nova definida no portfólio-alvo', 'ESR', 'message'),
             I('Estudo de saída de oferta ou aposta pedido', 'ESR', 'message'),
             I('Caso de empresa nascido de aposta arquivado', 'ESR', 'message'),
             I('Data de revisão ou de retomada da aposta atingida', 'ESR', 'timer')],
    fins=[F('Aposta aprovada para o estágio seguinte', 'ESR'),
          F('Aposta encerrada com lição registrada', 'ESR'),
          F('Aposta em espera', 'ESR'),
          F('Aposta devolvida para ajuste', 'ESR'),
          F('Aposta mantida depois da revisão', 'ESR'),
          F('Pedido sobre oferta em uso encaminhado à Inteligência', 'ESR'),
          F('Aposta encerrada com pendência de saída apontada', 'ESR')],
    etapas=[
        E('Registrar a aposta e completar o dossiê', 'Estratégia', 'Autopiloto', 'baixo',
          [('Ideia ou aposta nova', 'Solicitante'), (REVISAO_AP, 'Solicitante'), (REVISAO_AP, 'Inteligência'), (REVISAO_AP, 'ES-06'),
           (PEDIDO_OFERTA, 'Solicitante'),
           ('Pacote da oferta pronta para lançamento', 'Inteligência'), (DEVOLVIDA_IN, 'Inteligência'),
           (PORTALVO, 'ES-01'), (PORTALVO, 'ES-02'), (SAIDA, 'ES-02'), (ARQUIVADO, 'ES-05')],
          [T('Registrar a aposta, o que abriu o trabalho e o portão ou a revisão pedida', 'ESR'),
           D('O que abriu o trabalho?', 'ESR',
             [S('Ideia ou aposta nova', 'seg'),
              S('Aposta na carteira, oferta pronta para lançamento ou revisão vinda da Inteligência ou da ES-06', 'E2',
                via=[T('Reunir da carteira o dossiê, a decisão anterior e os recursos já aprovados', 'ESR')]),
              S('Pedido direto sobre oferta em uso, que não passou pela Inteligência', 'F6',
                via=[T('Encaminhar à Inteligência o pedido sobre oferta em uso, para separar ajuste de revisão', 'ESR')])]),
           T('Completar o dossiê: problema, público, hipótese, dono, estágio e recursos pedidos', 'ESA'),
           D('O dossiê tem o mínimo para avaliar?', 'ESA',
             [S('Sim', 'prox'),
              S('Não', 'F4', via=[T('Devolver a aposta a quem propôs com o que falta', 'ESR')])])],
          [('Dossiê da aposta', ['etapa 2']),
           ('Aposta devolvida com o que falta', ['Solicitante']),
           (PEDIDO_OFERTA, ['Inteligência'])]),
        E('Avaliar a aposta contra os critérios do portão', 'Estratégia, com Inteligência', 'Copiloto', 'médio',
          [('Dossiê da aposta', 'etapa 1'), (RESPOSTA_IN, 'Inteligência'), ('Pergunta devolvida com o motivo', 'Inteligência'),
           (INDIC, 'Inteligência'), (EXEC_ORC, 'Gestão'),
           (ESTRAT, 'ES-01'), (METODO, 'ES-01'), (ALOC, 'ES-02'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [D('A avaliação pede evidência que o dossiê não traz?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Enviar à Inteligência a pergunta de decisão do portão, com o risco e o prazo', 'ESR'),
                                   T('Receber a resposta com evidência sobre a aposta, ou a pergunta devolvida', 'ESR', 'receive')])]),
           T('Estimar tamanho, esforço, risco e retorno com a evidência, os indicadores e o gasto', 'ESA'),
           T('Conferir o encaixe com a estratégia, o portfólio-alvo e os critérios da identidade', 'ESA'),
           D('A aposta é coerente com a identidade?', 'ESP',
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Registrar na avaliação o ponto em que a aposta contraria a identidade', 'ESA')]),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da aposta', 'IDE', 'call'),
                                                 T('Registrar na avaliação o parecer da Identidade sobre a aposta', 'ESA')])]),
           T('Conferir os recursos pedidos contra o limite da alocação vigente', 'ESR', 'rule'),
           T('Conferir a evidência contra o critério do portão', 'ESP'),
           T('Recomendar a decisão do portão ou da revisão; o que contraria a identidade não avança', 'ESP')],
          [('Avaliação da aposta com recomendação', ['etapa 3']),
           (PERGUNTA, ['Inteligência']),
           (CONSULTA, ['Identidade'])]),
        E('Decidir o destino da aposta no portão ou na revisão', 'Estratégia com o executivo, ou os sócios', 'Assistido', 'alto',
          [('Avaliação da aposta com recomendação', 'etapa 2'), (ALCADAS, 'Governança'),
           ('Plano de saída que mostra que encerrar não é viável', 'etapa 4')],
          [T('Aplicar a tabela de alçadas aos recursos pedidos', 'ESR', 'rule'),
           T('Marcar a aposta com incoerência registrada com a identidade como impedida de avançar', 'ESR', 'rule'),
           T('Apresentar a avaliação e a recomendação a quem decide', 'ESP', 'manual'),
           D('A decisão passa da alçada da Estratégia?', 'ESR',
             [S('Não', 'seg', via=[T('Decidir com o executivo o destino da aposta e se ela vira oferta ou empresa própria', 'ESP', 'manual')]),
              S('Sim', 'seg', via=[T('Levar a aposta à decisão dos sócios', 'GOV', 'call'),
                                   T('Decidir o destino da aposta pelos sócios', 'SOC', 'manual')])]),
           D('Qual é a decisão do portão ou da revisão?', 'ESR',
             [S('Avança, se não há impedimento de identidade: oferta, lançamento ou empresa própria', 'E5'),
              S('Encerra aposta em desenvolvimento ou oferta em uso', 'prox',
                via=[T('Enviar a decisão de encerrar a quem desenha, vende e entrega, para parar novas vendas', 'ESR')]),
              S('Encerra aposta que ainda não entrou em desenvolvimento', 'F2',
                via=[T('Registrar na carteira a lição da aposta encerrada e os recursos a devolver', 'ESA')]),
              S('Segue como está', 'F5',
                via=[T('Registrar a revisão e a data da próxima e avisar a Inteligência e a Gestão', 'ESR')]),
              S('Espera', 'F3',
                via=[T('Registrar a condição e a data de retomada e avisar a Inteligência e a Gestão', 'ESR')]),
              S('Volta para ajuste', 'F4', via=[T('Devolver a aposta com os ajustes pedidos', 'ESR')])])],
          [('Decisão do portão', ['etapa 4', 'etapa 5', 'Governança', 'Integração']),
           (DEC_ENCERRAR, ['Inteligência', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Integração']),
           ('Lição da aposta encerrada', ['Inteligência', 'Solicitante']),
           ('Recursos da aposta encerrada a devolver', ['Gestão']),
           ('Aposta em espera ou devolvida', ['Solicitante', 'Inteligência', 'Gestão']),
           ('Aposta mantida depois da revisão', ['Solicitante', 'Inteligência', 'Gestão', 'Executivos']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
        E('Encerrar aposta em desenvolvimento ou oferta em uso, com o plano de saída', 'Estratégia com o executivo, com a Integração', 'Assistido', 'alto',
          [('Decisão do portão', 'etapa 3'), ('Plano de saída da oferta: clientes e contratos', 'Integração'),
           ('Conclusão do plano de saída da oferta', 'Integração')],
          [T('Pedir à Integração o plano de saída dos clientes e dos contratos da aposta ou da oferta', 'ESR'),
           T('Receber o plano de saída coordenado pela Integração', 'ESR', 'receive'),
           T('Conferir o plano de saída e decidir a data de saída com o executivo', 'ESP', 'manual'),
           D('O plano de saída serve?', 'ESP',
             [S('Sim', 'seg'), S('Não, refazer o plano', 'E4'),
              S('Não: o plano mostra que encerrar não é viável', 'E3')]),
           T('Registrar na carteira a lição, a data de saída e os recursos a devolver', 'ESA'),
           T('Enviar a data de saída a quem desenha, vende, entrega e coordena o plano de saída', 'ESR'),
           D('A oferta encerrada tem marca própria?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir à Identidade a retirada da marca da oferta, com a data de efeito', 'ESR')])]),
           T('Receber da Integração a conclusão do plano de saída', 'ESR', 'receive'),
           T('Conferir a saída contra o plano', 'ESP'),
           D('A saída foi concluída como planejado?', 'ESP',
             [S('Sim', 'F2'),
              S('Não', 'F7', via=[T('Registrar a pendência da saída e apontá-la ao executivo e à Integração', 'ESR')])])],
          [(DATA_SAIDA, ['Inteligência', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Integração', 'Gestão']),
           ('Pedido de plano de saída da oferta: clientes e contratos', ['Integração']),
           ('Pedido de retirada de marca', ['Identidade']),
           ('Lição da aposta encerrada', ['Inteligência', 'Solicitante']),
           ('Recursos da aposta encerrada a devolver', ['Gestão']),
           ('Pendência da saída da oferta encerrada', ['Executivos', 'Integração']),
           ('Plano de saída que mostra que encerrar não é viável', ['etapa 3']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
        E('Registrar a decisão e passar a aposta ao dono do estágio seguinte', 'Estratégia', 'Autômato', 'baixo',
          [('Decisão do portão', 'etapa 3')],
          [T('Registrar na carteira a decisão, os recursos aprovados e a data da próxima revisão', 'ESR'),
           D('Qual é o estágio seguinte decidido no portão?', 'ESR',
             [S('Desenho e validação da oferta', 'seg', via=[T('Passar a aposta à Inteligência para desenhar e validar a oferta', 'ESR')]),
              S('Lançamento', 'seg', via=[T('Avisar a Integração, que coordena o lançamento, e o executivo da empresa', 'ESR')]),
              S('Empresa própria', 'seg', via=[T('Abrir a jornada de criação de empresa', 'ESR')])]),
           T('Avisar a Gestão dos recursos aprovados', 'ESR')],
          [(AP_OFERTA, ['Inteligência']),
           (AP_EMPRESA, ['ES-05']),
           (OFERTA_LANC, ['Integração', 'Executivos', 'Relações', 'Negócios', 'Operações', 'Inteligência']),
           ('Recursos aprovados para a aposta', ['Gestão']),
           (CARTEIRA, ['ES-01', 'ES-02', 'ES-06'])]),
    ]))
