
JORNADAS.append(dict(
    code='ES-05',
    nome='Decidir e estruturar a criação, a aquisição, a venda ou o encerramento de uma empresa',
    dominio='Apostas e empresas', classe='essencial', onda=3,
    objetivo='Decidir com um caso escrito se o Ecossistema cria, adquire, vende ou encerra uma empresa; obter dos sócios a autorização para negociar e, depois, a decisão; firmar o contrato, quando há; emitir o mandato para os círculos que executam; e conferir o cumprimento. A Integração executa o mandato; a Estratégia confere.',
    frequencia='Rara: por evento',
    automacao=('baixa', 'Decisão dos sócios, rara e de risco alto. O agente monta o caso, os cenários e o mandato e confere a execução.'),
    base=['apqc', 'parenting', 'realloc', 'iia'],
    lanes=['SOL', 'SOC', 'ASS', 'GOV', 'GES', 'IDE', 'ITG', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Oportunidade de aquisição ou de venda recebida', 'SOL', 'message'),
             I('Aposta aprovada para empresa própria', 'ESR', 'message'),
             I('Estudo de saída de empresa pedido', 'ESR', 'message')],
    fins=[F('Mandato cumprido e portfólio atualizado', 'ESR'), F('Caso arquivado com o motivo', 'ESR')],
    etapas=[
        E('Montar o caso: por que criar, adquirir, vender ou encerrar', 'Estratégia, com quem propôs e Inteligência', 'Copiloto', 'médio',
          [(AP_EMPRESA, 'ES-04'), (SAIDA, 'ES-02'), ('Oportunidade de aquisição ou de venda', 'Solicitante'),
           (ESTRAT, 'ES-01'), (RESPOSTA_IN, 'Inteligência'), ('Pergunta devolvida com o motivo', 'Inteligência'),
           (RESULT, 'Gestão'), (DECL, 'Identidade'), (PADROES_ID, 'Identidade'), (RESPOSTA_ID, 'Identidade')],
          [T('Enviar à Inteligência a pergunta de decisão do caso, com o risco e o prazo', 'ESR'),
           T('Receber a resposta com evidência sobre o caso, ou a pergunta devolvida', 'ESR', 'receive'),
           T('Montar o caso e os cenários, incluindo a alternativa de não mudar', 'ESA'),
           T('Conferir se o caso cabe na estratégia', 'ESA'),
           T('Concluir o caso com quem propôs', 'ESP'),
           D('O caso se sustenta?', 'ESP',
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Redigir a lição do caso arquivado, sem dado sigiloso', 'ESP'),
                                  T('Arquivar o caso com o motivo e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])]),
           T('Conferir o caso com os critérios de decisão da identidade', 'ESA'),
           D('O caso é coerente com a identidade?', 'ESP',
             [S('Sim', 'prox'), S('Não, rever o caso', 'E1'),
              S('Caso de fronteira', 'seg', via=[T('Julgar o caso de fronteira da empresa', 'IDE', 'call')])]),
           D('A Identidade considera o caso coerente?', 'IDE', [S('Sim', 'prox'), S('Não, rever o caso', 'E1')])],
          [(CASO, ['etapa 2', 'etapa 3', 'etapa 4']),
           (PERGUNTA, ['Inteligência']),
           (CONSULTA, ['Identidade']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Obter dos sócios a autorização para negociar, com limites', 'Governança, com os sócios', 'Assistido', 'alto',
          [(CASO, 'etapa 1')],
          [D('O caso é de aquisição ou de venda?', 'ESP', [S('Não', 'prox'), S('Sim', 'seg')]),
           T('Propor os limites de preço e de condições da negociação', 'ESP'),
           T('Levar aos sócios o pedido de autorização para negociar, com os limites propostos', 'GOV', 'call'),
           T('Decidir a autorização para negociar e os limites de preço e de condições', 'SOC', 'manual'),
           D('Os sócios autorizaram a negociação?', 'SOC',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Redigir a lição do caso que os sócios não autorizaram, sem dado sigiloso', 'ESP'),
                                  T('Arquivar o caso sem autorização e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Autorização dos sócios para negociar, com os limites', ['etapa 3', 'Governança']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Apurar a empresa ou o negócio e negociar com a outra parte, quando houver', 'Estratégia, com Governança e Gestão', 'Assistido', 'alto',
          [(CASO, 'etapa 1'), ('Autorização dos sócios para negociar, com os limites', 'etapa 2'),
           ('Decisão dos sócios sobre a empresa', 'etapa 5')],
          [D('Qual é o caso?', 'ESR',
             [S('Criação de empresa nova', 'prox'),
              S('Encerramento, ou venda ainda sem comprador', 'seg'),
              S('Aquisição, ou venda com comprador identificado', 'seg',
                via=[T('Firmar o acordo de confidencialidade com a outra parte', 'GOV', 'call')])]),
           PAR([T('Apurar contratos, obrigações e riscos da empresa ou do negócio', 'GOV', 'call')],
               [T('Apurar contas e pessoas da empresa ou do negócio', 'GES', 'call')]),
           D('Há outra parte com quem negociar?', 'ESR',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Negociar preço e condições com a outra parte, dentro dos limites dos sócios', 'ESP', 'manual')])]),
           D('A apuração e a negociação mantêm o caso?', 'ESP',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Redigir a lição do caso arquivado depois da apuração, sem o que é confidencial', 'ESP'),
                                  T('Arquivar o caso depois da apuração e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Resultado da apuração e termos negociados', ['etapa 4']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Propor a estrutura societária e de governança', 'Estratégia, com Governança e assessoria', 'Copiloto', 'alto',
          [(CASO, 'etapa 1'), ('Resultado da apuração e termos negociados', 'etapa 3'),
           ('Decisão dos sócios sobre a empresa', 'etapa 5'), ('Pedido de mudança do mandato', 'etapa 8'),
           (ALCADAS, 'Governança')],
          [T('Comparar estruturas societárias e de governança', 'ESA'),
           T('Avaliar os efeitos jurídicos, fiscais e contábeis', 'ASS'),
           T('Conferir a estrutura com as regras e os riscos', 'GOV'),
           T('Decidir a estrutura e o executivo a propor', 'ESP')],
          [('Proposta de estrutura', ['etapa 5'])]),
        E('Aprovar o caso e a estrutura com os sócios e firmar o contrato, quando houver', 'Governança, com os sócios', 'Assistido', 'alto',
          [('Proposta de estrutura', 'etapa 4')],
          [T('Levar o caso e a estrutura à decisão dos sócios', 'GOV', 'call'),
           T('Decidir sobre a criação, a aquisição, a venda ou o encerramento', 'SOC', 'manual'),
           D('Proposta aprovada?', 'SOC',
             [S('Sim', 'seg'),
              S('Não, rever a estrutura', 'E4'),
              S('Não, renegociar', 'E3'),
              S('Não, manter o mandato já em execução', 'E7'),
              S('Não, arquivar (só antes de haver mandato em execução)', 'F2', via=[T('Redigir a lição do caso que os sócios decidiram não seguir, sem dado sigiloso', 'ESP'),
                                            T('Registrar a decisão de não seguir e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])]),
           D('O caso aprovado tem contrato a firmar com outra parte?', 'ESR',
             [S('Não: criação, encerramento, venda ainda sem comprador ou contrato já assinado', 'prox'),
              S('Sim: aquisição, ou venda com comprador', 'seg')]),
           T('Preparar o contrato de compra ou venda dentro do que os sócios decidiram', 'GOV', 'call'),
           T('Assinar o contrato de compra ou venda', 'SOC', 'manual'),
           D('O contrato foi assinado?', 'SOC',
             [S('Sim', 'prox'),
              S('Não, renegociar com a outra parte', 'E3'),
              S('Não, desistir', 'F2', via=[T('Redigir a lição do caso em que o contrato não foi assinado, sem o que é confidencial', 'ESP'),
                                            T('Arquivar o caso sem contrato e avisar quem propôs e, se nasceu de aposta, a carteira', 'ESR')])])],
          [('Decisão dos sócios sobre a empresa', ['etapa 6', 'etapa 4', 'etapa 3', 'Governança']),
           ('Contrato de compra ou venda assinado', ['etapa 6', 'Governança']),
           (ARQUIVADO, ['Solicitante', 'Sócios', 'Governança', 'ES-02', 'ES-04']),
           (LICAO_CASO, ['Inteligência'])]),
        E('Emitir o mandato para os círculos que executam', 'Estratégia', 'Copiloto', 'alto',
          [('Decisão dos sócios sobre a empresa', 'etapa 5'), ('Contrato de compra ou venda assinado', 'etapa 5'),
           (PLANO_SAIDA, 'Integração')],
          [T('Redigir o mandato: objetivo, estrutura, recursos, prazos e donos', 'ESA'),
           T('Definir com a Gestão o responsável e a equipe da execução', 'ESP', 'manual'),
           D('O mandato é novo ou muda um mandato já emitido?', 'ESR',
             [S('Muda um mandato já emitido', 'seg'),
              S('Novo, de busca de comprador para venda ainda sem comprador', 'seg'),
              S('Novo, de criação ou aquisição', 'seg', via=[T('Pedir a identidade e a marca da empresa, com a data de efeito', 'ESR')]),
              S('Novo, de venda com comprador ou de encerramento', 'seg',
                via=[T('Pedir à Integração o plano de saída: clientes, contratos e pessoas', 'ESR'),
                     T('Receber o plano de saída coordenado pela Integração', 'ESR', 'receive'),
                     T('Conferir o plano de saída e incluí-lo no mandato', 'ESP'),
                     T('Pedir a retirada da marca da empresa, com a data de efeito', 'ESR')])]),
           T('Aprovar o mandato', 'ESP'),
           T('Enviar o mandato a cada círculo que executa', 'ESR')],
          [(MANDATO, ['etapa 7', 'etapa 8', 'Integração', 'Governança', 'Gestão', 'Relações', 'Negócios', 'Operações',
                      'Inteligência', 'Executivos']),
           ('Pedido de identidade para empresa nova', ['Identidade']),
           ('Pedido de marca', ['Identidade']),
           ('Lista de pessoas da empresa adquirida', ['Gestão']),
           ('Pedido de plano de saída: clientes, contratos e pessoas', ['Integração']),
           ('Pedido de retirada de marca', ['Identidade'])]),
        E('Executar o mandato até a empresa operar ou sair do portfólio', 'Integração, como PMO corporativo, com Governança e Gestão', 'Assistido', 'alto',
          [(MANDATO, 'etapa 6'), ('Execução do mandato a completar', 'etapa 8'),
           ('Decisão sobre a marca do negócio', 'Identidade'), ('Pacote de marca publicado', 'Identidade'),
           ('Marca retirada de uso', 'Identidade'), (DECL, 'Identidade')],
          [T('Coordenar a execução do mandato, ou do que falta dele, entre os círculos', 'ITG', 'call'),
           T('Registrar a constituição, a alteração ou o encerramento da empresa', 'GOV', 'call'),
           PAR([T('Prover ou desmobilizar responsável, pessoas, contas e orçamento', 'GES', 'call')],
               [T('Ligar a empresa aos círculos ou desligá-la: acessos e acordos de serviço', 'ITG')]),
           D('A Identidade já entregou a marca ou confirmou a retirada?', 'ESR',
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Receber da Identidade a marca pronta ou a confirmação da retirada na data de efeito', 'ESR', 'receive')])]),
           T('Informar à Estratégia a situação da execução do mandato', 'ITG')],
          [('Situação da execução do mandato', ['etapa 8'])]),
        E('Conferir o cumprimento do mandato e atualizar o portfólio', 'Estratégia', 'Copiloto', 'médio',
          [(MANDATO, 'etapa 6'), ('Situação da execução do mandato', 'etapa 7')],
          [T('Conferir a execução contra o mandato', 'ESA'),
           T('Concluir se o mandato foi cumprido', 'ESP'),
           D('Mandato cumprido?', 'ESP',
             [S('Sim', 'seg'), S('Não, falta executar', 'E7'), S('Não, o mandato precisa mudar', 'E4')]),
           T('Atualizar o portfólio e avisar quem depende dele', 'ESR')],
          [(PORTF, ['ES-01', 'ES-02', 'ES-03', 'Identidade', 'Inteligência', 'Gestão', 'Governança']),
           ('Execução do mandato a completar', ['etapa 7']),
           ('Pedido de mudança do mandato', ['etapa 4'])]),
    ]))
