
# ========================================================== ACOMPANHAMENTO
JORNADAS.append(dict(
    code='ES-06',
    nome='Acompanhar a execução da estratégia e corrigir o rumo',
    dominio='Acompanhamento', classe='essencial', onda=1,
    objetivo='Saber a cada revisão se a estratégia está sendo executada e se as hipóteses continuam de pé, separar falha de execução de hipótese errada, decidir as correções de execução, abrir as revisões que só os sócios decidem e prestar contas. Usa as comparações que a Inteligência e a Gestão já fazem, num painel único.',
    frequencia='A cada revisão da estratégia (cadência a definir) e por evento, quando o ritual da Gestão aponta desvio grave',
    automacao=('média', 'O agente reúne os resultados, aponta os desvios e propõe causas; a Inteligência responde com os dados; a decisão de corrigir e a prestação de contas são de pessoas.'),
    base=['kaplan', 'apqc'],
    lanes=['GES', 'ESP', 'ESA', 'ESR'],
    inicios=[I('Desvio grave apontado pelo ritual', 'GES', 'message'),
             I('Ciclo de revisão da estratégia iniciado', 'ESR', 'timer')],
    fins=[F('Revisão concluída com correções encaminhadas', 'ESR'), F('Revisão concluída sem correção', 'ESR')],
    etapas=[
        E('Reunir os resultados contra os alvos e as hipóteses', 'Estratégia', 'Autopiloto', 'baixo',
          [(ALVOS, 'ES-03'), (ESTRAT, 'ES-01'), (HIPOT, 'ES-01'), (METODO, 'ES-01'), (MANTIDA, 'ES-01'), (CARTEIRA, 'ES-04'),
           ('Desvios e decisões do ritual de acompanhamento', 'Gestão'), (INDIC, 'Inteligência'),
           (LEITURA, 'Inteligência'), ('Contestação de indicador de alvo vigente', 'Inteligência'),
           ('Situação das iniciativas na carteira de projetos', 'Integração'), (RISCOS, 'Governança')],
          [T('Reunir no painel único os indicadores, os desvios do ritual e a situação das iniciativas', 'ESR'),
           T('Listar os desvios e os sinais que as comparações da Inteligência e da Gestão já apontam', 'ESA')],
          [('Desvios e sinais apontados no painel único', ['etapa 2'])]),
        E('Separar falha de execução de hipótese errada', 'Estratégia, com executivos e líderes dos círculos', 'Copiloto', 'médio',
          [('Desvios e sinais apontados no painel único', 'etapa 1'), (RESPOSTA_IN, 'Inteligência'),
           ('Pergunta devolvida com o motivo', 'Inteligência')],
          [T('Propor a causa de cada desvio: execução, recurso, alvo ou hipótese', 'ESA'),
           T('Enviar à Inteligência a pergunta sobre as causas propostas, com o risco e o prazo', 'ESR'),
           T('Receber a resposta da Inteligência sobre as causas, ou a pergunta devolvida', 'ESR', 'receive'),
           T('Discutir as causas com executivos e líderes dos círculos', 'ESP', 'manual'),
           T('Concluir a causa de cada desvio', 'ESP'),
           D('Há contestação de indicador de alvo vigente?', 'ESP',
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Decidir a contestação do indicador de alvo: manter a ficha ou abrir a correção do alvo', 'ESP')])]),
           D('Há correção a fazer?', 'ESP',
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a revisão sem correção e avisar quem apontou o desvio', 'ESR')])])],
          [(CAUSAS, ['etapa 3', 'ES-02']),
           (PERGUNTA, ['Inteligência']),
           ('Decisão sobre a contestação do indicador de alvo', ['Inteligência']),
           ('Revisão sem correção registrada', ['Gestão', 'Sócios'])]),
        E('Decidir as correções de execução e abrir as revisões que os sócios decidem', 'Estratégia, com os executivos', 'Copiloto', 'médio',
          [(CAUSAS, 'etapa 2')],
          [T('Propor alternativas de correção e o efeito de cada uma', 'ESA'),
           T('Decidir as correções de execução com os executivos', 'ESP', 'manual'),
           D('Há correção na execução?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Pedir o plano de correção ao dono da execução', 'ESR')])]),
           D('Há correção numa aposta ou numa oferta?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Pedir a revisão da aposta ou da oferta no portão', 'ESR')])]),
           D('Há correção nos alvos?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Abrir novo desdobramento dos alvos', 'ESR')])]),
           D('Há correção nos recursos ou no portfólio?', 'ESP',
             [S('Não', 'seg'), S('Sim', 'seg', via=[T('Abrir a revisão do portfólio', 'ESR')])]),
           D('A hipótese da estratégia falhou?', 'ESP',
             [S('Não', 'prox'), S('Sim', 'prox', via=[T('Abrir a revisão da estratégia', 'ESR')])])],
          [('Correções de execução decididas, com dono e prazo', ['etapa 4']),
           ('Revisões abertas para decisão dos sócios: alvos, portfólio ou estratégia', ['etapa 4']),
           ('Pedido de plano de correção', ['Executivos', 'Líderes dos círculos', 'Gestão']),
           (REVISAO_AP, ['ES-04']),
           ('Decisão de corrigir os alvos', ['ES-03']),
           ('Decisão de rever o portfólio', ['ES-02']),
           ('Decisão de rever a estratégia', ['ES-01'])]),
        E('Registrar as correções e prestar contas da revisão', 'Estratégia', 'Copiloto', 'baixo',
          [('Correções de execução decididas, com dono e prazo', 'etapa 3'),
           ('Revisões abertas para decisão dos sócios: alvos, portfólio ou estratégia', 'etapa 3')],
          [T('Registrar no painel único as correções de execução, os donos e os prazos', 'ESR'),
           T('Resumir o resultado, as revisões abertas para os sócios e as lições da revisão', 'ESA'),
           T('Aprovar a prestação de contas da revisão antes de enviá-la aos sócios', 'ESP'),
           T('Avisar círculos e executivos afetados e enviar o resultado aos sócios', 'ESR')],
          [('Correções de execução publicadas, com dono e prazo', [TODOS, 'Gestão']),
           ('Resultado da revisão da estratégia', ['Sócios', 'Governança']),
           ('Lições da revisão da estratégia', ['Inteligência'])]),
    ]))
