
# -------------------------------------------------------------- domínios
DOMINIOS = [
    ('Direção e recursos', 'Escolher onde atuar, alocar os recursos e fixar os alvos.'),
    ('Apostas e empresas', 'Decidir o que entra, o que avança e o que sai do portfólio.'),
    ('Acompanhamento', 'Conferir se a estratégia é executada e se continua certa.'),
]

ONDAS = {
    1: 'O que o modelo precisa para rodar: direção, alvos e correção de rumo',
    2: 'O que cuida do portfólio e das apostas',
    3: 'O que roda por evento raro',
}

# ------------------------------------------------- o que usamos de cada fonte
USO = {
    'apqc': 'PCF 7.4, categoria 1.0, Develop Vision and Strategy, com quatro grupos: 1.1, conceito de negócio e visão de longo prazo; 1.2, estratégia de negócio; 1.3, iniciativas estratégicas; 1.4, modelos de negócio. A tabela de cobertura, na aba Método, mostra onde cada processo foi parar: nas seis jornadas ou em outro círculo.',
    'kaplan': 'Sistema de gestão em cinco estágios: desenvolver a estratégia, traduzir a estratégia, planejar as operações, monitorar e aprender, testar e adaptar a estratégia. Os autores descrevem três tipos de reunião (revisão operacional, revisão da estratégia e teste e adaptação da estratégia) e pedem pautas distintas para a revisão operacional e a da estratégia, para o curto prazo não expulsar a discussão da estratégia. Base da sequência ES-01, ES-03 e ES-06. Pôr o ritual operacional na Gestão e a revisão da estratégia neste círculo é escolha nossa: os autores dizem que as mesmas pessoas costumam participar das duas reuniões.',
    'rumelt': 'O núcleo de uma boa estratégia tem três partes: diagnóstico, política orientadora e ações coerentes. Um dos sinais de estratégia ruim é confundir alvos com estratégia. Base das etapas 1 e 2 da ES-01 e da separação entre formular (ES-01) e fixar alvos (ES-03).',
    'okr': 'Objetivos ambiciosos e resultados-chave mensuráveis. Base das etapas 1 e 2 da ES-03.',
    'lei': 'Desdobramento da estratégia (hoshin kanri): alinha as funções e atividades da organização, na vertical e na horizontal, com os objetivos estratégicos, num processo de cima para baixo e de baixo para cima. O verbete chama esse diálogo de catchball. Base da etapa 2 da ES-03.',
    'horizons': 'Três horizontes de crescimento, geridos ao mesmo tempo: o negócio principal de hoje (horizonte 1), as oportunidades emergentes (horizonte 2) e as ideias de crescimento futuro (horizonte 3). Usado para dar papel a cada unidade no portfólio-alvo (ES-01 e ES-02) e para situar as apostas (ES-04).',
    'parenting': 'Duas perguntas que, segundo os autores, a maioria dos executivos-chefes deixa de responder na estratégia corporativa: que negócios esta empresa, e não as rivais, deve ter, e por quê; e que estrutura organizacional, processos de gestão e filosofia favorecem o desempenho superior dos seus negócios. Base do portfólio-alvo na ES-01, da leitura do portfólio na ES-02 e do caso na ES-05.',
    'realloc': 'Quatro atividades de alocação: semear (entrar em área de negócio nova, por aquisição ou investimento próprio), nutrir (reforçar um negócio existente), podar (tirar recursos de um negócio existente) e colher (vender negócios inteiros que não cabem mais no portfólio ou separá-los). Quatro recomendações: ter um portfólio-alvo, usar todos os instrumentos de realocação, adotar regras simples para romper o status quo e implantar processos que reduzam a inércia. Numa amostra de mais de 1.600 empresas dos Estados Unidos, de 1990 a 2005, os autores relatam que o terço que mais realocou capital entre unidades de negócio teve, em média, retorno total ao acionista 30% maior por ano que o terço que menos realocou: 10,2% contra 7,8% ao ano, diferença relativa, não de 30 pontos percentuais. Em períodos de menos de três anos, quem mais realocou teve retorno menor. Base da ES-02 e, na venda de empresa, da ES-05.',
    'stagegate': 'O trabalho de inovação é dividido em estágios, cada um precedido de um portão. Em cada portão, gestores seniores (os gatekeepers) decidem entre Go, Kill, Hold e Recycle. A página lista os quatro resultados sem defini-los; lê-los como avançar, encerrar, esperar e voltar para ajuste é interpretação nossa, e o resultado “segue como está”, da revisão de uma aposta, é acréscimo nosso. A fonte tem cinco estágios e cinco portões, de desenvolvimento de produto; a ES-04 usa a lógica, com dois portões.',
    'iia': 'No modelo, o órgão de governança presta contas pela supervisão da organização e delega responsabilidade e recursos à gestão; as três linhas ficam abaixo dele. Usado por analogia para separar o que os sócios aprovam (ES-01, ES-02, ES-03 e ES-05) do que a Estratégia propõe e decide dentro da alçada.',
    'bpmn': 'Notação dos fluxos. A ISO/IEC 19510:2013 é idêntica ao BPMN 2.0.1. Tipos de tarefa usados: usuário, manual, serviço, regra de negócio, script e recebimento, além da atividade de chamada.',
    'camunda': 'Regra de nomes: tarefa com verbo no infinitivo e objeto; evento com objeto e estado; gateway com pergunta; raia com papel ou sistema.',
    'dmn': 'Padrão de modelagem de decisões, que inclui tabelas de decisão. Usado na ES-04 para a tabela de alçadas e para o limite de recursos da alocação.',
    'sipoc': 'Fornecedor, entrada, processo, saída e cliente: a base de “quem gera a entrada” e “quem recebe a saída” em cada etapa.',
}

# ----------------------------------- cobertura do referencial (APQC PCF 7.4, categoria 1.0)
COBERTURA = [
    ('1.1.1', 'Assess the external environment', 'ES-01, etapa 1, com a leitura da Inteligência'),
    ('1.1.2', 'Survey market and determine customer needs and wants', 'Fora: Inteligência'),
    ('1.1.3', 'Assess the internal environment', 'ES-01, etapa 1'),
    ('1.1.4', 'Establish strategic vision', 'Fora: Identidade (ID-01)'),
    ('1.1.5', 'Conduct organization restructuring opportunities', 'ES-05'),
    ('1.2.1', 'Develop overall mission statement', 'Fora: Identidade (ID-01)'),
    ('1.2.2', 'Define and evaluate strategic options to achieve the mission', 'ES-01, etapa 2'),
    ('1.2.3', 'Set/Develop long-term enterprise strategy', 'ES-01 e ES-02. Serviços compartilhados (1.2.3.6) na ES-01, etapa 3; aquisição e saída (1.2.3.3) na ES-05; fusão e cisão não estão desenhadas'),
    ('1.2.4', 'Coordinate and align cross-functional and process strategies', 'ES-01, etapa 3, e ES-03, etapa 2'),
    ('1.2.5', 'Create organizational design', 'Fora: Integração (jornadas e catálogo) e Governança (alçadas)'),
    ('1.2.6', 'Develop and set organizational objectives', 'ES-03'),
    ('1.2.7', 'Formulate business unit strategies', 'ES-01, etapa 3'),
    ('1.2.8', 'Develop customer experience strategy', 'Fora: Relações, por decisão de 01/10/2026; entra no desenho do círculo 4'),
    ('1.2.9', 'Communicate strategies internally and externally', 'Fora: Gestão, para dentro, e Relações, para fora. A ES-01 entrega o que comunicar'),
    ('1.3.1 a 1.3.3', 'Develop strategic initiatives; Evaluate strategic initiatives; Select strategic initiatives', 'ES-03, para as iniciativas dos alvos; ES-04, para as apostas'),
    ('1.3.4', 'Establish high-level measures', 'ES-03, etapa 2, com as fichas dos indicadores que a Inteligência decide na IN-04'),
    ('1.3.5', 'Execute strategic initiatives', 'Fora: executivos e círculos; os projetos ficam na Integração'),
    ('1.3.6 e 1.3.7', 'Review execution of strategic initiatives; Refine strategic initiatives and project plans as needed', 'ES-06'),
    ('1.4', 'Develop and maintain business models', 'Fora: Inteligência, pela decisão D4 da rodada 2'),
]

# --------------------------------------------------- o que a Estratégia não faz
FRONTEIRAS = [
    ('Definir propósito, valores, marca e posicionamento', 'Identidade',
     'A direção e os públicos prioritários. Confere as próprias escolhas com a declaração e os critérios de decisão da Identidade.'),
    ('Ler mercado, clientes e concorrentes e medir indicadores', 'Inteligência',
     'As perguntas do diagnóstico, as hipóteses e os sinais a vigiar (ES-01); os alvos propostos, para a ficha do indicador de cada um (ES-03); e as perguntas de decisão dos portões, dos casos e das causas (ES-04, ES-05 e ES-06).'),
    ('Produtizar a oferta, desenhar o modelo de negócio e decidir o preço-base de cada oferta', 'Inteligência',
     'A decisão em cada portão: a aposta que entra e a oferta que é lançada (ES-04). O método de estratégia leva os critérios dos portões.'),
    ('Executar a estratégia da empresa', 'Executivo da empresa',
     'O método de estratégia, o papel da empresa no portfólio-alvo e a conferência de coerência entre as empresas (ES-01). O executivo propõe as escolhas da empresa e participa; a Estratégia formula e os sócios aprovam.'),
    ('Montar e controlar o orçamento', 'Gestão',
     'A alocação por empresa, oferta e aposta (ES-02) e os alvos e iniciativas (ES-03).'),
    ('Rodar o ritual de acompanhamento dos alvos', 'Gestão',
     'Os alvos, as iniciativas e os donos (ES-03). Recebe de volta os desvios e as decisões do ritual.'),
    ('Executar aportes, distribuição de resultado e ajustes de orçamento', 'Gestão',
     'A decisão de alocação e de destino do resultado (ES-02).'),
    ('Definir e aplicar o critério de rateio do custo dos círculos', 'Governança define, com a Estratégia; Gestão aplica',
     'O que é serviço comum a todas as empresas e o que é de cada uma (ES-01, etapa 3).'),
    ('Gerir os projetos das iniciativas, executar o mandato de empresa e coordenar o lançamento de oferta', 'Integração, como PMO corporativo',
     'As iniciativas aprovadas (ES-03), o mandato da empresa (ES-05), que a Integração executa e a Estratégia confere, e a oferta aprovada para lançamento (ES-04).'),
    ('Montar e executar o plano de saída de clientes, contratos e pessoas', 'Integração, como PMO corporativo, com Relações, Negócios, Operações, Governança e Gestão',
     'O pedido do plano de saída (ES-04 e ES-05). O plano volta à Estratégia, que o confere antes de decidir a data de saída (ES-04) ou de fechar o mandato (ES-05).'),
    ('Manter o painel único de indicadores', 'Inteligência',
     'Os alvos, as iniciativas e as correções, que a Estratégia registra no painel (ES-03 e ES-06).'),
    ('Constituir, alterar e encerrar empresas; registrar as decisões dos sócios; definir as alçadas', 'Governança',
     'O caso, a proposta de estrutura e cada proposta que sobe aos sócios.'),
    ('Captar dinheiro de fora ou admitir sócio numa empresa', 'Sócios, com Governança e Gestão',
     'O caso e a proposta de estrutura, quando a operação muda o portfólio (ES-05).'),
    ('Priorizar parceiros e gerar demanda', 'Relações',
     'A direção, os públicos prioritários e a oferta aprovada para lançamento.'),
    ('Definir a tabela de preços e a política comercial', 'Negócios',
     'O papel de cada oferta no portfólio-alvo e a oferta aprovada para lançamento.'),
    ('Comunicar a estratégia para dentro e para fora', 'Gestão, para dentro; Relações, para fora',
     'O resumo da direção, já com o que pode ser dito para fora, e o aviso do que mudou.'),
    ('Levar as lições entre empresas ao catálogo', 'Inteligência, com Integração',
     'A leitura do portfólio (ES-02), a lição da aposta encerrada (ES-04), a lição do caso arquivado, sem dado sigiloso (ES-05), e as lições da revisão (ES-06).'),
]

# ------------------------------------------------------- decisões de fechamento
PONTOS = []
DECISOES = [
    ('A Estratégia faz o trabalho de estratégia de ponta a ponta, os sócios aprovam e a Gestão opera a rotina',
     'Regra sua (15:48), sobre a minha proposta',
     'A Estratégia formula, propõe, desdobra, decide os portões dentro da alçada e acompanha. Li “rotina” como montar e controlar o orçamento e rodar o ritual de acompanhamento dos alvos.'),
    ('A Integração é o PMO corporativo, interno e externo',
     'Definição sua (15:48)',
     'Na ES-05 a Integração coordena a execução do mandato; na ES-03 confere a capacidade de executar as iniciativas. Vale como requisito para o círculo 6.'),
    ('Sobem para os sócios: a estratégia, a alocação e o destino do resultado, os alvos com o orçamento, e criar, adquirir, vender ou encerrar empresa',
     'Proposta minha aprovada (15:48)',
     'ES-01, ES-02, ES-03 e ES-05 têm etapa de aprovação pelos sócios. Na ES-04 só sobe o que passa da alçada da Estratégia.'),
    ('Uma aposta atravessa dois portões: a entrada na carteira e o lançamento',
     'Sua decisão D4 da rodada 2, confirmada (15:48)',
     'A validação com clientes é marco da jornada da Inteligência. Encerrar é resultado possível de qualquer portão ou revisão.'),
    ('A estratégia de experiência do cliente é de Relações',
     'Proposta minha aprovada (15:48)',
     'Fica fora das jornadas da Estratégia. Entra no desenho do círculo 4, com Operações no círculo 7.'),
    ('Vender ou encerrar uma empresa inclui retirar a marca de uso',
     'Decorre da proposta 1 do círculo 1, aprovada por você (15:48)',
     'A ES-05 pede a retirada à Identidade, que a executa pela ID-03.'),
]

PROPOSTAS = [
    ('ES-01, etapa 3: a Estratégia passa a ser a dona da etapa; o executivo e o líder do círculo propõem as escolhas; a divergência sem acordo sobe aos sócios',
     'Hoje os donos da etapa são os executivos e os líderes, e o executivo “decide” as escolhas da empresa. Isso contraria a regra de que a Estratégia faz e os sócios aprovam. O conflito entre empresas e círculos não tem saída para quando não há acordo.',
     'Revisão depois do fechamento · grave'),
    ('ES-01, etapa 1: o caminho da empresa nova usa a estratégia vigente e confere a identidade; a decisão de manter a estratégia gera aviso; o diagnóstico espera a leitura da Inteligência ou o aviso de leitura sem novidade',
     'Hoje o caminho da empresa nova salta para a etapa 3 sem as escolhas do Ecossistema e sem conferência de identidade. A decisão de manter a estratégia termina sem avisar ninguém. E a etapa pede a leitura de mercado e a usa no mesmo passo, refazendo parte do que é da Inteligência.',
     'Revisão depois do fechamento'),
    ('ES-01, etapas 2 a 5: o método de estratégia e as hipóteses entram na proposta que os sócios aprovam; o método vai também à Inteligência, aos líderes dos círculos, à Gestão, à Integração e à Governança',
     'Os critérios dos portões delimitam o que a Estratégia decide sozinha na ES-04, e hoje não está dito quem os aprova. A Inteligência prepara o pacote do portão de lançamento sem receber os critérios.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-02, etapa 2: o destino do resultado do período sobe sempre aos sócios, mesmo sem realocação',
     'Hoje a Estratégia pode encerrar a revisão sozinha, sem saída para os sócios, a Governança e a Gestão. Manter a alocação e dar destino ao resultado também são decisões dos sócios.',
     'Revisão depois do fechamento · grave'),
    ('ES-02, etapa 4: o portfólio-alvo atualizado vai aos mesmos destinos da ES-01; a alocação que muda alvos ou orçamento abre a ES-03',
     'Hoje a Inteligência e Negócios ficam com a versão anterior do portfólio-alvo depois de cada realocação, e o início “Alocação que muda alvos ou orçamento decidida”, da ES-03, não tem quem o dispare.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-03, etapas 2 e 3: a conferência dos indicadores chama a IN-04 antes da aprovação; a divergência que não cabe nos recursos sobe aos sócios com as alternativas',
     'Hoje a Inteligência confere indicador, fonte e linha de base antes de a ficha existir, e os sócios podem aprovar alvo que depois fica sem dado. O que não cabe no orçamento gira entre as etapas 2 e 3 sem chegar a quem decide.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-03: novos inícios “Nova estratégia publicada” e “Portfólio de empresas atualizado”',
     'Hoje os alvos da estratégia anterior valem até o próximo ciclo, mesmo depois de a estratégia mudar ou de uma empresa entrar ou sair.',
     'Revisão depois do fechamento'),
    ('ES-04: caminho de revisão da aposta, com o início “Revisão da aposta pedida” (pela Inteligência, pela ES-06 ou pelo executivo), os indicadores e o gasto realizado como entradas e um produto próprio para a aposta devolvida com evidência',
     'A IN-07 devolve a aposta quando o modelo não fecha ou o piloto refuta a hipótese, e a ES-04 não tem início que a receba: só reabre a aposta na data de revisão. A revisão e a saída indicada entram numa etapa que só registra aposta nova, e a avaliação não usa o resultado da aposta.',
     'Revisão depois do fechamento · grave'),
    ('ES-04, etapas 3 e 4: “empresa própria” passa a ser decidida no portão, por pessoa; o caso arquivado na ES-05 volta à ES-04',
     'Hoje o destino “empresa própria” é escolhido por automação depois do portão, e a aposta que vai à ES-05 não segue para a Inteligência. Se o caso é arquivado, a aposta continua aprovada e com recursos na carteira.',
     'Revisão depois do fechamento · grave'),
    ('ES-04, etapa 3: encerrar oferta em uso gera decisão própria, com plano de saída de clientes e contratos e retirada da marca; a retomada da aposta em espera fica só na ES-04',
     'Hoje a Inteligência recebe só a lição da aposta encerrada e a usa como ordem para retirar a oferta do catálogo. A espera não tem retomada clara no portão de entrada.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-04, etapa 2, ES-05, etapa 1, e ES-06, etapa 2: pedir a evidência ou a contestação à Inteligência com uma pergunta de decisão explícita e esperar a resposta',
     'Hoje a resposta com evidência é entrada da ES-04 e da ES-05 sem que nenhuma tarefa pergunte, e a contestação das causas, na ES-06, é tarefa da Inteligência sem pedido. A IN-02 só começa com uma pergunta de decisão.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-04, etapa 4: nomear o dono do lançamento, deixar a entrega do pacote só na IN-07 e enviar à Integração toda decisão de portão que abre, suspende ou encerra projeto',
     'Hoje a oferta aprovada vai ao executivo, a Relações e a Negócios sem dono do lançamento, e o pacote é entregue duas vezes. Depende do ponto 3 do círculo 3.',
     'Revisão depois do fechamento e ponto 3 do círculo 3'),
    ('ES-05, etapas 1 a 4: os sócios autorizam a negociação, com limites, antes de ela começar; o contrato de compra ou venda passa pela Governança; a apuração vale também para o encerramento; um só aviso de caso arquivado',
     'Hoje a Estratégia negocia preço e condições antes de qualquer decisão dos sócios, nenhuma tarefa redige e assina o contrato, o encerramento pula a apuração de contratos, obrigações e pessoas, e o caso arquivado leva à base de lições um resultado coberto por acordo de confidencialidade.',
     'Revisão depois do fechamento'),
    ('ES-05, etapas 5 e 6: um só pedido de marca, com data de efeito; plano de saída conferido antes de fechar o mandato; mandato também para Negócios, Operações e Inteligência; executar (Integração) separado de conferir (Estratégia)',
     'Hoje a marca é pedida na etapa 5 e chamada de novo na etapa 6, sem data: a retirada pode ser avisada enquanto a empresa ainda atende clientes. O plano de saída é pedido e não volta. Quem vende, quem entrega e quem cuida das ofertas no catálogo não recebem o mandato.',
     'Revisão depois do fechamento'),
    ('ES-06: usar as comparações já feitas pela Inteligência e pela Gestão, num painel único; separar a correção de execução do que só os sócios decidem; prestação de contas aprovada por pessoa',
     'Hoje a ES-06 refaz a comparação dos indicadores com os alvos e dos sinais com as hipóteses, há três painéis com nomes diferentes, as correções são publicadas para todos antes de os sócios decidirem o que é deles, e o resumo enviado aos sócios sai sem aprovação de pessoa.',
     'Revisão depois do fechamento e cruzamento com a Inteligência'),
    ('ES-02 a ES-05: a conferência de identidade ganha decisão e consulta à Identidade, como na ES-01',
     'Hoje o agente confere a proposta com os critérios da identidade e nada acontece com o resultado: não há decisão, ramo de ajuste nem consulta.',
     'Revisão depois do fechamento'),
    ('Nomes e textos: “Oferta aprovada no portfólio” passa a “Oferta aprovada para lançamento”; “Indicação de saída” passa a “Estudo de saída pedido”; fusão e cisão ganham ramo próprio ou saem do objetivo da ES-05',
     'Os nomes dizem mais do que o fluxo faz: os sócios mandam estudar a saída, não a decidem, e o objetivo da ES-05 promete fusão e cisão, que não têm ramo.',
     'Revisão depois do fechamento · leve'),
    ('ES-06, etapa 2: decidir a contestação de indicador de alvo vigente que a Inteligência registra no painel',
     'A IN-04 não muda indicador de alvo vigente: registra a contestação no painel e a aponta na revisão dos indicadores. Hoje nenhuma etapa da Estratégia decide se a régua do alvo muda.',
     'Cruzamento com a Inteligência'),
]

ALERTAS = [
    ('Integração como PMO corporativo', 'A definição pede, no círculo 6, as jornadas de carteira de projetos internos e externos e a coordenação de implantações. A ES-03 e a ES-05 já contam com elas.'),
    ('Alçadas e sócios', 'Faltam as alçadas que separam a decisão da Estratégia da decisão dos sócios, e quem são os sócios em cada caso: os do Ecossistema ou os de cada empresa. Fica para o círculo 9.'),
    ('Cadências', 'Ciclo estratégico, período de resultado, ciclo de alvos e revisão da estratégia continuam “a definir”. Sem base, não propus número.'),
    ('Método de estratégia', 'Tem lugar no desenho (ES-01), mas o conteúdo ainda não foi escrito: critérios dos portões, regras de realocação e calendário.'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'C1 · Da estratégia ao resultado', 'ES-01, ES-03 e ES-06',
     'Dividida em formular, desdobrar e acompanhar. O ritual de acompanhamento (W-C1.4) continua na Gestão.'),
    ('Ajustado', 'E4 · Do resultado da empresa à decisão do Ecossistema', 'ES-02',
     'Vira revisão do portfólio e realocação de recursos. Executar a decisão (W-E4.3) fica na Gestão; levar as lições ao catálogo (W-E4.4), na Inteligência.'),
    ('Ajustado', 'I-ES1 · Da ideia à aposta priorizada', 'ES-04',
     'Vira decisão por portões. A revisão da carteira (W-ES1.4) passa à ES-02, que só indica a saída; quem decide é o portão.'),
    ('Ajustado', 'W-V1.6 · Decidir o lançamento, dentro da V1', 'ES-04',
     'O lançamento vira o segundo portão. A V1 continua liderada pela Inteligência.'),
    ('Ajustado', 'E5 · Da aposta à empresa nova', 'ES-05',
     'Passa a cobrir também aquisição, venda e encerramento. Constituir e registrar (W-E5.3) fica na Governança; ligar aos círculos (W-E5.5), na Integração.'),
    ('Ajustado', 'Decisão D4: a Estratégia decide a aposta que entra e a oferta que é lançada', 'ES-04',
     'Mantida, com um limite: a Estratégia decide com o executivo dentro da alçada; acima dela, decidem os sócios.'),
    ('Acrescentado', 'Sem equivalente', 'Portfólio-alvo, hipóteses e método de estratégia',
     'Três produtos novos da ES-01. O portfólio-alvo é a referência da ES-02; as hipóteses e os sinais são o que a ES-06 acompanha; o método traz os critérios dos portões e as regras de realocação.'),
    ('Acrescentado', 'Sem equivalente', 'Escolhas de cada círculo',
     'Na ES-01, etapa 3, cada líder de círculo propõe o que é serviço comum, o que construir e o que comprar.'),
    ('Acrescentado', 'Sem equivalente', 'Ponto de conferência com a identidade',
     'Na ES-01, ES-02, ES-03, ES-04 e ES-05 o agente confere as propostas com os padrões da Identidade. Na ES-01, o caso de fronteira vira consulta à ID-02.'),
    ('Acrescentado', 'Sem equivalente', 'Raia e parte “Líder do círculo”',
     'Papel novo no vocabulário do modelo: na ES-01 e na ES-03, cada líder de círculo propõe as escolhas e os alvos do seu círculo.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'Nenhuma cadência foi fixada: ciclo estratégico, período de resultado, ciclo de alvos e revisão da estratégia estão como “a definir”.',
    'O método de estratégia tem lugar no desenho (ES-01), mas o conteúdo ainda não foi escrito: critérios dos portões, regras de realocação e calendário.',
    'As alçadas que separam a decisão da Estratégia da decisão dos sócios ainda não existem; serão definidas no círculo 9, Governança.',
    'A raia “Sócios” não distingue os sócios do Ecossistema dos sócios de cada empresa. Quem delibera o quê fica para o círculo 9.',
    'As trocas com a Identidade e a Inteligência foram conferidas dos dois lados. Com os outros seis círculos, estão descritas pelo nome do círculo e serão conferidas quando cada um for desenhado.',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = [
    'Um revisor independente leu a primeira versão das seis jornadas e apontou 33 achados, 6 graves. Todos foram tratados nesta versão; os que dependem de escolha sua viraram pontos para decidir. O grave principal: o texto dizia que a Estratégia decide, e nos fluxos quem decide são os sócios.',
    'Um segundo revisor reabriu as dez fontes deste círculo: sete confirmadas e três confirmadas em parte. As correções de redação foram aplicadas na aba Fontes.',
    'A versão corrigida passou de novo por todos os testes automáticos e foi a que você fechou.',
    'Depois do fechamento, um terceiro revisor independente leu esta versão junto com os círculos 1 e 3 e apontou 30 achados, 4 graves. Nenhum foi aplicado: o desenho desta página é o que você aprovou. Vinte e oito viraram as propostas 1 a 17 da aba Decisões; o das alçadas segue para o círculo 9, e o das fontes era limite do pacote entregue ao revisor. A proposta 18 veio do cruzamento com o círculo 3.',
]
