# ------------------------------------------------------- decisões de fechamento
PONTOS = []
DECISOES = [
    ('A Estratégia faz o trabalho de estratégia de ponta a ponta, os sócios aprovam e a Gestão opera a rotina',
     'Regra sua (15:48), sobre a minha proposta',
     'A Estratégia formula, propõe, desdobra, decide os portões dentro da alçada e acompanha. Li “rotina” como montar e controlar o orçamento e rodar o ritual de acompanhamento dos alvos.'),
    ('O executivo e o líder do círculo propõem e participam, mas não decidem',
     'Regra sua (20:02), ao aprovar a proposta 1',
     'Na ES-01, etapa 3, a Estratégia formula a estratégia de cada empresa e as escolhas de cada círculo, ouvidos o executivo e o líder; a divergência sem acordo sobe aos sócios, e a decisão deles é incorporada ao texto na etapa 5. Estender a regra à ES-02, à ES-04 e à ES-06, onde o texto fechado diz “com o executivo”, é proposta, não aplicada.'),
    ('A Integração é o PMO corporativo, interno e externo',
     'Definição sua (15:48)',
     'Na ES-05 a Integração executa o mandato e a Estratégia confere; na ES-03 confere a capacidade de executar as iniciativas; na ES-04 coordena o lançamento da oferta aprovada (ponto 3 do círculo 3, aprovado às 20:02) e o plano de saída de clientes e contratos. Vale como requisito para o círculo 6.'),
    ('Sobem para os sócios: a estratégia, a alocação e o destino do resultado, os alvos com o orçamento, e criar, adquirir, vender ou encerrar empresa',
     'Proposta minha aprovada (15:48), completada pelas propostas 3, 4, 6 e 13 (20:02)',
     'ES-01, ES-02, ES-03 e ES-05 têm etapa de aprovação pelos sócios. Sobem também o método de estratégia e as hipóteses, a proposta de manter a alocação, as divergências sem acordo e a autorização para negociar. Na ES-04 só sobe o que passa da alçada da Estratégia.'),
    ('Os sócios autorizam a negociação, com limites, antes de ela começar',
     'Proposta 13, aprovada por você (20:02)',
     'A ES-05 ganha a etapa 2. O contrato de compra ou venda é preparado pela Governança e assinado depois da decisão dos sócios e antes do mandato (etapa 5).'),
    ('Uma aposta atravessa dois portões: a entrada na carteira e o lançamento',
     'Sua decisão D4 da rodada 2, confirmada (15:48)',
     'A validação com clientes é marco da jornada da Inteligência. Encerrar é resultado possível de qualquer portão ou revisão.'),
    ('A estratégia de experiência do cliente é de Relações',
     'Proposta minha aprovada (15:48)',
     'Fica fora das jornadas da Estratégia. Entra no desenho do círculo 4, com Operações no círculo 7.'),
    ('Vender ou encerrar uma empresa inclui retirar a marca de uso',
     'Decorre da proposta 1 do círculo 1, aprovada por você (15:48)',
     'A ES-05 pede a retirada à Identidade, com a data de efeito, e a ES-04 faz o mesmo pedido quando encerra oferta com marca própria. A ID-03 ainda não trata a data de efeito: é proposta pendente no círculo 1.'),
    ('As 18 propostas de mudança deste círculo foram aprovadas',
     'Sua resposta das 20:02',
     'Estão aplicadas nesta versão. Cada uma aparece na aba O que mudou com a marca “aprovada às 20:02”.'),
]

# propostas de mudança em conteúdo já aprovado: só entram com a sua aprovação
PROPOSTAS = [
    ('ES-02, ES-04 e ES-06: estender a regra “o executivo propõe e participa, mas não decide” à mudança de papel, ao portão e às correções de execução',
     'Às 20:02 você fixou a regra ao aprovar a proposta 1, que trata da ES-01. Nesses três pontos o texto fechado diz “com o executivo”. Com a mudança, a Estratégia decide depois de ouvir o executivo. A mesma pergunta está no círculo 1, para a escolha da identidade da marca.',
     'Revisão independente do fechamento, em 02/10/2026'),
    ('ES-05, etapas 1 e 3: arquivar caso que os sócios mandaram estudar, ou cuja negociação autorizaram, sobe a eles como proposta',
     'Hoje a Estratégia arquiva sozinha o estudo de saída pedido pelos sócios e o caso com negociação autorizada; eles só recebem o aviso.',
     'Revisão independente do fechamento'),
    ('ES-01, etapa 1: manter a estratégia no ciclo sobe aos sócios, como já acontece com manter a alocação',
     'Hoje, quando o diagnóstico não pede mudança, a Estratégia decide manter e avisa. Na ES-02, a proposta de manter a alocação sobe aos sócios. Está como você aprovou na proposta 2; a pergunta é se quer igualar.',
     'Revisão independente do fechamento'),
    ('ES-06, etapa 3: abrir só a revisão de nível mais alto',
     'Hoje a mesma revisão pode abrir juntas a revisão da estratégia, a do portfólio e a dos alvos, e as três rodam em paralelo. Com a mudança, a estratégia puxa o portfólio, que puxa os alvos.',
     'Revisão independente do fechamento'),
    ('Avisos e nomes: os ramos “manter” avisam quem abriu a revisão; as três “Decisão de rever…” da ES-06 passam a “Revisão aberta…”; o nome do método inclui o critério de desvio grave; captação e novo sócio ganham ramo na ES-05 ou saem da tabela de fronteiras',
     'São acertos leves de texto e de aviso, sem mudança de quem decide.',
     'Revisão independente do fechamento · leve'),
]

ALERTAS = [
    ('Integração como PMO corporativo', 'A definição pede, no círculo 6, as jornadas de carteira de projetos internos e externos, a execução de mandato de empresa e a coordenação de lançamento de oferta. A ES-03, a ES-04 e a ES-05 já contam com elas.'),
    ('Plano de saída', 'O plano de saída de clientes, contratos e pessoas (ES-05) e o de clientes e contratos de oferta encerrada (ES-04) são pedidos à Integração, que coordena Relações, Negócios, Operações, Governança e Gestão. Viram requisito dos círculos 4 a 9. A Integração como dona do plano e a data de saída decidida pela Estratégia com o executivo são escolhas do desenho para a proposta 10 funcionar: falta a sua confirmação.'),
    ('Alçadas e sócios', 'Faltam as alçadas que separam a decisão da Estratégia da decisão dos sócios, por recursos e por tipo de decisão (encerrar oferta em uso, virar empresa própria, contrariar o portfólio-alvo aprovado), e quem são os sócios em cada caso: os do Ecossistema ou os de cada empresa. Fica para o círculo 9.'),
    ('Cadências', 'Ciclo estratégico, período de resultado, ciclo de alvos e revisão da estratégia continuam “a definir”. Sem base, não propus número.'),
    ('Método de estratégia', 'Tem lugar no desenho (ES-01) e passa a ser aprovado pelos sócios, mas o conteúdo ainda não foi escrito: critérios dos portões, regras de realocação, critério de desvio grave e calendário.'),
]

# ------------------------------------------------ relação com o catálogo da rodada 2
MUDANCAS = [
    ('Ajustado', 'C1 · Da estratégia ao resultado', 'ES-01, ES-03 e ES-06',
     'Dividida em formular, desdobrar e acompanhar. O ritual de acompanhamento (W-C1.4) continua na Gestão.'),
    ('Ajustado', 'E4 · Do resultado da empresa à decisão do Ecossistema', 'ES-02',
     'Vira revisão do portfólio e realocação de recursos. Executar a decisão (W-E4.3) fica na Gestão; levar as lições ao catálogo (W-E4.4), na Inteligência.'),
    ('Ajustado', 'I-ES1 · Da ideia à aposta priorizada', 'ES-04',
     'Vira decisão por portões. A revisão da carteira (W-ES1.4) passa à ES-02, que só pede o estudo de saída; quem decide é o portão.'),
    ('Ajustado', 'W-V1.6 · Decidir o lançamento, dentro da V1', 'ES-04',
     'O lançamento vira o segundo portão. A V1 continua liderada pela Inteligência.'),
    ('Ajustado', 'E5 · Da aposta à empresa nova', 'ES-05',
     'Passa a cobrir também aquisição, venda e encerramento. Constituir e registrar (W-E5.3) fica na Governança; ligar aos círculos (W-E5.5), na Integração.'),
    ('Ajustado', 'Decisão D4: a Estratégia decide a aposta que entra e a oferta que é lançada', 'ES-04',
     'Mantida, com um limite: a Estratégia decide com o executivo dentro da alçada; acima dela, decidem os sócios.'),
    ('Acrescentado', 'Sem equivalente', 'Portfólio-alvo, hipóteses e método de estratégia',
     'Três produtos novos da ES-01. O portfólio-alvo é a referência da ES-02; as hipóteses e os sinais são o que a ES-06 acompanha; o método traz os critérios dos portões e as regras de realocação.'),
    ('Acrescentado', 'Sem equivalente', 'Escolhas de cada círculo',
     'Na ES-01, etapa 3, cada líder de círculo propõe o que é serviço comum, o que construir e o que comprar.'),
    ('Acrescentado', 'Sem equivalente', 'Ponto de conferência com a identidade',
     'Da ES-01 à ES-05, o agente confere as propostas com os padrões da Identidade, uma pessoa decide se são coerentes e o caso de fronteira vira consulta à ID-02.'),
    ('Acrescentado', 'Sem equivalente', 'Raia e parte “Líder do círculo”',
     'Papel novo no vocabulário do modelo: na ES-01 e na ES-03, cada líder de círculo propõe as escolhas e os alvos do seu círculo.'),
    ('Ajustado', 'ES-01, etapa 3: o executivo decidia as escolhas da empresa', 'A Estratégia formula; o executivo e o líder propõem',
     'A divergência sem acordo sobe aos sócios, e a decisão deles é incorporada ao texto e aprovada por pessoa, na etapa 5, antes de publicar. Proposta 1, aprovada às 20:02.'),
    ('Ajustado', 'ES-01, etapa 1: o diagnóstico usava a leitura no mesmo passo em que a pedia', 'Espera a leitura da Inteligência ou o aviso de leitura sem novidade',
     'A empresa nova usa a estratégia vigente e passa pela conferência de identidade; manter a estratégia gera aviso. Proposta 2, aprovada às 20:02.'),
    ('Ajustado', 'ES-01, etapas 2 a 5: método e hipóteses fora da aprovação', 'Os sócios aprovam também as hipóteses e o método',
     'O método vai também à Inteligência, aos líderes dos círculos, à Gestão, à Integração e à Governança. Proposta 3, aprovada às 20:02.'),
    ('Ajustado', 'ES-02, etapa 2: a revisão podia terminar sem ir aos sócios', 'A proposta sobe sempre aos sócios',
     'Vale também para manter a alocação e para o destino do resultado. A decisão de manter também é comunicada, e a jornada passa a ter um fim só. Proposta 4, aprovada às 20:02.'),
    ('Ajustado', 'ES-02, etapa 4: portfólio-alvo atualizado só para a ES-04 e os executivos', 'Mesmos destinos da ES-01',
     'A alocação que muda alvos ou orçamento abre a ES-03. Proposta 5, aprovada às 20:02.'),
    ('Ajustado', 'ES-03, etapas 2 e 3: a Inteligência conferia o indicador antes de a ficha existir', 'A ES-03 pede as fichas à IN-04 e espera',
     'A ES-03 negocia antes e pede só as fichas dos alvos novos ou alterados. O que não cabe nos recursos e não tem acordo sobe aos sócios com as alternativas. Proposta 6, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-03: inícios “Nova estratégia publicada” e “Portfólio de empresas atualizado”',
     'Os alvos deixam de valer até o próximo ciclo quando a estratégia ou o portfólio mudam. Quando o início é estratégia nova ou empresa nova, o desdobramento espera a alocação. Proposta 7, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-04: caminho de revisão da aposta',
     'Inícios para a aposta devolvida pela Inteligência, a revisão pedida, o caso arquivado e a retomada; a avaliação usa os indicadores e o gasto realizado; a revisão pode terminar em “segue como está”; a decisão da revisão vai também à Inteligência e à Gestão. Proposta 8, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, etapas 3 e 4: “empresa própria” escolhida por automação depois do portão', 'Decidida no portão, por pessoa',
     'O caso nascido de aposta e arquivado na ES-05 volta à ES-04. Proposta 9, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-04, etapa 4: encerramento de aposta em desenvolvimento ou de oferta em uso',
     'A decisão de encerrar sai no portão, para parar o desenvolvimento e as novas vendas. Na etapa nova, a Integração coordena o plano de saída de clientes e contratos; a Estratégia o confere, decide a data de saída com o executivo, pede a retirada da marca própria e confere a saída no fim. A retomada da aposta em espera fica só na ES-04. Proposta 10, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, ES-05 e ES-06: a resposta da Inteligência era esperada sem pergunta', 'Pergunta de decisão explícita e espera da resposta',
     'A IN-02 começa por uma pergunta. A espera aceita também a pergunta devolvida. Na ES-06 sai a raia da Inteligência. Proposta 11, aprovada às 20:02.'),
    ('Ajustado', 'ES-04, última etapa: oferta aprovada sem dono do lançamento', 'A Integração coordena o lançamento, com o executivo',
     'O pacote é entregue só pela IN-07, e a decisão do portão vai também à Integração. Proposta 12, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-05, etapa 2: autorização dos sócios para negociar, com limites',
     'A apuração vale também para o encerramento; o contrato é preparado pela Governança e assinado antes do mandato; há um só aviso de caso arquivado, e a lição sai sem dado sigiloso. Proposta 13, aprovada às 20:02.'),
    ('Ajustado', 'ES-05, etapas 5 e 6: marca pedida duas vezes e sem data; execução e conferência na mesma etapa', 'Um pedido com data de efeito; executar (etapa 7) separado de conferir (etapa 8)',
     'O plano de saída, coordenado pela Integração, volta e é conferido antes de fechar o mandato, que vai também a Negócios, Operações e Inteligência. Proposta 14, aprovada às 20:02.'),
    ('Ajustado', 'ES-06: três painéis e comparações refeitas', 'Painel único, com as comparações da Inteligência e da Gestão',
     'As correções de execução ficam separadas das revisões que só os sócios decidem; a prestação de contas é aprovada por pessoa. Proposta 15, aprovada às 20:02.'),
    ('Ajustado', 'ES-02 a ES-05: conferência de identidade sem decisão', 'Decisão e consulta à Identidade, como na ES-01',
     'Na ES-04, a incoerência fica registrada na avaliação e impede a recomendação de avançar. Proposta 16, aprovada às 20:02.'),
    ('Ajustado', 'Nomes “Oferta aprovada no portfólio” e “Indicação de saída”', '“Oferta aprovada para lançamento” e “Estudo de saída pedido”',
     'Fusão e cisão saem do objetivo da ES-05 e viram limite declarado. Proposta 17, aprovada às 20:02.'),
    ('Acrescentado', 'Sem equivalente', 'ES-06, etapa 2: decisão da contestação de indicador de alvo vigente',
     'A Estratégia mantém a ficha ou abre a correção do alvo, e a resposta volta à IN-04. Proposta 18, aprovada às 20:02.'),
]

LIMITES = [
    'Os fluxos são descritivos. Para executar falta escolher o motor e ligar cada tarefa a um sistema.',
    'Não há tempo, volume nem carga por pessoa: nada disso foi medido, então nada foi estimado.',
    'Nenhuma cadência foi fixada: ciclo estratégico, período de resultado, ciclo de alvos e revisão da estratégia estão como “a definir”.',
    'O método de estratégia tem lugar no desenho (ES-01), mas o conteúdo ainda não foi escrito: critérios dos portões, regras de realocação, critério de desvio grave e calendário.',
    'As alçadas que separam a decisão da Estratégia da decisão dos sócios ainda não existem; serão definidas no círculo 9, Governança.',
    'A raia “Sócios” não distingue os sócios do Ecossistema dos sócios de cada empresa. Quem delibera o quê fica para o círculo 9.',
    'Fusão e cisão de empresas não estão desenhadas: a ES-05 cobre criação, aquisição, venda e encerramento.',
    'O plano de saída de clientes, contratos e pessoas é pedido à Integração e conferido pela Estratégia; como ele é montado só será desenhado nos círculos 4 a 9.',
    'A retirada de marca é pedida com data de efeito, mas a ID-03 ainda não trata essa data: depende de proposta pendente no círculo 1.',
    'Quando uma mensagem pode tanto retomar uma jornada em espera quanto abrir outra (a alocação que chega à ES-03, a decisão do portão que chega à IN-07), a correlação fica para o motor de execução.',
    'Um laço de volta refaz a etapa inteira: o desenho não marca o que já foi feito na passagem anterior.',
    'As esperas por outro círculo (plano de saída, fichas dos indicadores, resposta da Inteligência) não têm prazo desenhado.',
    'Na venda decidida sem comprador, a busca do comprador não está desenhada: o mandato a descreve, e a oportunidade volta à ES-05 quando houver comprador.',
    'A ES-04 registra a incoerência com a identidade na avaliação e não recomenda avançar; a decisão do portão continua sendo de pessoas.',
    'As ofertas de uma empresa adquirida não têm caminho desenhado até o catálogo de ofertas.',
    'As trocas com a Identidade e a Inteligência foram conferidas dos dois lados. Com os outros seis círculos, estão descritas pelo nome do círculo e serão conferidas quando cada um for desenhado.',
    'As conferências feitas por outros círculos não têm ramo de recusa desenhado: a recusa devolve o trabalho à tarefa anterior.',
    'Os números descrevem este desenho, não a operação atual.',
]

REVISAO_TXT = [
    'Um revisor independente leu a primeira versão das seis jornadas e apontou 33 achados, 6 graves. Todos foram tratados antes do fechamento das 15:48; os que dependiam de escolha sua viraram pontos para decidir.',
    'Um segundo revisor reabriu as dez fontes deste círculo: sete confirmadas e três confirmadas em parte. As correções de redação foram aplicadas na aba Fontes.',
    'Depois do fechamento, um terceiro revisor independente leu a versão fechada junto com os círculos 1 e 3 e apontou 30 achados, 4 graves. Vinte e oito viraram 17 propostas, e a décima oitava veio do cruzamento com o círculo 3. Você aprovou as 18 às 20:02.',
    'Em 02/10/2026, um quarto revisor independente leu a versão com as 18 mudanças aplicadas: 13 aplicadas por inteiro, 4 em parte e 1 além do aprovado, com 25 achados, 2 graves. Os dois graves e os demais defeitos da aplicação foram corrigidos; a extensão da regra do executivo à ES-02, à ES-04 e à ES-06 foi desfeita e virou proposta; o que mudava conteúdo que você já tinha fechado virou as cinco propostas da aba Decisões.',
    'Dois verificadores independentes conferiram as correções em seguida. O primeiro achou 10 defeitos criados por elas, 1 grave (a ES-03 podia ficar parada à espera da alocação), todos tratados. O segundo não confirmou nenhum grave e apontou 4 defeitos médios neste círculo, também tratados. Esses últimos acertos passaram por todos os testes automáticos, mas não por nova revisão independente.',
]
