
# ========================================================== REGRAS E DECISÕES
JORNADAS.append(dict(
    code='GO-01',
    nome='Manter as regras, as políticas e as alçadas de pessoas e agentes',
    dominio='Regras e decisões', classe='essencial', onda=1,
    objetivo='Fazer cada regra, política, alçada de pessoa ou de agente, regra de sigilo e de dados pessoais, regra de guarda, critério de rateio e modelo de proposta e de contrato nascer de um pedido, de uma decisão dos sócios ou de uma causa achada pela conformidade; ser redigida ouvidos os donos e, no rateio, a Estratégia; ser decidida pela Governança, dentro da sua alçada, ou pelos sócios; e ser publicada, versionada, a quem a usa. A Governança redige e publica; os sócios decidem as regras gerais e as alçadas dos executivos.',
    frequencia='Por evento: pedido, decisão dos sócios, mudança no catálogo de dados, contestação ou causa achada pela conformidade; e a cada revisão periódica (cadência: anual, e por evento)',
    automacao=('média', 'Registrar, levantar o que vale, redigir, versionar e publicar são de agente e automação; revisar o risco jurídico e decidir dentro da alçada são de pessoa da Governança; as regras gerais, dos sócios.'),
    base=['apqc', 'lgpd'],
    lanes=['SOL', 'SOC', 'EST', P, A, R],
    inicios=[I('Regra, alçada, critério ou modelo pedido', 'SOL', 'message'),
             I('Revisão periódica das regras iniciada', R, 'timer'),
             I('Decisão dos sócios ou causa da conformidade recebida', R, 'message')],
    fins=[F('Regras vigentes publicadas', R),
          F('Regra mantida, com o motivo avisado a quem pediu', R)],
    etapas=[
        E('Receber o pedido e levantar o que vale', 'Governança', 'Autopiloto', 'baixo',
          [('Pedido de regra, de alçada ou de modelo', 'Solicitante'), (DEC_CRIT, 'Identidade'), (USO_MARCA, 'Identidade'),
           (DEC_ESTRAT, 'Estratégia'), (METODO_EST, 'Estratégia'), (PORTFOLIO, 'Estratégia'), (CAT_DADOS, 'Inteligência'),
           (DADO_RET, 'Inteligência'), (CONTESTACAO, 'Gestão'), (REGRA_REVER, 'GO-03')],
          [T('Registrar o pedido e as regras, as alçadas e os modelos afetados', R),
           T('Levantar a lei, os contratos e as decisões dos sócios que valem', A)],
          [('Pedido de regra analisado', ['etapa 2'])]),
        E('Redigir e decidir a regra', 'Governança, pela lista de matérias; as regras gerais, as alçadas dos executivos e as da própria Governança, os sócios', 'Copiloto', 'médio',
          [('Pedido de regra analisado', 'etapa 1')],
          [T('Redigir a regra, a alçada, o critério ou o modelo, ouvidos os donos', A),
           T('Revisar a redação e o risco jurídico', P),
           D('Quem decide, pela lista de matérias aprovada pelos sócios?', R,
             [S('A Governança: regra que aplica regra geral aprovada, modelo de proposta ou de contrato, sigilo, dados e guarda, alçada de pessoas de outro círculo, matriz no apetite ou amostra', 'seg',
                via=[T('Decidir a regra dentro da alçada da Governança', P)]),
              S('A Governança, com a Estratégia: critério de rateio', 'seg',
                via=[T('Definir o critério de rateio com a Governança', 'EST'),
                     T('Decidir o critério de rateio', P)]),
              S('Os sócios: regra geral, alçada dos executivos, exceção, alçada da Governança ou das pessoas da Governança, limites dos agentes', 'seg',
                via=[T('Levar a regra à decisão dos sócios', P),
                     T('Decidir a regra', 'SOC')])]),
           D('A regra foi aprovada?', P,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Manter a regra vigente e avisar quem pediu, com o motivo', R)])])],
          [('Regra decidida', ['etapa 3'])]),
        E('Publicar as regras vigentes', 'Governança', 'Autômato', 'baixo',
          [('Regra decidida', 'etapa 2')],
          [T('Versionar e publicar as regras, as alçadas, os critérios e os modelos', R),
           T('Avisar os donos do que mudou', R)],
          [(ALCADAS, [TODOS]),
           (SIGILO, [TODOS]),
           (GUARDA, ['Inteligência']),
           (RATEIO_CRIT, ['Gestão']),
           (MODELOS, ['Negócios'])]),
    ]))

JORNADAS.append(dict(
    code='GO-02',
    nome='Secretariar as decisões dos sócios e cumprir os atos societários',
    dominio='Regras e decisões', classe='essencial', onda=1,
    objetivo='Fazer cada matéria que vai aos sócios chegar completa e dentro das regras, numa pauta convocada; cada decisão ser registrada em ata, com votos, responsável e prazo; cada ato societário (constituição, alteração ou encerramento de empresa) ser registrado nos órgãos; e cada decisão ter o cumprimento acompanhado e cobrado. Os círculos levam as matérias; os sócios decidem; a Governança secretaria, registra e acompanha.',
    frequencia='No calendário dos sócios (cadência: trimestral, e por evento) e por evento: matéria levada à decisão',
    automacao=('média', 'Registrar a matéria, conferir se está completa, lavrar a ata e acompanhar o cumprimento são de agente e automação; fechar a pauta, conferir a ata e fazer os registros são de pessoa da Governança; decidir é dos sócios.'),
    base=['apqc'],
    lanes=['SOL', 'SOC', P, A, R],
    inicios=[I('Matéria para decisão dos sócios recebida', 'SOL', 'message'),
             I('Reunião dos sócios do calendário', R, 'timer')],
    fins=[F('Decisões registradas e cumprimento acompanhado', R)],
    etapas=[
        E('Montar a pauta e preparar as matérias', 'Governança', 'Copiloto', 'baixo',
          [('Matéria para decisão dos sócios', 'Solicitante'), (METODO_EST, 'Estratégia')],
          [T('Registrar a matéria, quem a propõe e o prazo', R),
           T('Conferir se a matéria está completa e dentro das regras', A),
           D('A matéria está completa e dentro das regras?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Decidir a devolução da matéria, com o que falta', P),
                                   T('Devolver a matéria a quem propôs, com o que falta', R)])]),
           T('Fechar a pauta e convocar os sócios', P)],
          [('Pauta e matérias preparadas', ['etapa 2'])]),
        E('Registrar as decisões dos sócios', 'Sócios decidem; a Governança registra', 'Assistido', 'médio',
          [('Pauta e matérias preparadas', 'etapa 1'), (DEC_REG_ID, 'Identidade'), (DEC_CRIT, 'Identidade'),
           (DEC_ESTRAT, 'Estratégia'), (DIAG, 'Estratégia'), (DEC_SOCIOS, 'Estratégia'), (DEC_ALOC, 'Estratégia'),
           (DEC_PORTAO, 'Estratégia'), (AUTORIZ, 'Estratégia'), (DEC_EMPRESA, 'Estratégia'), (ARQUIVADO, 'Estratégia'),
           (REV_EST, 'Estratégia')],
          [D('A decisão já foi tomada na jornada dona?', R,
             [S('Sim', 'seg', via=[T('Juntar a decisão já tomada ao livro de atas', R)]),
              S('Não: matéria da pauta', 'seg', via=[T('Decidir as matérias da pauta', 'SOC'),
                                                    T('Lavrar a ata com as decisões, os votos, os responsáveis e os prazos', A)])]),
           T('Conferir a ata e colher as assinaturas', P)],
          [('Decisões dos sócios registradas, com responsável e prazo', ['Executivos', 'Líderes dos círculos', 'etapa 3'])]),
        E('Cumprir os atos societários e acompanhar as decisões', 'Governança', 'Copiloto', 'médio',
          [('Decisões dos sócios registradas, com responsável e prazo', 'etapa 2'), (MANDATO, 'Estratégia'),
           (PORTFOLIO, 'Estratégia'), (CONTR_CV, 'Estratégia'), (APORTES, 'Gestão')],
          [D('A decisão pede ato societário fora de um mandato?', A,
             [S('Não, ou o ato é do mandato e é registrado na ES-05', 'seg'),
              S('Sim', 'seg', via=[T('Registrar a alteração societária nos órgãos', P)])]),
           T('Acompanhar o cumprimento de cada decisão e cobrar o responsável', R),
           T('Conferir o cumprimento e apontar aos sócios o que atrasou', P)],
          [('Situação do cumprimento das decisões dos sócios', ['Sócios', 'Executivos'])]),
    ]))

JORNADAS.append(dict(
    code='GO-03',
    nome='Gerir os riscos, a conformidade e os controles internos',
    dominio='Riscos e conformidade', classe='essencial', onda=1,
    objetivo='Fazer os riscos de cada círculo, empresa, oferta, contrato e agente serem reunidos, avaliados pela matriz e tratados por decisão; os controles internos e a conformidade serem testados; cada falha de controle ou não conformidade virar plano de remediação com dono e prazo e, quando a causa pede, regra nova ou revista; e o relatório de riscos e conformidade ir aos sócios e à Estratégia. A Governança avalia, testa e relata; os donos tratam os riscos e remediam.',
    frequencia='A cada ciclo de riscos e conformidade (cadência: trimestral) e por evento: risco, falha de controle ou mudança relevante',
    automacao=('média', 'Reunir, avaliar pela matriz, testar controles e consolidar o relatório são de agente e automação; decidir o tratamento e montar a remediação são de pessoa da Governança, com os donos; o tratamento dos riscos de nota 15 ou mais é dos sócios.'),
    base=['apqc'],
    lanes=['SOC', P, A, R],
    inicios=[I('Ciclo de riscos e conformidade iniciado', R, 'timer'),
             I('Risco, falha de controle ou mudança relevante recebida', R, 'message')],
    fins=[F('Relatório de riscos e conformidade publicado', R)],
    etapas=[
        E('Identificar e avaliar os riscos', 'Governança, com os donos; nota 15 ou mais, os sócios', 'Copiloto', 'médio',
          [(PLANO_LANC, 'Integração'), (SAIDA_CLI, 'Integração'), (AG_SUSPENSO, 'Integração'), (DEMONSTRACOES, 'Gestão'),
           (PORTFOLIO, 'Estratégia'), (LACUNAS_EXEC, 'Identidade'), (PAINEL, 'Inteligência'), (RES_AUDIT, 'GO-06'),
           (RELATOS, 'GO-09'), (CONTRATOS_REG, 'GO-05'), (OBRIG_LEGAIS, 'GO-04'), (REG_TITULARES, 'GO-07'),
           (LICOES_CRISE, 'GO-08')],
          [T('Reunir os riscos de cada círculo, empresa, oferta, contrato e agente', R),
           T('Avaliar probabilidade, impacto e controles de cada risco pela matriz', A),
           T('Decidir o tratamento de cada risco: aceitar, mitigar, transferir ou evitar, com o dono', P),
           D('Algum risco tem nota 15 ou mais na matriz?', R,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Levar aos sócios os riscos de nota 15 ou mais, com a proposta de tratamento', P),
                                    T('Decidir o tratamento dos riscos de nota 15 ou mais', 'SOC')])])],
          [('Riscos avaliados, com o tratamento', ['etapa 2'])]),
        E('Testar os controles e a conformidade', 'Governança', 'Copiloto', 'médio',
          [('Riscos avaliados, com o tratamento', 'etapa 1')],
          [T('Testar os controles internos e a conformidade com a lei e as regras', A),
           T('Conferir os achados dos testes com os donos', P),
           T('Testar uma amostra dos indicadores publicados contra a fonte', A),
           D('Há falha de controle ou não conformidade?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Montar o plano de remediação com o dono, o prazo e a causa', P)])]),
           D('A causa pede regra nova ou revista?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Abrir a revisão da regra', R)])])],
          [(REGRA_REVER, ['GO-01']),
           ('Plano de remediação, com dono e prazo', ['Executivos', 'Líderes dos círculos']),
           ('Resultado dos testes de controle', ['etapa 3'])]),
        E('Relatar os riscos e a conformidade', 'Governança', 'Autopiloto', 'baixo',
          [('Resultado dos testes de controle', 'etapa 2'), ('Remediação executada, com a evidência', 'Executivos'),
           ('Remediação executada, com a evidência', 'Líderes dos círculos')],
          [T('Conferir a evidência das remediações e apontar as vencidas', A),
           T('Consolidar o relatório de riscos, conformidade e remediações', A),
           T('Publicar o relatório aos sócios e à Estratégia', R)],
          [(RELATORIO, ['Estratégia', 'Sócios'])]),
    ]))

JORNADAS.append(dict(
    code='GO-04',
    nome='Manter em dia as obrigações legais: registros, certidões, marcas, procurações e seguros',
    dominio='Riscos e conformidade', classe='essencial', onda=1,
    objetivo='Fazer cada licença, certidão, registro de empresa e de marca, procuração e seguro estar no calendário com o prazo; cada obrigação ser cumprida antes de vencer, com as exigências do órgão atendidas e o indeferimento levado ao executivo; e as certidões e os documentos de habilitação estarem em dia para Negócios. A Governança mantém e cumpre; a Identidade decide a marca.',
    frequencia='Por prazo de cada obrigação e por evento: registro de marca, marca retirada, mandato, compra ou venda de empresa',
    automacao=('alta', 'Manter o calendário, apontar o que vence, preparar o pedido e registrar são de agente e automação; conferir, protocolar e cumprir as exigências são de pessoa da Governança.'),
    base=['apqc'],
    lanes=['SOL', P, A, R],
    inicios=[I('Prazo de obrigação legal próximo', R, 'timer'),
             I('Registro, documento ou certidão pedido', 'SOL', 'message')],
    fins=[F('Obrigação cumprida e registrada', R),
          F('Obrigação indeferida, levada ao executivo', R)],
    etapas=[
        E('Manter o calendário de obrigações', 'Governança', 'Autopiloto', 'baixo',
          [('Pedido de documento, registro ou certidão', 'Solicitante'), (REGISTRO_MARCA, 'Identidade'),
           (MARCA_RET, 'Identidade'), (MANDATO, 'Estratégia'), (PORTFOLIO, 'Estratégia'), (CONTR_CV, 'Estratégia')],
          [T('Registrar licenças, certidões, registros, marcas, procurações e seguros com o prazo', R),
           T('Apontar o que vence, o que falta e o que o mandato ou a marca retirada pedem', A)],
          [('Obrigações a cumprir', ['etapa 2'])]),
        E('Cumprir a obrigação', 'Governança', 'Copiloto', 'médio',
          [('Obrigações a cumprir', 'etapa 1')],
          [T('Preparar o pedido, a renovação, a transferência ou a baixa', A),
           T('Conferir e protocolar no órgão', P),
           D('O órgão deferiu?', P,
             [S('Sim', 'seg'),
              S('Não, com exigência', 'seg', via=[T('Cumprir a exigência do órgão e protocolar de novo', P)]),
              S('Não, indeferido', 'F2', via=[T('Levar o indeferimento ao executivo, com as opções e o efeito na habilitação', R)])]),
           T('Registrar o documento e o novo prazo', R)],
          [(CERTIDOES, ['Negócios']),
           (OBRIG_LEGAIS, ['GO-03'])]),
    ]))
