
# ========================================================== CONTRATOS E AUDITORIA
JORNADAS.append(dict(
    code='GO-05',
    nome='Revisar os contratos, guardá-los e acompanhar prazos e obrigações',
    dominio='Contratos e auditoria', classe='essencial', onda=1,
    objetivo='Fazer cada contrato de cliente, de fornecedor, de tecnologia, de parceria, de oferta conjunta e de compra ou venda de empresa ser comparado com o modelo, ter a cláusula fora dele e o risco revisados e os poderes de quem assina conferidos; ser guardado com partes, prazos, valores e obrigações registrados; e ter cada vencimento e obrigação avisados ao dono com antecedência, com o vencimento sem decisão levado ao executivo. A frente dona origina e negocia o contrato; a Governança revisa, guarda e acompanha.',
    frequencia='Por evento: contrato a revisar ou a guardar; e por prazo de cada vencimento e obrigação',
    automacao=('média', 'Comparar com o modelo, conferir poderes, guardar, registrar e avisar prazos são de agente e automação; revisar cláusulas e riscos, liberar o contrato e conferir o cumprimento são de pessoa da Governança.'),
    base=['apqc', 'cc2002'],
    lanes=['SOL', 'SOC', 'EXE', P, A, R],
    inicios=[I('Contrato para revisar ou guardar recebido', 'SOL', 'message'),
             I('Vencimento ou obrigação de contrato próximo', R, 'timer')],
    fins=[F('Vencimento ou obrigação de contrato acompanhado', R),
          F('Contrato guardado, com as obrigações registradas', R)],
    etapas=[
        E('Revisar o contrato', 'Governança; as matérias da regra 10 dos contratos, os sócios', 'Copiloto', 'médio',
          [(CONTRATO_NEG, 'Negócios'), (ACORDO_CONJ, 'Negócios'), (CONTRATO_TEC, 'Integração'), (CONTRATO_FORN, 'Gestão'),
           (CONTR_CV, 'Estratégia'), (AUT_MARCA, 'Relações'), ('Contrato para revisar ou guardar', 'Solicitante')],
          [D('O que iniciou o trabalho?', R,
             [S('Contrato a revisar', 'seg'),
              S('Contrato já revisado e assinado na jornada dona', 'E2'),
              S('Vencimento ou obrigação próxima', 'E3')]),
           T('Comparar o contrato com o modelo e apontar as cláusulas fora dele', A),
           D('Há cláusula fora do modelo ou risco relevante?', P,
             [S('Não', 'seg'),
              S('Sim, na alçada da Governança', 'seg', via=[T('Revisar a cláusula e o risco e propor a redação', P)]),
              S('Sim, matéria dos sócios: exclusividade, prazo maior que o ciclo, multa acima do modelo, foro ou arbitragem, garantia financeira', 'seg',
                via=[T('Revisar a cláusula e o risco e levar a proposta aos sócios', P),
                     T('Decidir a cláusula que vai aos sócios pela regra dos contratos', 'SOC')])]),
           T('Conferir os poderes de quem assina', A),
           T('Liberar o contrato para assinatura ou para a guarda', P)],
          [('Contrato revisado', ['etapa 2'])]),
        E('Guardar o contrato e registrar as obrigações', 'Governança', 'Autômato', 'baixo',
          [('Contrato revisado', 'etapa 1')],
          [T('Receber o contrato assinado', R, 'receive'),
           T('Guardar o contrato assinado e registrar partes, prazos, valores e obrigações', R),
           D('Há prazo ou obrigação a acompanhar agora?', R,
             [S('Não', 'F2'),
              S('Sim', 'prox')])],
          [(CONTRATOS_REG, ['GO-03', 'etapa 3'])]),
        E('Acompanhar vencimentos e obrigações', 'Governança, com o dono do contrato', 'Copiloto', 'médio',
          [(CONTRATOS_REG, 'etapa 2')],
          [T('Avisar o dono do contrato do vencimento ou da obrigação, com antecedência', R),
           T('Conferir o cumprimento ou a decisão de renovar ou encerrar', P),
           D('O dono cumpriu ou decidiu?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Levar ao executivo o vencimento sem decisão', R),
                                   T('Decidir renovar ou encerrar o contrato vencido sem decisão do dono', 'EXE')])]),
           T('Registrar o cumprimento ou a decisão', R)],
          [('Vencimentos e obrigações de contratos avisados', ['Executivos', 'Líderes dos círculos'])]),
    ]))

JORNADAS.append(dict(
    code='GO-06',
    nome='Auditar se as entregas de pessoas e agentes seguem a identidade e a alçada',
    dominio='Contratos e auditoria', classe='essencial', onda=1,
    objetivo='Fazer uma amostra única de entregas de pessoas e agentes ser sorteada por círculo e por risco e servir à auditoria e à avaliação dos métodos pela Inteligência; cada entrega ser comparada com os critérios e os casos de teste da Identidade e com a alçada; cada caso de fronteira ser julgado pela Identidade e cada não conformidade pela Governança, com a causa achada; cada causa ir a quem corrige (o dono da entrega, a Identidade no padrão ambíguo, a Integração no desvio de agente); e o resultado ser publicado; e a própria Governança ser auditada uma vez por ano por assessoria externa, com as correções decididas pelos sócios. A Identidade define os critérios e julga os casos de fronteira; a Governança sorteia, julga as não conformidades e publica.',
    frequencia='A cada ciclo de auditoria (cadência: trimestral, antes da revisão da execução (ES-06)) e por evento: agente suspenso ou lacuna de execução apontada',
    automacao=('alta', 'Sortear, comparar, classificar, achar a causa provável, calcular o índice e publicar são de agente e automação; julgar os casos, rever a amostra dos conformes e decidir a causa são de pessoa da Governança; uma vez por ano, a assessoria externa audita a própria Governança e os sócios decidem as correções.'),
    base=['apqc'],
    lanes=['IDE', 'ASS', 'SOC', P, A, R],
    inicios=[I('Ciclo de auditoria iniciado', R, 'timer'),
             I('Agente suspenso ou lacuna recebida', R, 'message'),
             I('Ciclo anual de auditoria externa da Governança iniciado', R, 'timer')],
    fins=[F('Resultado da auditoria publicado', R)],
    etapas=[
        E('Sortear a amostra', 'Governança', 'Autômato', 'baixo',
          [(CRITERIOS, 'Identidade'), (REG_ENTREGAS, 'Integração'), (AG_SUSPENSO, 'Integração'), (RESUMO_PAD, 'Identidade'),
           (LACUNAS_EXEC, 'Identidade')],
          [D('O que iniciou a auditoria?', R,
             [S('Ciclo de auditoria', 'seg'),
              S('Agente suspenso ou lacuna apontada', 'seg',
                via=[T('Separar uma amostra dirigida ao agente ou à lacuna', R)]),
              S('Auditoria externa da Governança', 'E4')]),
           T('Sortear a amostra de entregas de pessoas e agentes por círculo e por risco', R),
           T('Registrar a amostra e entregá-la à Inteligência', R)],
          [(AMOSTRA, ['Inteligência', 'etapa 2'])]),
        E('Comparar as entregas com os padrões e a alçada', 'Governança', 'Autopiloto', 'baixo',
          [(AMOSTRA, 'etapa 1'), (PADROES_ID, 'Identidade'), ('Correção feita pelo dono da entrega', 'Líderes dos círculos')],
          [T('Conferir as correções pedidas no ciclo anterior', A),
           T('Comparar cada entrega com os critérios, os casos de teste e a alçada', A),
           T('Separar conformes, não conformes e casos de fronteira', A)],
          [('Entregas classificadas', ['etapa 3'])]),
        E('Julgar os casos e achar a causa', 'Governança', 'Assistido', 'médio',
          [('Entregas classificadas', 'etapa 2')],
          [D('Há casos de fronteira?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Julgar os casos de fronteira', 'IDE')])]),
           T('Rever por amostra as entregas que o agente classificou como conformes', P),
           T('Julgar as não conformidades', P),
           T('Achar a causa provável de cada não conformidade', A),
           D('Há falha de execução?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir a correção ao dono da entrega', R)])]),
           D('Há padrão ambíguo?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Apontar o padrão ambíguo à Identidade', R)])]),
           D('Há desvio de agente?', P,
             [S('Não', 'E5'),
              S('Sim', 'E5', via=[T('Apontar o desvio do agente à Integração', R)])])],
          [(AMBIGUO, ['Identidade']),
           (DESVIO_AG, ['Integração']),
           ('Correção pedida ao dono da entrega', ['Líderes dos círculos']),
           ('Casos julgados, com a causa', ['etapa 5'])]),
        E('Auditar a Governança por assessoria externa', 'Assessoria externa; as correções, os sócios', 'Assistido', 'médio',
          [(REG_ENTREGAS, 'Integração')],
          [T('Separar os registros do ano: entregas, julgamentos e decisões da Governança', R),
           T('Auditar por amostra as entregas, os julgamentos e as decisões da Governança', 'ASS'),
           T('Decidir as correções apontadas pela auditoria externa da Governança', 'SOC')],
          [('Resultado da auditoria externa da Governança, com as correções decididas', ['etapa 5', 'Sócios'])]),
        E('Publicar o resultado da auditoria', 'Governança', 'Autopiloto', 'baixo',
          [('Casos julgados, com a causa', 'etapa 3'), ('Resultado da auditoria externa da Governança, com as correções decididas', 'etapa 4')],
          [T('Calcular o índice de conformidade por círculo e por tipo de entrega', A),
           T('Publicar o resultado da auditoria', R)],
          [(RES_AUDIT, ['Identidade', 'Inteligência', 'GO-03'])]),
    ]))
