
# ========================================================== DADOS, CRISES E RELATOS
JORNADAS.append(dict(
    code='GO-07',
    nome='Responder aos titulares de dados pessoais',
    dominio='Dados, crises e relatos', classe='essencial', onda=1,
    objetivo='Fazer cada pedido de titular de dados ser registrado, com a identidade do titular confirmada antes de qualquer resposta; os dados dele serem localizados no catálogo de dados, com quem os guarda; a resposta ser decidida pela Governança, no papel de encarregada, pelos direitos e pelas bases legais da LGPD, com os motivos informados quando o pedido não procede no todo ou em parte; a execução ser pedida a quem guarda os dados (Relações, na base de relacionamento, e os demais círculos); e o titular receber a resposta depois de conferido o cumprimento. A Governança decide; quem guarda o dado executa.',
    frequencia='Por evento: pedido de titular',
    automacao=('alta', 'Registrar, confirmar a identidade, localizar os dados, propor a resposta, conferir o cumprimento e responder são de agente e automação; decidir a resposta é de pessoa da Governança.'),
    base=['apqc', 'lgpd'],
    lanes=['SOL', P, A, R],
    inicios=[I('Pedido de titular recebido', 'SOL', 'message')],
    fins=[F('Pedido de titular respondido e registrado', R),
          F('Pedido parado, à espera da confirmação da identidade', R)],
    etapas=[
        E('Receber o pedido e localizar os dados', 'Governança', 'Autopiloto', 'baixo',
          [('Pedido de titular de dados', 'Solicitante'), (CAT_DADOS, 'Inteligência')],
          [T('Registrar o pedido, avisar o recebimento e anotar o prazo', R),
           D('A identidade do titular foi confirmada?', A,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Pedir ao titular a confirmação da identidade', R)])]),
           T('Localizar os dados do titular no catálogo de dados e quem os guarda', A)],
          [('Pedido de titular analisado', ['etapa 2'])]),
        E('Decidir a resposta ao titular', 'Governança, como encarregada', 'Copiloto', 'médio',
          [('Pedido de titular analisado', 'etapa 1')],
          [T('Propor a resposta pelos direitos do titular e pelas bases legais do tratamento', A),
           T('Decidir a resposta como encarregada', P),
           D('O pedido procede?', P,
             [S('Sim, no todo ou em parte', 'seg',
                via=[T('Pedir a execução a quem guarda os dados', R)]),
              S('Não', 'E3')])],
          [(TITULAR_RESP, ['Relações']),
           ('Pedido de execução a quem guarda os dados', ['Líderes dos círculos']),
           ('Resposta decidida, com os motivos', ['etapa 3'])]),
        E('Conferir o cumprimento e responder ao titular', 'Governança', 'Autômato', 'baixo',
          [('Resposta decidida, com os motivos', 'etapa 2'), (TITULAR_OK, 'Relações')],
          [D('Há execução a conferir?', R,
             [S('Não: pedido negado', 'seg'),
              S('Sim', 'seg', via=[T('Conferir o cumprimento e o prazo e cobrar quem atrasou', R)])]),
           T('Responder ao titular, com os motivos do que não procede', R),
           T('Registrar o pedido, a resposta e o cumprimento', R)],
          [('Resposta ao titular', ['Solicitante']),
           (REG_TITULARES, ['GO-03'])]),
    ]))

JORNADAS.append(dict(
    code='GO-08',
    nome='Conduzir o comitê de crise, da declaração ao encerramento',
    dominio='Dados, crises e relatos', classe='essencial', onda=1,
    objetivo='Fazer cada alerta de crise de Relações acionar o comitê pelo protocolo, com assento da Identidade; os fatos, o risco jurídico e o dever de comunicar à autoridade serem conferidos, e esse dever levado ao canal próprio; a crise ser declarada ou não, com a posição, o porta-voz e o que pode ser dito decididos pela Governança e aprovados pelo executivo, e a decisão avisada a Relações; a posição ser revista enquanto a crise durar e o encerramento decidido com o executivo; e as lições irem à Identidade e à conformidade. Relações monitora e comunica; a Governança, com o executivo, decide.',
    frequencia='Por evento: alerta de crise',
    automacao=('média', 'Convocar, conferir fatos e obrigações, avisar e consolidar as lições são de agente e automação; decidir a posição e o encerramento são de pessoa da Governança, com o executivo.'),
    base=['apqc'],
    lanes=['REL', 'IDE', 'EXE', P, A, R],
    inicios=[I('Alerta de crise recebido', 'REL', 'message')],
    fins=[F('Crise encerrada e lições registradas', R),
          F('Alerta sem crise declarada, registrado e avisado', R)],
    etapas=[
        E('Acionar o comitê e conferir os fatos', 'Governança, com a Identidade', 'Copiloto', 'alto',
          [(ALERTA_CRISE, 'Relações'), (PROTOCOLO, 'Identidade'), (POSIC, 'Identidade')],
          [T('Convocar o comitê de crise pelo protocolo, com a Identidade', R),
           T('Conferir os fatos, o risco jurídico e o dever de comunicar à autoridade', A),
           T('Avaliar o risco jurídico e o que pode ser dito', P),
           D('Há dever de comunicar à autoridade?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Abrir a comunicação à autoridade no canal próprio', R)])])],
          [('Fatos e riscos conferidos', ['etapa 2']),
           ('Dever de comunicar à autoridade apontado na crise', ['GO-09'])]),
        E('Decidir a declaração, a posição e o porta-voz', 'Governança; o executivo aprova', 'Assistido', 'alto',
          [('Fatos e riscos conferidos', 'etapa 1')],
          [T('Opinar sobre a posição pela identidade e pelo protocolo', 'IDE'),
           T('Propor a declaração, a posição, o porta-voz e o que pode ser dito', P),
           T('Aprovar a decisão do comitê', 'EXE'),
           T('Avisar Relações da decisão do comitê', R),
           D('A crise foi declarada?', P,
             [S('Não', 'F2', via=[T('Registrar o alerta e o motivo de não declarar', R)]),
              S('Sim', 'prox')])],
          [(DECL_CRISE, ['Relações']),
           ('Crise declarada', ['etapa 3'])]),
        E('Acompanhar a crise até encerrar e registrar as lições', 'Governança, com o executivo', 'Copiloto', 'alto',
          [('Crise declarada', 'etapa 2'), (LICOES_CRISE, 'Relações')],
          [T('Acompanhar a crise com o comitê', P),
           D('A crise pode ser encerrada?', P,
             [S('Não', 'E3', via=[T('Rever a posição com o executivo e avisar Relações', P)]),
              S('Sim', 'seg', via=[T('Aprovar o encerramento da crise', 'EXE')])]),
           T('Consolidar as lições e as causas', A)],
          [(DECL_CRISE, ['Relações']),
           (LICOES_CRISE, ['Identidade', 'GO-03'])]),
    ]))

JORNADAS.append(dict(
    code='GO-09',
    nome='Receber relatos, apurar com independência e comunicar às autoridades',
    dominio='Dados, crises e relatos', classe='essencial', onda=1,
    objetivo='Fazer cada relato de conduta, fraude ou descumprimento ser registrado com a identidade de quem relata protegida, classificado e apurado com independência, com a medida decidida com o executivo ou, se ele, a Governança ou um sócio estiver envolvido, pelos sócios não envolvidos; cada incidente ou risco que a lei manda comunicar ser comunicado à autoridade competente pela Governança, salvo o do recall, que a Governança já comunica dentro da OP-07 e aqui só registra; e cada causa ir à conformidade. A Governança recebe, apura e comunica; os donos corrigem.',
    frequencia='Por evento: relato no canal; incidente ou risco a comunicar à autoridade',
    automacao=('média', 'Registrar, propor a classificação, preparar a comunicação e registrar são de agente e automação; confirmar a classificação, apurar e enviar a comunicação são de pessoa da Governança.'),
    base=['apqc', 'lgpd', 'anpd15'],
    lanes=['SOL', 'EXE', 'SOC', P, A, R],
    inicios=[I('Relato recebido no canal', 'SOL', 'message'),
             I('Incidente ou risco a comunicar à autoridade recebido', R, 'message')],
    fins=[F('Relato tratado ou autoridade comunicada, e registrado', R)],
    etapas=[
        E('Receber e classificar o relato ou o incidente', 'Governança', 'Copiloto', 'médio',
          [('Relato de conduta, fraude ou descumprimento', 'Solicitante'), ('Incidente de segurança com dados pessoais', 'Solicitante'),
           (AUTORIDADE, 'Operações'), (REL_RECALL, 'Operações'), ('Dever de comunicar à autoridade apontado na crise', 'GO-08')],
          [T('Registrar o relato ou o incidente, protegendo a identidade de quem relata', R),
           T('Propor a classificação: gravidade e dever de comunicar à autoridade', A),
           T('Confirmar a classificação', P),
           D('O que é preciso fazer?', P,
             [S('Apurar o relato', 'prox'),
              S('Comunicar à autoridade', 'E3'),
              S('Registrar o que já foi comunicado na OP-07', 'E4')])],
          [('Relato ou incidente classificado', ['etapa 2', 'etapa 3'])]),
        E('Apurar o relato e decidir a medida', 'Governança, com o executivo ou os sócios', 'Assistido', 'alto',
          [('Relato ou incidente classificado', 'etapa 1')],
          [T('Apurar os fatos com independência', P),
           D('Quem está envolvido no relato?', P,
             [S('Ninguém da decisão', 'seg', via=[T('Decidir a medida e a correção da causa', 'EXE')]),
              S('O executivo, a Governança ou um sócio', 'seg',
                via=[T('Decidir a medida e a correção da causa pelos sócios não envolvidos', 'SOC')])]),
           D('Há dever de comunicar à autoridade?', P,
             [S('Não', 'E4'),
              S('Sim', 'prox')])],
          [('Relato apurado, com a medida', ['etapa 3', 'etapa 4'])]),
        E('Comunicar à autoridade', 'Governança', 'Copiloto', 'alto',
          [('Relato ou incidente classificado', 'etapa 1'), ('Relato apurado, com a medida', 'etapa 2')],
          [T('Preparar a comunicação à autoridade competente e, no incidente com dados pessoais, ao titular', A),
           T('Conferir e enviar a comunicação no prazo', P)],
          [('Comunicação à autoridade registrada', ['etapa 4'])]),
        E('Registrar e levar a causa à conformidade', 'Governança', 'Autômato', 'baixo',
          [('Relato apurado, com a medida', 'etapa 2'), ('Comunicação à autoridade registrada', 'etapa 3')],
          [T('Registrar o relato, a medida, a comunicação e a causa', R),
           D('Há quem relatou e possa receber resposta?', R,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Responder a quem relatou', R)])])],
          [(RELATOS, ['GO-03']),
           ('Resposta ao relato', ['Solicitante'])]),
    ]))

JORNADAS.append(dict(
    code='GO-10',
    nome='Apurar e publicar o relato anual de impacto',
    dominio='Dados, crises e relatos', classe='recomendada', onda=2,
    objetivo='Fazer que, a cada ano, os temas e os indicadores de impacto sejam escolhidos pela definição da Identidade; os dados sejam coletados no catálogo de dados e analisados com avanços e lacunas; e o relato seja redigido na voz do Ecossistema, validado com os dados e o risco jurídico, aprovado pelos sócios e publicado. A Identidade define o que conta como impacto; a Governança apura e publica.',
    frequencia='Anual',
    automacao=('média', 'Propor temas, coletar, analisar, redigir e publicar são de agente e automação; decidir os temas e validar são de pessoa da Governança; aprovar é dos sócios.'),
    base=['apqc'],
    lanes=['SOC', P, A, R],
    inicios=[I('Ciclo anual do relato de impacto iniciado', R, 'timer')],
    fins=[F('Relato de impacto publicado', R)],
    etapas=[
        E('Definir os temas e os indicadores', 'Governança', 'Copiloto', 'baixo',
          [(IMPACTO_DEF, 'Identidade'), (PAINEL, 'Inteligência')],
          [T('Propor os temas e os indicadores de impacto do ano pela definição', A),
           T('Decidir os temas e os indicadores', P)],
          [('Temas e indicadores do relato', ['etapa 2'])]),
        E('Coletar e analisar os dados', 'Governança', 'Autopiloto', 'baixo',
          [('Temas e indicadores do relato', 'etapa 1'), (DADO_OK, 'Inteligência')],
          [T('Coletar os dados dos indicadores no catálogo de dados', R),
           T('Analisar o impacto e apontar avanços e lacunas', A)],
          [('Análise do impacto', ['etapa 3'])]),
        E('Redigir o relato, validá-lo e publicá-lo', 'Governança; os sócios aprovam', 'Copiloto', 'médio',
          [('Análise do impacto', 'etapa 2'), (POSIC, 'Identidade')],
          [T('Redigir o relato na voz do Ecossistema', A),
           T('Validar o relato com os dados e o risco jurídico', P),
           T('Aprovar o relato', 'SOC'),
           D('Os sócios aprovaram o relato?', P,
             [S('Sim', 'seg'),
              S('Não, com ajustes', 'E3', via=[T('Registrar os ajustes pedidos pelos sócios', R)])]),
           T('Publicar o relato', R)],
          [('Relato de impacto publicado', ['Públicos externos', TODOS])]),
    ]))
