
# ========================================================== CAPACIDADE E ENTREGA
JORNADAS.append(dict(
    code='OP-01',
    nome='Planejar a capacidade de entrega de cada oferta e cobrir as faltas',
    dominio='Capacidade e entrega', classe='essencial', onda=1,
    objetivo='Fazer a capacidade de pessoas, agentes, parceiros, materiais e ativos acompanhar a demanda prevista: cada oferta lançada, mudada ou retirada, cada previsão de vendas, ata, parceria e mandato traduzidos em trabalho; cada falta coberta (remanejar, contratar, usar parceiro, automatizar ou recusar) por decisão de Operações ou, acima da alçada, do executivo; e um plano publicado, usado para confirmar propostas, implantações e lançamentos. Operações planeja e decide; a Gestão contrata e compra; a Integração cria a capacidade que falta.',
    frequencia='A cada ciclo de planejamento (cadência: trimestral) e por evento: previsão de vendas, oferta aprovada, lançada ou retirada, parceria ativa ou mandato de empresa',
    automacao=('alta', 'Reunir, traduzir a demanda em trabalho, comparar com a capacidade e pedir recursos são de agente e automação; decidir o plano é de pessoa de Operações; o que passa da alçada é do executivo.'),
    base=['apqc'],
    lanes=['NEG', 'INT', 'EST', 'ITG', 'REL', 'GES', 'EXE', P, A, R],
    inicios=[I('Ciclo de planejamento da capacidade iniciado', R, 'timer'),
             I('Previsão de vendas ou ata recebida', 'NEG', 'message'),
             I('Oferta, parceria ou mandato que muda a capacidade recebido', R, 'message')],
    fins=[F('Plano de capacidade decidido e publicado', R)],
    etapas=[
        E('Reunir a demanda prevista e o que cada oferta exige', 'Operações', 'Autopiloto', 'baixo',
          [(PREVISAO, 'Negócios'), (ATA, 'Negócios'), (OFERTA_CAT, 'Inteligência'), (OFERTA_FORA, 'Inteligência'),
           (PAINEL, 'Inteligência'), (OFERTA_LANC, 'Estratégia'), (MANDATO, 'Estratégia'), (PLANO_LANC, 'Integração'),
           (OFERTA_LANCADA, 'Integração'), (CATALOGO, 'Integração'), (PARCERIA, 'Relações'), (RECURSOS_OK, 'Gestão')],
          [T('Reunir previsão de vendas, atas, ofertas, lançamentos, parcerias, mandatos e recursos confirmados', R),
           T('Traduzir a demanda prevista em trabalho por oferta, perfil e recurso', A),
           T('Comparar a demanda com a capacidade de pessoas, agentes, parceiros e ativos', A)],
          [('Demanda e capacidade comparadas, com as faltas e as sobras', ['etapa 2'])]),
        E('Decidir como cobrir as faltas e usar as sobras', 'Operações; acima da alçada, o executivo', 'Copiloto', 'médio',
          [('Demanda e capacidade comparadas, com as faltas e as sobras', 'etapa 1'), (ALCADAS, 'Governança')],
          [T('Propor como cobrir cada falta: remanejar, contratar, usar parceiro, automatizar ou recusar', A),
           D('A cobertura cabe na alçada de Operações?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Decidir a cobertura acima da alçada de Operações', 'EXE')])]),
           T('Decidir o plano de capacidade do ciclo', P)],
          [('Plano de capacidade decidido', ['etapa 3'])]),
        E('Pedir os recursos e publicar o plano', 'Operações', 'Autômato', 'baixo',
          [('Plano de capacidade decidido', 'etapa 2')],
          [D('O plano pede capacidade nova, agente ou automação?', R,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Pedir à Integração a capacidade nova ou mudada', R)])]),
           T('Pedir à Gestão as pessoas, as compras e os ativos do plano', R),
           T('Publicar o plano e o mapa de capacidade usados para confirmar propostas e implantações', R)],
          [(PLANO_CAP, ['Gestão', 'Executivos', 'OP-06']),
           (NEC_CAP, ['Integração'])]),
    ]))

JORNADAS.append(dict(
    code='OP-02',
    nome='Entregar o serviço a cada cliente, ciclo a ciclo',
    dominio='Capacidade e entrega', classe='essencial', onda=1,
    objetivo='Fazer cada cliente implantado ter um plano de entrega com escopo, nível de serviço, equipe, agentes e contatos; cada entrega feita pelo método da oferta, conferida contra o escopo e o padrão e aceita pelo cliente; cada ciclo confirmado conforme o contrato, com a medição dos níveis de serviço, e passado à Gestão para faturar; cada impasse sobre a entrega virar reclamação tratada; e cada plano de recuperação de Relações virar ajuste do plano de entrega. Operações entrega; o cliente aceita; a Gestão fatura.',
    frequencia='Por cliente: ao receber o cliente implantado (novo, renovado ou ampliado) ou o plano de recuperação, e a cada ciclo de entrega do contrato (cadência do contrato)',
    automacao=('alta', 'Programar, conferir, confirmar e registrar são de agente e automação; a entrega é de pessoa ou de agente, conforme o método da oferta; aprovar o plano e corrigir a entrega são de pessoa de Operações.'),
    base=['apqc', 'l14133'],
    lanes=['ITG', 'REL', 'CLI', P, A, R],
    inicios=[I('Cliente implantado recebido', 'ITG', 'message'),
             I('Plano de recuperação do cliente recebido', 'REL', 'message'),
             I('Ciclo de entrega do cliente iniciado', R, 'timer')],
    fins=[F('Ciclo de entrega confirmado, passado a faturar e registrado', R)],
    etapas=[
        E('Assumir o cliente e planejar a entrega', 'Operações', 'Copiloto', 'médio',
          [(CLI_IMPL, 'Integração'), (PLANO_IMPL, 'Integração'), (CONTRATO, 'Negócios'), (TABELA, 'Negócios'),
           (PLANO_SUC, 'Relações'), (PLANO_REC, 'Relações'), (CX, 'Relações'), (OFERTA_CAT, 'Inteligência'),
           (METODO_PUB, 'Inteligência'), (PACOTE_MARCA, 'Identidade'), (MARCA_RET, 'Identidade'), (PROCED, 'OP-05')],
          [D('O que iniciou a entrega?', R,
             [S('Cliente implantado, novo, renovado ou ampliado, ou plano de recuperação', 'seg'),
              S('Ciclo de entrega de cliente já assumido', 'E2')]),
           T('Conferir o escopo vendido, os termos e o nível de serviço do contrato', A),
           T('Montar ou ajustar o plano de entrega: entregas, nível de serviço, equipe, agentes e contatos', A),
           T('Aprovar o plano de entrega e designar o responsável pelo cliente', P)],
          [('Plano de entrega do cliente', ['etapa 2'])]),
        E('Executar as entregas do ciclo', 'Operações', 'Copiloto', 'médio',
          [('Plano de entrega do cliente', 'etapa 1'), (BASE_PUB, 'Inteligência'), (PADROES_ID, 'Identidade')],
          [T('Programar as entregas do ciclo e alocar pessoas, agentes e parceiros', A),
           PAR([T('Executar as entregas feitas por agentes e automações', A)],
               [T('Executar as entregas feitas por pessoas', P)]),
           T('Conferir cada entrega contra o escopo e o padrão de qualidade', A),
           D('A entrega passou na conferência?', A,
             [S('Sim', 'prox'),
              S('Não', 'E2', via=[T('Corrigir a entrega e registrar a não conformidade', P)])])],
          [('Entregas do ciclo conferidas', ['etapa 3'])]),
        E('Confirmar a entrega com o cliente e passar a faturar', 'Operações, com o aceite do cliente', 'Copiloto', 'médio',
          [('Entregas do ciclo conferidas', 'etapa 2')],
          [T('Aceitar as entregas do ciclo', 'CLI'),
           D('O cliente aceitou as entregas?', P,
             [S('Sim', 'seg'),
              S('Não, com correção possível', 'E2', via=[T('Registrar o motivo da recusa e replanejar a entrega', A)]),
              S('Não, sem acordo sobre a entrega', 'E4', via=[T('Abrir a reclamação sobre a entrega não aceita', R)])]),
           T('Confirmar a entrega conforme os termos do contrato e medir os níveis de serviço do ciclo', R)],
          [(FATURAR, ['Gestão']),
           ('Entrega do ciclo confirmada', ['etapa 4']),
           ('Entrega não aceita, com a reclamação aberta', ['etapa 4']),
           (RECL_REG, ['OP-04'])]),
        E('Registrar o ciclo e apontar o que ensina', 'Operações', 'Autopiloto', 'baixo',
          [('Entrega do ciclo confirmada', 'etapa 3'), ('Entrega não aceita, com a reclamação aberta', 'etapa 3')],
          [T('Registrar entregas, prazos, não conformidades e esforço do ciclo', R),
           T('Apontar a lição do ciclo e os sinais de ampliação ou de risco do cliente', A)],
          [(REG_OP, ['Inteligência']),
           (REG_CLI, ['Relações']),
           (LICAO_AP, ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='OP-08',
    nome='Encerrar as entregas no fim do contrato ou na saída da oferta ou da empresa',
    dominio='Capacidade e entrega', classe='essencial', onda=1,
    objetivo='Fazer cada contrato encerrado e cada saída de oferta ou de empresa virar um fim de entregas planejado: no fim do contrato, de imediato; na saída, preparado pelo plano de saída da Integração e executado na data confirmada pela Estratégia. As entregas são concluídas ou transferidas na transição combinada por Relações; o último ciclo é passado a faturar; os dados e materiais do cliente são devolvidos ou eliminados, com aprovação de pessoa, guardado só o que a lei ou o contrato mandam guardar; os recursos são liberados à Gestão; e a conclusão vai à Integração e as lições à Inteligência.',
    frequencia='Por evento: contrato encerrado, plano de saída, data de saída confirmada ou mandato de empresa',
    automacao=('média', 'Listar o que está em curso, executar a devolução ou a eliminação aprovada, liberar recursos e arquivar são de agente e automação; planejar, concluir as entregas e aprovar o destino dos dados são de pessoa de Operações; o cliente confirma.'),
    base=['apqc', 'lgpd'],
    lanes=['NEG', 'ITG', 'EST', 'CLI', P, A, R],
    inicios=[I('Contrato encerrado recebido', 'NEG', 'message'),
             I('Plano de saída de clientes e contratos recebido', 'ITG', 'message'),
             I('Data de saída ou mandato recebido', 'EST', 'message')],
    fins=[F('Entregas encerradas e recursos liberados', R),
          F('Fim das entregas preparado, à espera da data ou do plano de saída', R)],
    etapas=[
        E('Planejar o fim das entregas', 'Operações', 'Copiloto', 'médio',
          [(CONTR_FIM, 'Negócios'), (SAIDA_CLI, 'Integração'), (CLI_SAIDA, 'Relações'), (DEC_ENCERRAR, 'Estratégia'),
           (DATA_SAIDA, 'Estratégia'), (MANDATO, 'Estratégia'), (OFERTA_FORA, 'Inteligência')],
          [D('O que iniciou o encerramento?', R,
             [S('Contrato encerrado', 'seg'),
              S('Data de saída ou mandato, com o plano de saída já recebido', 'seg'),
              S('Plano de saída, ainda sem a data', 'F2',
                via=[T('Preparar o fim das entregas pelo plano e aguardar a data de saída', A)]),
              S('Decisão de encerrar ou data, ainda sem o plano de saída', 'F2',
                via=[T('Registrar a decisão e aguardar o plano de saída da Integração', R)])]),
           T('Listar as entregas em curso, os compromissos e os dados e materiais do cliente', A),
           T('Planejar o fim, a transição combinada e o destino de dados e materiais', P)],
          [('Plano de fim das entregas', ['etapa 2'])]),
        E('Concluir as entregas e devolver o que é do cliente', 'Operações, com o cliente', 'Assistido', 'médio',
          [('Plano de fim das entregas', 'etapa 1'), (SIGILO, 'Governança')],
          [T('Concluir ou transferir as entregas em curso conforme o plano', P),
           T('Aprovar o que devolver, o que eliminar e o que a lei ou o contrato mandam guardar', P),
           T('Devolver ou eliminar os dados e materiais do cliente como aprovado', R),
           T('Confirmar o fim das entregas', 'CLI')],
          [('Entregas encerradas', ['etapa 3'])]),
        E('Liberar os recursos e guardar o conhecimento', 'Operações', 'Autopiloto', 'baixo',
          [('Entregas encerradas', 'etapa 2')],
          [T('Passar o último ciclo a faturar', R),
           T('Registrar a liberação de pessoas, agentes, parceiros e ativos alocados ao cliente ou à oferta', R),
           T('Arquivar os registros que devem ser guardados e atualizar os sistemas', R),
           T('Apontar as lições do encerramento', A)],
          [(FATURAR, ['Gestão']),
           ('Recursos da operação liberados, com a data', ['Gestão']),
           ('Entregas encerradas na saída', ['Integração']),
           (REG_CLI, ['Relações']),
           (REG_OP, ['Inteligência']),
           (LICAO_AP, ['Inteligência'])]),
    ]))
