
# ========================================================== ATENDIMENTO E QUALIDADE
JORNADAS.append(dict(
    code='OP-03',
    nome='Atender o cliente: pedidos, dúvidas e problemas, do contato à solução',
    dominio='Atendimento e qualidade', classe='essencial', onda=1,
    objetivo='Fazer cada contato de cliente ser registrado, classificado pelo nível de serviço que vale, resolvido pela base de conhecimento ou por pessoa e respondido; cada problema de tecnologia ir à Integração; cada caso sem padrão ir à Identidade e cada dúvida sobre a oferta em uso à Inteligência; cada reclamação, e cada caso que não se resolve, ir ao tratamento de reclamações; cada pedido comercial ir a Negócios; e cada atendimento deixar registro e o conteúdo que faltou. Operações atende; Negócios trata o pedido comercial.',
    frequencia='Por evento: cada contato do cliente, em qualquer canal',
    automacao=('alta', 'Registrar, classificar, responder o que a base cobre, consultar e registrar são de agente e automação; resolver o caso que o agente não resolve é de pessoa de Operações, só quando a resposta não resolveu.'),
    base=['apqc'],
    lanes=['CLI', 'NEG', P, A, R],
    inicios=[I('Pedido, dúvida ou problema do cliente recebido', 'CLI', 'message')],
    fins=[F('Contato resolvido, respondido e registrado', R),
          F('Reclamação passada ao tratamento de reclamações', R),
          F('Pedido comercial passado a Negócios', R)],
    etapas=[
        E('Receber e classificar o contato do cliente', 'Operações', 'Autopiloto', 'baixo',
          [('Pedido, dúvida ou problema do cliente', 'Clientes'), (PLANO_SUC, 'Relações'), (PROCED, 'OP-05'),
           (SIGILO, 'Governança')],
          [T('Registrar o contato, o cliente, o contrato e o canal', R),
           T('Classificar o tipo, a urgência e o nível de serviço que vale', A),
           D('O que o cliente pede?', A,
             [S('Pedido, dúvida ou problema da entrega', 'prox'),
              S('Reclamação', 'F2', via=[T('Abrir a reclamação no tratamento de reclamações', R)]),
              S('Pedido comercial: ampliação, preço ou cancelamento', 'F3',
                via=[T('Receber o pedido comercial do cliente e tratá-lo na proposta ou no contrato', 'NEG')])])],
          [('Contato classificado', ['etapa 2']),
           (RECL_REG, ['OP-04'])]),
        E('Resolver e responder ao cliente', 'Operações', 'Autopiloto', 'médio',
          [('Contato classificado', 'etapa 1'), (BASE_PUB, 'Inteligência'), (RESP_OFERTA, 'Inteligência'),
           (RESPOSTA_ID, 'Identidade')],
          [D('O problema é de tecnologia?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Abrir o pedido ou o incidente na Integração e acompanhar até a solução', R)])]),
           D('Falta padrão ou regra para responder?', A,
             [S('Não', 'seg'),
              S('Falta padrão de identidade', 'seg', via=[T('Consultar a Identidade sobre o caso não coberto', R)]),
              S('Falta regra da oferta em uso', 'seg', via=[T('Pedir à Inteligência a resposta sobre a oferta em uso', R)])]),
           T('Responder o que a base de conhecimento e as respostas recebidas cobrem', A),
           D('A resposta resolveu?', A,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Analisar e resolver o caso que o agente não resolve', P)])]),
           D('O caso foi resolvido?', A,
             [S('Sim', 'seg'),
              S('Não', 'F2', via=[T('Abrir a reclamação pelo caso não resolvido', R)])]),
           T('Responder ao cliente e confirmar que resolveu', R)],
          [('Contato resolvido', ['etapa 3']),
           (PED_TEC, ['Integração']),
           (CONSULTA, ['Identidade']),
           (PED_AJUSTE, ['Inteligência']),
           (RECL_REG, ['OP-04'])]),
        E('Registrar o atendimento e o que ele ensina', 'Operações', 'Autopiloto', 'baixo',
          [('Contato resolvido', 'etapa 2')],
          [T('Registrar o atendimento, o tempo, a causa e a avaliação do cliente', R),
           T('Apontar sinais de ampliação e de risco de perda e o conteúdo que faltou na base', A)],
          [(REG_OP, ['Inteligência']),
           (PED_RECL, ['Inteligência']),
           (REG_CLI, ['Relações']),
           (CONTEUDO_AP, ['Inteligência'])]),
    ]))

JORNADAS.append(dict(
    code='OP-04',
    nome='Tratar reclamações e incidentes de clientes e corrigir a causa',
    dominio='Atendimento e qualidade', classe='essencial', onda=1,
    objetivo='Fazer cada reclamação ou incidente de cliente ser registrado com o prazo de resposta, classificado pela gravidade e pelo risco legal, investigado até a causa e resolvido por decisão de Operações ou, acima da alçada, do executivo; quando o cliente é consumidor, oferecidas as alternativas da lei; a resposta, inclusive a de improcedência, dada por escrito e registrada; o caso sem acordo encerrado com a informação de onde mais o cliente pode recorrer; e cada causa virar ação corretiva, pedido de ajuste da oferta ou lacuna de experiência. Operações trata; a Governança avalia o dever de comunicar a autoridade; Relações recebe a reclamação com a causa.',
    frequencia='Por evento: reclamação aberta no atendimento ou na entrega, ou recebida de outro canal',
    automacao=('média', 'Registrar, classificar, confirmar o recebimento, propor a solução, analisar a causa e registrar são de agente e automação; conferir a classificação, decidir a solução e aplicá-la são de pessoa de Operações; o que passa da alçada é do executivo.'),
    base=['apqc', 'iso10002', 'cdc'],
    lanes=['SOL', 'GOV', 'EXE', P, A, R],
    inicios=[I('Reclamação aberta no atendimento ou na entrega', R, 'message'),
             I('Reclamação ou incidente recebido de outro canal', 'SOL', 'message')],
    fins=[F('Reclamação resolvida ou respondida, com a causa tratada', R)],
    etapas=[
        E('Receber e classificar a reclamação', 'Operações; o risco legal, com a Governança', 'Copiloto', 'médio',
          [(RECL_REG, 'OP-03'), (RECL_REG, 'OP-02'), ('Reclamação ou incidente de cliente', 'Solicitante'),
           (SIGILO, 'Governança'), (ALCADAS, 'Governança')],
          [T('Registrar a reclamação ou o incidente, o cliente, o contrato e o prazo de resposta', R),
           T('Classificar a gravidade, o risco legal e quem deve resolver', A),
           T('Conferir a classificação de gravidade e de risco legal', P),
           D('Há risco à saúde ou à segurança, ou dever de comunicar a autoridade?', P,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Avaliar o risco e o dever de comunicar a autoridade', 'GOV')])]),
           T('Confirmar o recebimento ao cliente, com o prazo de resposta', R)],
          [('Reclamação classificada', ['etapa 2']),
           (AUTORIDADE, ['Governança'])]),
        E('Investigar e decidir a solução', 'Operações; acima da alçada, o executivo', 'Copiloto', 'médio',
          [('Reclamação classificada', 'etapa 1')],
          [T('Investigar o fato e achar a causa provável', A),
           T('Propor a solução e, se o cliente é consumidor, as alternativas da lei', A),
           T('Conferir a solução proposta e a alçada que ela pede', P),
           D('A solução cabe na alçada de Operações?', P,
             [S('Sim', 'seg', via=[T('Decidir a solução da reclamação', P)]),
              S('Não', 'seg', via=[T('Decidir a solução acima da alçada de Operações', 'EXE')])]),
           D('A reclamação procede?', P,
             [S('Sim', 'prox'),
              S('Não', 'E4', via=[T('Responder ao cliente por escrito com o motivo da improcedência', R)])])],
          [('Solução decidida', ['etapa 3']),
           ('Reclamação improcedente respondida', ['etapa 4'])]),
        E('Aplicar a solução e confirmar com o cliente', 'Operações', 'Copiloto', 'médio',
          [('Solução decidida', 'etapa 2')],
          [T('Aplicar a solução: refazer ou corrigir a entrega, ou pedir o crédito ou o reembolso', P),
           T('Responder ao cliente por escrito com a solução', R),
           D('O cliente aceitou a solução?', P,
             [S('Sim', 'prox'),
              S('Não, com outra solução possível', 'E2', via=[T('Registrar a objeção do cliente e rever a solução', A)]),
              S('Não, sem acordo', 'prox',
                via=[T('Encerrar a reclamação e informar ao cliente onde mais pode recorrer', R)])])],
          [('Reclamação resolvida ou encerrada', ['etapa 4']),
           (CREDITO, ['Gestão'])]),
        E('Tratar a causa e entregar o aprendizado', 'Operações', 'Copiloto', 'médio',
          [('Reclamação resolvida ou encerrada', 'etapa 3'), ('Reclamação improcedente respondida', 'etapa 2')],
          [T('Analisar a causa raiz e a recorrência das reclamações', A),
           T('Decidir como tratar a causa', P),
           D('A causa pede mudança?', P,
             [S('Não', 'seg'),
              S('Na operação', 'seg', via=[T('Abrir a ação corretiva na qualidade', R)]),
              S('Na oferta', 'seg', via=[T('Pedir o ajuste da oferta em uso à Inteligência', R)]),
              S('Na experiência', 'seg', via=[T('Apontar a lacuna de experiência a Relações', R)])]),
           T('Registrar a reclamação, a causa, a solução e o prazo cumprido', R)],
          [(RECL_CAUSA, ['Relações']),
           (PED_RECL, ['Inteligência']),
           (ACAO_AB, ['OP-05']),
           (PED_AJUSTE, ['Inteligência']),
           (LAC_EXP, ['Relações'])]),
    ]))

JORNADAS.append(dict(
    code='OP-05',
    nome='Garantir a qualidade e os níveis de serviço: padrões, medida e ação corretiva',
    dominio='Atendimento e qualidade', classe='essencial', onda=1,
    objetivo='Fazer os padrões de experiência de Relações e o método de cada oferta virarem procedimentos e níveis de serviço por oferta e por segmento de cliente; a qualidade e os níveis de serviço serem medidos; cada não conformidade, reclamação recorrente ou lacuna apontada ter a causa achada e uma ação corretiva decidida, implantada e conferida; a causa que Operações não consegue eliminar ir ao executivo; e o padrão que a operação não consegue cumprir voltar a Relações como lacuna. Operações define e mede; Relações define a experiência; a Inteligência publica o painel.',
    frequencia='A cada ciclo de avaliação da qualidade (cadência: mensal) e por evento: padrão ou oferta nova ou mudada, ação corretiva aberta, lacuna de execução ou de percepção',
    automacao=('alta', 'Traduzir padrões, medir, comparar com os alvos, analisar a causa e registrar são de agente e automação; decidir procedimentos, níveis de serviço e ação corretiva e implantá-la são de pessoa de Operações.'),
    base=['apqc', 'iso9001'],
    lanes=['EXE', P, A, R],
    inicios=[I('Ciclo de avaliação da qualidade iniciado', R, 'timer'),
             I('Padrão, oferta ou método novo ou mudado recebido', R, 'message'),
             I('Ação corretiva ou lacuna recebida', R, 'message')],
    fins=[F('Ação corretiva concluída e registrada', R),
          F('Qualidade dentro dos níveis de serviço, sem ação', R)],
    etapas=[
        E('Definir os procedimentos e os níveis de serviço', 'Operações', 'Copiloto', 'médio',
          [(CX, 'Relações'), (AVAL_SEM, 'Relações'), (OFERTA_CAT, 'Inteligência'), (METODO_PUB, 'Inteligência'),
           (METODO_RET, 'Inteligência'), (PADROES_ID, 'Identidade'), (CONTRATO, 'Negócios')],
          [D('O que iniciou o trabalho?', R,
             [S('Padrão, oferta ou método novo ou mudado', 'seg'),
              S('Ciclo de avaliação', 'E2'),
              S('Ação corretiva ou lacuna apontada', 'E3')]),
           T('Traduzir os padrões de experiência e o método da oferta em procedimentos e níveis de serviço', A),
           T('Decidir os procedimentos e os níveis de serviço por oferta e por segmento de cliente', P),
           D('Algum padrão de experiência não pode ser cumprido pela operação?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Apontar a Relações a lacuna, com a causa e o que seria preciso', R)])])],
          [(PROCED, ['etapa 2', 'OP-02', 'OP-03']),
           (LAC_EXP, ['Relações'])]),
        E('Medir a qualidade e o cumprimento dos níveis de serviço', 'Operações', 'Autopiloto', 'baixo',
          [(PROCED, 'etapa 1'), (PAINEL, 'Inteligência')],
          [T('Medir qualidade, prazos e níveis de serviço por oferta, cliente e equipe', R),
           T('Comparar com os alvos e achar as não conformidades e as tendências', A),
           D('Há não conformidade ou tendência que pede ação?', A,
             [S('Sim', 'prox'),
              S('Não', 'F2', via=[T('Registrar a medida do ciclo', R)])])],
          [('Não conformidades e tendências, com a evidência', ['etapa 3']),
           (REG_OP, ['Inteligência'])]),
        E('Achar a causa e decidir a ação corretiva', 'Operações', 'Copiloto', 'médio',
          [('Não conformidades e tendências, com a evidência', 'etapa 2'), (ACAO_AB, 'OP-04'), (ACAO_AB, 'OP-07'),
           (LACUNAS_EXEC, 'Identidade'), (LAC_PERC, 'Relações'), (CORRECOES, 'Estratégia'),
           ('Ação que não eliminou a causa', 'etapa 4')],
          [T('Analisar a causa raiz da não conformidade ou da lacuna', A),
           T('Propor a ação corretiva, com dono, prazo e ganho esperado', A),
           T('Decidir a ação corretiva', P),
           D('A ação pede capacidade, agente ou ajuste da oferta?', P,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Pedir a capacidade ou o agente à Integração, ou o ajuste da oferta à Inteligência', R)])])],
          [('Ação corretiva decidida', ['etapa 4']),
           (NEC_CAP, ['Integração']),
           (PED_AJUSTE, ['Inteligência'])]),
        E('Implantar a ação e conferir o efeito', 'Operações', 'Copiloto', 'baixo',
          [('Ação corretiva decidida', 'etapa 3')],
          [T('Implantar a ação corretiva e treinar quem executa', P),
           T('Medir de novo e conferir se a causa foi eliminada', A),
           D('A ação eliminou a causa?', P,
             [S('Sim', 'prox', via=[T('Registrar a ação e o efeito conferido', R)]),
              S('Não, há outra ação possível', 'E3'),
              S('Não, a causa passa da alçada de Operações', 'prox',
                via=[T('Decidir o que fazer com a causa não eliminada', 'EXE')])])],
          [(LICAO_AP, ['Inteligência']),
           ('Ação que não eliminou a causa', ['etapa 3'])]),
    ]))
