
# ========================================================== PRODUTO FÍSICO
JORNADAS.append(dict(
    code='OP-06',
    nome='Abastecer e entregar o produto físico: demanda, materiais, produção, estoque e transporte',
    dominio='Produto físico', classe='recomendada', onda=2,
    objetivo='Onde a oferta tem produto físico, fazer a previsão de vendas e os contratos virarem plano de produção e de materiais; cada material ser pedido à Gestão, recebido e inspecionado, e o não conforme recusado e reposto; cada produto ser produzido ou montado, testado pelo procedimento padrão e registrado por lote; cada defeito com risco à saúde ou à segurança ir ao pós-venda; e cada pedido ser guardado, expedido, transportado, recebido pelo cliente e passado à Gestão para faturar. Operações planeja, produz e entrega; a Gestão compra.',
    frequencia='A cada ciclo de planejamento de suprimentos (cadência: mensal) e por contrato com produto assinado',
    automacao=('média', 'Prever, calcular a necessidade, pedir a compra, programar, testar, controlar o estoque, acompanhar o transporte e registrar são de agente e automação; decidir o plano, receber materiais, produzir e expedir são de pessoa de Operações.'),
    base=['apqc'],
    lanes=['NEG', 'GES', 'CLI', P, A, R],
    inicios=[I('Ciclo de planejamento de suprimentos iniciado', R, 'timer'),
             I('Contrato com produto assinado', 'NEG', 'message')],
    fins=[F('Produto entregue, passado a faturar e registrado', R)],
    etapas=[
        E('Prever a demanda e planejar materiais e produção', 'Operações', 'Copiloto', 'médio',
          [(PREVISAO, 'Negócios'), (CONTRATO, 'Negócios'), (OFERTA_CAT, 'Inteligência'), (PLANO_CAP, 'OP-01')],
          [T('Montar a previsão de demanda por produto e conferir com a previsão de vendas e os contratos', A),
           T('Calcular a necessidade de materiais e a capacidade de produção e de estoque', A),
           T('Decidir o plano de produção e de materiais do ciclo', P)],
          [('Plano de produção e de materiais', ['etapa 2', 'etapa 3'])]),
        E('Pedir e receber os materiais e serviços', 'Operações; a compra, com a Gestão', 'Copiloto', 'médio',
          [('Plano de produção e de materiais', 'etapa 1'), (COMPRADOS, 'Gestão')],
          [T('Pedir à Gestão a compra dos materiais e serviços do plano', R),
           T('Fazer a compra e informar a data de entrega', 'GES'),
           T('Receber e inspecionar os materiais e guardá-los', P),
           D('O material recebido está conforme?', P,
             [S('Sim', 'prox'),
              S('Não', 'E2', via=[T('Recusar o material, registrar a falha do fornecedor e pedir a reposição', R)])])],
          [('Pedido de compra de materiais e serviços', ['Gestão']),
           ('Desempenho dos fornecedores na entrega e na qualidade', ['Gestão']),
           ('Materiais disponíveis', ['etapa 3'])]),
        E('Produzir ou montar o produto e testá-lo', 'Operações', 'Copiloto', 'médio',
          [('Plano de produção e de materiais', 'etapa 1'), ('Materiais disponíveis', 'etapa 2')],
          [T('Programar a produção e liberar as ordens por lote', R),
           T('Produzir ou montar o produto', P),
           T('Testar o produto pelo procedimento padrão e registrar o resultado', A),
           D('O produto passou no teste?', A,
             [S('Sim', 'prox'),
              S('Não', 'E3', via=[T('Separar o item, refazer ou descartar e registrar a não conformidade', P)]),
              S('Não: defeito com risco à saúde ou à segurança', 'E3',
                via=[T('Bloquear o lote e levar o defeito ao pós-venda', R)])])],
          [('Produto pronto, com o lote registrado', ['etapa 4']),
           (RISCO_DEF, ['OP-07'])]),
        E('Guardar o produto e entregá-lo ao cliente', 'Operações, com o cliente', 'Copiloto', 'médio',
          [('Produto pronto, com o lote registrado', 'etapa 3')],
          [T('Guardar o produto e controlar o estoque', R),
           T('Preparar e expedir o pedido', P),
           T('Acompanhar o transporte até a entrega', A),
           T('Confirmar o recebimento do produto', 'CLI'),
           T('Registrar a entrega, o lote e o prazo cumprido e passar a faturar', R)],
          [(FATURAR, ['Gestão']),
           (REG_OP, ['Inteligência']),
           (REG_CLI, ['Relações'])]),
    ]))

JORNADAS.append(dict(
    code='OP-07',
    nome='Prestar o pós-venda do produto: devolução, garantia, assistência e recall',
    dominio='Produto físico', classe='recomendada', onda=2,
    objetivo='Onde a oferta tem produto físico, fazer cada pedido de devolução, garantia ou assistência ser conferido contra os termos e os prazos legais, contados pelo tipo de vício; cada vício ser sanado no prazo e, quando não for, resolvido pela escolha do cliente consumidor (troca, devolução do valor ou abatimento); cada defeito com risco à saúde ou à segurança, venha do cliente ou da própria operação, ser comunicado de imediato à autoridade e aos consumidores e virar proposta de recall decidida pelo executivo, acompanhada e encerrada; e cada causa recorrente virar ação corretiva ou cobrança do fornecedor. Operações atende e propõe; a Governança comunica a autoridade; Relações comunica o público; o executivo decide o recall.',
    frequencia='Por evento: pedido de devolução, garantia ou assistência; defeito com risco à saúde ou à segurança',
    automacao=('média', 'Registrar, conferir os termos e prazos, avaliar o risco, acompanhar o recall e analisar a recorrência são de agente e automação; investigar, sanar e cumprir a escolha do cliente são de pessoa de Operações; o recall é do executivo.'),
    base=['apqc', 'cdc', 'cc2002'],
    lanes=['CLI', 'GOV', 'EXE', P, A, R],
    inicios=[I('Pedido de devolução, garantia ou assistência recebido', 'CLI', 'message'),
             I('Defeito com risco detectado na operação', R, 'message')],
    fins=[F('Pedido de pós-venda resolvido e registrado', R),
          F('Pedido fora da garantia respondido e registrado', R)],
    etapas=[
        E('Receber o pedido e avaliar o risco', 'Operações', 'Copiloto', 'médio',
          [('Pedido de devolução, garantia ou assistência', 'Clientes'), (CONTRATO, 'Negócios'),
           (OFERTA_CAT, 'Inteligência')],
          [D('O que iniciou o trabalho?', R,
             [S('Pedido do cliente', 'seg'),
              S('Defeito com risco detectado na operação', 'E3')]),
           T('Registrar o pedido, o produto, o lote e a data de entrega', R),
           T('Triar o relato e apontar os sinais de risco à saúde ou à segurança', A),
           T('Decidir se o defeito relatado pode pôr em risco a saúde ou a segurança', P),
           D('O defeito relatado pode pôr em risco a saúde ou a segurança?', P,
             [S('Não', 'seg'),
              S('Sim, ou há dúvida', 'E3', via=[T('Levar o caso à avaliação de recall', R)])]),
           T('Conferir o pedido contra os termos e os prazos legais, pelo tipo de vício: aparente ou oculto', A),
           D('O pedido está coberto?', A,
             [S('Sim', 'prox'),
              S('Não', 'seg', via=[T('Revisar a negativa de cobertura apontada pelo agente', P)])]),
           D('A negativa de cobertura se confirma?', P,
             [S('Não', 'prox'),
              S('Sim', 'F2', via=[T('Responder ao cliente com o motivo e o caminho para contestar e registrar', R)])])],
          [('Pedido conferido', ['etapa 2']),
           ('Caso levado à avaliação de recall', ['etapa 3'])]),
        E('Sanar o vício ou cumprir a escolha do cliente', 'Operações', 'Assistido', 'médio',
          [('Pedido conferido', 'etapa 1')],
          [T('Receber o produto e investigar o defeito e a causa', P),
           T('Reparar o produto dentro do prazo legal para sanar o vício', P),
           D('O vício foi sanado no prazo?', P,
             [S('Sim', 'seg'),
              S('Não', 'seg', via=[T('Escolher a troca, a devolução do valor ou o abatimento do preço', 'CLI'),
                                   T('Cumprir a escolha do cliente', P)])]),
           T('Atribuir o custo: garantia, cliente ou fornecedor', A)],
          [(CREDITO, ['Gestão']),
           ('Solução aplicada ao cliente', ['etapa 5'])]),
        E('Comunicar o risco e decidir o recall', 'Operações propõe; a Governança comunica; o executivo decide', 'Copiloto', 'alto',
          [('Caso levado à avaliação de recall', 'etapa 1'), (RISCO_DEF, 'OP-06'), (ALCADAS, 'Governança')],
          [T('Avaliar a probabilidade e a consequência do risco e os lotes afetados', A),
           T('Comunicar o risco à autoridade competente', 'GOV'),
           T('Pedir a Relações a comunicação aos consumidores', R),
           T('Propor o recall: lotes, clientes, comunicação e solução', P),
           T('Decidir o recall', 'EXE'),
           D('O recall foi decidido?', P,
             [S('Sim', 'prox', via=[T('Recolher os produtos afetados e repará-los ou trocá-los', P)]),
              S('Não', 'E5', via=[T('Registrar a decisão e o motivo', R)])])],
          [(AUTORIDADE, ['Governança']),
           (FATO, ['Relações']),
           ('Recall em curso', ['etapa 4']),
           ('Recall recusado, com o motivo', ['etapa 5'])]),
        E('Acompanhar a eficácia do recall e encerrá-lo', 'Operações, com a Governança', 'Copiloto', 'alto',
          [('Recall em curso', 'etapa 3')],
          [T('Acompanhar os produtos recolhidos e os clientes atendidos', R),
           T('Enviar à autoridade os relatórios do recall', 'GOV'),
           T('Avaliar a eficácia e decidir o encerramento do recall', P)],
          [('Relatórios do recall para a autoridade', ['Governança']),
           ('Recall encerrado, com a eficácia medida', ['etapa 5'])]),
        E('Registrar e tratar a causa', 'Operações', 'Autopiloto', 'baixo',
          [('Solução aplicada ao cliente', 'etapa 2'), ('Recall recusado, com o motivo', 'etapa 3'),
           ('Recall encerrado, com a eficácia medida', 'etapa 4')],
          [T('Registrar o pedido, a causa, a solução, o custo e o prazo', R),
           T('Analisar a recorrência por produto, lote e fornecedor', A),
           D('A causa é recorrente ou grave?', A,
             [S('Não', 'seg'),
              S('Sim', 'seg', via=[T('Abrir a ação corretiva na qualidade', R)])]),
           D('A causa vem do fornecedor?', A,
             [S('Não', 'prox'),
              S('Sim', 'prox', via=[T('Pedir à Gestão a cobrança do fornecedor pela falha', R)])])],
          [(REG_OP, ['Inteligência']),
           (PED_RECL, ['Inteligência']),
           (REG_CLI, ['Relações']),
           (ACAO_AB, ['OP-05']),
           ('Pedido de cobrança do fornecedor pela falha', ['Gestão'])]),
    ]))
